### ISSUE TITLE
Adjust menu icon size

### ISSUE THREAD

**Issue by jannotabamo** [akveo/nebular#1002]
How to adjust the icon size in my menu?

**Comment by nnixaa** [comment]
Hi @jannotabamo, you can change the `icon-font-size` theme property to adjust menu icons. Here are some more details https://akveo.github.io/nebular/docs/components/menu/theme.

**Comment by jannotabamo** [comment]
@nnixaa i mean for a specific icon in menu. Because when I used 'nb' icons the icon size is not a problem. But when I used font-awesome/ionic icons, it is collapsing with the menu title.

**Comment by z31fbras** [comment]
Is there a solution to this problem?

I need to mix both Nebular and Font Awesome icons in my menu but there is no resizing a specific icon T_T

**Comment by pzaramella** [comment]
Hello, i cant use nb icons. Any idea? I have problem importing NbIconModule, not found, and with this installation npm i @nebular/eva-icons@next, have errors with the theme: 
has no exported member 'NbIconLibraries'
has no exported member 'iconSvg

thanks

**Comment by suppadeliux** [comment]
I am looking forward to see a possible solution too :d

**Comment by aam-antonio** [comment]
I found a solution for this:

*/styles.scss
```
nb-menu .menu-item .menu-icon.svg-inline--fa {
  font-size: 2rem;
}
```

Package versions that I am using:
`"@fortawesome/fontawesome-free": "^5.11.2"`
`"@nebular/theme": "3.6.2"`

**Comment by jgomesmv** [comment]
I'm also facing this issue.
This property should be available on register theme: "menu-item-icon-font-size"

**Comment by jgomesmv** [comment]
Another possible solution can be set the menu-item-icon-width to the desired size. Since icons are sized with rem's they will scale accordingly
