### ISSUE TITLE
Window bugs on minimize/maximize

### ISSUE THREAD

**Issue by meyacine** [akveo/nebular#1003]
### BUG

**I'm submitting a ...**

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
When i minimize Window, and click again to bring it to front, it loose the template.
When i try to put it fullScreen, it place it to the bottom right position
**Expected behavior:**
Click on minimized window, bring it normaly with the template.
Click on fullScreen, make the window full screen.

**Steps to reproduce:**
See documentation, it's bugged
[window documentaiton] (https://akveo.github.io/nebular/docs/components/window/examples)

**Related code:**
```
import { Component } from '@angular/core';
import { NbWindowRef, NbWindowService } from '@nebular/theme';

@Component({
  template: `
    <form class="form">
      <label for="subject">Subject:</label>
      <input nbInput id="subject" type="text">

      <label class="text-label" for="text">Text:</label>
      <textarea nbInput id="text"></textarea>
    </form>
  `,
})
export class NbFormComponent {
  constructor(public windowRef: NbWindowRef) {}

  close() {
    this.windowRef.close();
  }
}

@Component({
  template: `<button (click)="openWindow()" nbButton>Open window</button>`,
  styleUrls: [ './window.scss' ],
})
export class NbWindowShowcaseComponent {

  constructor(private windowService: NbWindowService) {}

  openWindow() {
    this.windowService.open(NbFormComponent, { title: `Window` });
  }
}
```
### Other information:

**npm, node, OS, Browser**
```
Node, npm: `v8.11.1` and `5.6.0`
OS: Windows (7/8/10).
Browser: Chrome
```

**Angular, Nebular**
```
angular: 7.0.0
nebular: 2.0.2
```

**Comment by nnixaa** [comment]
Confirmed.

**Comment by nnixaa** [comment]
@meyacine thanks for reporting!

**Comment by Evitalz** [comment]
When minimizing window the component is destroyed.
When maximizing the minimized window, it create a new instance.
So the data on the template is loose. 

Kindly let me know its can be fixed?

**Comment by senthilmnhr87** [comment]
When minimizing window the component is destroyed.
When maximizing the minimized window, it create a new instance.
So the data on the template is loose.

Kindly let me know its can be fixed?

**Comment by tomer953** [comment]
Same issue, anyway to prevent the destroy on minimize ?

**Comment by omidkh68** [comment]
@nnixaa 
Same issue, I don't want component destroyed when window minimized, any idea for this?

**Comment by carmeloNET** [comment]
i have the same problem, now i am working with a window dialog and when minimize or maximize the component referenced is destroyed. when you open again the dialog, lost all the previous state.

**Comment by carmeloNET** [comment]
an idea, if you are using ngrx, create a object state for the form in the component, and when show again the dialog get data from the object state, with that you coul reset the object or continue writting in it

**Comment by naingaungphyo** [comment]
@carmeloNET 
I want to save the state in services without using ngrx.
So to save the state before the component get destroyed by pressing minimize button, I think I need to subscribe stateChanges. But can you confirm that it is safe to save the sate inside NbWindowRef.stateChanges.subscirbe() block?
What I'm worrying is that, component being destroyed before the state is saved.

**Comment by AmolSB** [comment]
Is it resolved?

**Comment by PPrasai** [comment]
@naingaungphyo Did it work? I am facing a similar issue. My nbWindow contains a form which I would like to retain its values on minimizing.

**Comment by carmeloNET** [comment]
@naingaungphyo  @AmolSB I did a project for example using nebular starter kit to have running the nebular template and give you an idea how can work nbWindow with a angular service to keep the state saved. It is found in this repo
https://github.com/carmeloNET/ngx-admin-nbWindow , just need run npm install and ng serve.

**Comment by weedkiller** [comment]
@carmeloNET which file/line or section is it. BTW very nice theme!

**Comment by naingaungphyo** [comment]
@weedkiller 
It is [here](https://github.com/carmeloNET/ngx-admin-nbWindow/blob/02283cb74c20ec052fa0120bf2b64893bd4e218d/src/app/pages/dashboard/form/form.component.ts#L17). 
It is saving form value in a variable using custom service when the certain state change.
I was trying to do that too but in my case, there were a lot of different fields and variables to be saved. It was not that simple to implement set and get.

**Comment by betodasilva** [comment]
why is this issues closed? the problem is not solved yet

**Comment by khalifa005** [comment]
2024 still not resolved yet

**Comment by khalifa005** [comment]
@nnixaa 
@carmeloNET 
@naingaungphyo 
@omidkh68 

Fixed when minimizing window the component won't get destroyed.
had to override the nb window files 
![image](https://github.com/user-attachments/assets/e11bdf88-822e-4df0-919e-eb1a58efab97)
in window component.css
![image](https://github.com/user-attachments/assets/332d721a-ee07-4bf5-ac3c-56010581a81c)

and in the component 
![image](https://github.com/user-attachments/assets/81133470-2aed-4fe8-9bf5-626ebb52411b)

too late but i had to do it and also updated ngx admin to work with angular 18 and also can work with angular matrial

**Comment by omidkh68** [comment]
> [@nnixaa](https://github.com/nnixaa) [@carmeloNET](https://github.com/carmeloNET) [@naingaungphyo](https://github.com/naingaungphyo) [@omidkh68](https://github.com/omidkh68)
> 
> Fixed when minimizing window the component won't get destroyed. had to override the nb window files ![image](https://github.com/user-attachments/assets/e11bdf88-822e-4df0-919e-eb1a58efab97) in window component.css ![image](https://github.com/user-attachments/assets/332d721a-ee07-4bf5-ac3c-56010581a81c)
> 
> and in the component ![image](https://github.com/user-attachments/assets/81133470-2aed-4fe8-9bf5-626ebb52411b)
> 
> too late but i had to do it and also updated ngx admin to work with angular 18 and also can work with angular matrial

Thank you after 5 years, The company which I worked on it, closed 2 years ago 😂.
