### ISSUE TITLE
is posible to deactivate pace-js?

### ISSUE THREAD

**Issue by jromerob** [akveo/nebular#1005]
Hi, i want to deactivate pace-js on ngx-admin. Is posible ?
I can't read anything about it on docs.

**Comment by ilDon** [comment]
As far as I can tell (I'm not a maintainer) yes, I've removed it completely. Just get rid of all peace-js related code. If I'm remember correctly, there should be some peace-js related code in index.html as well.

**Comment by Tibing** [comment]
Hope the issue is resolved. If you have more questions about ngx-admin, please, open them in the [appropriate repository](https://github.com/akveo/ngx-admin).
