### ISSUE TITLE
Popover arrow has wrong style in prod mode 

### ISSUE THREAD

**Issue by denStrigo** [akveo/nebular#1006]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Popover array has wrong style in prod mode.
![popover_arrow_bug](https://user-images.githubusercontent.com/8480994/48835059-52801780-ed90-11e8-9dab-fe3c04e2de30.jpg)

**Expected behavior:**
Should be:
![popover_arrow](https://user-images.githubusercontent.com/8480994/48834908-f0bfad80-ed8f-11e8-9290-5991e7bde9b3.jpg)

**Steps to reproduce:**
Buld peoject in prod mode

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by yggg** [comment]
Caused by https://github.com/jakubpawlowicz/clean-css/issues/1053
