### ISSUE TITLE
no "~bootstrap/scss/functions" in latest version

### ISSUE THREAD

**Issue by jomalonejia** [akveo/nebular#101]
nebular version: @nebular@2.0.0-rc.3
bootstrap version: 4.0.0-alpha.6

when i update nebular version to 3 version , the `~@nebular/theme/styles/global/bootstrap/_bootstrap.theme.scss  `
need 
`_@import '~bootstrap/scss/functions';`

but in the newest bootstrap does not include the scss file

**Comment by nnixaa** [comment]
Hi @jomalonejia, please update bootstrap to `"bootstrap": "^4.0.0-beta.2"`
