### ISSUE TITLE
OAuth2 implementation flow

### ISSUE THREAD

**Issue by StiviiK** [akveo/nebular#1015]
Hey there,
i have a problem on how to implement properly the authentication flow with OAuth2.
### E-Mail/Password flow
1. User enters creds `->`
2. POST `http://API_URL/login` `->`
3. Api verifys the creds and responds with an JWT Token (Nebular class: `NbAuthJWTToken`, this token been generated by the backend generated and is required for all api calls) `->`
4. Angular stores the token in localStorage `->` done.  

### Wanted OAuth2 flow (similar to E-Mail/Password)
1. User presses OAuth2 login button `->`
2. User gets redirected to auth provider `->`
3. auth provider redirects after successfull auth to callback url (with an access code) `->`
4. POST `http://API_URL/oauth/login` `->`
5. Api verifys the access code and responds with an JWT Token (this token been generated by the backend and is required for all api calls) `->`
6. Angular stores the token in localStorage `->` done.

My Problem currently are the points 1-5 working as expected, my backend gets called with  
`{ grant_type: 'authorization_code', code: '...', client_id: '...' }`
which is perfectly fine, i'll repsond with folowing json  
`{ data: { token: "BACKEND JWT TOKEN" } }` (which works perfectly fine with E-Mail/Password)  
and NebularAuth wraps this respond into an `NbOAuth2Token`, where the payload is the response from the Backend. But i want that my backend-token is stored in localStorage like with E-Mail/Password without wrapping into an `NbOAuth2Token`.

This is how my Strategy is implemented:
```
NbOAuth2AuthStrategy.setup({
  name: 'azuread',
  clientId: '[...]',
  clientSecret: '',
  authorize: {
    endpoint: 'https://login.microsoftonline.com/[...]/oauth2/authorize',
    responseType: NbOAuth2ResponseType.CODE,
    scope: '',
  },
  token: {
    endpoint: `${ApiService.API_URL}/auth/oauth2/token`,
    grantType: NbOAuth2GrantType.AUTHORIZATION_CODE,
    class: NbAuthOAuth2Token, // i tried here NbAuthJWTToken, but this causes an error
  },
  redirect: {
    success: '/pages/dashboard',
    failure: '/pages/error',
  },
}),
```

I hope you can understand my Problem.
Thanks.

**Comment by nnixaa** [comment]
Hi @StiviiK, could you elaborate on this part `But i want that my backend-token is stored in localStorage like with E-Mail/Password without wrapping into an NbOAuth2Token.` please?

Also, have you tried the `NbAuthOAuth2JWTToken` token?

**Comment by StiviiK** [comment]
>could you elaborate on this part  

Yeah sure, it was a bit incomprehensive, so with E-Mail strategy my LocalStorage looks like this:
![image](https://user-images.githubusercontent.com/8115642/48941053-3ad49a80-ef1a-11e8-8455-d5ef4382fae0.png)
as value is the correct JWT Token, provided by my backend.
For Example in my `JWTTokenInterceptor` i can intercept my token in any request like this:
![image](https://user-images.githubusercontent.com/8115642/48941139-99017d80-ef1a-11e8-9045-5bba9016e30e.png)
Or as another example my JWTRoleProvider:
![image](https://user-images.githubusercontent.com/8115642/48941113-85eead80-ef1a-11e8-8b83-104a928ab548.png)

But when using OAauth the hole code breaks as my LocalStorage entry looks like this:
![image](https://user-images.githubusercontent.com/8115642/48941293-44123700-ef1b-11e8-87ee-ec1825f3daa2.png)
And this breaks, at first my code from above but also when I adjust my code the type-saftey from Typescript breaks as i have to interpret the Token as `any` or as a own class because i need the methods.

>Also, have you tried the NbAuthOAuth2JWTToken token?  

![image](https://user-images.githubusercontent.com/8115642/48941314-5ee4ab80-ef1b-11e8-9329-7aa463607127.png)
Same result.

**Comment by StiviiK** [comment]
With Email strategy it also gets correctly decocded:
![image](https://user-images.githubusercontent.com/8115642/48941903-a9672780-ef1d-11e8-9197-dd4f232a3bfe.png)

With OAuth2 strategy its of course broken:
![image](https://user-images.githubusercontent.com/8115642/48942074-44f89800-ef1e-11e8-8703-0fe2585b2241.png)

**Comment by StiviiK** [comment]
I probably found the issue, see here for details: (i'm not sure if this breaks anything)
https://github.com/StiviiK/nebular/commit/4ddf519e46e2747d24c9d3706d4e535bffa38351
https://github.com/StiviiK/nebular/commit/d85ad9890021151b74b800deae24c720cb09b094
https://github.com/StiviiK/nebular/commit/bae71ce14925e27bbf14bc785155fa516fe5d2a7

**Comment by StiviiK** [comment]
This isn't a problem of nebular, i just have understod OAuth2 wrong. So i'll close this.
