### ISSUE TITLE
How to provide suggestion while typing in NbSearch

### ISSUE THREAD

**Issue by WLun001** [akveo/nebular#1016]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [X] feature request

### Issue description

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by Tibing** [comment]
Hi @WLun001, could you please describe slightly deeper what do you mean?

**Comment by WLun001** [comment]
Hi @Tibing 
What I mean is when we type something on the NbSearch bar, it will emit event so that we can handle it, and show suggestion 

As I go through the source code, https://github.com/akveo/nebular/blob/master/src/framework/theme/components/search/search.component.ts#L54, it is listen to keuyp,enter event

It is okay that change to input event?So that event will emit continuously as the user is typing

**Comment by WLun001** [comment]
No problem, there you go

https://github.com/akveo/nebular/pull/1038

**Comment by Tibing** [comment]
Here is a possible workaround: https://github.com/akveo/nebular/pull/1038#issuecomment-452268785
