### ISSUE TITLE
nb-datepicker default required, how to make it not validate required

### ISSUE THREAD

**Issue by sami6002** [akveo/nebular#1019]
<input nbInput fullWidth fieldSize="small" autocomplete="off" name="investmentDate" [(ngModel)]="cim.investmentDate" placeholder="DD/MM/YYYY" [nbDatepicker]="investmentDate">
<nb-datepicker #investmentDate></nb-datepicker>

-> validate the form, want to let this date can be empty
-> set required=false to input is doesn't work

I dont know how to make it.

**Comment by Tibing** [comment]
Hi @sami6002, as I see your issue properly, you have to set `required` attribute on your `input` element.

**Comment by fabienCambournacAcseo** [comment]
`<nb-datepicker filter="false" #datepicker></nb-datepicker>`
