### ISSUE TITLE
Multiple select wrong behavior with options selecting from keyboard

### ISSUE THREAD

**Issue by V-Ahmetvaliev** [akveo/nebular#1031]
### Issue type

**I'm submitting a ...**  

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Multiple select works incorrect with keyboard, it's possible to navigate inside select and switch between options, but selecting any option with keyboard will not highlight element, will not add check-mark and next option selection will add one more instance of this selection, instead of removing previous selection.

**Expected behavior:**
Selection might work the same way it works with mouse clicks

**Steps to reproduce:**
1) Go to [Multiple select](https://akveo.github.io/nebular/example/select/select-multiple.component)
2) Open select with keyboard and navigate to any option with keyboard (i.e. Tab -> Space -> Tab -> Tab to navigate on 2 option.)
![focus on option](https://user-images.githubusercontent.com/18722006/49289087-b488fd00-f4b3-11e8-807c-cf59f2777a41.png)
3) Press space multiple times. Normally it might check then uncheck option, but element will not be highlighted and more then 1 instance of this option selection will be in list
![1 item selected multiple times](https://user-images.githubusercontent.com/18722006/49289118-d6827f80-f4b3-11e8-8038-2e2ff99b211e.png)
![Selections inside button](https://user-images.githubusercontent.com/18722006/49289148-f2862100-f4b3-11e8-8270-43cf843a731c.png)

**Comment by yggg** [comment]
Fixed in 4
