### ISSUE TITLE
Help needed with NB Dialog

### ISSUE THREAD

**Issue by andredatsch** [akveo/nebular#1035]
### Issue type

* [ ] bug report
* [ ] feature request
* [ X ] Help needed
### Issue description

**Current behavior:**
How do i set the fixed width of my dialog? it changes the size depends on the content

**Expected behavior:**
There is any configuration like on NGB Modal where you pass what size of modal you want?

**Steps to reproduce:**

**Related code:**

![24122fe28571f42b0bae816c1fedcabe](https://user-images.githubusercontent.com/3539904/49304414-6a078080-f4b3-11e8-8de1-5ffc61cea6e7.gif)

To Open: 
const dialogRef = this.dialogService.open(ModalPessoasComponent);
    
![c31a8872790abdd495a95d176c42920b](https://user-images.githubusercontent.com/3539904/49304464-90c5b700-f4b3-11e8-83bf-d232981570a1.png)

**Comment by andredatsch** [comment]
Fixed it making a custom css with media query, will close the Issue

**Comment by VladFlorian** [comment]
lol why didn't you post your result? Fixed it see ya later guys!!!!! hahha
