### ISSUE TITLE
Upgrading to 3.0.0 - HTTP_INTERCEPTORS not sending http bearer

### ISSUE THREAD

**Issue by Alkasih** [akveo/nebular#1048]
### Issue type

**I'm submitting a ...**  
* [x ] bug report

### Issue description

By providing `{ provide: HTTP_INTERCEPTORS, useClass: NbAuthJWTInterceptor, multi: true}` in 2.0.0-rc.9 set the http bearer after success login for every request, but it doesn't in 3.0.0

**Comment by nnixaa** [comment]
Hi @Alkasih, I believe you need to walk through the https://github.com/akveo/nebular/blob/master/CHANGELOG.md as since rc.9 quite a lot has been changed.

**Comment by nnixaa** [comment]
Closing as it seems addressed.
