### ISSUE TITLE
nb-select multi - Drop down list checkbox disabled

### ISSUE THREAD

**Issue by tpehrsson** [akveo/nebular#1053]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

When list of nb-select options are populated in constructor, the drop down works as expected.
When list of nb-select options are populated using method (onPopulate) the list is populated,
but the checkbox control is disabled. In other word, no drop down values can be selected

**Expected behavior:**

**Steps to reproduce:**

import { Component } from '@angular/core';

@Component({
  selector: 'test',
  templateUrl: './test.component.html',
  styles: [`
    nb-card {
      transform: translate3d(0, 0, 0);
    }
  `],
})
export class TestComponent {
  selectTableOptions: any[] = [];
  selectLabel: string = "Select Tables";
  selectedTables: any[];

  constructor() {
    this.selectTableOptions.push("Customers");
    this.selectTableOptions.push("Employees");  }

  onPopulate() {
    this.setSelectTables();
  }
  setSelectTables() {
    this.selectTableOptions.splice(0,this.selectTableOptions.length)
    this.selectTableOptions.push("Order");
    this.selectTableOptions.push("Order_Details");
    this.selectLabel = "Selected Tables: " +this.selectTableOptions.length + " of " + this.selectTableOptions.length;   
  }   
  onSelectedTableChange(event): void {
    if (event !== null) {
      this.selectedTables = event;
      this.selectLabel = "Selected Tables: " + event.length + " of " + this.selectedTables.length;       
    }
  }
}

<nb-card>
  <nb-card-header>
      Populate Table List
  </nb-card-header>

  <nb-card-body>
    <div id="select_assets" class="row">
      <div class="col-sm-6">
        <nb-select multiple placeholder="Select Tables" 
            shape="rectangle" size="small" 
            [ngModel]="selectTableOptions"
            (selectedChange)="onSelectedTableChange($event)">
        <nb-select-label>
              {{ selectLabel }}
        </nb-select-label>        
          <nb-option *ngFor="let tableName of selectTableOptions" [value]="tableName">{{tableName}}</nb-option> 
        </nb-select>
      </div>
      <div class="col-sm-6">
        <button nbButton (click)="onPopulate()" size="small">Populate Table List</button>
      </div>
    </div>  
  </nb-card-body>
</nb-card>

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by tpehrsson** [comment]
[test.component.txt](https://github.com/akveo/nebular/files/2653953/test.component.txt)

**Comment by tpehrsson** [comment]
[test.component.txt](https://github.com/akveo/nebular/files/2653969/test.component.txt)

**Comment by Tibing** [comment]
Hi @tpehrsson, I've tried to reproduce the issue via coping code you've posted here and it works fine for me.
![kapture 2018-12-20 at 17 12 29](https://user-images.githubusercontent.com/17410089/50290992-5a5dd500-047e-11e9-801d-9f3b386b0250.gif)
Could you please create a reproducible [stackblitz](stackblitz.com)?

**Comment by nnixaa** [comment]
Closing as no answer.
