### ISSUE TITLE
Nb-select Cascading

### ISSUE THREAD

**Issue by tanmayparmar** [akveo/nebular#1054]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [* ] feature request

### Issue description

**Current behavior:**
i am using [this example](https://stackblitz.com/edit/cascading-dropdown-angular) for cascading NB-select. However, it is not sending selected value onchange event. it is initially loading dropdown. So, my services are running fine.  

**Expected behavior:**
It should send value onchange event to populate drop-down. 

Do nb-select have a onChange event like this: 
`<select [(ngModel)]="selectedCountry.id" (change)="onSelect($event.target.value)">`

**Comment by Tibing** [comment]
Hi @tanmayparmar, regarding your example, you're trying to use `nb-select` with Angular 5, but `nb-select` was introduced after Angular 6 release. Moreover, Nebular requires Angular 7 now. So, could you please try with the latest Angular and Nebular versions?

**Comment by tanmayparmar** [comment]
> Hi @tanmayparmar, regarding your example, you're trying to use `nb-select` with Angular 5, but `nb-select` was introduced after Angular 6 release. Moreover, Nebular requires Angular 7 now. So, could you please try with the latest Angular and Nebular versions? Hopefully, `nb-select` will work fine.

Hello @Tibing , i am using anguar 7.  That example is just what i wanted to do. So, Do you have any event  that gave me values on change. 

Like this.
<select [(ngModel)]="selectedCountry.id" (change)="onSelect($event.target.value)">

**Comment by Tibing** [comment]
Hi @tanmayparmar, oh, ok, regarding the [documentation](https://akveo.github.io/nebular/docs/components/select/api#nbselectcomponent) `nb-select` has `selectedChange` output. As I understand properly it's exactly what are you searching for.

**Comment by ivan966** [comment]
hello I had problems with the following line,
<select (change)="onSelect($event.target.value)" [(ngModel)]="selectedCountry.id">
this gives me an error in the value of the onSelect. the error is the following
Property 'value' does not exist on type 'EventTarget'.ngtsc(2339)
I would appreciate if you can help me
