### ISSUE TITLE
Rxjs subscriptions management refactoring

### ISSUE THREAD

**Issue by Tibing** [akveo/nebular#1059]
Change all `takeWhile(() => this.alive)` to the `takeUntil(this.destroyed$)`. Because of possible memory leaks.

**Comment by Kshitij-Banerjee** [comment]
@Tibing  nbIsGranted is also leaking. This may be a possible reason.

**Comment by yggg** [comment]
Let's also add `rxjs-tslint-rules` package and enable `rxjs-no-unsafe-takeuntil` rule.

Details https://blog.angularindepth.com/rxjs-avoiding-takeuntil-leaks-fb5182d047ef
