### ISSUE TITLE
File to import not found or unreadable error

### ISSUE THREAD

**Issue by sameerpallav** [akveo/nebular#1061]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
npm start fails to complie bcoz of these errors

**Expected behavior:**
Run the webpack server succesfully

**Steps to reproduce:**

**Related code:**
{
  "name": "ngx-admin",
  "version": "2.1.0",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/akveo/ngx-admin.git"
  },
  "bugs": {
    "url": "https://github.com/akveo/ngx-admin/issues"
  },
  "scripts": {
    "ng": "ng",
    "conventional-changelog": "conventional-changelog",
    "start": "ng serve --proxy-config proxy.conf.js",
    "build": "ng build",
    "build:prod": "ng build --env=prod --aot --prod --build-optimizer=true --vendor-chunk=true",
    "publish": "./dispatch.sh",
    "test": "ng test -sr",
    "test:coverage": "rimraf coverage && npm run test -- -cc",
    "lint": "ng lint --type-check",
    "lint:fix": "ng lint --fix",
    "lint:styles": "stylelint ./src/**/*.scss",
    "lint:ci": "npm run lint && npm run lint:styles",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "ng e2e",
    "docs": "compodoc -p src/tsconfig.app.json -d docs",
    "docs:serve": "compodoc -p src/tsconfig.app.json -d docs -s",
    "prepush": "npm run lint:ci",
    "release:changelog": "npm run conventional-changelog -- -p angular -i CHANGELOG.md -s"
  },
  "dependencies": {
    "@angular/cdk": "^7.0.3",
    "@nebular/bootstrap": "3.0.0",
    "angular-tree-component": "7.2.0",
    "eva-icons": "^1.1.0",
    "@agm/core": "1.0.0-beta.5",
    "@angular/animations": "7.1.2",
    "@angular/common": "7.1.2",
    "@angular/compiler": "7.1.2",
    "@angular/core": "7.1.2",
    "@angular/forms": "7.1.2",
    "@angular/http": "7.1.2",
    "@angular/platform-browser": "7.1.2",
    "@angular/platform-browser-dynamic": "7.1.2",
    "@angular/router": "7.1.2",
    "@asymmetrik/ngx-leaflet": "3.0.1",
    "@fortawesome/angular-fontawesome": "0.1.0-10",
    "@fortawesome/fontawesome-free": "^5.2.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.9",
    "@fortawesome/free-brands-svg-icons": "^5.6.0",
    "@fortawesome/free-solid-svg-icons": "^5.6.0",
    "@nebular/auth": "2.0.0-rc.6",
    "@nebular/security": "3.0.0",
    "@nebular/theme": "3.0.0",
    "@ng-bootstrap/ng-bootstrap": "^4.0.0",
    "@ngx-share/button": "^5.3.1",
    "@ngx-share/buttons": "^5.3.1",
    "@ngx-share/core": "^5.3.1",
    "@swimlane/ngx-charts": "^10.0.0",
    "angular-particle": "^1.0.4",
    "angular2-chartjs": "0.4.1",
    "angular2-toaster": "^6.0.1",
    "angularx-social-login": "github:captainjackrana/angularx-social-login",
    "bootstrap": "4.0.0",
    "chart.js": "2.7.1",
    "ckeditor": "4.7.3",
    "classlist.js": "1.1.20150312",
    "core-js": "2.5.1",
    "echarts": "^4.1.0",
    "font-awesome": "4.7.0",
    "gsap": "^1.20.6",
    "intl": "1.2.5",
    "ionicons": "2.0.1",
    "leaflet": "1.2.0",
    "nebular-icons": "1.0.6",
    "ng-animate": "^0.3.4",
    "ng-recaptcha": "^4.2.1",
    "ng2-ckeditor": "1.1.13",
    "ng2-completer": "^1.6.3",
    "ng2-nouislider": "^1.7.13",
    "ng2-slider-component": "^1.0.9",
    "ng2-smart-table": "1.2.2",
    "ng2-tree": "2.0.0-rc.4",
    "ngx-bootstrap": "^2.0.5",
    "ngx-chips": "^1.9.8",
    "ngx-cookie-service": "^1.0.10",
    "ngx-echarts": "^4.0.1",
    "ngx-swiper-wrapper": "^6.4.1",
    "node-sass": "^4.8.1",
    "normalize.css": "6.0.0",
    "nouislider": "^11.1.0",
    "pace-js": "1.0.2",
    "roboto-fontface": "0.8.0",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.3.3",
    "socicon": "3.0.5",
    "tinymce": "4.5.7",
    "typeface-exo": "0.0.22",
    "web-animations-js": "2.2.5",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.11.2",
    "@angular/cli": "7.1.2",
    "@angular/compiler-cli": "7.1.2",
    "@angular/language-service": "7.1.2",
    "@compodoc/compodoc": "1.0.1",
    "@fortawesome/fontawesome-free": "^5.2.0",
    "@types/chartjs": "0.0.31",
    "@types/d3-color": "1.0.5",
    "@types/googlemaps": "3.30.4",
    "@types/jasmine": "2.5.54",
    "@types/jasminewd2": "2.0.3",
    "@types/leaflet": "1.2.3",
    "@types/node": "6.0.90",
    "codelyzer": "4.0.2",
    "conventional-changelog-cli": "1.3.4",
    "husky": "0.13.3",
    "jasmine-core": "2.6.4",
    "jasmine-spec-reporter": "4.1.1",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.1.1",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.3.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "npm-run-all": "4.0.2",
    "protractor": "5.1.2",
    "rimraf": "2.6.1",
    "stylelint": "7.13.0",
    "ts-node": "3.2.2",
    "tslint": "^5.11.0",
    "tslint-language-service": "0.9.6",
    "typescript": "3.1.6"
  }
}

```
insert short code snippets here
```

### Other information:
Stack trace:
ERROR in ./src/app/@theme/components/footer/footer.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/@theme/components/footer/footer.component.scss (line 2, column 1)
ERROR in ./src/app/@theme/components/header/header.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/@theme/components/header/header.component.scss (line 3, column 1)
ERROR in ./src/app/@theme/layouts/one-column/one-column.layout.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/@theme/layouts/one-column/one-column.layout.scss (line 3, column 1)
ERROR in ./src/app/@theme/layouts/sample/sample.layout.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/@theme/layouts/sample/sample.layout.scss (line 3, column 1)
ERROR in ./src/app/@theme/layouts/three-columns/three-columns.layout.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/@theme/layouts/three-columns/three-columns.layout.scss (line 3, column 1)
ERROR in ./src/app/@theme/layouts/two-columns/two-columns.layout.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/@theme/layouts/two-columns/two-columns.layout.scss (line 3, column 1)
ERROR in ./src/app/pages/calculator/calculator.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/calculator/calculator.component.scss (line 3, column 1)
ERROR in ./src/app/pages/career/career-distribution/career-distribution.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/career/career-distribution/career-distribution.component.scss (line 5, column 1)
ERROR in ./src/app/pages/career/career-skillage/career-skillage.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/career/career-skillage/career-skillage.component.scss (line 5, column 1)
ERROR in ./src/app/pages/career/career-worth/career-worth.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/career/career-worth/career-worth.component.scss (line 5, column 1)
ERROR in ./src/app/pages/career/career.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/career/career.component.scss (line 3, column 1)
ERROR in ./src/app/pages/career/overall/overall.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/career/overall/overall.component.scss (line 2, column 1)
ERROR in ./src/app/pages/career/rank-card/rank-card.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/career/rank-card/rank-card.component.scss (line 2, column 1)
ERROR in ./src/app/pages/career/rank-radar/rank-radar.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/career/rank-radar/rank-radar.component.scss (line 5, column 1)
ERROR in ./src/app/pages/compare/compare-culture/compare-culture.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/compare/compare-culture/compare-culture.component.scss (line 5, column 1)
ERROR in ./src/app/pages/compare/compare-eliteness/compare-eliteness.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/compare/compare-eliteness/compare-eliteness.component.scss (line 5, column 1)
ERROR in ./src/app/pages/compare/compare-intro/compare-intro.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/compare/compare-intro/compare-intro.component.scss (line 3, column 1)
ERROR in ./src/app/pages/compare/compare-marketpay/compare-marketpay.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/compare/compare-marketpay/compare-marketpay.component.scss (line 5, column 1)
ERROR in ./src/app/pages/compare/compare-radar/compare-radar.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/compare/compare-radar/compare-radar.component.scss (line 5, column 1)
ERROR in ./src/app/pages/compare/compare-users/compare-users.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/compare/compare-users/compare-users.component.scss (line 3, column 1)
ERROR in ./src/app/pages/compare/compare.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/compare/compare.component.scss (line 3, column 1)
ERROR in ./src/app/pages/dashboard/dashboard.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/dashboard/dashboard.component.scss (line 3, column 1)
ERROR in ./src/app/pages/dashboard/electricity/electricity.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/dashboard/electricity/electricity.component.scss (line 5, column 1)
ERROR in ./src/app/pages/dashboard/rooms/player/player.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/dashboard/rooms/player/player.component.scss (line 4, column 1)
ERROR in ./src/app/pages/dashboard/rooms/rooms.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/dashboard/rooms/rooms.component.scss (line 3, column 1)
ERROR in ./src/app/pages/dashboard/security-cameras/security-cameras.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/dashboard/security-cameras/security-cameras.component.scss (line 2, column 1)
ERROR in ./src/app/pages/dashboard/solar/solar.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/dashboard/solar/solar.component.scss (line 2, column 1)
ERROR in ./src/app/pages/dashboard/temperature/temperature.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/dashboard/temperature/temperature.component.scss (line 3, column 1)
ERROR in ./src/app/pages/dashboard/weather/weather.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/dashboard/weather/weather.component.scss (line 2, column 1)
ERROR in ./src/app/pages/forms/form-inputs/form-inputs.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/forms/form-inputs/form-inputs.component.scss (line 3, column 1)
ERROR in ./src/app/pages/future/future-switch/future-switch.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/future/future-switch/future-switch.component.scss (line 5, column 1)
ERROR in ./src/app/pages/home/home.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/home/home.component.scss (line 4, column 1)
ERROR in ./src/app/pages/landing/landing.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/landing/landing.component.scss (line 3, column 1)
ERROR in ./src/app/pages/profile/profile.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/profile/profile.component.scss (line 3, column 1)
ERROR in ./src/app/pages/salary/average-age/average-age.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/salary/average-age/average-age.component.scss (line 2, column 1)
ERROR in ./src/app/pages/salary/average/average.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/salary/average/average.component.scss (line 2, column 1)
ERROR in ./src/app/pages/salary/distribution/distribution.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/salary/distribution/distribution.component.scss (line 5, column 1)
ERROR in ./src/app/pages/salary/salary-profiles/salary-profiles.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/salary/salary-profiles/salary-profiles.component.scss (line 3, column 1)
ERROR in ./src/app/pages/salary/salary-stocks/salary-stocks.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/salary/salary-stocks/salary-stocks.component.scss (line 5, column 1)
ERROR in ./src/app/pages/salary/salary.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/salary/salary.component.scss (line 3, column 1)
ERROR in ./src/app/pages/salary/top-schools/top-schools.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/salary/top-schools/top-schools.component.scss (line 5, column 1)
ERROR in ./src/app/pages/salary/trending-skills/trending-skills.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/salary/trending-skills/trending-skills.component.scss (line 5, column 1)
ERROR in ./src/app/shared/profile-form/profile-form.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/shared/profile-form/profile-form.component.scss (line 3, column 1)
ERROR in ./src/app/shared/salary-pop-form/salary-pop-form.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/shared/salary-pop-form/salary-pop-form.component.scss (line 3, column 1)
ERROR in ./src/app/@theme/components/theme-switcher/theme-switcher.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/hero-buttons';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/hero-buttons.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/@theme/components/theme-switcher/theme-switcher.component.scss (line 2, column 1)
ERROR in ./src/app/pages/dashboard/contacts/contacts.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/hero-buttons';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/hero-buttons.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/dashboard/contacts/contacts.component.scss (line 2, column 1)
ERROR in ./src/app/pages/dashboard/status-card/status-card.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/hero-buttons';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/hero-buttons.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/dashboard/status-card/status-card.component.scss (line 2, column 1)
ERROR in ./src/app/pages/dashboard/temperature/temperature-dragger/temperature-dragger.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/hero-buttons';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/hero-buttons.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/dashboard/temperature/temperature-dragger/temperature-dragger.component.scss (line 2, column 1)
ERROR in ./src/app/pages/salary/salary-status-card/salary-status-card.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@nebular/theme/styles/global/bootstrap/hero-buttons';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/hero-buttons.
Parent style sheet: stdin
      in /Users/Inso/io/rasalghul/src/app/pages/salary/salary-status-card/salary-status-card.component.scss (line 2, column 1)
ℹ ｢wdm｣: Failed to compile.
**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by Tibing** [comment]
Hi @sameerpallav, as I see, you're trying to run `ngx-admin`. And errors mentioned above may appear if you update Nebular without updating `ngx-admin`. So, please, update `ngx-admin` first.

This issue isn't related to the Nebular project but to the `ngx-admin`, so, if you still have the same errors, please, reopen the issue in the [ngx-admin repo](https://github.com/akveo/ngx-admin).

**Comment by sameerpallav** [comment]
Thanks @Tibing. I'll check it out

**Comment by kryptus47** [comment]
Just in case another lost soul end up here because of this issue, 

replacing 
`@import '~@nebular/auth/styles/all'; `
by
`@import '~@nebular/auth/styles/globals';`
fixed the bug.

**Comment by devin1996** [comment]
After Updating into Angular 9 from 8 I have changed the import as below

Replaced this
`@import '~@nebular/theme/styles/global/bootstrap/breakpoints';`
into this
`@import '~@nebular/theme/styles/global/breakpoints';`
