### ISSUE TITLE
nb-select changing outline color

### ISSUE THREAD

**Issue by ganapathymano** [akveo/nebular#1062]
I am trying to change the outline color of nb-select while validating.
I am using nb-select with outline option and status="success"

when the user didnt select this required field i am trying to change the outline color of nb-select. But unable to do that, could you please help in doing this?

### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
<nb-select placeholder="Gender" outline status="success"
                 name="gender" #gender="ngModel" [(ngModel)]="employee.gender" required>
     <nb-option *ngFor="let gender of genderTypes" [value]=gender>{{gender}}</nb-option>
</nb-select>
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by Tibing** [comment]
Hi @ganapathymano, as the `status` is plain Angular Input property you may change its value the following way:
```
status = 'success';

onChange() {
  if (invalid) {
    this.status = 'danger';
  } else {
    this.status = 'success';
  }
}
```
```
<nb-select [status]="status"></nb-select>
```

**Comment by erickvls** [comment]
How can i customize my color ? For example i dont want primary,success,warning, info. i want pink. How can i change only to specific select(nb-select) using outline ?
