### ISSUE TITLE
update to angular 5

### ISSUE THREAD

**Issue by nnixaa** [akveo/nebular#108]

**Comment by nnixaa** [comment]
https://github.com/akveo/nebular/issues/56

**Comment by jonathanpmartins** [comment]
please update!

**Comment by nnixaa** [comment]
@jonathanpmartins hopefully we have it in 2017 🎄 !

**Comment by nnixaa** [comment]
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#200-rc4-2017-12-31-christmas_tree
