### ISSUE TITLE
Need to call function on selected particular nb-tab

### ISSUE THREAD

**Issue by akshaykinhikar** [akveo/nebular#109]
hi, I need to call my custome function on tab selection of any tab, is there any particular way? 
OR will need to extend the existing component.

**Comment by nnixaa** [comment]
Hi @akshaykinhikar, as per documentation here https://akveo.github.io/nebular/#/docs/components/tabs there is an output called changeTab:
```
<nb-tabset (changeTab)="onChangeTab($event)">...
```
Hope this helps.

**Comment by akshaykinhikar** [comment]
Its worked, but I have scenario like this: 
`<nb-tabset (changeTab)="selectTab($event)">
                    <div *ngFor="let element of arrayOfElement">
                        <nb-tab tabTitle="{{element}}">
                        </nb-tab>
                    </div>
</nb-tabset>`
 and I'm currently unable to get selected tab.

**Comment by akshaykinhikar** [comment]
`event.tabTitle`

It Worked.., Thank you..,

**Comment by nnixaa** [comment]
Great! Closing now.

**Comment by sarangun** [comment]
@nnixaa , I know its closed from the post but, still I am unable to use it properly. My event is getting fired when switching the tabs (by nb-tabset changeTab emitter) but as mentioned by @akshaykinhikar event.tabTitle, it says tabTitle is undefined. I am performing a similar situation, tabs are created based on ngFor from db collections, and if I change the tab the data should be populated based on the tab. 
Thank you in advanced, sorry if I searched the issue log but could not get any tickets for this so placing it here itself.

**Comment by gregoryalary** [comment]
It looks like the `changeTab` output does not appear in the doc anymore.

**Comment by Tarak1246** [comment]
Hi changeTab was not work me

**Comment by jvegaseg** [comment]
What about using a template in some tabs (nbTabTitle)? In this case, event.tabTitle does not exist. Instead there is a event.tabTitleDirective but it does not helps.

I can not find any way to know which tab was selected (using a easy way)

**Comment by GustavoRea615** [comment]
Hi,
Complementing what nnixaa commented, we can add the "**tabId**" property and it would look like this:
```
<nb-tabset fullWidth (changeTab)="selectTab($event)">
                    <nb-tab tabTitle="1" tabId="nota_credito">
                        <div class="row">
                            <div class="col-12 form-control-group">
                                1
                            </div>
                        </div>
                    </nb-tab>
                    <nb-tab tabTitle="2" tabId="nota_recargo">
                        <div class="row">
                            <div class="col-12 form-control-group">
                                2
                            </div>
                        </div>
                    </nb-tab>
                </nb-tabset>
```
In component you can work with the object **$event**
```
selectTab($event: any): void {
    console.log("selectTab $event:", $event)
  }
```

**Comment by addaissaabdoulrazak** [comment]
"Hi! I would like to capture the tab index using the (changeTab) event. How can I do it? I don't understand why event.index didn't work."
