### ISSUE TITLE
Cannot active search component

### ISSUE THREAD

**Issue by do-yeon** [akveo/nebular#1094]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Can't activate the NbSearchComponent by using NbSearchService in all of components.
and can't subscribe this service.

**Expected behavior:**

NbSearchComponent should activate.
**Steps to reproduce:**

![2018-12-19 10 46 16](https://user-images.githubusercontent.com/4496770/50193785-6f057480-037b-11e9-824c-1cb2e3a85d3f.png)

I use ngx-admin-starter-kit
What I did is just npm install and write this code.

**Related code:**

```
  /***
   * Activate (open) search component
   * @param {string} searchType
   * @param {string} tag
   */
  activateSearch(searchType: string, tag?: string) {
    this.searchActivations$.next({ searchType, tag });
  }
```

### Other information:

**npm, node, OS, Browser**
```
node: v10.13.0
npm: v6.4.1
Tested OS: Mac Mojave, Windows 10
Tested Browser: Chrome/Safari/Edge
```

**Angular, Nebular**
```
it's the same as the files in ngx-admin-starter-kit
```

**Comment by Tibing** [comment]
Hi @do-yeon, could you please check this [stackblitz](https://stackblitz.com/edit/github-assamy) it seems to be working properly.

**Comment by nnixaa** [comment]
Closing as it seems outdated. Please open a new issue if you still experience this behavior.
