### ISSUE TITLE
Toastr doesn't appear 

### ISSUE THREAD

**Issue by do-yeon** [akveo/nebular#1099]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [x] feature request

### Issue description

**Current behavior:**

First, you go to the dashboard page that includes some codes to show toastr on AfterViewInit. It will show toastr. 
And then you go to login page(because of logout), 
when you try to open again the dashboard, it doesn't appear.
The global overlay wrapper that contains nb-toastr-container is not in the login page.
so, whenever you get the dashboard again(right after opening one of auth page) angular will re-render layouts and components you made but toastr seems still holding destroyed nb-toastr-container and it's not re-rendered.

**Expected behavior:**

Showing toastr

**Steps to reproduce:**

with ngx-admin
1. add toastr call on dashboard.
2. open dashboard.
3. go to one of auth page.
4. back to dashboard
5. toastr doesn't appear

### Other information:

**npm, node, OS, Browser**
```
node: v10.13.0
npm: v6.4.1
Tested OS: Mac Mojave, Windows 10
Tested Browser: Chrome/Safari/Edge
```

**Angular, Nebular**
```
it's the same as the files in ngx-admin
```

feature request
is there any way to place toast component manually?
if a page I made is not in layout(but it imports theme module like auth page), there is no way to use toastr.
sometimes we need full screen page with using toastr this way.

**Comment by developcodeza-matthew** [comment]
I've been struggling with this for the past couple weeks as well. Hoping someone has a solution.

**Comment by FilipK23** [comment]
I have the same problem. If I change module 2 times than toasts does not appear. I have my own modules client and admin and if I go from client to admin and back than any toast show. With login and logout it is the same.

**Comment by FilipK23** [comment]
Hello @nnixaa its not fixed.

Using 3.2.1 version (so latest release) and still not working.

**Comment by nnixaa** [comment]
It is scheduled for 3.3.0, should be released relatively soon:
![image](https://user-images.githubusercontent.com/230527/52798883-e3157d80-3089-11e9-96ba-3dab5a5e7870.png)

**Comment by Eve-1995** [comment]
I have the same problem.

**Comment by FilipK23** [comment]
I still have the same issue. When I navigate from auth module to main module toastr doesn't appear. (version 4.5.0)

**Comment by mirpuicor** [comment]
> It is scheduled for 3.3.0, should be released relatively soon:
> ![image](https://user-images.githubusercontent.com/230527/52798883-e3157d80-3089-11e9-96ba-3dab5a5e7870.png)

Same problem with v 5.0.0

**Comment by ganesh2ram** [comment]
Temporary Work around:
Go to node_modules/@nebular/theme/components/toastr/toastr.service.js
Go to line no:103  
NbToastrContainerRegistry.prototype.get = function (position) {
        var logicalPosition = this.positionHelper.toLogicalPosition(position);
       // if (!this.overlays.has(logicalPosition)) {
            this.instantiateContainer(logicalPosition);
       // }
        return this.overlays.get(logicalPosition);
    };
