### ISSUE TITLE
Protect onTokenChange when token is cleared

### ISSUE THREAD

**Issue by hulehule20** [akveo/nebular#110]
There's a specific case in nebular's [documentation]( https://github.com/akveo/nebular/blob/master/docs/articles/auth-token.md) that teaches you how to update Header's user when token is updated, using the  `NbAuthService.onTokenChange()` observable.  However, this ends in an application crash when you implement it in real case with the logout functionality, because when NbAuthService performs logout the token is cleared and deleted, and the function in `HeaderComponent` tries to call `token.getValue()`, the token is `null` and the app crashes.

    this.authService.onTokenChange()
      .subscribe((token: NbAuthJWTToken) => {
        if (token.getValue()) {
            this.user = token.getPayload();
        }
    });

With this exposed, I think that either there should be a protection for `token==null` on the `onTokenChange()` function implementation or you should update that specific document on your documentation with that security check, for example like this:

    this.authService.onTokenChange()
      .subscribe((token: NbAuthJWTToken) => {
        if(token != null) {
            if (token.getValue()) {
                this.user = token.getPayload();
            }
        }
    });

**Comment by nnixaa** [comment]
Hey @hulehule20, many thanks!

**Comment by hulehule20** [comment]
If you tell me which option do you think is better, I can implement it myself and make a PR.  
I think the most convenient solutions would be:
1. Update the documentation page about [getting the user token](https://akveo.github.io/nebular/#/docs/auth/getting-user-token).  The documentation should advise to safe-check the token existance when you call `onTokenChange()` for specific cases, like when the user logs out. Or
2. Implement a solution on NbAuthService.

**Comment by gael-ft** [comment]
Why not updating NbTokenService with something like  

`deleter: (): Observable<NbAuthSimpleToken> => {`
`localStorage.removeItem(this.getConfigValue('token.key'));`
`this.tokenWrapper.set(null);`
`return Observable.of(this.projectWrapper);`
`},`
in config.

`clear(): Observable<NbAuthSimpleToken> {`
`    return this.getConfigValue('project.deleter')()`
`      .do(token => this.publishProject(token));`
`  }`
for clear function.

?

**Comment by nnixaa** [comment]
as of `rc.6` token will never be empty, only valid or not, which could be checked using `isValid` method.
