### ISSUE TITLE
Trigger change tab in nb-tabset

### ISSUE THREAD

**Issue by pawelmaziarz** [akveo/nebular#1103]
Hi, I have form with multiple steps - each step is on new tab. Of course I can switch between tabs clicking on tab title, however I would also like to use custom button on the bottom of the step like ,,Next step''. Is it currently easily possible to create custom buttom with action which changes current tab?

**Comment by Tibing** [comment]
Hi @pawelmaziarz, I don't think this behavior is available now. Moreover, use case you've described above sounds more like [stepper](https://akveo.github.io/nebular/docs/components/stepper/api#nbsteppercomponent) rather than tabs.

**Comment by Tibing** [comment]
@pawelmaziarz, hi again. In general, if you really want to do this, you may manipulate the `active` property of the tab to switch them. The more detailed explanation you can find [here](https://github.com/akveo/nebular/issues/305#issuecomment-374207633).
