### ISSUE TITLE
Input box with Outline border like material design

### ISSUE THREAD

**Issue by tanmayparmar** [akveo/nebular#1115]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [* ] feature request

### Issue description
Are you guys planning to have something like this. As a user and developer i personally find it more useful and beneficial to end user.

**Current behavior:**
There is no InputBox with outline border. 

**Expected behavior:**

There should be Input box with outline border like one in material design. 

![image](https://user-images.githubusercontent.com/7348352/50520409-27bf6800-0a8e-11e9-9a1a-1735fd729138.png)

This kind of box make it more usability for end user as they know what kind of data they need to input with that place holder.

**Comment by Tibing** [comment]
Hi @tanmayparmar, we're not planning to this in the nearest version.

**Comment by Tibing** [comment]
Hi @tanmayparmar, also, you may check [the documentation](https://akveo.github.io/nebular/docs/components/input/overview#nbinputdirective) of the input component. It has examples with the outline.
