### ISSUE TITLE
Text doesn't wrap in Chat UI

### ISSUE THREAD

**Issue by jjgriff93** [akveo/nebular#1118]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**
In the chat UI, when a message goes over multiple lines, it doesn't wrap - so words are cut off midway through and makes the message hard to read.

![image](https://user-images.githubusercontent.com/25235950/50543712-2ea5c200-0bd7-11e9-9375-e8f2c8912242.png)

**Expected behavior:**
Text wraps so words are moved to a new line when necessary and kept intact

**Steps to reproduce:**
Use chat UI component out of the box and send/receive a long message

Nebular version: 3.0.1

**Comment by Urban123** [comment]
When is this expected?

**Comment by robin4002** [comment]
Hi,
You can use css to format \n as a new line:
```css
nb-chat-message {
    white-space: pre-line;
}
```

**Comment by yggg** [comment]
Fixed by #1408
