### ISSUE TITLE
Getting Template parse errors: The pipe 'date' could not be found while running "ng build --prod"

### ISSUE THREAD

**Issue by mobarokhossain** [akveo/nebular#1122]
**Getting date pipe error while running "ng build --prod"**

> Using angular version 7.1.4

@rande @ceefour @beeman @mterwoord @nnixaa
If you are available, please help me to resolve this issue.

![image](https://user-images.githubusercontent.com/14954948/50691326-90907c80-105a-11e9-8dbe-bfd495cebe42.png)

**Comment by beeman** [comment]
@mobarokhossain it's a bit hard to find the issue without a sample repo. Feel free to share the repo with me and I will take a look to see if I can find it.

**Comment by juliusiqbal** [comment]
set **enableIvy** to false in **angularCompilerOptions** in tsconfig.json or tsconfig.app.json,
`"angularCompilerOptions": {
    "enableIvy": false
}`

**Comment by mobarokhossain** [comment]
@juliusiqbal  bhai, Its worked for me.
I appreciate your feedback. thanks a lot!

**Comment by mobarokhossain** [comment]
@beeman thanks a lot for your response.
