### ISSUE TITLE
How to use time picker in nbDatepicker?

### ISSUE THREAD

**Issue by karthikkavin** [akveo/nebular#1126]
Hi!!! 
Please help how to add time picker feature while using nbDatepicker?

**Comment by Tibing** [comment]
Hi @karthikkavin, for now, time picker is not available in Nebular.

**Comment by bessam-haj-salem** [comment]
First you must import it in your module :

import {NbTimepickerModule } from "@nebular/theme";
@NgModule({
  imports: [
    // ...
    NbTimepickerModule,
  ],
})
Second add the NbTimepickerModule.forRoot() to your module too :

@NgModule({
  imports: [
    // ...
    NbTimepickerModule.forRoot(),
  ],
})
for more details this is the link you need : https://akveo.github.io/nebular/docs/components/timepicker/overview#nbtimepickerdirective
