### ISSUE TITLE
Provide a way to hash password on register/login

### ISSUE THREAD

**Issue by nmorenor** [akveo/nebular#1128]
Right now when you register/login using the NbPasswordAuthStrategy at the time when the request is sent to the back-end on the specified endpoint. The password is on plain/text, it would be nice to add a hash function, as a parameter of the strategy setup, that is used to get a hash for the password before it is sent to the back-end. May be also have some pre-built hash functions?

### Issue type

**I'm submitting a Feature Request

* [ ] bug report
* [ x ] feature request

**Comment by Tibing** [comment]
Hi @nmorenor, please, check[ this issue ](https://github.com/akveo/ngx-admin/issues/1572#issuecomment-368895438)for the detailed answer. Even if you really want to do this, you may process your passwords in HTTP interceptors.
