### ISSUE TITLE
Class constructor OverlayContainer cannot be invoked without 'new'

### ISSUE THREAD

**Issue by calchuchesta** [akveo/nebular#1134]
### Issue type

**I'm submitting a ...** 
* [ X ] bug report
* [    ] feature request

### Issue description

**Current behavior:**
After updating from Angular 5 to 7.1 and updating the necessary code, this error pops up. The app builds, the error appears on the browser console.

**Expected behavior:**
No error.

**Steps to reproduce:**
Update to Angular 7 from a previous version and run ng serve.

**Related code:**
N/A

### Other information:

```
Node v10.6.0
npm 6.1.0
Chrome 71
Windows 10
```

**Angular, Nebular**
```
Angular 7.1.4
Nebular 3.1.0
```

**Comment by nnixaa** [comment]
Closing as duplicate.
