### ISSUE TITLE
question about  method:   isAuthenticated() 

### ISSUE THREAD

**Issue by im-Luxqi** [akveo/nebular#1156]
i don`t understand this method;
who can tell me how can return true,  it always return false;
![image](https://user-images.githubusercontent.com/33117225/51169637-630fc280-18e7-11e9-986a-af5611ae22cb.png)
what is auth token?
thanks;

**Comment by Tibing** [comment]
Hi @im-Luxqi, could you please provide us with more context? Meanwhile, auth token is an authenticate token (JWT for example) which you have to acquire from your backend service. `isAuthenticated()` method will return true if your token is in storage and not expired.

**Comment by im-Luxqi** [comment]
> Hi @im-Luxqi, could you please provide us with more context? Meanwhile, auth token is an authenticate token (JWT for example) which you have to acquire from your backend service. `isAuthenticated()` method will return true if your token is in storage and not expired.

Thank you for your answer

**Comment by nnixaa** [comment]
Seems resolved.
