### ISSUE TITLE
Add Time Picker

### ISSUE THREAD

**Issue by alexsintoni** [akveo/nebular#1168]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**
It would be nice to add a Time Picker component to the Nebular Framework.
I would suggest to create similar to [angular-material-time-picker](https://www.npmjs.com/package/angular-material-time-picker) or [ngx-material-timepicker](https://github.com/Agranom/ngx-material-timepicker) because they have a very good user experience.

It sould be nice to have it also integrated to the Datepicker

**Comment by maciejniedzielski** [comment]
Hello.
What's the status of this issue? It would be great to get implementation of timepicker and use it in my new project that will be based on Nebular :smiley: 

I will be forced to make custom timepicker component for this project so I thought that maybe I can help you with this implementation, but how about design? I looked for timepicker design in Eva Design System but unfortunately I didn't find one.

For now, I decided to present it as follow: 
![timepicker](https://user-images.githubusercontent.com/32812848/61620097-6dcd5a80-ac70-11e9-915d-602bb3147010.png)

Are you planning to design it on your own or specify component's behaviour? Maybe my custom component based on your designed guidelines (that you will describe somewhere) will be sufficient to contribute to this project.

**Comment by alexsintoni** [comment]
Hi @maciejniedzielski 

that would be great. I need this too.
Just one point, if you want to implement this component, can I suggest you to use this UI: [angular-material-time-picker](https://www.npmjs.com/package/angular-material-time-picker), here the [demo](https://codepen.io/mattbajorek/pen/OpGVyv)

In my opinion, this user experience is very good. It has the same user experience of the timepicker in Google Calendar to create an appointment. 
Moreover, there is even the possibility to change the format from 12h to 24h, which is more flexible and it can be used everywhere.

**Comment by nvmnghia** [comment]
Please add this too...

**Comment by Olivier4444** [comment]
Yes, we are truly missing it as well. Please add this

**Comment by beriniwlew** [comment]
Let me add my voice here as well.

**Comment by papiliond** [comment]
+

**Comment by arpansac** [comment]
+1

**Comment by geogramdotcom** [comment]
+1

**Comment by xdrago1** [comment]
+1

**Comment by notsaltydev** [comment]
+1

**Comment by khalimec** [comment]
We are missing a bunch of components, and the timepicker is the most needed component (99% needed), therefore we are considering in the future to migrate from Nebular to google material.

**Comment by murbanowicz** [comment]
@nnixaa  I would say interest in this component is pretty high so P3 is quite too low...

**Comment by AbdallahAbdedaiem** [comment]
I think such a component i needed in so many project. If you're planning to make one soon, let us know.

**Comment by murbanowicz** [comment]
@nnixaa Thank you for increasing the priority! I appreciate it so much! 
I think we will all appreciate some updates on that.

**Comment by ambativamsi** [comment]
Need this!!
Good to have this one within datepicker

**Comment by murbanowicz** [comment]
@nnixaa would you mind to state totally rough estimation when it will be implemented? At the moment it is go/no-go with Nebular for me as I will need a lot of this in my project...

**Comment by nnixaa** [comment]
This is a work in progress now, we anticipate having it released in 2-3 upcoming weeks.

**Comment by murbanowicz** [comment]
Wow! Love it! 24 hours format will be supported ?

**Comment by nnixaa** [comment]
Yes, both am/pm and 24h formats will be supported.

**Comment by alexsintoni** [comment]
@nnixaa 

in the meantime that you are working on it, will you fix also this bug #2338 ?
Another question, the timepicker will be also included into the calendar as well?
Like [datetimepicker](https://h2qutc.github.io/angular-material-components/datetimepicker)

**Comment by praveentcom** [comment]
@nnixaa, we're currently doing the UI design in Sketch. Is the layout fixed so that we can use them to design right now.

It would be even fine if time picker is available in the repo a few weeks later.

**Comment by praveentcom** [comment]
@nnixaa, is the TimePicker feature released?

**Comment by MAbdanM** [comment]
> Hello.
> What's the status of this issue? It would be great to get implementation of timepicker and use it in my new project that will be based on Nebular 😃
> 
> I will be forced to make custom timepicker component for this project so I thought that maybe I can help you with this implementation, but how about design? I looked for timepicker design in Eva Design System but unfortunately I didn't find one.
> 
> For now, I decided to present it as follows:
> ![timepicker](https://user-images.githubusercontent.com/32812848/61620097-6dcd5a80-ac70-11e9-915d-602bb3147010.png)
> 
> Are you planning to design it on your own or specify component's behaviour? Maybe my custom component based on your designed guidelines (that you will describe somewhere) will be sufficient to contribute to this project.

Can you give me for your code?

**Comment by arpansac** [comment]
This is already live!

> > Hello.
> > What's the status of this issue? It would be great to get implementation of timepicker and use it in my new project that will be based on Nebular 😃
> > I will be forced to make custom timepicker component for this project so I thought that maybe I can help you with this implementation, but how about design? I looked for timepicker design in Eva Design System but unfortunately I didn't find one.
> > For now, I decided to present it as follows:
> > ![timepicker](https://user-images.githubusercontent.com/32812848/61620097-6dcd5a80-ac70-11e9-915d-602bb3147010.png)
> > Are you planning to design it on your own or specify component's behaviour? Maybe my custom component based on your designed guidelines (that you will describe somewhere) will be sufficient to contribute to this project.
> 
> Can you give me for your code?
