### ISSUE TITLE
How can I  layout similar to  Bootstrap 12 columns

### ISSUE THREAD

**Issue by leopard168** [akveo/nebular#1170]
I  am familiar to  Bootstrap  12 columns layout .   For example,   using  Bootstrap like this ： 
`
 < class="col-6" >
`

but Now , I am using nb-layout just like below .   I  do not know how to  set the column percentage.  for example :

`
  <nb-layout-column >
     ......    
   </nb-layout-column>
`

I am wondering how to achieve the layout using Nebular like Bootstrap with column ：

I  am looking forwards to your feedback.

with best regards

**Comment by nnixaa** [comment]
Closing as it seems answered.
