### ISSUE TITLE
NbPasswordAuthStrategy refresh token concept

### ISSUE THREAD

**Issue by uracs** [akveo/nebular#1178]
Hi!

I want to implement a refreshing token concept with NbPasswordAuthStrategy but I can't find how I can store and reach refresh token using NbAuthService.
Is it possible to configurate the NbPasswordAuthStrategy class, or I have to write a custom logic?
If you had an example for this I would be very glad. 

Thanks advanced,
l.

**Comment by nnixaa** [comment]
Let's close this one as a duplicate of https://github.com/akveo/nebular/issues/1131
