### ISSUE TITLE
nb-sidebar-content is not a known element

### ISSUE THREAD

**Issue by tdzierza** [akveo/nebular#118]
/docs/components/sidebar - example of fixed sidebar not working

Uncaught Error: Template parse errors:
'nb-sidebar-content' is not a known element

**Comment by nnixaa** [comment]
Hi @tdzierza, could you please post a complete example?

**Comment by kenji-1996** [comment]
Yeah the example for creating a sidebar/documentation for implimenting nebular found here: https://akveo.github.io/nebular/#/docs/components/sidebar gives a snippet of code,
```
<nb-sidebar left fixed state="collapsed">
 <nb-sidebar-header>Header</nb-sidebar-header>
 <nb-sidebar-content>
   Menu or another component here
 </nb-sidebar-content>
 <nb-sidebar-footer>
   Footer components here
 </nb-sidebar-footer>
</nb-sidebar>
```
The nb-sidebar-content gives an error and I dont see any way of 'importing' a module for this, I think its just an example of a component you would put in yourself

**Comment by nnixaa** [comment]
Thanks, @kenji-1996, looks like an error in the documentation.
