### ISSUE TITLE
Compile error in @nebular/theme schematics folder version 3.0.1

### ISSUE THREAD

**Issue by smithbrianscott** [akveo/nebular#1183]
### Issue type

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
I am currently running @nebular/theme version 2.0.1 and tried updating to version 3.1.0. After updating and running the project I get the following error: 

`ERROR in node_modules/@nebular/theme/schematics/ng-add/register-theme/index.d.ts(9,82): error TS1005: ',' expected.
node_modules/@nebular/theme/schematics/ng-add/register-theme/index.d.ts(9,131): error TS1144: '{' or ';' expected.
node_modules/@nebular/theme/schematics/ng-add/register-theme/index.d.ts(9,136): error TS1005: ';' expected.
node_modules/@nebular/theme/schematics/ng-add/register-theme/index.d.ts(9,138): error TS1128: Declaration or statement expected.
node_modules/@nebular/theme/schematics/ng-add/register-theme/index.d.ts(13,78): error TS1005: ',' expected.
node_modules/@nebular/theme/schematics/ng-add/register-theme/index.d.ts(13,127): error TS1144: '{' or ';' expected.
node_modules/@nebular/theme/schematics/ng-add/register-theme/index.d.ts(13,132): error TS1005: ';' expected.
node_modules/@nebular/theme/schematics/ng-add/register-theme/index.d.ts(13,134): error TS1128: Declaration or statement expected.
node_modules/@nebular/theme/schematics/ng-add/setup.d.ts(6,50): error TS1144: '{' or ';' expected.`

**Expected behavior:**
Compile without issue

**Steps to reproduce:**
Angular Version: 6.0.0
Prevously running 2.0.1 and ran the following in the console:
`npm install @nebular/theme@latest`

**Related code:**

A sample application via GitHub

StackBlitz [StackBlitz Seed Project](https://stackblitz.com/github/akveo/nebular-seed)

-->

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by nnixaa** [comment]
Hi @smithbrianscott, could you provide a reproducible example?

**Comment by smithbrianscott** [comment]
Unfortunately, I cannot provide my project. I tried reproducing it with StackBlitz and couldn't. I will trouble more on my end. I ended up staying with version 2.0.1 for now. 

Is the 3.0.1 version only compatible with Angular 7?

**Comment by nnixaa** [comment]
Yes, 7+ version.

**Comment by nnixaa** [comment]
Closing as it seems outdated. Please open a new issue if you still experience this behavior.
