### ISSUE TITLE
Changing the font family to "Open-Sans" causes significant performance degradation

### ISSUE THREAD

**Issue by swayam18** [akveo/nebular#1192]
### Issue type

**I'm submitting a ...**

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Loads open-sans font after main css, slowing down page load

**Expected behavior:**
Preloads open-sans font. Google auditor complains about un-preloaded font.

**Steps to reproduce:**
1. Set main font to: "Open Sans"
2. Run google chrome's audit feature

### Other information:

**npm, node, OS, Browser**
Node, npm: v10.11.0, 6.4.1

**Angular, Nebular**
Angular: 6.0.0
Nebular: 2.0.0

**Comment by nnixaa** [comment]
I don't think this is a Nebular issue as a UI Library, but the app itself. Closing.
