### ISSUE TITLE
NbDatepicker "next month" skips one month

### ISSUE THREAD

**Issue by marchrius** [akveo/nebular#1195]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

When open the datepicker and from January 29 or January 30 go to the next month it shows March view instead of February

**Expected behavior:**

**Steps to reproduce:**

Go to official ngx-admin demo page in the datepicker section and open datepicker, then simply go to the next month by arrow.

You can also see the bug in month selection, there are 2 "Mar" after January. I'll attach the screenshot.

![schermata 2019-01-29 alle 12 16 59](https://user-images.githubusercontent.com/534837/51967608-1217d680-2470-11e9-8014-db6e2ce38d78.png)
![schermata 2019-01-30 alle 11 11 45](https://user-images.githubusercontent.com/534837/51974380-12b86900-2480-11e9-898d-f3d6a01bfd4e.png)

This is a video demostration
https://youtu.be/ismJz5y2yiQ

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
node: v11.8.0
npm: 6.7.0
Darwin Mat-Pro-di-Luna.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
Google Chrome: 71.0.3578.98 (Official build) (a 64 bit)
```

**Angular, Nebular**
I think that this informations are not useful as the bug is present also in official demo.
```
Angular 6.1.0
Nebular 3.1.0
```

**EDIT:** This seems to happen on every month that has more days than next.

Eg.
31st May skips to July instead of June.

**Comment by developcodeza-matthew** [comment]
Was about to submit this myself 😅.  Also when selecting the greyed out numbers next to Jan it jumps to March, skipping Feb. 

![screen shot 2019-01-30 at 4 20 47 pm](https://user-images.githubusercontent.com/26629247/51987419-22997280-24ab-11e9-817a-d3495166b1c4.jpg)

For the mean while you an select the first March option, then reselect the year -> month and now Feb should be available. Otherwise you can just type the date as dd Feb, yyyy in the input field.

**Comment by marchrius** [comment]
@developcodeza-matthew ATM the problem seems to be the @nebular/date-fns because with @nebular/moment the problem does not exists.

**Comment by marchrius** [comment]
A possible solution seems to be use @nebular/moment BUT this module does not support "null" or "undefined" initial dates, so I've implemented the same service code on my own and added the check for null / undefined vallues
