### ISSUE TITLE
Add Switcher component directly to Nebular framework

### ISSUE THREAD

**Issue by alexsintoni** [akveo/nebular#1196]
* [ ] bug report
* [x] feature request

### Issue description

In my opinion, it would be nice to have the [Switcher Component](https://github.com/akveo/ngx-admin/tree/master/src/app/%40theme/components/switcher) which is in [ngx-admin](https://github.com/akveo/ngx-admin) dashboard directly in [Nebular](https://akveo.github.io/nebular/) framework.

**Comment by nnixaa** [comment]
Closing as a duplicate of https://github.com/akveo/nebular/issues/778
