### ISSUE TITLE
how to customize auth components?

### ISSUE THREAD

**Issue by kwesifokuo** [akveo/nebular#12]
Hello. I am trying to remove some parts of the login page but do not know how to figure it out. Do I have to edit the metadata file in @nebular/auth ?
I copied the files to the app folder to make changes but still no effect. Please help.
Thanks.

**Comment by nnixaa** [comment]
Hey @kwesifokuo, basically you can just copy over the sources of the components into your project and customize them as you need.

**Comment by YukiDmZhao** [comment]
I just copy source and into myself project ,is good!

**Comment by kwesifokuo** [comment]
Thanks for your quick help. One last thing, I have copied @nebular folder from node_modules to myproject/src/app folder. But when I edit the login.component.metadata.json file, the html still shows the same. Perhaps, I am doing it wrong. Can you please guide me? Thanks a lot!

**Comment by nnixaa** [comment]
@kwesifokuo the node_modules one contains the `built` version of the components, but you need the sources. You can get the sources here https://github.com/akveo/nebular/tree/master/src/framework/auth/components and should be all right :)

**Comment by kwesifokuo** [comment]
Thanks. I have downloaded the entire source folder, I have copied the auth folder in src/framework/auth to myproject/app/auth and I still try changes and don't see them. Sorry to be such a bother. :( but I don't know what to do to make changes to the login template html since whatever I do so far doesn't reflect. Please can you give me a directory structure example of where to put the _auth_ folder into my myproject folder?

**Comment by nnixaa** [comment]
@kwesifokuo I would say this is not an issue with Nebular, it's more of a general Angular framework knowledge. Please consider looking through the Angular documentation or post a question with a reproducible demo on StackOverflow.
In your particular case make sure that your `app.routes` correctly linked with your copied auth components, plus, as you copied them you have to tell Angular about that - so you need import them in some of your Angular modules (depending on your project structure). Hope this helps.

**Comment by Zhigalin** [comment]
> Hey @kwesifokuo, basically you can just copy over the sources of the components into your project and customize them as you need.

And what about ngx-admin?
How to use that thing?
Where is the documentation?
What it sends to the backend?
What it expects in response?

**Comment by wilson-young** [comment]
> In your particular case make sure that your app.routes correctly linked with your copied auth components, plus, as you copied them you have to tell Angular about that - so you need import them in some of your Angular modules (depending on your project structure). Hope this helps.

can we have documentation about this? i also stuck in this auth setting part. Thanks

**Comment by mantupani17** [comment]
hello @nnixaa  how do i use my custom css

**Comment by nabgilby** [comment]
I am new to Nebular, and looking over the documentation and ngx-admin code. It would be great to have more example projects using nebular beyond ngx-admin, with different auth providers to learn from, are there any that you can point me to? Probably would help  kwesifokuo as well as others to use an adopt Nebular.
