### ISSUE TITLE
🎁 ✉️ 📆 [Sticky] Nebular Release Notes & News

### ISSUE THREAD

**Issue by nnixaa** [akveo/nebular#1204]
- :newspaper: This is a read-only Nebular newsletter. 
- :mailbox: Only latest news and release notes.
- :rocket: Subscribe (on the right) to stay tuned!

**Comment by nnixaa** [comment]
## :tada: v3.2.0 (2019-01-31)

**Release Notes:** 
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#320-2019-01-31


### Highlights 🚀 

✅ :speech_balloon: **Popover** and Tooltip now can accept dynamic input:
```
<button [nbPopover]="dynamicVariable">Show Popover</button>
...

changePopoverContent() {
  this.dynamicVariable = 'New Popover Text';
}
```
*Examples*
https://akveo.github.io/nebular/docs/components/popover/overview
https://akveo.github.io/nebular/docs/components/tooltip/overview

✅ :feet: **Stepper** got `linear` and `disableStepNavigation` modes

*Examples*
https://akveo.github.io/nebular/docs/components/stepper/overview


✅ 📑 **Tab** now can be disabled using `disabled` property

*Examples*
https://akveo.github.io/nebular/docs/components/tabs/overview

**Comment by nnixaa** [comment]
## :tada: v3.3.0 (2019-02-18)

**Release Notes:** 
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#330-2019-02-18


#### Highlights :rocket: 

✅ :palm_tree: new **Tree Grid** component!

*Examples*
https://akveo.github.io/nebular/docs/components/tree-grid/overview

✅ :speech_balloon: **Context Menu** can accept dynamic input.

✅ :speech_balloon: new **Context Menu** `right-click` example:
```

  <button nbButton
          [nbContextMenu]="items"
          nbContextMenuTrigger="noop"
          (contextmenu)="open()">
    Right Click
  </button>

//...
  @ViewChild(NbContextMenuDirective) contextMenu: NbContextMenuDirective;
  
  open() {
    this.contextMenu.show();
    return false;
  }

```
*Examples*
https://akveo.github.io/nebular/docs/components/context-menu/overview#nbcontextmenudirective


✅ :hammer: **Bug-fixes** and improvements!

**Comment by Tibing** [comment]
## 🎉 v3.3.0 (2019-02-25)
**Release Notes:**
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#340-2019-02-25

#### Highlights 🚀
✅ 🌴 **tree-grid** allows define getters for row properties:

```
this.dataSource = dataSourceBuilder.create(this.data,  {
  dataGetter: (row: Row) => row,
  childrenGetter: (row: Row) => row.childEntries,
  expandedGetter: (row: Row) => !!row.expanded,
});
```
_Examples_
https://akveo.github.io/nebular/docs/components/tree-grid/overview

✅ 📑 **route-tabset** got configurable *routerLinkActiveOptions*:

_Examples_
https://akveo.github.io/nebular/docs/components/tabs/overview#nbroutetabsetcomponent

✅ 🔨 **Bug-fixes** and improvements!

**Comment by nnixaa** [comment]
## :tada: v3.4.1 (2019-02-25)
**Release Notes:**
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#341-2019-03-18

#### Highlights :rocket:
✅ :speech_balloon: **Context Menu** arrow position is fixed in IE.

✅ :date: **Date Picker** fixed not starting from date typed in input:

✅ :hammer: **Bug-fixes** and improvements!

**Comment by yggg** [comment]
### :tada: v3.4.2 (2019-04-01)
**Release Notes:**
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#342-2019-03-31

#### Highlights :rocket:
✅ 🐛 Fixed **Select**, **Datepicker** and other overlay components failing to open after host component being destroyed and re-created.

✅ 🐛 **Menu** items with the specified fragment can now be selected.

✅ :hammer: **Bug-fixes** and improvements!

**Comment by nnixaa** [comment]
## 🎉 v3.5.0 (2019-04-16)
**Release Notes:**
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#350-2019-04-12

#### Highlights 🚀
🔍 **search** now has `input` event allowing to create suggestions list
_Docs_
https://akveo.github.io/nebular/docs/components/global-search/api#nbsearchservice

✅ 🐛 Fixed ** calendar** duplicating months

✅ 🐛 Fixed **Dialog**, **Select** and other overlay components breaking page by adding an unnecessary bottom offset

✅ 🔨 Other **Bug-fixes** and improvements!

**Comment by yggg** [comment]
## 🎉 v4.0.0 (2019-06-03)
**Release Notes:**
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#400-2019-06-03

#### Highlights 🚀

✅ :nail_care: Eva Design System and updated theming system

✅ :new_moon_with_face: New Dark theme

✅ :arrow_up: Angular 8

✅ :truck: distributed in both ES5 and ES2015 formats, meaning you can build your apps with target ES2015

✅ :wrench: Unified component interfaces for statuses, shapes, etc. (@Input's and @Output's)

✅ 🔨 Lots of **[bug-fixes and improvements](https://github.com/akveo/nebular/blob/master/CHANGELOG.md#400-2019-06-03)**!

**Comment by yggg** [comment]
## 🎉 v3.6.0 LTS (2019-06-07)
**Release Notes:**
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#360-lts-2019-06-07

#### Highlights 🚀
:truck: Nebular 3 updated to Angular 8 and distributed in both ES5 and ES2015 formats. We will support this version with critical updates for 6 months.

✅ 🐛 **select** now allows usage of falsy values in nb-option

✅ 🔨 Other **[Bug-fixes and improvements](https://github.com/akveo/nebular/blob/master/CHANGELOG.md#360-lts-2019-06-07)**!

**Comment by yggg** [comment]
## 🎉 v3.6.1 (2019-06-14)
**Release Notes:**
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#361-2019-06-14

#### Highlights 🚀

✅ 🐛 Fix for disappearing **header** and **sidebar** on pages with select

**Comment by yggg** [comment]
## 🎉 v4.1.0 (2019-06-14)
**Release Notes:**
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#410-2019-06-14

#### Highlights 🚀

✅ :floppy_disk: Version select in the documentation for those who still on 3 LTS version

✅ 🐛 Fix **header** and **sidebar** disappearing when opening select

✅ 🐛 **checkbox** now emit change event only after user interaction. `value` input deprecated and should be replaced with `checked`.

**Comment by yggg** [comment]
## 🎉 v4.1.1 (2019-07-09)
**Release Notes:**
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#411-2019-07-09

#### Highlights 🚀

✅ 🖍 New classes for text styling like `.text-primary`, `.text-danger`, `.subtitle`, `.subtitle-2` etc.

✅ 🐛 Fixed compacted **sidebar** expanding when clicking on menu icon

✅ 🔨 Updated js themes

✅ 🔨 Lots of other **[bug-fixes and improvements](https://github.com/akveo/nebular/blob/master/CHANGELOG.md#411-2019-07-09)**!

**Comment by yggg** [comment]
## 🎉 v4.1.2 (2019-07-12)
**Release Notes:**
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#412-2019-07-12

#### Highlights 🚀


✅ 🐛 Fixed **menu** items highlight when item has fragment

✅ 🐛 Fixed **layout** content changing width when overlay blocks scroll in `withScroll` mode

✅ 🔨 Other **[bug-fixes and improvements](https://github.com/akveo/nebular/blob/master/CHANGELOG.md#412-2019-07-12)**!

**Comment by yggg** [comment]
## 🎉 v4.1.3 (2019-07-29)
**Release Notes:**
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#413-2019-07-29

✅ 🐛 Minor **[bug fixes](https://github.com/akveo/nebular/blob/master/CHANGELOG.md#413-2019-07-29)**

**Comment by yggg** [comment]
## 🎉 v4.2.0 (2019-08-22)
**Release Notes:**
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#420-2019-08-22

#### Highlights 🚀

✅ :boom: New [toggle](https://akveo.github.io/nebular/docs/components/toggle/overview) component

✅ 🐛 Fixed **context menu** not being rendered after router navigation with a layout change. Other overlay components with the same problem should work now too.

✅ 🔨 Other **[bug-fixes](https://github.com/akveo/nebular/blob/master/CHANGELOG.md#420-2019-08-22)**!

**Comment by yggg** [comment]
## 🎉 v4.2.1 (2019-08-29)
**Release Notes:**
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#421-2019-08-29

#### Highlights 🚀

✅ :raised_hands: **menu**, **tabs**, **actions** and other components with icons now accept icon config with pack, status and options settings

✅ :bookmark_tabs: New docs article on **auth** backend API endpoints 

✅ 🐛 Fixed memory leak in **window** component

✅ 🔨 Other **[bug-fixes](https://github.com/akveo/nebular/blob/master/CHANGELOG.md#421-2019-08-29)**!

**Comment by yggg** [comment]
## 🎉 v4.3.0 (2019-09-20)
**Release Notes:**
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#430-2019-09-20

#### Highlights 🚀

✅ :date: **calendar** now has week number column

**Comment by yggg** [comment]
## 🎉 v4.4.0 (2019-10-07)
**Release Notes:**
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#440-2019-10-07

#### Highlights 🚀

💅 Nebular 4.4.0 features synchronization with Eva 1.1 adding transparent colors.

✅ 🔨 Other **[bug-fixes and improvements](https://github.com/akveo/nebular/blob/master/CHANGELOG.md#440-2019-10-07)**!

**Comment by yggg** [comment]
## 🎉 v4.5.0 (2019-10-31)
**Release Notes:**
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#450-2019-10-31

#### Highlights 🚀

💅 Nebular 4.5.0 introduces a new basic and control component statuses.

Please note, some theme properties were changed. If you use Nebular Theming or have custom themes, check out updated variables list.

✅ 🐛 Fixed issue with the **icon** being rendered with `null` in Microsoft Edge (#2043).

✅ 🔨 Other **[bug-fixes and improvements](https://github.com/akveo/nebular/blob/master/CHANGELOG.md#450-2019-10-31)**!

**Comment by yggg** [comment]
## 🎉 v4.6.0 (2019-11-26)
**Release Notes:**
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#460-2019-11-26

#### Highlights 🚀

Angular 9 RC compatibility.

✅ 🔨 Lots of **[bug-fixes and improvements](https://github.com/akveo/nebular/blob/master/CHANGELOG.md#450-2019-10-31)**!

**Comment by yggg** [comment]
## 🎉 v5.0.0 (2020-03-09)
**Release Notes:**
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#400-2019-06-03

#### Highlights:

:truck: Angular 9.

:sparkles: New [autocomplete](https://akveo.github.io/nebular/docs/components/autocomplete/overview#nbautocompletedirective) component.

- New `nb-form-field` component allows you to add an icon or button to `nbInput`.

🔨 Lots of **[bug-fixes and improvements](https://github.com/akveo/nebular/blob/master/CHANGELOG.md#500-2020-03-09)**!

**Comment by yggg** [comment]
Release notes moved to the [releases page](https://github.com/akveo/nebular/releases).
