### ISSUE TITLE
WARNING: Invalid value for $grid-breakpoints

### ISSUE THREAD

**Issue by alexsintoni** [akveo/nebular#1208]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
When I start my project containing Nebuar framework with `npm start` I get:
```
WARNING: Invalid value for $grid-breakpoints: This map must be in ascending order, but key 'is' has value 400px which isn't greater than 1200px, the value of the previous key 'xl' !
    node_modules/bootstrap/scss/_functions.scss 16:7          _assert-ascending()
    node_modules/bootstrap/scss/_variables.scss 201:1         @import
    node_modules/@nebular/bootstrap/styles/_globals.scss 8:9  @import
    stdin 7:9                                                 root stylesheet

WARNING: Invalid value for $container-max-widths: This map must be in ascending order, but key 'is' has value 380px which isn't greater than 1140px, the value of the previous key 'xl' !
```

**Expected behavior:**
Not warnings

**Steps to reproduce:**

### Other information:

**npm, node, OS, Browser**
Node version: v8.11.4
npm version: 6.5.0
Browser: Chrome

**Angular, Nebular**
Angular version: 7.2.2
@Nebular/Theme version: 3.2.1

**Comment by wallopthecat** [comment]
Downgrade to Bootstrap 4.1 
https://github.com/twbs/bootstrap/issues/27927

**Comment by yggg** [comment]
Can't see any errors with latest 3 and 4 versions. Closing as resolved.
