### ISSUE TITLE
Browser cache problem

### ISSUE THREAD

**Issue by serbasii** [akveo/nebular#1227]
hi, how to prevent the browser cache, when i deployed as versioning  on nginx, not redirecting to upper version. Only way ctrl+f5.

old    host.com/v4
new  host.com/v5

**Comment by yggg** [comment]
Hi @serbasii. There is `outputHashing` option for `ng build` command (also configurable in angular.json). When it's on, Angular adds hash to resources file names. So once file change, its name in resulting bundle changes as well and the browser will load this file again.
