### ISSUE TITLE
Configurable request headers for auth strategies

### ISSUE THREAD

**Issue by yggg** [akveo/nebular#1232]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**
There is no way to specify additional headers for requests sent from auth strategies.

**Expected behavior:**
Be able to set additional headers in strategy options.

**Related code:**
https://github.com/akveo/nebular/blob/3343136e8b50b29d18cd8e90ba67575f0001e4e8/src/framework/auth/strategies/oauth2/oauth2-strategy.ts#L249
https://github.com/akveo/nebular/blob/3343136e8b50b29d18cd8e90ba67575f0001e4e8/src/framework/auth/strategies/password/password-strategy.ts#L160

**Comment by Eolykab** [comment]
As this been implemented?

**Comment by Eolykab** [comment]
Any feedbak on the above?

**Comment by Eolykab** [comment]
Any feedback on this issue?

**Comment by benjaminmbrown** [comment]
How do we add add custom headers?

**Comment by Aaron-Linkforce** [comment]
@nnixaa  Was this ever seen to?

I need to set different auth headers - instead of 'email' and 'password' I need to set something like 'x-username' and 'x-password'.
