### ISSUE TITLE
can't custom UI login component

### ISSUE THREAD

**Issue by xeti34** [akveo/nebular#1234]
### Issue type

**I'm submitting a ...** 

* [X ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Error: Can't resolve all parameters for NgxLoginComponent: ([object Object], ?, [object Object], [object Object]).

**Expected behavior:**
I try to extend NgLoginComponent with a constructor inside

**Related code:**

```
import {ChangeDetectorRef, Component, Injectable} from '@angular/core';
import {NbAuthService, NbLoginComponent} from '@nebular/auth';
import {AuthService} from '../auth.service';
import {Router} from '@angular/router';


@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
})

export class NgxLoginComponent extends NbLoginComponent {
  constructor(service: NbAuthService, options: {}, cd: ChangeDetectorRef, routes: Router){
    super(service, options, cd, routes);
  }
}
```

The issue appear only if I use constructor.
I need to use a constructor because I need implement my own auth service in this component.
### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: v11.6.0, 6.5.0-next.0
OS: macOS Mojave (10.14.2)
Browser: Chrome  72.0.3626.96 
-->
```

**Comment by yggg** [comment]
Hi @xeti34. You need to use `@Inject(NB_AUTH_OPTIONS) protected options` as a second parameter of constructor, instead of `options: {}`. See dependency-injection in angular [docs](https://angular.io/guide/dependency-injection).

**Comment by xeti34** [comment]
@yggg it's working !!!! thank's 👍

**Comment by mugambiwarwema** [comment]
@yggg  My case is same and also different kindly assist because I wish to use ActivatedRoute to get url params


```
@Component({
  selector: 'ngx-register',
  templateUrl: './register.component.html',
  providers: [
    
    {provide: ActivatedRoute, useValue: { snapshot: { paramMap: { get(): string { return 'referral_code'; }, },},},},
   ]
})
export class NgxRegisterComponent extends NbRegisterComponent implements OnInit {

  constructor(
    service: NbAuthService, 
    @Inject(NB_AUTH_OPTIONS) protected options,
    cd: ChangeDetectorRef, 
    router: Router,

    @Inject(ActivatedRoute) protected activateRoute : ActivatedRoute,
  ){
    super(
      service, 
      options, 
      cd, 
      router,
      activateRoute);
  }
```


but when I try to subscribe to the params like 

```
this.activateRoute.params.subscribe(params =>{
            console.log('urlParam', params);
}
```

I get several console error leading with 

> Cannot read property 'subscribe' of undefined

**Comment by ukikalix** [comment]
Has anyone tried this on **Nebular 5**?

```
constructor(service: NbAuthService,
    @Inject(NB_AUTH_OPTIONS) protected options: {},
    cd: ChangeDetectorRef, routes: Router){
    super(service, options, cd, routes);
  }
```

I also tried that, but I get the same _**"Can't resolve all parameters"**_ error.

**Comment by mugambiwarwema** [comment]
@ukikalix 

Here's my [answer ](https://stackoverflow.com/questions/61686673/i-cannot-find-how-i-can-access-di-properties-from-a-child-class/61699122#61699122)as posted on SO

**Comment by ukikalix** [comment]
> @ukikalix
> 
> Here's my [answer ](https://stackoverflow.com/questions/61686673/i-cannot-find-how-i-can-access-di-properties-from-a-child-class/61699122#61699122)as posted on SO

The ctor always marks me the arguments it expects to receive, specifically 4 arguments, idk but I send them, and in the same way I get the error that in previous versions, this solved it

**Comment by mugambiwarwema** [comment]
your Login/Logout component inherits from Nebular Auth Component.

The parent should also inject the desired services into its constructor in
that the arguments match with those of the inherited class.

**Comment by ukikalix** [comment]
Well, I really do, it worked in version 4.x, but not in version 5.x.

Here is the code:
```
constructor(service: NbAuthService,
    @Inject(NB_AUTH_OPTIONS) protected options = {},
    cd: ChangeDetectorRef,
    router: Router) {
    super(service, options, cd, router);
  }
```

**Comment by mugambiwarwema** [comment]
Then post your errors for further scrutiny

**Comment by ukikalix** [comment]
The same error "can't resolve all parameters for ownauthlogin component in login.component.ts: ([object object], ?, [object object], [object object])."

**Comment by mugambiwarwema** [comment]
Show me the code for login.components.ts, Also, that for the class it implements.

**Comment by AvshT** [comment]
Hi,
Whats works for me its to add the @Option() annotation

**@Inject(NB_AUTH_OPTIONS) @Optional() public options**

Hope its helps
