### ISSUE TITLE
Smart table under tabs

### ISSUE THREAD

**Issue by obarazan** [akveo/nebular#1236]
Hi all,

I'm trying to create a smart table under tabs, its route me to another page. It's possible to create it in the same page under the current tab (the smart table component is located in another folder)?

Thanks & regards,
Or

**Comment by yggg** [comment]
Hi @obarazan.

**Comment by yggg** [comment]
Hi @obarazan. Sorry, not sure if I got you right. Could you please create an example on [stackblitz](https://stackblitz.com/github/akveo/nebular-seed) if my answer isn't what you asked for?

To navigate inside the current tab, the route of the current tab should have child routes and also it should have `<router-outlet>` inside. Then you'll be able to navigate to child routes within the current tab. See [example](https://stackblitz.com/edit/nebular-1236).

As for now, active tab styling not applied, when you navigate to child routes of the current tab. There is an upcoming fix (#1239). Then you'll be able to set `[activeLinkOptions]="{exact: false}"` and tab will be active even after navigation to child routes.

**Comment by obarazan** [comment]
Hi @yggg ,
Thanks
![tabs](https://user-images.githubusercontent.com/47638725/52909492-e24f3800-3291-11e9-9c22-09ef60fff04c.PNG)
 for your response.
In your example the tab provide me link to another internal page I want to display the table when I click on the tab. It is possible?
I my attached file I want to display the table instead Content #3.

**Comment by yggg** [comment]
Yes, you can. Here is [example](https://stackblitz.com/edit/nebular-1236-2?file=src%2Fapp%2Fapp.component.ts). Notice that this example uses `nb-route-tabset`, so each tab is a separate route in your app. If you don't need tabs to be routable you can use `nb-tabset`, then you can do something like this:
```
<nb-tabset>
  <nb-tab tabTitle="Home tab">
    Home
  </nb-tab>
  <nb-tab tabTitle="Table Tab">
    <table>
      <tr>
        <th>First name</th>
        <th>Last name</th>
      </tr>
      <tr>
        <td>John</td>
        <td>Doe</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Doe</td>
      </tr>
    </table>
  </nb-tab>
</nb-tabset>
```

See [docs](https://akveo.github.io/nebular/docs/components/tabs/overview#nbtabsetcomponent) for component api and more examples.

**Comment by yggg** [comment]
Closing as seems to be resolved
