### ISSUE TITLE
NbWindowService Error 'Element matching '[cdkFocusInitial]' is not focusable' 

### ISSUE THREAD

**Issue by yggg** [akveo/nebular#1238]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description
Original akveo/ngx-admin#2004

**Current behavior:**
Window service uses cached overlay container even when container removed from DOM.

**Expected behavior:**
Check if windowsContainerViewRef is still in the DOM.

**Related code:**
https://github.com/akveo/nebular/blob/3343136e8b50b29d18cd8e90ba67575f0001e4e8/src/framework/theme/components/window/window.service.ts#L127

**Comment by craigchandler** [comment]
Hitting this too, any workarounds?

**Comment by khoinguyendang** [comment]
Has this been solved yet? I have this problem too and no solution is found.

**Comment by marifnst** [comment]
is there any update for this issue ?

**Comment by surya0809** [comment]
![Screenshot 2020-10-07 024135](https://user-images.githubusercontent.com/20340431/95260609-a55cfe00-0846-11eb-8334-6e9ed27e1517.jpg)
 
The issue seems to be closed, but I am still facing this issue. Could you please help me in solving this?
