### ISSUE TITLE
NbSidebarComponent State

### ISSUE THREAD

**Issue by xndrmd** [akveo/nebular#1241]
Hi all, is it possible to know the current state of a sidebar.

Regards.

**Comment by nnixaa** [comment]
Hi @xndrmd, it seems that currently, it is not possible. Though you can subscribe to `onToggle, onCollaplse, onExpand` methods to listen to the sidebar state change.

**Comment by xndrmd** [comment]
@nnixaa Thanks for the response, though when the sidebar collapses/compacts through breakpoints we don't get notified by those observables

**Comment by baldemarnr** [comment]
Is there any updates on this? I was just going through your docs and noticed that, indeed, we're not get notified if this is done through breakpoints.
