### ISSUE TITLE
Auth require valid token by default

### ISSUE THREAD

**Issue by Tibing** [akveo/nebular#1246]
Each auth module(login, redirect, etc.) has `requireValidToken` setting which is `false` by default. If that setting set to `true` module will fail in cases of positive response (Http status 200) with an invalid token. Otherwise, it will signal that operation completed successfully, however it was actually failed.

I propose to set `requireValidToken` to `true` by default. Because it sounds more like natural behavior for modules.

**Comment by digitalberry-ahmed** [comment]
I'm using NbAuthJWTToken as wrapper class to authenticate users to /pages/** and i noticed that if i change the value of the json web token from local storage the user still authenticated even with invalid token !! below my module configuration : 
` NbAuthModule.forRoot({
      strategies : [
        NbPasswordAuthStrategy.setup({
          name : 'email' , 
          baseEndpoint : 'http://localhost:8088/api' ,
          login : {
            endpoint : '/authenticate' , 
            method : 'post',
            requireValidToken : true , 
            redirect : {
              success : '/pages'  ,
              requireValidToken : true ,
              failure : null ,
              error : true ,
            }
          } , 
          token : {
            class : NbAuthJWTToken ,
            key : 'id_token' , 
          }
        }) , 
      ],` 

So how can I verify the token validity after every route call ?
Regards

**Comment by nnixaa** [comment]
@digitalberry-ahmed could you post an example of how you make this change to the token?

**Comment by digitalberry-ahmed** [comment]
Thank you for your responsiveness @nnixaa 
fter the authentication , if I delete the last 4 characters of the token value no validation on token validity is made and the page remains accessible
![invalid-token](https://user-images.githubusercontent.com/36071409/54202498-78acfd00-44d0-11e9-9611-42284443067a.PNG)
![valid-jwt](https://user-images.githubusercontent.com/36071409/54202499-79459380-44d0-11e9-9e1c-d31c628f8131.PNG)

**Comment by nnixaa** [comment]
Well this is expected behavior since Nebular cannot be aware of the external changes you made outside of the Angular.
In this very case, you need to refresh the page to notify Nebular about the changes made.
On the other hand, if you want to manually control a token from your code - you can inject `NbTokenStorage` and call `clear` method. More details on the API https://akveo.github.io/nebular/docs/auth/nbtokenlocalstorage#nbtokenlocalstorage
