### ISSUE TITLE
Bug on layout when Dialog is open

### ISSUE THREAD

**Issue by nckenn** [akveo/nebular#1259]
i dont know if this is a bug or not, currently clone the master branch, and when i try to open dialog this happen, but on your demo its seems ok, but on my local its not. hope someone can help me :) thanks

![chrome_2019-02-19_18-29-46](https://user-images.githubusercontent.com/7109270/53008576-ac1dde00-3474-11e9-8cb7-09395fa19158.png)

**Comment by aefox** [comment]
I did some extra investigations. I found a way to reproduce this issue:
- navigate to the ngx-admin
- open developer tools
- move developer tools at the bottom of the window
- focus on the html tag in the explorer tab
- increase the developer tools height until the height of the html becomes smaller than 647px
- scroll at the bottom of the window
- open any dialog

Screenshot with the style on the html when the scroll of the page is at the top:
![image](https://user-images.githubusercontent.com/8288413/53951551-5fbed900-40d7-11e9-9f22-49a2578b2a86.png)

Screenshot with the style on the html when the scroll of the page is at the bottom:
![image](https://user-images.githubusercontent.com/8288413/53951622-8bda5a00-40d7-11e9-8aaf-358c56cc417d.png)



I don't know where this could come from. If anyone has any idea I could do a PR.

**Comment by nckenn** [comment]
for now i added this class in my styles.scss  to make it work properly : 
`.cdk-global-scrollblock {
	position: initial;
	width: initial;
	overflow: hidden;
}`

**Comment by aefox** [comment]
This seems to be coming from https://github.com/angular/material2/issues/7512 and https://github.com/angular/material2/issues/7390.

I started from @nckenn 's reply above and isolated the change to be:
```
.cdk-global-scrollblock {
  position: initial;
  overflow-y: hidden;
}
```

I have tested this fix on Edge, FF and Chrome and it works as expected (on both `ltr` and `rtl`). I wasn't able to test on IE11 because dev tools does not show me the styles for the html element (really weird).

@nnixaa @yggg what do you guys think? Should we do this override? If yes, where should this be best placed?

**Comment by nnixaa** [comment]
@aefox I guess we should try and check it doesn't introduce any performance drawbacks. I believe https://github.com/akveo/nebular/blob/master/src/framework/theme/components/cdk/overlay/_overlay.theme.scss would be a good place since we already overwriting some styles there.

**Comment by akvaliya** [comment]
What is the status on this issue? It adds top & left to html which creates issue.

**Comment by nbomberger** [comment]
For anyone that is still on 3.5.  This still works.

**Comment by sharankasandula** [comment]
> For anyone that is still on 3.5. This still works. Simply add this line to your index.html.
> 
> `<style>.cdk-global-scrollblock { position: initial; width: initial; overflow: hidden; }</style> `

For me, overflow: hidden did not work but overflow: initial worked.

**Comment by akvaliya** [comment]
For me `<style>html { overflow: hidden; }</style>` worked. Because `cdk-global-scrollblock` will be added runtime & before that scrollbar in html is generated.

**Comment by chuck0523** [comment]
This happened to me too

```css
.cdk-global-scrollblock {
  position: initial;
  overflow-y: hidden;
}
```

With only this style doesn't solve problem.
But combination with style for html worked.

```css
html {
  position: fixed;
  top: 0;
}

.cdk-global-scrollblock {
  position: initial;
  overflow-y: hidden;
}
```
