### ISSUE TITLE
nb-select doesn't deselect option when resetting ngModel

### ISSUE THREAD

**Issue by frankie567** [akveo/nebular#1260]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**

After having selected an option with `nb-select`, if the binded `ngModel` is resetted (`null` or `undefined` value) by the component, the option is still selected in the `nb-select`.

**Expected behavior:**

After having selected an option with `nb-select`, if the binded `ngModel` is resetted (`null` or `undefined` value) by the component, the option should be unselected in the `nb-select`.

**Steps to reproduce:**

* Define a data model in the component.
* Bind it to a `nb-select` in the template.
* Create a button that resets the data model to `null` on click.
* Select an option in `nb-select`.
* Click on the button.

**Related code:**

https://stackblitz.com/edit/github-naqwyy

### Other information:

* npm: 6.4.1
* node: 10.15.0
* macOS 10.14.2
* Chrome 72

**Angular, Nebular**

* @angular/core: 7.1.4
* @angular/forms: 7.1.4
* @nebular/theme: 3.3.0

**Comment by aefox** [comment]
Fix provided in https://github.com/akveo/nebular/pull/1265 (will require discussion and if approved adding some tests)

**Comment by aefox** [comment]
Fix provided in https://github.com/akveo/nebular/pull/1282

**Comment by yggg** [comment]
Closing as fix (#1282) was merged

**Comment by TeodorKolev** [comment]
This is not fixed at version 3.1.0 that we are using...
