### ISSUE TITLE
Consider to add Nebular to angular resource page, https://angular.io/resources?

### ISSUE THREAD

**Issue by WLun001** [akveo/nebular#1263]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
*  [x] feature request

### Issue description
Hi Nebula team, have you all consider to add Nebular into Angular resource page under UI components to increase discoverability?

**Comment by Tibing** [comment]
Hi @WLun001, thanks for the feature request! Our request to add Nebular into Angular resources page was merged recently and Nebular will appear there with the nearest update of angular.io
