### ISSUE TITLE
NbContextMenu stops working after parent element is "reattached"

### ISSUE THREAD

**Issue by Roman-Simik** [akveo/nebular#1273]
### Issue type

**I'm submitting a ...** 

* [x] bug report
* [ ] feature request

### Issue description
- _NbContextMenu_ **stops working** after parent element/component is "refreshed".

**Current behavior:**

- After "refreshing" the element/component, every _NbContextMenu_ inside that element/component stops working. 
- **PS:** By refreshing I don't mean using "F5", but by `detaching` and then `attaching` the parent element (or component) by custom `directive` (you can see that in repro).

**Expected behavior:**

- After "reattaching" the element/component, every _NbContextMenu_ located in that element/component should still be working.

**StackBlitz repro:**

- https://stackblitz.com/edit/github-fnq8mz

**Steps to reproduce:**

- Open atleast once the _NbContextMenu_ (by clicking on ContextMenu button) and then click "call directive refresh method" button. After that, every _NbContextMenu_ inside the `div` element in `app.component`  **stops working** and you aren't able to open it again.

### Other information:
OS: **propably ALL** (tested on Windows 10)
Browser: **propably ALL** (tested on Chrome, Firefox)
Angular: **7.1**
Nebular **3.1**
Node: **8.9.4**

All versions you can see of course in the **StackBlitz repro**

**Comment by nnixaa** [comment]
Fixed in https://github.com/akveo/nebular/pull/1316

**Comment by Roman-Simik** [comment]
Hi, so after I tested new version (3.4.2) where this bug is supposed to be fixed, it's not,
Check this [Stackblitz](https://stackblitz.com/edit/github-fnq8mz-6sefyj) with updated version
