### ISSUE TITLE
Installation Nebular hosting

### ISSUE THREAD

**Issue by Dimich0304** [akveo/nebular#128]
Hello! Can help with the installation Nebular hosting?

**Comment by nnixaa** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/akveo/nebular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
If you are looking to submit a feature request, please use the New Issue template.
