### ISSUE TITLE
Datepicker on change

### ISSUE THREAD

**Issue by jhonattan471** [akveo/nebular#1285]
* [ ] bug report
* [x ] feature request

### Issue description

Datepicker, When a user input a date, there is a way to trigger a event ? I need to have something like (change) like others inputs, so i can call my function when the date is selected.

**Comment by jhonattan471** [comment]
I found a solution

in the component  : 

@ViewChild('rangepicker') rangepicker;

this.rangepicker.rangeChange.subscribe(e =>{
      console.log("ONCHANGE....");
});

**Comment by troddick** [comment]
I am using: 
`<nb-rangepicker (rangeChange)="onEventStartEndRange($event)" #eventPicker></nb-rangepicker>`
to get the change event when a date is chosen from the calendar. But what about if I paste a date in, or type a date, or chose a date range that was previously chosen (shows up in as option right under the input as previous values for this field)? No change event is triggered.

![image](https://user-images.githubusercontent.com/1580076/58573290-08766380-8203-11e9-9a36-7ab1d48f86a3.png)

**Comment by adrianobono** [comment]
Use in your datepicker: <nb-datepicker (dateChange)="yourFunction($event)" ...>

**Comment by caiusCitiriga** [comment]
> Use in your datepicker: <nb-datepicker (dateChange)="yourFunction($event)" ...>

Tried, and this does not fire...

**Comment by aqeelhaider88** [comment]
> Use in your datepicker: <nb-datepicker (dateChange)="yourFunction($event)" ...>

does not fire.

**Comment by aqeelhaider88** [comment]
> Use in your datepicker: <nb-datepicker (dateChange)="yourFunction($event)" ...>

its working.

**Comment by evtkhvch** [comment]
@troddick, seems like it works correct. 
`rangeChange` description: Emits range when start selected and emits again when end selected. 
See docs: https://akveo.github.io/nebular/docs/components/datepicker/api#nbdatepickercomponent
If you wanna paste a date in, or type a date you should listen the input

**Comment by evtkhvch** [comment]
> I found a solution
> 
> in the component :
> 
> @ViewChild('rangepicker') rangepicker;
> 
> this.rangepicker.rangeChange.subscribe(e =>{
> console.log("ONCHANGE....");
> });

If you use `nb-rangepicker` you should use `rangeChange` output, see docs: https://akveo.github.io/nebular/docs/components/datepicker/api#nbdatepickercomponent

**Comment by evtkhvch** [comment]
@adrianobono @aqeelhaider88 Thank you.

**Comment by abuzaforfagun** [comment]
Still, it's not working for me.

HTML:
```
<input nbInput placeholder="Pick Date" [nbDatepicker]="startsOnFormControl" [formControl]="bidAuctionStartsOnFormControl"><nb-date-timepicker (dateChange)="changeMinAuctionEndDate($event)" 
            [min]="minAuctionStartDate" format="yyyy-MM-dd HH:mm:ss" #startsOnFormControl></nb-date-timepicker>
```
TS:
```
changeMinAuctionEndDate($event: any): void {
    debugger;
  }
```

When I subscribe to the onChange event, it works for me.
```
this.startsOnDatePicker.onChange$.subscribe(data => {
              debugger;
            })
```

Nebular version: 8.0.0

**Comment by MaaxGr** [comment]
The behaviour explained by @troddick is still present also in my codebase (nebular 8.0.0). Could you clarify or reopen the issue? @evtkhvch

**Comment by MaaxGr** [comment]
This was also a bug und Chrome and Firefox, so not only IE11 related
