### ISSUE TITLE
Getting errors when trying to bind formControl to nb-select multiple

### ISSUE THREAD

**Issue by jjgriff93** [akveo/nebular#1293]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**
I'm using formBuilder and creating a form like this: 
```
searchByTermForm: FormGroup;
  searchOptions = {
    filterByTypes: [
      { id: 'calls', name: 'Calls' },
      { id: 'sms', name: 'SMS' },
      { id: 'chat', name: 'Chat' },
      { id: 'emails', name: 'Emails' },
      { id: 'contacts', name: 'Contacts' },
      { id: 'web_history', name: 'Web History' },
      { id: 'web_searches', name: 'Web Searches' },
      { id: 'pictures', name: 'Pictures' }
    ]
  };

...

const filterTypesValues = [];
    this.searchOptions.filterByTypes.forEach(type => {
      filterTypesValues.push(true);
    });

    this.searchByTermForm = this.formBuilder.group({
      searchTerm: ['', Validators.required],
      filterByTypes: formBuilder.array(filterTypesValues),
      filterByDateRange: ''
    });
```

This is populating an array of boolean values, initially setting each value in the array to true as by default I want all of the nb-select options to be checked. 

Then in the template I'm binding to the control like illustrated in the documentation for other form elements. It is however not shown in the docs how this should work with nb-select multiple, so I expect this may not yet be possible or doesn't work yet:

```
<nb-select multiple placeholder="Filter by evidence types" [formControl]="searchByTermForm.controls['filterByTypes']">
      <nb-option value="searchOptions.filterByTypes[i].name" *ngFor="let control of searchByTermForm.controls['filterByTypes'].controls; let i = index"></nb-option>
</nb-select>
```

When running this I get:

```
RROR TypeError: control.registerOnChange is not a function
    at setUpModelChangePipeline (forms.js:2116)
    at setUpControl (forms.js:2059)
    at FormControlDirective.push../node_modules/@angular/forms/fesm5/forms.js.FormControlDirective.ngOnChanges (forms.js:5064)
    at checkAndUpdateDirectiveInline (core.js:22094)
    at checkAndUpdateNodeInline (core.js:23362)
    at checkAndUpdateNode (core.js:23324)
    at debugCheckAndUpdateNode (core.js:23958)
    at debugCheckDirectivesFn (core.js:23918)
    at Object.eval [as updateDirectives] (SearchByTermComponent.html:9)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:23910)
```

**Expected behavior:**
For the form binding to work successfully like with other nebular elements

**Steps to reproduce:**
Use the ngx starter app and add the code outlined above

Latest Nebular and Angular (3.4, 7.2)

**Comment by yggg** [comment]
Hi @jjgriff93!
Regarding `[formControl]="searchByTermForm.controls['filterByTypes']"` (from the code you provided).
I don't think it's possible to use `[formControl]` directive this way. According to the [source](https://github.com/angular/angular/blob/bf656d64b8fc66ad2a39dccdee59f993a6c202ed/packages/forms/src/directives/reactive_directives/form_control_directive.ts#L143) directive expects `FormControl`, when `searchByTermForm.controls['filterByTypes']` is an `FormArray`.

>This is populating an array of boolean values, initially setting each value in the array to true as by default I want all of the nb-select options to be checked.

Options become selected when its value property is equal to form control value. For `multiple` select, an option is selected when form control value (array) includes option value.
Assuming you could use `id` as option value. Then you can go with the following code:
```
<div [formGroup]="searchByTermForm">
  ...
  <nb-select multiple formControlName="filterByTypes" placeholder="Filter by evidence types">
    <nb-option *ngFor="let filter of searchOptions.filterByTypes" [value]="filter.id">
      {{ filter.name }}
    </nb-option>
  </nb-select>
  ...
</div>
```
And in `component.ts`:
```
searchByTermForm: FormGroup;
searchOptions = {
  filterByTypes: [
    { id: 'calls', name: 'Calls' },
    { id: 'sms', name: 'SMS' },
    { id: 'chat', name: 'Chat' },
    { id: 'emails', name: 'Emails' },
    { id: 'contacts', name: 'Contacts' },
    { id: 'web_history', name: 'Web History' },
    { id: 'web_searches', name: 'Web Searches' },
    { id: 'pictures', name: 'Pictures' },
  ],
};

ngOnInit() {
  const filterTypesIds = this.searchOptions.filterByTypes.map(filter => filter.id);

  this.searchByTermForm = this.formBuilder.group({
    // ...
    filterByTypes: new FormControl(filterTypesIds),
  });
  this.changeDetectorRef.detectChanges();
}
```
Please notice `this.changeDetectorRef.detectChanges()` call in OnInit.
It's required until `3.4.1` release since we have an [issue](#1157) in selects with an initially defined value.

**Comment by jjgriff93** [comment]
Hi @yggg - thank you for this, your suggestion worked perfectly! Now having a styling issue with the multiple seclect however but will raise a separate issue. Thank you for your help
