### ISSUE TITLE
Token doesn't expire via HTTP request

### ISSUE THREAD

**Issue by jpandaconnor** [akveo/nebular#1294]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**

When using the NbAuthJWTInterceptor class, the token expires and will redirect the user to the login screen when the page is changed. However, when a HTTP request is made (To our back end API, it will not recognize the token as expired)

**Expected behavior:**

For the token to be recognized as expired and then be able to implement the redirect logic for HTTP requests

**Steps to reproduce:**

1: Send HTTP request
2: The HTTP request sends as the token doesn't recognize as expired.

**Related code:**

```
        {provide: HTTP_INTERCEPTORS, useClass: NbAuthJWTInterceptor, multi: true},
```

### Other information:

**npm, node, OS, Browser**
```
OS: Windows 10
npm: 6.4.1
```

**Angular, Nebular**
```
Angular: 7.2.2
Nebular: 3.1.0
```

**Comment by Tibing** [comment]
Hi @jpandaconnor, could you please explain your issue slightly deeper? Also, it would be awesome if you'll be able to create a reproducible example with https://stackblitz.com/github/akveo/nebular-seed
With current information, it seems like the solution was posted in another your issue #1237
