### ISSUE TITLE
flipcard like we see in the demo

### ISSUE THREAD

**Issue by michabbb** [akveo/nebular#1295]
pardon, if this is not the right place for asking general questions: where is that place ? 🤔 
because i didn´t find any link to a forum or anything else, i do it anyway here and apologize!

i would like to use a flipcard like we see in the [demo](http://akveo.com/ngx-admin/pages/dashboard),
but the docu gives me no info, howto put the flip-button on top, instead of bottom right 😕 

![image](https://user-images.githubusercontent.com/3524595/54203207-0d642a80-44d2-11e9-8a0e-122f8d625912.png)

thanks for any help!

**Comment by JrPribs** [comment]
@michabbb It seems to get the desired effect you are looking for you would just set `showToggleButton` to false on the component and then add your own button in the content that would ultimately call the flip cards `toggle` method orset the provided `flipped` `@Input()`

**Comment by michabbb** [comment]
@JrPribs thanks a lot, I will try! 👍

**Comment by michabbb** [comment]
okay, seems to work 😏 

```html
<nb-flip-card [showToggleButton]="false" #cardComponent1>
        <nb-card-front>
            <nb-card>
                <nb-card-header>Front <i (click)="toggleCard($event,cardComponent1)" class="eva eva-arrow-right-outline card-flip-toggle-btn"></i></nb-card-header>
                <nb-card-body>
                    Front
                </nb-card-body>
            </nb-card>
        </nb-card-front>
        <nb-card-back>
            <nb-card>
                <nb-card-header>Back <i (click)="toggleCard($event,cardComponent1)" class="eva eva-arrow-right-outline card-flip-toggle-btn"></i></nb-card-header>
                <nb-card-body>
                    Back
                </nb-card-body>
            </nb-card>
        </nb-card-back>
    </nb-flip-card>
```
```css
.card-flip-toggle-btn {
  font-size: 25px;
  vertical-align: text-bottom;
  float: right;
}
```

```js
toggleCard($event: any, $cardComponent: NbFlipCardComponent) {
        $cardComponent.toggle();
    }
```

@JrPribs thanks for the hint!
