### ISSUE TITLE
No mixin named nb-install

### ISSUE THREAD

**Issue by wendellmva** [akveo/nebular#1296]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Throws an error:

    @include nb-install() {
            ^
          No mixin named nb-install
          in D:\repositories\tmp\PAC.MyAppHero ...

**Expected behavior:**

**Steps to reproduce:**
git clone https://gitlab.com/wendellmva/myapphero.git
npm install
npm serve

**Related code:**
https://gitlab.com/wendellmva/myapphero

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
node --version=11.11.0
npm --version=6.7.0
windows 10
chrome 72.0.3626.119
```

**Angular, Nebular**
```
@angular/cli@7.3.1
@nebular/theme@3.4.0
```

**Comment by nnixaa** [comment]
Hi @wendellmva, it seems that the installation is not complete from the provided code. Please make sure you followed all of the steps https://akveo.github.io/nebular/docs/guides/add-into-existing-project#add-into-existing-project
