### ISSUE TITLE
Datepicker - Set first day of the week

### ISSUE THREAD

**Issue by z31fbras** [akveo/nebular#1298]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**
We cannot set the first day of the week on the Calendar component.
First day of the week is always Sunday.

**Expected behavior:**
I live in France and the first day of the week is Monday here.
I'd love to be able set a config parameter for the first day of the week.

Thanks a lot for your help!

**Comment by Tibing** [comment]
Hi @z31fbras, to change the first day of the week you have to override [`NbNativeDateService`](https://github.com/akveo/nebular/blob/3cf29d8659/src/framework/theme/components/calendar-kit/services/native-date.service.ts#L66) and make *getFirstDayOfWeek()* method return required day.

**Comment by z31fbras** [comment]
Hi @Tibing,
Since getFirstDayOfWeek() uses getLocaleFirstDayOfWeek(this.locale); and this.locale uses the LOCALE_ID token, shouldn't it work automatically by detecting the locale of my computer?

**Comment by z31fbras** [comment]
@Tibing Nevermind, I've just managed to solve my problem by setting LOCALE_ID in my AppModule ;)

Thanks a lot for your help and have a nice day =)

**Comment by Makentosha** [comment]
> Hi @z31fbras, to change the first day of the week you have to override [`NbNativeDateService`](https://github.com/akveo/nebular/blob/3cf29d8659/src/framework/theme/components/calendar-kit/services/native-date.service.ts#L66) and make _getFirstDayOfWeek()_ method return required day.

If you just overwrite the getFirstDayOfWeek() method, it will break the date picker. The picker will return wrong selected values by the user, and the days inside a month will be wrongly diplayed

**Comment by saidsoualhi** [comment]
Hello, is there any news about this topic, I tried to overwrite the getFirstDayOfWeek() method and it didn't work for me!
