### ISSUE TITLE
NbMenuItem problem

### ISSUE THREAD

**Issue by YukiDmZhao** [akveo/nebular#13]
if i want to create dynamicate menu , But NbMenuItem can not use

convModel(con) {
    let model_front: Object[] = [];

    for (let backItem of con) {
      let descMenu: Object = {};
      descMenu['title'] = backItem['label'];
      descMenu['icon'] = backItem['icon'];
      descMenu['expanded'] = backItem['expanded'];
      let surl_ = backItem['url'];
      if (isNullOrUndefined(surl_) || surl_.length == 0) {
        descMenu['link'] = '/pages/' + backItem['routerLink'];
      } else {
        descMenu['link'] = '/pages/' + surl_ + '/' + backItem['routerLink'];
      }

      if (backItem['leaf'] == false) {
        let temp = backItem['items'];
        // this.convModel(temp);
        if (isNullOrUndefined(temp) || temp.length == 0) {

        } else {
          descMenu['children'] = this.convModel(temp);
        }

      }
      if (isNullOrUndefined(descMenu)) {
      } else {
        model_front.push(descMenu);
      }

    }
    // console.log('====>', model_front);
    return model_front;
  }

this model_front can not setting NbMenuItem, & ,

**Comment by YukiDmZhao** [comment]
ERROR TypeError: Cannot read property 'push' of undefined
    at NbMenuComponent.webpackJsonp.../../../../@nebular/theme/components/menu/menu.component.js.NbMenuComponent.ngOnInit (menu.component.js:172)
    at checkAndUpdateDirectiveInline (core.es5.js:10856)
    at checkAndUpdateNodeInline (core.es5.js:12357)

**Comment by YukiDmZhao** [comment]
menu,json
[
{
    "title": "Dashboard",
    "icon": "nb-home",
    "link": "/pages/dashboard",
    "home": true
},
{
    "title": "FEATURES",
    "group": true
},
{
    "title": "UI Features",
    "icon": "nb-keypad",
    "link": "/pages/ui-features",
    "children": [
        {
            "title": "Buttons",
            "link": "/pages/ui-features/buttons"
        },
        {
            "title": "Grid",
            "link": "/pages/ui-features/grid"
        },
        {
            "title": "Icons",
            "link": "/pages/ui-features/icons"
        },
        {
            "title": "Modals",
            "link": "/pages/ui-features/modals"
        }
    ]
},
{
    "title": "Forms",
    "icon": "nb-compose",
    "children": [
        {
            "title": "Form Inputs",
            "link": "/pages/forms/inputs"
        },
        {
            "title": "Form Layouts",
            "link": "/pages/forms/layouts"
        }
    ]
}
]

 this.httpService.get('assets/mocks/menu.json').then(result => {
      this.menu =result;
    });

error:
ERROR TypeError: Cannot read property 'push' of undefined
    at NbMenuComponent.webpackJsonp.../../../../@nebular/theme/components/menu/menu.component.js.NbMenuComponent.ngOnInit (vendor.bundle.js:3555)
    at checkAndUpdateDirectiveInline (vendor.bundle.js:81767)
    at checkAndUpdateNodeInline (vendor.bundle.js:83268)
    at checkAndUpdateNode (vendor.bundle.js:83207)
    at debugCheckAndUpdateNode (vendor.bundle.js:84071)
    at debugCheckDirectivesFn (vendor.bundle.js:84012)
    at Object.eval [as updateDirectives] (ng:///PagesModule/PagesComponent.ngfactory.js:23)
    at Object.debugUpdateDirectives [as updateDirectives] (vendor.bundle.js:83997)
    at checkAndUpdateView (vendor.bundle.js:83174)
    at callViewAction (vendor.bundle.js:83542)
View_PagesComponent_0 @ ng:///PagesModule/PagesComponent.ngfactory.js:12
11:17:05.066

**Comment by YukiDmZhao** [comment]
menu;
  menu0: NbMenuItem[] = [];

if use menu0:  can not get menu, and error so up.
if use menu: can get menu, and error so up.

**Comment by nnixaa** [comment]
@YukiDmZhao please post more or less complete reproducible example with a concrete example of the issue with Nebular, as this looks like an issue with your code, and pretty hard to understand what you are trying to achieve. Thanks.

**Comment by prathyushp1** [comment]
can i create dynamic menu item using NbMenuItem

 export const MENU_ITEMS: NbMenuItem[] = [
  {
    title: 'Dashboard',
    icon: 'nb-home',
    link: '/pages/dashboard',
    home: true,
  },  {
    title: 'Schedule',
    icon: 'nb-home',
    link: '/pages/welcome',
    home: true,
  }, {
    title: 'Draft',
    icon: 'nb-home',
    link: '/pages/welcome',
    home: true,
  }, {
    title: 'Approve Tasks',
    icon: 'nb-home',
    link: '/pages/welcome',
    home: true,
  },
