### ISSUE TITLE
Incorrect values in documentation

### ISSUE THREAD

**Issue by tndrm** [akveo/nebular#130]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

Documentation of cosmic theme contains incorrect value for variable
 `btn-hero-shadow: 0, 4px, 10px, 0, rgba(33, 7, 77, 0.5)`

**Expected behavior:**

value should be without commas
`btn-hero-shadow: 0 4px 10px 0 rgba(33, 7, 77, 0.5)`

**Steps to reproduce:**

**Comment by nnixaa** [comment]
Done rc.6.
