### ISSUE TITLE
Styling inconsistency between datepicker and select form inputs

### ISSUE THREAD

**Issue by jjgriff93** [akveo/nebular#1312]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [X] feature request

### Issue description

**Current behavior:**
The datePicker form element currently seems to only have a grey outline styling, without any ability to customise. The select element however has theming/status support, for everything BUT a grey outline (which would be status="secondary"), which leads to an inconsistent UI:

![image](https://user-images.githubusercontent.com/25235950/54784531-0947b380-4c1c-11e9-8d39-93314a61e4d9.png)

**Expected behavior:**
Ability to set `status="secondary"` on select inputs, and ability to pass `status` into the datepicker element

**Comment by nnixaa** [comment]
Fixed in 4.0
