### ISSUE TITLE
Calendar on March shows Februari ending on the 31st

### ISSUE THREAD

**Issue by cryosgurl** [akveo/nebular#1332]
### Issue type

**I'm submitting a ...**

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
The calendar on refresh shows February ending on the 31st while you are looking at it in the month of March (at least from the 29th of March). With further inspection it showed that it was basically copying the end of March again. When you use the arrow to the left to go to the month February it corrects itself but stays on March and does not go to February

**Expected behavior:**
The calendar needs to show correct dates

**Steps to reproduce:**
Check demo website and load the calendar

![image](https://user-images.githubusercontent.com/16616874/55229777-37ca1d80-521e-11e9-855b-17dd7b1e1ba7.png)

**Comment by mividedaninni** [comment]
Same issue on December 31, 2018 
![image](https://user-images.githubusercontent.com/36071229/55249851-54ca1500-524d-11e9-96e3-977b3afadc20.png)
