### ISSUE TITLE
nb-select not working with dynamic data

### ISSUE THREAD

**Issue by AbdulRehman3** [akveo/nebular#1336]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description
Nb-Select not working with dynamic data
The form is loaded/created, then data is fetched from database and put in the form, the select option not changing after fetching the data
**Current behavior:**

countryCode = null
countriesList  = null
no option selected
after the data is fetched

countryCode = PK
slected option does not change to PK
**Expected behavior:**

The option with value PK should be selected

**Related code:**
Here is the sample code, this also not working
[stackblitz](https://stackblitz.com/edit/github-kkt2hz-ugcvqu?file=src%2Fapp%2Fhome%2Fhome.component.html)
### Other information:

**npm, node,**
```
Node 10
Angular 7
Nebular 3
```

**OS Browser**
OS - Ubuntu 18.04
Browsers - Chrome, Mozillah

**Comment by maihannijat** [comment]
Everything seems working except **nb-select with ngFor and ng-container**, and I guess that's because select should have list of options as children.

**Comment by yggg** [comment]
Hi @AbdulRehman3! Could you please verify the issue still persist with latest Nebular version (3.4.2)? We fixed this just recently. In the example, you referenced, all selects work as expected on 3.4.2 version. Except for selects with `ng-container` instead of `nb-option`. This is unsupported.

>Current behavior:
>countryCode = null
>countriesList = null
>no option selected
>after the data is fetched
>countryCode = PK
>slected option does not change to PK
>Expected behavior:
>The option with value PK should be selected

Can't find `countryCode` and `countriesList` in the example you referenced.

**Comment by mfuentescas** [comment]
I have the same problem using 3.5.0.

**Comment by mfuentescas** [comment]
Using **ngFor**.

**Comment by BruneXX** [comment]
Why this is closed if the problem is still there?

**Comment by sameerpallav** [comment]
Why is this closed? nb select still doesnt work with dynamic data

**Comment by Yurifull** [comment]
Fix this problem...Please!!

**Comment by mogu00712** [comment]
still not fix ...

**Comment by 128keaton** [comment]
Looks like a PR that hopefully fixes this, was merged. I am assuming that this is not yet released? Thanks.

**Comment by vamidi** [comment]
Works for me now in latest release

**Comment by shireefadel** [comment]
not working if I need to apply cascading selects

**Comment by rardila-uniajc** [comment]
> Works for me now in latest release

how? what versión?

**Comment by vamidi** [comment]
> how? what versión?

version `6.2.1`. I think it works even on `5.1.0`.

The reason why it works for me is because I do the following.
```ts
// Make sure it says static true, to access it in ngOnInit
@ViewChild('selectComponent', { static: true })
public selectComponent: NbSelectComponent = null;

// If you want to, you can emit the change function again in ngAfterViewInit.
// or you can fetch the data in ngOnInit and emit the change to the component. Since the ViewChild is static
// you can reference it in NgOnInit as well.
public ngAfterViewInit()
{
    this.selectComponent.selectedChange.emit(SELECTED_VALUE);
}

// or you can fetch the data and set a timeout.
setTimeout(() =>
{
    this.selectedDialogueComponent.selectedChange.emit(SELECTED_VALUE);
},1000);
```

If you do the following things it should work. this is what I do. good luck!

**Comment by rardila-uniajc** [comment]
Hi, this is the solution i used

static setOptionNbSelect(selectComponent: NbSelectComponent, optToCompare: any) {
        setTimeout(() => {
            if (selectComponent) {
                const selectedOptions: NbOptionComponent[] = [];
                for (const option of selectComponent.options['_results']) {
                    if (_.isEqual(optToCompare, option['value'])) {
                        selectedOptions.push(option);
                        break;
                    }
                }
                for (const option of selectedOptions) {
                    selectComponent['selectOption'](option);
                }
                selectComponent['cd'].detectChanges();
            }
        }, 500);
        
    }

**Comment by rardila-uniajc** [comment]
> > how? what versión?
> 
> version `6.2.1`. I think it works even on `5.1.0`.
> 
> The reason why it works for me is because I do the following.
> 
> ```ts
> // Make sure it says static true, to access it in ngOnInit
> @ViewChild('selectComponent', { static: true })
> public selectComponent: NbSelectComponent = null;
> 
> // If you want to, you can emit the change function again in ngAfterViewInit.
> // or you can fetch the data in ngOnInit and emit the change to the component. Since the ViewChild is static
> // you can reference it in NgOnInit as well.
> public ngAfterViewInit()
> {
>     this.selectComponent.selectedChange.emit(SELECTED_VALUE);
> }
> 
> // or you can fetch the data and set a timeout.
> setTimeout(() =>
> {
>     this.selectedDialogueComponent.selectedChange.emit(SELECTED_VALUE);
> },1000);
> ```
> 
> If you do the following things it should work. this is what I do. good luck!

Thanks for response but it didn't work for me...

**Anyway i found another way to fix it**

```
static setOptionNbSelect(selectComponent: NbSelectComponent, optToCompare: any) {
        setTimeout(() => {
            if (selectComponent) {
                const selectedOptions: NbOptionComponent[] = [];
                for (const option of selectComponent.options['_results']) {
                    if (_.isEqual(optToCompare, option['value'])) {
                        selectedOptions.push(option);
                        break;
                    }
                }
                for (const option of selectedOptions) {
                    selectComponent['selectOption'](option);
                }
                selectComponent['cd'].detectChanges();
            }
        }, 500);
        
    }
```

I hope it works for someone else.

**Comment by bluriverIt** [comment]
> > > how? what versión?
> > 
> > 
> > version `6.2.1`. I think it works even on `5.1.0`.
> > The reason why it works for me is because I do the following.
> > ```ts
> > // Make sure it says static true, to access it in ngOnInit
> > @ViewChild('selectComponent', { static: true })
> > public selectComponent: NbSelectComponent = null;
> > 
> > // If you want to, you can emit the change function again in ngAfterViewInit.
> > // or you can fetch the data in ngOnInit and emit the change to the component. Since the ViewChild is static
> > // you can reference it in NgOnInit as well.
> > public ngAfterViewInit()
> > {
> >     this.selectComponent.selectedChange.emit(SELECTED_VALUE);
> > }
> > 
> > // or you can fetch the data and set a timeout.
> > setTimeout(() =>
> > {
> >     this.selectedDialogueComponent.selectedChange.emit(SELECTED_VALUE);
> > },1000);
> > ```
> > 
> > 
> > If you do the following things it should work. this is what I do. good luck!
> 
> Thanks for response but it didn't work for me...
> 
> **Anyway i found another way to fix it**
> 
> ```
> static setOptionNbSelect(selectComponent: NbSelectComponent, optToCompare: any) {
>         setTimeout(() => {
>             if (selectComponent) {
>                 const selectedOptions: NbOptionComponent[] = [];
>                 for (const option of selectComponent.options['_results']) {
>                     if (_.isEqual(optToCompare, option['value'])) {
>                         selectedOptions.push(option);
>                         break;
>                     }
>                 }
>                 for (const option of selectedOptions) {
>                     selectComponent['selectOption'](option);
>                 }
>                 selectComponent['cd'].detectChanges();
>             }
>         }, 500);
>         
>     }
> ```
> 
> I hope it works for someone else.

what's the _ underscore in _.isEqual(optToCompare, options['results']). ??

**Comment by rardila-uniajc** [comment]
> > > > how? what versión?
> > > 
> > > 
> > > version `6.2.1`. I think it works even on `5.1.0`.
> > > The reason why it works for me is because I do the following.
> > > ```ts
> > > // Make sure it says static true, to access it in ngOnInit
> > > @ViewChild('selectComponent', { static: true })
> > > public selectComponent: NbSelectComponent = null;
> > > 
> > > // If you want to, you can emit the change function again in ngAfterViewInit.
> > > // or you can fetch the data in ngOnInit and emit the change to the component. Since the ViewChild is static
> > > // you can reference it in NgOnInit as well.
> > > public ngAfterViewInit()
> > > {
> > >     this.selectComponent.selectedChange.emit(SELECTED_VALUE);
> > > }
> > > 
> > > // or you can fetch the data and set a timeout.
> > > setTimeout(() =>
> > > {
> > >     this.selectedDialogueComponent.selectedChange.emit(SELECTED_VALUE);
> > > },1000);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > If you do the following things it should work. this is what I do. good luck!
> > 
> > 
> > Thanks for response but it didn't work for me...
> > **Anyway i found another way to fix it**
> > ```
> > static setOptionNbSelect(selectComponent: NbSelectComponent, optToCompare: any) {
> >         setTimeout(() => {
> >             if (selectComponent) {
> >                 const selectedOptions: NbOptionComponent[] = [];
> >                 for (const option of selectComponent.options['_results']) {
> >                     if (_.isEqual(optToCompare, option['value'])) {
> >                         selectedOptions.push(option);
> >                         break;
> >                     }
> >                 }
> >                 for (const option of selectedOptions) {
> >                     selectComponent['selectOption'](option);
> >                 }
> >                 selectComponent['cd'].detectChanges();
> >             }
> >         }, 500);
> >         
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I hope it works for someone else.
> 
> what's the _ underscore in _.isEqual(optToCompare, options['results']). ??

Hi @bluriverIt 

import * as _ from 'lodash';
