### ISSUE TITLE
Can not add @nebular/theme to angular 7.2.12 project.

### ISSUE THREAD

**Issue by ericardezp** [akveo/nebular#1358]
**Describe the bug**
Can not add @nebular/theme to angular 7.2.12 project.

get error :
Skipping installation: Package already installed
? Which Nebular theme do you want to use: corporate
? Use customizable scss themes? Yes
? Set up browser animations for Nebular? Yes
UPDATE package.json (2775 bytes)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular/cdk@~7.2.12
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'SampleApp'
npm ERR! notarget

**To Reproduce**
add new angular 7.2.12 project
add ng add @nebular/theme

**Expected behavior**
Sucssess adding @nebular/theme

**Additional context**
Windows 10 Enterprise 64
Visual Studio Code 1.33.0
Angular CLI version 7.3.8
Node version 10.15.3
NPM version 6.4.1

npm info  @nebular/theme

@nebular/theme@4.0.0-beta.0 | MIT | deps: 1 | versions: 27
@nebular/theme
https://github.com/akveo/nebular#readme

keywords: angular, typescript, ng2-admin, ngx-admin, theme, nebular

dist
.tarball: https://registry.npmjs.org/@nebular/theme/-/theme-4.0.0-beta.0.tgz
.shasum: 8d02436c110ef2109f0acbaa94296971f668d02a
.integrity: sha512-7HR0IyamdX2J679tHdbDSzDWVPzIY0gtgXIoV/v2BDa7+g7FuTj5eRaEfp06QkmDpXLQJdW7gppJ8HdoBw9tGw==
.unpackedSize: 4.6 MB

dependencies:
intersection-observer: 0.5.0

maintainers:
- nebular <contact@akveo.com>

dist-tags:
latest: 4.0.0-beta.0

published 6 days ago by nebular <contact@akveo.com>

**Comment by LucasG04** [comment]
I get a similar error (Angular CLI 7.0.2). In my case this line is different:
`npm ERR! notarget No matching version found for @schematics/angular@7.0.0`

**Comment by LucasG04** [comment]
I had a very similar issue.  
Try to change the version in your `package.json` to the version in `package-lock.json`.

**Comment by tranvannhatdev** [comment]
This issue happened same with #1370

**Comment by sarmon** [comment]
use "ng add @nebular/theme@3.4.2"

**Comment by nnixaa** [comment]
Unfortunately, we released 4.0.0-beta.0 not as pre-release, so yeah, at the moment the fix would be to stick the version to 3.* - `ng add @nebular/theme@3` should do the trick.

**Comment by gregoryalary** [comment]
No update?

**Comment by xavidram** [comment]
Any Update? I am using nrwl's project structure for my applications, but it seems the @nebular/theme does not let me specify the icon pack, preventing eva-icons to be found.
