### ISSUE TITLE
Problem compatibility between Nebular Bootstrap and Kendo UI Bootstrap

### ISSUE THREAD

**Issue by Maxxil** [akveo/nebular#1375]
### Issue type

**I'm submitting a

* [ ] bug report
* [x] feature request
* [ ] question about the decisions made in the repository

### Issue description

**Current behavior:**

We use Nebular with Nebular Bootstrap's Theme.
We added another ui library : [KendoUI for Angular ](https://www.telerik.com/kendo-angular-ui)

[KendoUI for Angular ](https://www.telerik.com/kendo-angular-ui) has a bootstrap theme :[ kendo-theme-bootstrap](https://www.telerik.com/kendo-angular-ui/components/styling/theme-bootstrap/)

That's why we imported the kendo-theme-bootstrap in the **styles.scss**.

See **styles.scss**:

```
@import 'themes';
@import 'node_modules/@nebular/theme/styles/globals';
@import 'node_modules/@nebular/bootstrap/styles/globals';
@import "node_modules/bootstrap/scss/bootstrap";

@import 'node_modules/@progress/kendo-theme-bootstrap/scss/button';

@include nb-install() {
    @include nb-theme-global();
    @include nb-bootstrap-global();
};
```

When we are on the first nebular theme (cosmic), we have this:

![image](https://user-images.githubusercontent.com/15669706/55896473-a6b05a80-5bbe-11e9-82fd-07b8669b940a.png)

**### We can't synchonize the Nebular bootstrap's theme with the Kendo Bootstrap's theme.**

When we change the theme, the buttons: **PRIMARY NEBULAR** and **PRIMARY BOOTSTRAP** change, but not **Primary Kendo**:

![image](https://user-images.githubusercontent.com/15669706/55896487-b2038600-5bbe-11e9-83e4-c104b39ec51b.png)

We think that we have to add a kendo mixin in the nb-install, but we can't find which one or if it's a solution.

**Expected behavior:**

For every **Nebular bootstrap's** theme, the **Kendo bootstrap's** themeintegrated should adapt the design depending the configuration in the style.scss (or themes.scss).

**Steps to reproduce:**

Download the Nebular project, add any kendo component, try to adapt the kendo design.

`npm install --save @progress/kendo-theme-bootstrap`

**Related code:**

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
Node : 10.15.3
Npm: 6.4.1
Angular: 7.3.7
```

**Angular, Nebular**
```
    "@nebular/bootstrap": "3.4.2",
    "@nebular/theme": "3.4.2",
    "@ng-bootstrap/ng-bootstrap": "4.1.1",
    "@ng-select/ng-select": "^2.16.4",
    "@progress/kendo-angular-buttons": "^4.3.3",
    "@progress/kendo-angular-dateinputs": "^3.7.1",
    "@progress/kendo-angular-dropdowns": "^3.5.2",
    "@progress/kendo-angular-excel-export": "^2.3.0",
    "@progress/kendo-angular-grid": "^3.13.1",
    "@progress/kendo-angular-inputs": "^4.2.1",
    "@progress/kendo-angular-intl": "^1.7.0",
    "@progress/kendo-angular-l10n": "^1.3.0",
    "@progress/kendo-data-query": "^1.5.1",
    "@progress/kendo-drawing": "^1.5.10",
    "@progress/kendo-theme-bootstrap": "^3.3.1",
    "@progress/kendo-theme-default": "^3.5.1",
    "bootstrap": "4.1.2",
```

**Comment by nnixaa** [comment]
Hi @Maxxil, am I correct to assume that you are expecting Nebular Theme System to affect styles and colors of Kendo UI components?

**Comment by Maxxil** [comment]
Hello @nnixaa , it's exactly what I want ! 
I thought it was possible 'cause Kendo UI support Bootstrap (like Nebular)

**Comment by Maxxil** [comment]
Hello @nnixaa , do you need some more information ?

**Comment by nnixaa** [comment]
Hey @Maxxil, unfortunately, this won't be possible at the moment. Nebular Theme System is a custom themization framework available inside of Nebular and other supporting packages. Kendo UI is not one of these packages, meaning that it doesn't implement necessary functionality to support Nebular themization.
The only possible way I see is using custom styles on top of the Kendo UI css.

**Comment by Deepeeper** [comment]
Hello, just highligting that our team also needs this functionality.
