### ISSUE TITLE
Memory leak in nbIsGranted

### ISSUE THREAD

**Issue by Kshitij-Banerjee** [akveo/nebular#1385]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Any usage of nbIsGranted in html, doesn't clear the observables and the components hence stay in memory even after destroying, creating a severe memory leak. 

**Expected behavior:**
On component destroy, nbIsGranted should remove its subscription and allow the component to be GC'd.

**Steps to reproduce:**
Use nbIsGranted in html, move away from component. Take a heap snapshot and check retainers for the component.  Sample image below.

**Related code:**

![image](https://user-images.githubusercontent.com/1330389/56089302-635a3280-5ec3-11e9-8e66-92ebad3d2f32.png)

### Other information:

**npm, node, OS, Browser**
```

Node, npm: 
npm --version
5.6.0
node --version
v8.9.4
OS: Mac
Browser: Chrome/Safari/Firefox/etc?

```

**Angular, Nebular**

```
angular: 6.0.1
nebular     "@nebular/security": "2.0.2",

```

**Comment by Kshitij-Banerjee** [comment]
Using NbAccessChecker.isGranted   | async in  *ngIf resolves the issue and prevents the memory leak.

**Comment by Kshitij-Banerjee** [comment]
I'm not sure why, but I guess the isAlive method isn't the right way to clean up.
 better to use destroy$ subjects  in the directive...

**Comment by nnixaa** [comment]
Thanks for digging in! Would you like to open a PR with a fix?

**Comment by soyoeml** [comment]
+1, please open a PR to fix it. Thanks
