### ISSUE TITLE
Question on Tooltip behavior and Icon in NbButton

### ISSUE THREAD

**Issue by sukeshlaghate** [akveo/nebular#1386]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [ ] feature request
* [x] question

### Issue description
1. I have enabled tooltip on nbbutton, if this button is disabled then tooltip doesn't show up is this intended behavior? I would expect that tooltip should be visible even if button is disabled. Use case is using submit and reset buttons with icons in form where buttons are disabled till pre-requisite fields are filled up. User should still be able to hover on disabled buttons and see tooltip.

2. If I set icon on nbbutton in a component, icon size shown in button is small. How can I set font-size/iconsize for nb-button in scss file of the component?  

StackBlitz [tooltip behavior](https://stackblitz.com/edit/github-8lkxgl)

![NbButton](https://user-images.githubusercontent.com/25061957/56097569-d55a6800-5f13-11e9-96a8-bb36befce886.PNG)

Appreciate your help in this regard.

**Comment by yggg** [comment]
Hi @sukeshlaghate. Regarding tooltip on the disabled button. Disabled form element doesn't fire mouse events so we can't track when it's clicked, hovered, etc to open tooltip. See this [article](https://jakearchibald.com/2017/events-and-disabled-form-fields/) for details. I'm not sure should we implement something on the Nebular side, but anyway there is a proposed fix in the article which you could implement your app.

>If I set icon on nbbutton in a component, icon size shown in button is small. How can I set font-size/iconsize for nb-button in scss file of the component?
Button styles were heavily updated in Nebular 4 and icon sizes should be fine now. But in case you still need to adjust it, adding something like:
```
.button-bigger-icon {
  font-size: 2rem;
}
```
should be enough.
