### ISSUE TITLE
Strategy's refreshToken getting called multiple times

### ISSUE THREAD

**Issue by MihirManek** [akveo/nebular#1390]
I am using the `isAuthenticatedOrRefresh()` method for my OAuth implementation and everything is working fine at first. The token get's refreshed as expected and all. But only when the application is running. 

If I reload my browser tab after the token has expired, I see that two consequent refreshToken requests are sent wherein the first request works as expected. But the second request sends the previous (stale) refresh token which causes the refresh to fail.

### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Sends two (multiple) refresh token requests on browser refresh after the token has expired

**Expected behavior:**
Should send only one refresh token request

**Steps to reproduce:**
1. Login and obtain a new token
2. After the token has expired, load a guarded route via the browser (or simply refresh the current guarded route)

### Other information:

**npm, node, OS, Browser**
```
Node: 11.9.0
npm: 6.5.0
OS: Windows 10
Browser: Chrome
```

**Angular, Nebular**
```
"@angular/animations": "~7.1.0",
"@angular/cdk": "^7.1.1",
"@angular/common": "~7.1.0",
"@angular/compiler": "~7.1.0",
"@angular/core": "~7.1.0",
"@angular/flex-layout": "^7.0.0-beta.19",
"@angular/forms": "~7.1.0",
"@angular/material": "^7.1.1",
"@angular/platform-browser": "~7.1.0",
"@angular/platform-browser-dynamic": "~7.1.0",
"@angular/router": "~7.1.0",
"@nebular/auth": "^3.4.1",
"@nebular/theme": "^3.4.1",
```

**Comment by MihirManek** [comment]
Can you help me with this @nnixaa @yggg?

**Comment by craigchandler** [comment]
Why was this closed, is it fixed?

I have same issue but its due to users clicking around the app quickly causing concurrent refresh calls
