### ISSUE TITLE
Updating Nebular Theme without Refactoring

### ISSUE THREAD

**Issue by itanimo** [akveo/nebular#1393]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**
I'm using an older version of nebular, and intend to use newer features added in later versions. However this involves me fully refactoring my work.

**Expected behavior:**
Would like to update to get new features (nb-multiselect for one), would simply installing the later versions be added to my current one?

### Other information:

**npm, node, OS, Browser**
```
<!--
Angular CLI: 6.0.0
Node: 8.9.0
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  7.3.8
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.29.0


-->
```

**Angular, Nebular**
```
<!--
     Nebular version
    "@nebular/theme": "^2.0.0-rc.9",
-->
```

**Comment by nnixaa** [comment]
We are hoping to achieve this in the future so that you can simply `ng update @nebular/theme` and the rest will be done automagically.
