### ISSUE TITLE
Nebular Styles Not Applied inside Lazy Loaded Feature Modules

### ISSUE THREAD

**Issue by Mayocampo** [akveo/nebular#1400]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
I have a project with "Default" Theme loaded in the app.module file and referenced in the angular.json, all works there. But when i add a lazy loaded feature module, styles applied to it are the "Cosmic" ones. my router-outlet is inside an nb-layout component and the feature module imports NbThemeModule.forRoot({ name: 'default'}) too.

**Expected behavior:**
Feature modules should take themes and styles defined in angular.json and app.module.

**Steps to reproduce:**
- Create a new project and add Nebular components to it. 
- Change styles and themes to point to 'Default' or 'Corporate'
- Create a new module and add some nebular components there too. 
- Lazy load the new module

The new module will have the 'Cosmic' themes applied by default and no the ones i choose on the second step

### Other information:

Angular CLI: 7.3.8
Node: 10.15.3
OS: linux x64
Angular: 7.2.13
Browser: Chromium Version 73.0.3683.86 (Official Build) Built on Ubuntu , running on LinuxMint 19.1 (64-bit)
```
Angular - Nebular
"@angular/animations": "^7.2.13",
"@angular/cdk": "^7.3.7",
"@angular/common": "^7.2.13",
"@angular/compiler": "^7.2.13",
"@angular/compiler-cli": "^7.2.13",
"@angular/core": "^7.2.13",
"@nebular/auth": "3.1.0",
"@nebular/bootstrap": "3.1.0",
"@nebular/security": "3.1.0",
"@nebular/theme": "3.1.0",
"@ng-bootstrap/ng-bootstrap": "^4.1.0"
```

**Comment by nnixaa** [comment]
Your app should be wrapped with `<nb-layout>` component, it is a requirement for Nebular styles to be applied.
