### ISSUE TITLE
Error Trying to Render Nb-Select inside Feature Module

### ISSUE THREAD

**Issue by Mayocampo** [akveo/nebular#1401]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
The following error is happening when trying to render a simple nb-select inside a form.

Directly related to [this issue](https://github.com/akveo/nebular/issues/1389)

`ERROR TypeError: Cannot read property 'appendChild' of undefined
at NbOverlayContainerAdapter.push../node_modules/@nebular/theme/components/cdk/adapter/overlay-container-adapter.js.NbOverlayContainerAdapter._createContainer (overlay-container-adapter.js:44)
at NbOverlayContainerAdapter.push../node_modules/@angular/cdk/esm5/overlay.es5.js.OverlayContainer.getContainerElement (overlay.es5.js:831)
at NbOverlay.push../node_modules/@angular/cdk/esm5/overlay.es5.js.Overlay._createHostElement (overlay.es5.js:4138)
at NbOverlay.push../node_modules/@angular/cdk/esm5/overlay.es5.js.Overlay.create (overlay.es5.js:4066)
at NbOverlayService.push../node_modules/@nebular/theme/components/cdk/overlay/overlay.js.NbOverlayService.create (overlay.js:36)
at NbSelectComponent.push../node_modules/@nebular/theme/components/select/select.component.js.NbSelectComponent.createOverlay (select.component.js:365)
at NbSelectComponent.push../node_modules/@nebular/theme/components/select/select.component.js.NbSelectComponent.ngOnInit (select.component.js:238)
at checkAndUpdateDirectiveInline (core.js:22099)
at checkAndUpdateNodeInline (core.js:23363)
at checkAndUpdateNode (core.js:23325)`

Every other single component from Nebular is working as expected, but nb-select is failing at render. disabling its functionality completely. I'm using version 3.5.0 but the error was throwing up with 3.1.0 too.

**Expected behavior:**
nb-select must render without issues when added to a form.

**Steps to reproduce:**
- Create New angular project
- Add nb-sidebar to app.component (any component will be ok)
- Create new module with routing
- Lazy load the new module
- Add new component to the lazy-loaded module
- Add new simple form
- Add nb-select inside the form

All nb components should be added to the main module accordingly
**Related code:**

```
<div class="form-group">
     <nb-select fullWidth outline status="info" placeholder="Route" size="xsmall">
          <nb-option value="1">Option 1</nb-option>
     </nb-select>
</div>
```

### Other information:

**npm, node, OS, Browser**

```
Angular CLI: 7.3.8
Node: 10.15.3
Npm: 6.4.1
OS: linux x64
Angular: 7.2.13
Browser: Chromium
```

**Angular, Nebular**
```
    "@angular/animations": "^7.2.13",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "^7.2.13",
    "@angular/compiler": "^7.2.13",
    "@angular/compiler-cli": "^7.2.13",
    "@angular/core": "^7.2.13",
    "@angular/flex-layout": "^7.0.0-beta.24",
    "@angular/forms": "^7.2.13",
    "@angular/http": "^7.2.13",
    "@angular/platform-browser": "^7.2.13",
    "@angular/platform-browser-dynamic": "^7.2.13",
    "@angular/router": "^7.2.13",
    "@nebular/auth": "3.5.0",
    "@nebular/bootstrap": "3.5.0",
    "@nebular/security": "3.5.0",
    "@nebular/theme": "3.5.0",
    "@ng-bootstrap/ng-bootstrap": "^4.1.1"
```

**Comment by Mayocampo** [comment]
Any help @nnixaa @yggg ? thanks.

**Comment by nnixaa** [comment]
Have you added the `<nb-layout>` component to your page?

**Comment by Mayocampo** [comment]
> Have you added the `<nb-layout>` component to your page?

Good morning @nnixaa. Yes i have the layout tag and as i said, all other nebular components are working as expected, including a sidebar...

After a couple of test i found that the nb-select is not working in any place of my app. Not in the nested router-outlet (for my lazy-loaded module) , not in the main router outlet, not in the root of the application. I have all necessary elements imported into the main module and into my lazy-loaded module.

Strange part is that code was working a week ago with nebular@3.1.0 and angular core@7.2.9 ... i updated those to last version and all stopped working. I deleted my local repo and downloaded the "working version" again, but this time, no luck at all... NB-select is not working anymore no matter the version of angular-core/nebular i choose.

**Comment by Mayocampo** [comment]
Good afternoon @nnixaa. 

Everything's working now. This is the thing:

- I have a feature module with routing
- I have nb-layout surrounding nb-sidebar and my "feature" router-outlet
- In order to properly render each component inside the feature module, each component MUST have AGAIN the nb-layout tag.

Maybe (probably) this is a huge lack of knowledge and understanding from me. But i would like to know why do we have to write an nb-layout for the router-outlet and another nb-layout for each component inside that router-outlet. I don't know if i'm being clear.

Anyway, the components work just fine once i added the second nb-layout for my "feature" component.

Thanks. Any knowledge you can share with us will be great.

**Comment by yggg** [comment]
Hi @Mayocampo! Sorry for the waiting time and thanks for getting back with a solution.
I can't reproduce the issue with provided steps. See example [stackblitz](https://stackblitz.com/edit/nebular-1401?file=src%2Fapp%2Fhome%2Fhome.component.html) and feel free to correct if there is something wrong.

> why do we have to write an nb-layout for the router-outlet and another nb-layout for each component 

It's not the way layout meant to be used. You should have one layout on the page at a time, no two siblings, nested layouts, etc.
Out of the issue, looks like you had multiple nested layouts and then when the nested layout was removed, overlay container was cleared as well. Like in the issue you mentioned.
The correct fix would be to remove all nested layouts and use one layout as a `router-outlet` container in the root component of the feature module.

Feel free to reopen, if you still experience the issue or it's not the case described above.

**Comment by parthgodhani** [comment]
is there any way to nestead nb-layout @yggg

**Comment by yggg** [comment]
@parthgodhani No. At the time nested layouts would break components with overlays (like select, dialog, context menu, etc.) once nested layout is destroyed.

**Comment by parthgodhani** [comment]
> @parthgodhani No. At the time nested layouts would break components with overlays (like select, dialog, context menu, etc.) once nested layout is destroyed.

i need 2 sidebars like i mention in picture.
i got exsetly error which you mentioned.
i need solution for it.
if you can help me.

**Comment by firasprymo** [comment]
Try to put your appmodule the first one in imports (the module that contains your routers
![image](https://user-images.githubusercontent.com/36497297/144826337-24eb2283-3550-4b20-8810-19d9e1e8eeba.png)
and if you accede your page try to use navigatebyurl('name_url')

**Comment by khalifa005** [comment]
Simple solution add 
 <nb-layout></nb-layout> 
at bottom
![image](https://github.com/akveo/nebular/assets/29863643/b3ba98c9-5bf2-457a-a275-a58062ec3b32)

**Comment by khalifa005** [comment]
After struggling with this for a while, I figured it out: you have to import NbThemeModule just once, in the app module, and avoid loading it in submodules.

That, along with using a single <nb-layout>, fixes the issue.

You're welcome.
