### ISSUE TITLE
Hello, how can I call the'reset'method of'nb-select'?

### ISSUE THREAD

**Issue by 15206125206** [akveo/nebular#1410]
Hello, how can I call the'reset'method of'nb-select'?

**Comment by EvgenyProkopovich** [comment]
Maybe help you
![image](https://user-images.githubusercontent.com/39822739/56564791-85d10780-65b7-11e9-80ae-d3935e4ddfe3.png)
![image](https://user-images.githubusercontent.com/39822739/56564987-f1b37000-65b7-11e9-969b-5d0febe39cb7.png)

**Comment by nnixaa** [comment]
seems resolved
