### ISSUE TITLE
stepper: docs typos and mistakes 

### ISSUE THREAD

**Issue by SashaSkywalker** [akveo/nebular#1414]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report

### Issue description
1. Incorrect closing tag for `nb-step` in examples
![image](https://user-images.githubusercontent.com/6690616/56646244-db74e500-6687-11e9-8fa4-4d53cba31eda.png)
2. Incorrect data type for inputs
![image](https://user-images.githubusercontent.com/6690616/56646363-16771880-6688-11e9-8f06-3b18096e29d7.png)

**Comment by nnixaa** [comment]
Fixed in 4.0
