### ISSUE TITLE
Style replacing and weird impact for all app

### ISSUE THREAD

**Issue by frct1** [akveo/nebular#1422]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Compatibility with other UI libraries and different component's styles replacing.
On docs page https://akveo.github.io/nebular/docs/guides/add-into-existing-project#adding-into said `<nb-layout></nb-layout> is a required root component for Nebular to work`. But components not working if they are not in `<nb-layout-column>${component}</nb-layout-column>`

**Expected behavior:**
Stable working without similar issues and impacts related to components from other UI libs.
That's will good to see working components outside from `<nb-layout></nb-layout>` like Angular Material

**Steps to reproduce:**
Render any component inside <nb-layout> will cause styles replacing globally.

**Related code:**
```
<a mat-button color="primary">12312312</a>
<nb-layout>
  <nb-layout-column>
    <button nbButton>12313</button>
  </nb-layout-column>
</nb-layout>
```
![image](https://user-images.githubusercontent.com/25178244/56733595-4cd89480-6769-11e9-8b22-eda7075c054a.png)

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: 11.6.0, 6.8.0
OS: Windows 10 
Browser: Chrome?
-->
```

**Comment by yggg** [comment]
Closing in favor of #1834

**Comment by frct1** [comment]
@yggg Glad to see that :)
Good luck in work

**Comment by frct1** [comment]
Hi @yggg 
Is there any forecasts to improve usability with independent components ?
