### ISSUE TITLE
Needs more variables for checkbox component

### ISSUE THREAD

**Issue by tndrm** [akveo/nebular#143]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**
There are not enough variables for the hover and active state. 
For example, it is impossible to configure the checkbox for this design:
![image](https://user-images.githubusercontent.com/18443898/34988098-86569274-face-11e7-9b5a-e935beac0106.png)

**Expected behavior:**

Create new variables for hover and active checkbox state:

checkbox-selected-bg
checkbox-selected-fg
checkbox-active-bg
checkbox-active-fg

**Comment by dimaatkaev** [comment]
Proposed changes: update checkbox to have following settings:
* checkbox-bg
* checkbox-fg
* checkbox-size
* checkbox-border
  * size
  * color
* checkbox-selected-bg
* checkbox-selected-fg
* checkbox-selected-size
* checkbox-selected-border
  * size
  * color
* checkbox-disabled-bg
* checkbox-disabled-fg
* checkbox-disabled-size
* checkbox-disabled-border
  * size
  * color

@tndrm Could you please review preposition.
