### ISSUE TITLE
multi-line string in _breaking-notice.scss errors

### ISSUE THREAD

**Issue by Emeryao** [akveo/nebular#1430]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

the multi-line `@warn` statement errors when trying to serve the angular application as below  

![image](https://user-images.githubusercontent.com/3591899/56860308-dab1bb00-69c7-11e9-953e-05e0425a7de8.png)

![image](https://user-images.githubusercontent.com/3591899/56860333-206e8380-69c8-11e9-8b62-71f7df2a0347.png)

when I update the `@warn` to a single line string all goes well

**Angular, Nebular**
```
{
    "dependencies": {
        "@angular/animations": "^7.2.14",
        "@angular/cdk": "^7.3.7",
        "@angular/common": "^7.2.14",
        "@angular/compiler": "^7.2.14",
        "@angular/core": "^7.2.14",
        "@angular/forms": "^7.2.14",
        "@angular/material": "^7.3.7",
        "@angular/platform-browser": "^7.2.14",
        "@angular/platform-browser-dynamic": "^7.2.14",
        "@angular/router": "^7.2.14",
        "@nebular/theme": "^3.5.0",
        "core-js": "2.6.5",
        "rxjs": "^6.5.1",
        "tslib": "^1.9.3",
        "zone.js": "^0.9.0"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^0.13.8",
        "@angular/cli": "^7.3.8",
        "@angular/compiler-cli": "^7.2.14",
        "@angular/language-service": "^7.2.14",
        "@types/node": "^11.13.8",
        "codelyzer": "^5.0.1",
        "dart-sass": "^1.19.0",
        "sass": "^1.19.0",
        "ts-node": "^8.1.0",
        "tslint": "^5.16.0",
        "typescript": "3.2.4"
    },
    "name": "nebular",
    "private": true,
    "scripts": {
        "build": "ng build",
        "e2e": "ng e2e",
        "lint": "ng lint",
        "ng": "ng",
        "start": "ng serve",
        "test": "ng test"
    },
    "version": "0.0.0"
}
```

**Comment by Emeryao** [comment]
the `sass compiler` I use is the `dart-sass` which is supported by `@angular/cli` and `@angular-devkit/build-angular`  
all the `angular` packages are of the latest versions

and the versions of `angular` packages for `ngx-admin` is not the latest ones
so I think the issue is related to the latest angular packages

---
sorry for my poor English

**Comment by XUANHAVU** [comment]
I also, somebody can help me?
my project deadline is last of next month.
i must complete

**Comment by Emeryao** [comment]
I just roll back to the version `3.4.1` to get rid of this issue now 😆  @XUANHAVU

**Comment by chaitut715** [comment]
Hi @Emeryao , can you tell me which version you reverted to 3.4.1

**Comment by Emeryao** [comment]
`3.4.1` is the version which I reverted to for this issue and it was the version of `3.5.0` that I found this issue

and I think this issue is gone for the 4.x

@chaitut715
