### ISSUE TITLE
nb-tabset may optionally use hidden elements instead of  ng-template

### ISSUE THREAD

**Issue by burton-scalefastr** [akveo/nebular#144]
I have some iframes that I want pre-rendered so that when the user selects the second and 3rd tab, they're ready go to. 

Right now that's not possible because the content isn't in the dom and the iframe isn't loaded until the tab is changed.

**Comment by nnixaa** [comment]
@burton-scalefastr good point for such cases. Though sometimes we explicitly do not want to load the content (from the performance standpoint). I would suggest making it optional.

**Comment by burton-scalefastr** [comment]
I'd kill to have it optional now. Re-loading the iframes is really hurting performance and I"ll have to rework everything to use my own charting library.. but it's not the end of the world I imagine.
