### ISSUE TITLE
@import 'core/mixins';

### ISSUE THREAD

**Issue by dalu** [akveo/nebular#1454]
Please rename issue

### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

```
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import 'core/mixins';
^
      File to import not found or unreadable: core/mixins.
      in /home/darko/WebstormProjects/videoadmin/node_modules/@nebular/theme/styles/_theming.scss (line 12, column 1)
ℹ ｢wdm｣: Failed to compile.

```

**Expected behavior:**

**Steps to reproduce:**
```
ng new --routing --prefix icod --style scss videoadmin
cd videoadmin
ng add @nebular/theme@next
ng serve -o
```

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
Angular CLI: 7.3.8
Node: 10.15.3
OS: linux x64
Angular: 7.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cdk                      8.0.0-rc.0
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.2.4
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
```

**Angular, Nebular**
```
    "@nebular/theme": "^4.0.0-rc.2",

```

**Comment by maihannijat** [comment]
It was happening to my project too. I copied the package from one of my another project and it worked. I thoughts it's just me :)

**Comment by Tokrat** [comment]
I have the same problem, it seems that the folder "core" is missing in the last version [here](https://github.com/akveo/nebular/tree/master/src/framework/theme/styles/core)

I had them manually and it works, it says that Dart Sass 2.0.0 is depreciated but except that it works. I don't know if core is supposed to be missing (obsolete) but it's still reference in theming.scss [here](https://github.com/akveo/nebular/blob/6ae213cefd487e3036f933ba24dacf977a0592a5/src/framework/theme/styles/_theming.scss#L12)

I am using the workaround for now but since it's in node_modules, it's not very clean.. what should I do ?

**Comment by wuboy0307** [comment]
npm version 4.0.0-rc.2 is not working due to this issue. Please update it

**Comment by patriceo** [comment]
I have the same issue here

**Comment by yggg** [comment]
Sorry for the late response, fixed in `rc.4`.
There was an [issue](https://npm.community/t/npm-pack-leaving-out-files-6-8-0-only/5382) with npm not publishing `core` directory.

**Comment by nnixaa** [comment]
Fixed in rc.4.
