### ISSUE TITLE
How to wrap user data ( permission, role, user's info) on JWT payloader

### ISSUE THREAD

**Issue by jdjacopodario** [akveo/nebular#1455]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [ X] question

### Issue description

**Current behavior:**

I had develop a mail strategy auth. Backend is based on Laravel passport , login request returns many data includig token, tokent type, exp date, user data, user roles e permissions.

How can I map this information in auth strategy so that i can use and store before login?

In this moment i have one request for each function. One for login, one for getUser one for all Role/Permission and one for getUserRole.
 My getRole() method now is like this:
`getRole(): Observable<string> {

     if (!this.roleGet) {
       this.roleGet = this._http.get<string>(`${this.baseUrl}/auth/role-permission/GetUserRoles`);
       return this.roleGet;
         }),
       );*/
     } else {
       return this.roleGet;
     }`

But with this way on every request 'isGranted' app call backend every time, even if i set a local variable to store this value at the first time.

I Would like to manage this by accessing to payload token.

**Comment by gyab12** [comment]
@jdjacopodario did you find a workaround?
