### ISSUE TITLE
4.0 and Angular 7

### ISSUE THREAD

**Issue by SpiraMira** [akveo/nebular#1456]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x ] feature request

### Issue description

Out of curiosity, are there any plans to release 4.0 for Angular 7.  How dependent is 4.0 on the Angular 8 feature set?  I have other components that may move slower to ng 8.

Thanks in advance.

**Comment by nnixaa** [comment]
We are not planning to support Nebular 4 on Angular 7. Some of the changes made are specific to Angular 8, so I presume it won't even compile, but I haven't checked that.
