### ISSUE TITLE
Option to remove the menu borders

### ISSUE THREAD

**Issue by gregoryalary** [akveo/nebular#1458]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x ] feature request

### Issue description

**Current behavior:**
There is currently no way to remove the border of the menu items in a default menu.
![nebular border](https://user-images.githubusercontent.com/20248805/57293302-9f4c7600-70c4-11e9-9743-b9604dd92863.PNG)

**Expected behavior:**
We should be able to customize the borders style in our theme.

**Steps to reproduce:**

**Related code:**

```
// html
<nb-menu autoCollapse="true" [items]="menuItems"></nb-menu>

// scss
a.menu-item {
  border: none !important;
} // does nothing

// scss theme configuration
$nb-themes: nb-register-theme((
  // [...]
  // Sidebar menu
  menu-submenu-item-border-radius: 0, // does nothing
  menu-submenu-item-border-width: 0 // does nothing
), default, default);
```

### Other information:

**npm, node, OS, Browser**
```
Node: v10.15.3
npm : 6.4.1
OS: Windows (7/8/10)
Browser: Chrome
```

**Angular, Nebular**
```
Angular : 7.2.0
Nebular: 3.5.0
```

Thanks in advance 😄

**Comment by yggg** [comment]
Hi @gregoryalary. You can control menu divider with following theme variables `menu-item-divider-color`, `menu-item-divider-style`, `menu-item-divider-width`.
Setting `menu-item-divider-color` to `transparent` or `menu-item-divider-width` to `0` should help.

**Comment by gregoryalary** [comment]
```
$nb-themes: nb-register-theme((
  // ...
  menu-submenu-item-border-width: 0,
  menu-item-divider-width: 0,
  menu-item-divider-color: transparent,
  // ...
), default, default);
```
This still won't change anything :confused:

**Comment by i7326** [comment]
@gregoryalary try   

```
$nb-themes: nb-register-theme((
// ..
menu-item-separator: transparent, //for main menu
  menu-submenu-active-border-color: none, //for submenu
```

**Comment by gregoryalary** [comment]
This one's working !
