### ISSUE TITLE
how to hide the sidemenubar in particular page

### ISSUE THREAD

**Issue by sivaadhithya** [akveo/nebular#1460]
i want to hide the sidebarmenu in the particular page  and anyone please help me out 

### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by yggg** [comment]
HI @sivaadhithya. You need to inject `NbSidebarService` into the page component where you need to hide it and call `collapse`.
