### ISSUE TITLE
style issue in https://akveo.github.io/nebular/docs/components/popover/overview#nbpopoverdirective

### ISSUE THREAD

**Issue by ZQ-jhon** [akveo/nebular#1473]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

https://akveo.github.io/nebular/docs/components/popover/overview#nbpopoverdirective this arrow down position x length is not enough
see:
![issue](https://user-images.githubusercontent.com/26297704/58082796-47e0f680-7bea-11e9-8797-2cd0a5bc03ab.png)

**Expected behavior:**

take top property to 4px, like : 
![fix](https://user-images.githubusercontent.com/26297704/58082909-8676b100-7bea-11e9-9ced-0fb029a1cc25.png)

**Steps to reproduce:**

**Related code:**
no

-->

**Comment by yggg** [comment]
Closing as seems to be fixed in Nebular 4. Thanks for reporting @ZQ-jhon.
