### ISSUE TITLE
Feature nb-radio placeholder

### ISSUE THREAD

**Issue by StanislavChankov** [akveo/nebular#1475]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**

Currently `nb-radio` component does not have placeholder property.

**Expected behavior:**

Since `nb-radio` is working with `input` it would be useful to have a placeholder property binded to its `input` element.

```
<nb-radio-group [(ngModel)]="option">
      <nb-radio
        *ngFor="let option of options"
        [value]="option.value" placeholder="example placeholder">
        {{ option.label }}
      </nb-radio>
    </nb-radio-group>
```

**Comment by StanislavChankov** [comment]
Hey guys @nnixaa @yggg ,
what would you say about this feature request?

**Comment by yggg** [comment]
Hi @StanislavChankov, thanks for your interest and sorry for the late response.
Could you please elaborate on your suggestion? I'm not sure how `placeholder` is different from text associated with `input` via `label` element.
Regular `<input type="radio" ...>` renders as a circle and has no space for any text. Also, according to [mdn](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement) `placeholder` attribute is ignored on radio inputs.
