### ISSUE TITLE
nb-checkbox (change) event.returnValue is always true in FireFox.

### ISSUE THREAD

**Issue by viqashussain** [akveo/nebular#1478]
### Issue type

**I'm submitting a ...

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
The (change) output event of nb-checkbox component does not provide the correct value for the checkbox in firefox, as it is always true. 

**Expected behavior:**
The (change) output event of nb-checkbox component should provide the correct value of the checkbox

**Steps to reproduce:**
Use the nb-checkbox component with a change output event. In the consuming method, the event.returnValue should be the value of the checkbox but is always true in FireFox. 

**Related code:**
https://stackblitz.com/edit/github-2uedts-mqc2hn

```
<nb-checkbox (change)="checkValue($event)">Show all issues</nb-checkbox>

checkValue(event: any) {
    console.log(event.returnValue)
  }
```

### Other information:

**Angular, Nebular**
```
@nebular/theme: 3.5.0
@angular: 7.*.*
```

**Comment by shreekrishnaban** [comment]
Use `event.target.checked` instead of `event.returnValue`.
