### ISSUE TITLE
Has Nebular Auth login with username ? 

### ISSUE THREAD

**Issue by nhdanh** [akveo/nebular#149]
Nebular Auth has support with username ? My Api will auth with username and password. I need config with Nebular Auth. But Login form in Nebular only support email. Can I config with Username ?

**Comment by nnixaa** [comment]
Hi @nhdanh, please take a look at https://github.com/akveo/nebular/issues/12 and https://akveo.github.io/nebular/#/docs/auth/configuring-ui. 
I have to close the issue  as https://github.com/akveo/nebular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Comment by mushu8** [comment]
Hi @nnixaa,
i've had a look at the configuring-ui documentation but cannot so much informations about customizing the login with a username instead of an email.
I've found :
`export const defaultSettings: any = {
  forms: {
    login: {
      redirectDelay: 500, // delay before redirect after a successful login, while success message is shown to the user
      strategy: 'email',  // strategy id key.
      [...]
      },
    },
}
`
It seems that the field 'strategy' would be a good fit for this use case but what value could be set here ? 'usename' ? Is there a dedicated doc about this ?

**Comment by jonastandinco** [comment]
Sadly, I'm needing the same customization. I'm using a library from backend which only accepts username as the field name instead of email. @mushu8 did you find a solution?

**Comment by materazu** [comment]
@jonastandinco same here, and no custom property was provided for this case. Maybe we can fork this repository to implement some new behavior for our case and submit a Pull Request.

**Comment by khashashin** [comment]
Same here, some configurable solution would be very nice

**Comment by HashtagAssist** [comment]
+1

**Comment by gbanusi** [comment]
+1

**Comment by arminhumic** [comment]
I found a workaround for this problem. You have to implement custom login page as stated here: https://akveo.github.io/nebular/docs/auth/custom-auth-components#setup-auth-container

After that just replace part of html where it binds user's email `[(ngModel)]="user.email"` with this `[(ngModel)]="user.username"` and it will send json with username and password to the server.
