### ISSUE TITLE
When building under angular 8 with nrwl/nx Deprecation warning about Dart-sass 2.0.0 globals

### ISSUE THREAD

**Issue by Destreyf** [akveo/nebular#1495]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description
When compiling an application, this may be specific to the nrwl/nx setup with the rc.1 of nrwl/workspace but it appears to be an error thrown from the angular compiler, i haven't tried this on an non nrwl/nx workspace, you can see the deprecation message here: https://gist.github.com/Destreyf/03a3b910d677a01feb827120c93f5977

**Current behavior:**
Deprecation warnings are thrown during compilation.

**Expected behavior:**
Preferrably no deprecation messages would be thrown.

**Steps to reproduce:**
Use Angular 8 RC.5, CLI RC.4, nrwl/nx rc.1

### Other information:

```
Angular CLI: 8.0.0-rc.4
Node: 10.13.0
OS: win32 x64
Angular: 8.0.0-rc.5
Nebular: Theme 4.0.0-rc.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.4
@angular-devkit/build-angular     0.800.0-rc.4
@angular-devkit/build-optimizer   0.800.0-rc.4
@angular-devkit/build-webpack     0.800.0-rc.4
@angular-devkit/core              8.0.0-rc.4
@angular-devkit/schematics        8.0.0-rc.4
@angular/cdk                      8.0.0-rc.2
@angular/cli                      8.0.0-rc.4
@angular/material                 8.0.0-rc.2
@ngtools/webpack                  8.0.0-rc.4
@schematics/angular               7.3.9
@schematics/update                0.800.0-rc.4
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.32.2
```

**Comment by khalifa005** [comment]
I developed a full template that uses nebular and 
the NX workspace and a demo on dynamic model federation 
with the latest angular version 
https://github.com/khalifa005/e-proc
