### ISSUE TITLE
How to get true/false from NbAuthService.isAuthenticated()

### ISSUE THREAD

**Issue by nnixaa** [akveo/nebular#15]
_by:_ @dzungdev  
_moved from:_ https://github.com/akveo/ngx-admin/issues/1298

Hi all,
I would like to ask how I can get true/false from NbAuthService.isAuthenticated()? The problem now is it always returns the Observable so my if() is always true even I haven't logged-in yet (suppose false if haven't logged-in yet)

if (this.nbAuthService.isAuthenticated()) { console.log('run here2'); return true; }
Best regards

**Comment by nnixaa** [comment]
@dzungdev as this is observable, you need to subscribe to it and move your `if` statement into the subscribe callback:

**Comment by dzungdev** [comment]
Hi @nnixaa , thank you very much for your helping. I changed to use `onAuthenticationChange ` and it can check the result now, it go to `true` if I logged-in but then it doesn't route to dashboard. 

Before I applied the `AuthGuard implements CanActivate`, if I logged-in, then it auto redirect to dashboard page. Could you please give me the hint? I have willing to finish this part and submit the document for it as I don't see we have document for this part.

![image](https://user-images.githubusercontent.com/5888611/31027667-db826810-a4ff-11e7-8397-48a6297e75d3.png)

Best regards

**Comment by gael-ft** [comment]
Hey @nnixaa, `isAuthenticated()` is always returning the token value (null or the real value).
It is not a boolean as we should expect.
In the code I can see that `isAuthticated()` is applying a `.map(token => token && token.getValue())` which not produces a boolean but returns 

> token.getValue() if not null

> token object otherwise

Am I right ?

Is it the normal behavior ?

**Comment by gael-ft** [comment]
Hey @nnixaa `isAuthenticated()` is never returning `true` or `false`.
It return the token value (a string for example) or null.
It comes from `token && token.getValue()` which not produce a boolean but the right part if the first is not null.

Is it the normal behavior ?

**Comment by nnixaa** [comment]
Hey @gael-ft, yep you right, this is clearly a bug, we'll fix it soon.
