### ISSUE TITLE
Error creating a Dialog from a Window

### ISSUE THREAD

**Issue by Luca1991** [akveo/nebular#1516]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**
For some reason, I can't open a Dialog from a Window. I get "No component factory found for RemoveMediaDialogComponent"

**Expected behavior:**
I should be able to open a Dialog from a Window.

**Steps to reproduce:**
Inside my window component html I have this click event:

`<i class="eva eva-trash-2" (click)="showRemoveMediaDialog()"></i>`

that call this function:

```
showRemoveMediaDialog() {
    this.dialogService.open(RemoveMediaDialogComponent, {
      context: {
        title: 'Do you really want to delete this media?',
        media: this.mediaId,
      },
    });
  }

```
But instead of creating the Dialog, I get:

> No component factory found for RemoveMediaDialogComponent

If I open the dialog from the main component, it is displayed correctly.

Of course I have declared it:

```
  declarations: [
    ...
    RemoveMediaDialogComponent,
    ...
  ],
  entryComponents: [
    ...
    RemoveMediaDialogComponent,
    ...
  ],
```

### Other information:

**npm, node, OS, Browser**
```
    "@nebular/bootstrap": "3.5.0",
    "@nebular/date-fns": "3.5.0",
    "@nebular/theme": "3.5.0",

    Latest version of Chrome
```

**Comment by Luca1991** [comment]
UPDATE:
This might now be a bug: If I move declarations and entryComponents on the root module (app.module.ts), the dialog is displayed correctly.

So now the question is: is possible to keep declarations and entryComponents in the sub module (for blablabla.module.ts) ?

**Comment by wuboy0307** [comment]
I found a solution.
https://github.com/angular/angular/issues/14324#issuecomment-481898762
work like a charm!

Just follow the steps and then move all your entryComponents to PagesModule (of course also included in declarations).

**Comment by yggg** [comment]
Closing as resolved
