### ISSUE TITLE
withScroll mode and nb-select - view width changes in chrome

### ISSUE THREAD

**Issue by bppn** [akveo/nebular#1519]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
When withScroll is active, and there is a nb-select component, the current behavior is that the scroll mode changes when the popup is activated.

In safari and firefox, this gives no issues.  However, in chrome, the view width is changing, causing the form to redraw a few pixels wider (scrollbars).

**Expected behavior:**
The current behavior causes a drawing flicker.  Is it possible to make this the same behavior in chrome as in other browsers?

**Steps to reproduce:**
The ngx-admin page has the same behavior as described:
http://akveo.com/ngx-admin/pages/extra-components/form-inputs

**Comment by yggg** [comment]
Thanks for reporting @bppn. Fixed by #1805
