### ISSUE TITLE
Persian website 

### ISSUE THREAD

**Issue by behroozbc** [akveo/nebular#1526]
hi 
i developing Persian website but in auth component i want persian text but show english how i must fix ?

**Comment by maihannijat** [comment]
Which text are you talking about? Be more specific please.

**Comment by behroozbc** [comment]
![image](https://user-images.githubusercontent.com/20381616/58655300-14f7da80-832f-11e9-8f9d-2217b0e2a0f1.png)

**Comment by maihannijat** [comment]
The text is under **login.component.html**

**Comment by behroozbc** [comment]
where is login component ????

**Comment by anthowm** [comment]
Hi, you should extends login component and do a custom component with your requirements. Check the docs
https://akveo.github.io/nebular/docs/auth/custom-auth-components#login-component-extension

**Comment by yggg** [comment]
Closing as answered. Thanks @anthowm 👍
