### ISSUE TITLE
CSS grid support with dragging cards

### ISSUE THREAD

**Issue by jacksylvane** [akveo/nebular#154]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ X ] bug report

### Issue description

**Current behavior:**
I made a CSS grid of nb-cards. Each card has a unique position.(grid-column & grid-row). I have done this so users can customize position of cards and save it.
I have included ng2-dragula package but I am having problems connecting the package with component. I get error that can't bind to 'dragula' since it is not a known property of 'div'.

I found this problem on ng2-dragula's [page](https://github.com/valor-software/ng2-dragula/issues/418) where one commenter suggested to move importing the package to a parent component. I am importing it into app.module but does not work. 

> 
> It's happens because of your component has his own parent module (Maybe you've added some routing module or your component is a part of separated module).
> 
> I've faced with this issue too and solved it when realized that my component was a part of separated module. I've just move import to its parent and there we go!

I think this is happening because of the routing. To which component should I import package in order to make it work? 

```
<div class="row gridContainer" [dragula]='"whatever"'>
```

**Comment by nnixaa** [comment]
Hi @jacksylvane, honestly I'm not familiar with dragula, but from the error you mentioned, you need to import the dragula module into the module where are you going to use it (so not the parent or any other module).

**Comment by jacksylvane** [comment]
Thank for your suggestion @nnixaa . Unfortunately, it does not work. I tried to import the module to pretty much every component I could find. I copied code from other project that this is working on but without any success. Could it be because of some dependency related with bootstrap? 
This is what I am getting during npm install.
![ffff](https://user-images.githubusercontent.com/32455147/35211731-fd4c804a-ff57-11e7-82fd-a0f141a031b7.PNG)

**Comment by nnixaa** [comment]
@jacksylvane I doubt these peer dependency errors could be related. 
>  tried to import the module to pretty much every component I could find.
but you need to import it into a module, not a component

Have you tried the same on an empty angular-cli project?

**Comment by jacksylvane** [comment]
@nnixaa  I've tried every module I could find as well. 
I have basic angular-cli(without nebular theme) for testing new stuff and there it seems to be working. I imported it in app.module and put it inside imports and also to the component where I have container. Have no idea what I am doing wrong. I've tried everything..

**Comment by jacksylvane** [comment]
@nnixaa  I tried every module but missed dashboard.module.ts. Now it is working! Thank you so much

**Comment by nnixaa** [comment]
Glad to hear that.
