### ISSUE TITLE
nb-request-password is not a known element

### ISSUE THREAD

**Issue by 839998664** [akveo/nebular#1554]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ X] bug report

### Issue description

**Current behavior:**
Trying to use the nb-request-password component. Error stating nb-request-password is not a known element.

**Expected behavior:**
On click of Forgot password Request Password Page should open.
**Steps to reproduce:**
Add the nb-request-password selector to the template of a component.

### Other information:

**npm, node, OS, Browser**
```
Chrome, Node 12.3.1, npm 6.9.0, Windows 10

```

**Angular, Nebular**
```
Angular 8.0.0
Nebular 4.0.0-rc.6

```

**Comment by nnixaa** [comment]
Please post a reproducible example.

**Comment by 839998664** [comment]
I have tried to put together a reproducible example at 

https://stackblitz.com/edit/github-t9rkmy

First time user of stackblitz though. Tried to do my best.

**Comment by 839998664** [comment]
Did this example work?
