### ISSUE TITLE
Missing required OpenStreetMap attribution for leaflet map on demo

### ISSUE THREAD

**Issue by bagage** [akveo/nebular#1567]
### Issue type

**I'm submitting a ...**

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

On [leaflet demo](http://akveo.com/ngx-admin/pages/maps/leaflet), OpenStreetMap map is displayed (using Leaflet). However, there is no attribution in bottom right corner:
![image](https://user-images.githubusercontent.com/1451988/58827317-079a6300-8643-11e9-9032-5b62cf749771.png)

**Expected behavior:**

Attribution must be displayed, see [OpenStreetMap copyright](https://www.openstreetmap.org/copyright).

**Steps to reproduce:**

Open [demo](http://akveo.com/ngx-admin/pages/maps/leaflet)

**Comment by maihannijat** [comment]
That's ngx-admin issue?

**Comment by bagage** [comment]
Indeed: https://github.com/akveo/ngx-admin/blob/0624e3feb91ea5afc70504a0c9a7a5abae078e41/src/app/pages/maps/leaflet/leaflet.component.ts#L22

Reporting the issue there then, thanks!
