### ISSUE TITLE
Property 'setSelected' does not exist on type 'NbSelectComponent<any>'

### ISSUE THREAD

**Issue by Mayocampo** [akveo/nebular#1568]
**I'm submitting a ...**  (check one with "x")

* [ x ] bug report
* [ ] feature request

**Current behavior:**
After updating to version 4.0.0 with Angular 8 APP i'm receiving the following error: 

"Property 'setSelected' does not exist on type 'NbSelectComponent<any>'".

Obviously, the property does exist (Autocomplete is showing it) and it was working just fine with version 3.5.0. But Ng Build and Ng Serve are failing because of that. There's no reason for TS to be failing in compiling becaise the property is there.

**Expected behavior:**
NbSelectedComponent.setSelected should be working fine as in version 3.5.0

(Also, there's no enough documentation for simple and common necessities like set a selected element via source code)

**Steps to reproduce:**
- Recently updated Angular app from version 7 to version 8. 
- Recently updated Nebular/Theme from 3.5.0 to 4.0.0
- Reference nb-select through @ViewChild as NbSelectComponent
- Try to select specific option inside nb-select using "myNbSelect.setSelected = {};"

**Related code:**
```
@ViewChild('routeSelect', {static: false}) routeSelect: NbSelectComponent<any>;

...

this.routeSelect.setSelected = {};
```

### Other information:
```
Node: v12.3.1
NPM: v6.9.0
```

**Angular, Nebular**
```
    "@angular/animations": "^8.0.0",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/compiler-cli": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/forms": "^8.0.0",
    "@angular/http": "^7.2.15",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/router": "^8.0.0",
    "@nebular/theme": "4.0.0"
```

**Comment by caiusCitiriga** [comment]
The worst component in the whole library.... Lacking documentation for basic tasks like 
@Mayocampo said `(Also, there's no enough documentation for simple and common necessities like set a selected element via source code)`. 

Also setting the selected element using the right methods does not update the selection...

**Comment by yggg** [comment]
Regarding `Property 'setSelected' does not exist on type 'NbSelectComponent'`.
Setter `setSelected` was removed as a breaking change in the 4th version. You can use `selected` property instead.

>Obviously, the property does exist (Autocomplete is showing it)
There is no `setSelected` property in typings file and autocomplete should show it. Not sure why this happens. Maybe screenshot can help?

And thanks for the docs feedback @Mayocampo @caiusCitiriga. I extracted this into separate issue so we don't lose track of it. If you have an additional suggestion on select docs add it in #1830.
