### ISSUE TITLE
Title does not displayed on context menu

### ISSUE THREAD

**Issue by fasisi** [akveo/nebular#157]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**

I initialize the plugin with setup structure like this:
`var menu = [
          {
            name: 'gantipenempatan',
            img: '',
            title: 'Pindah kelas',
            fun: function()
            {
              alert('Pindah kelas :: idkelas = ');
            }
          },
          {
            name: 'editkelas',
            img: '',
            title: 'Edit kelas',
            fun: function()
            {
              alert('Edit kelas :: idkelas = ');
            }
          }
        ];`

The context menu showed 2 menu items but menu #1 said "gantipenempatan" dan menu #2 said "editkelas".

**Expected behavior:**

It should show context menu with 2 menus:
1. Menu #1 will says "Pindah kelas"
2. Menu #2 will says "Edit kelas"

**Steps to reproduce:**

**Related code:**

```
`var menu = [
          {
            name: 'gantipenempatan',
            img: '',
            title: 'Pindah kelas',
            fun: function()
            {
              alert('Pindah kelas :: idkelas = ');
            }
          },
          {
            name: 'editkelas',
            img: '',
            title: 'Edit kelas',
            fun: function()
            {
              alert('Edit kelas :: idkelas = ');
            }
          }
        ];
        $('.menu_kelas').contextMenu(menu);`
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```
I use contextMenu version: v 1.4.1

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by nnixaa** [comment]
Hi @fasisi, are you sure this is a correct repository? As you are most likely referring to something else.

**Comment by fasisi** [comment]
Oops, I am sorry.
