### ISSUE TITLE
how to access documentation of previous version, like v3.5.0?

### ISSUE THREAD

**Issue by liujie20087349** [akveo/nebular#1571]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**

how can I see the doc of previous version, like v3.5.0, I can't find a link
thanks

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by yggg** [comment]
Hi @liujie20087349! You can find `3.5.0` at https://akveo.github.io/nebular/3.5.0/. We'll add version switcher shortly.

**Comment by liujie20087349** [comment]
thanks

**Comment by epgeroy** [comment]
hi there, I'm trying to access to the 4.6.x version, but I find it impossible. Is there a link to such documentation?
Thanks in advance
