### ISSUE TITLE
[Select]: if no value selected - the height is wrong

### ISSUE THREAD

**Issue by nnixaa** [akveo/nebular#1575]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

![image](https://user-images.githubusercontent.com/230527/58890131-b8137000-86f2-11e9-8a25-6e79bdf789e7.png)

**Expected behavior:**

Default height.

**Steps to reproduce:**

```
<nb-select size="medium">
      <nb-option value="all">All</nb-option>
      <nb-option value="completed">Completed</nb-option>
      <nb-option value="active">Active</nb-option>
    </nb-select>
```

Nebular 4.0

**Comment by yggg** [comment]
Fixed by #1643
