### ISSUE TITLE
[Checkbox]: hover styles stay active even for unchecked state (confusing)

### ISSUE THREAD

**Issue by nnixaa** [akveo/nebular#1578]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

![image](https://user-images.githubusercontent.com/230527/58890761-ec3b6080-86f3-11e9-87f3-7524717b35d5.png)

**Expected behavior:**

Unchecked checkbox should not have hover styles on mobile.

**Steps to reproduce:**

Check and uncheck the checkbox on iOS.

**Comment by blaze-rowland** [comment]
If I had to guess it has something to do with hover-states on mobile.

**Comment by yggg** [comment]
Closing as seems to be resolved
