### ISSUE TITLE
Docs website css seems broken 

### ISSUE THREAD

**Issue by dhrn** [akveo/nebular#1584]
### Issue type

**Docs website seems broken with input elements actions** 

* [ ] bug report
* [ ] feature request

### Issue description

**Current behavior:**

![issue](https://user-images.githubusercontent.com/14145706/58962304-8967c900-87c8-11e9-92f7-f3cd213c00de.gif)

**Comment by yggg** [comment]
Fixed in https://github.com/akveo/ngx-admin/pull/2114
