### ISSUE TITLE
No Eva Design System

### ISSUE THREAD

**Issue by ericis** [akveo/nebular#1590]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

> "... based on [Eva Design System](https://eva.design/) specifications."

Link on website correctly goes to a website with a header and an email address. (No actual design system.)

**Expected behavior:**

The referenced design system exists.

**Steps to reproduce:**

Visit the Eva Design System link.

**Comment by nnixaa** [comment]
Hey @ericis, thanks for your questions. As it says on the website, it's going to be there in a month. The design system itself is already integrated into Nebular, you can start with this https://akveo.github.io/nebular/docs/design-system/eva-design-system-intro/ article and follow the next pages. 
If you need more details on Eva before lunch, you can ping us at the email provided and we will answer to your questions.

**Comment by Davnatomy** [comment]
I have the same issue. Are you implementing a grid system? How would I position content with in the<nb-layout-header> for example or the Nb card? with nebular v4?
