### ISSUE TITLE
NX architecture support

### ISSUE THREAD

**Issue by oscarlagatta** [akveo/nebular#1597]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**
what are the steps to integrate Nebular using the **monorepo** approach, as a single library that can be used by as many applications as the workspace can hold ? 

**Expected behavior:**
Be able to create a library/package that can be reused by many applications in the same workspace

**Steps to reproduce:**
Create a NX workspace and add a library with all the  nebular UI components

**Related code:**
https://github.com/nrwl/nx

A sample application via GitHub
https://github.com/nrwl/nx

StackBlitz [StackBlitz Seed Project](https://stackblitz.com/github/akveo/nebular-seed)

-->

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by nnixaa** [comment]
Hi @oscarlagatta, would you mind elaborating and describe your use case a bit deeper?

**Comment by Destreyf** [comment]
@oscarlagatta I am doing something very similar, there isn't anything that nebular needs to support for this to work.

What i ended up doing is creating a library (`ng g lib theme` i created it as an angular library.  I have a single `theme.module.ts` file that's exported by the index.  This setups up any defaults i have as well as a couple other modules i use  (like `angular-fontawesome`).

I then have a themes.scss file that imports my relevant themes i have, I have done quite a bit of extra work to simplify the management of properties & customization's that we are doing.  Most of this is to organize the changes into a re-usable structure.

Below is an image of my directory structure.
![image](https://user-images.githubusercontent.com/967304/59221562-cba45800-8b84-11e9-85e8-7125125a7b09.png)

Then inside of my `apps/app-name/styles.scss` file, i have it reference the theme file like this:

```scss
@import '../../../libs/theme/src/themes';
@import '~@nebular/theme/styles/globals';

$nebular-breaking-notice-enable: false;
@include nb-install() {
  @include nb-theme-global();
}
```

This allows me to re-use the base configuration with my (currently 3) separate applications hosted in this mono-repo.

I would like to iterate that my setup is much more built out than it needs to be, you can have all your properties in the `_theme-dark.scss` and `_theme-light.scss` but we wanted to make it easier to identify where changes should be made as a whole for our platform and where individual themes can have overrides.  We keep all override logic for each theme in it's respective `_theme-<name>.scss` file and we're overriding the general styles for each component in their `styles/nebular-components/_<component-name>.scss` file for management purposes.

**Comment by oscarlagatta** [comment]
Thank you @Destreyf and @nnixaa! When working in a monorepo using the Narwhal Extensions (NX) we create libraries using @nrwl/schematics for adding new libs and apps to the workspace; not the @angular/schematics from the Angular CLI, therefore when adding a library using NX the changes will have different impact in configuration, like adding namespaces, adding tags, and rendering the lib available as per shared or feature specific. So was wondering what's the principle so I can add Nebular to a NX workspace as shared library or app specific library?

**Comment by Destreyf** [comment]
@oscarlagatta I would do it the way i described where you create a library using `ng g lib theme`  If you setup your workspace with `nrwl/nx` or `nrwl/workspace` then the default schematic is already the nrwl one.

It should generate an angular module, at which point you could initialize the nebular theme module in that that NgModule and export it in your index by doing `export * from './lib/theme.module.ts';`.

This gives you a generic/drop in module that contains your shared logic, if you need to use a specific part of nebular for a single application, there's not much reason in putting it into a lib.

Beyond doing this, it's entirely up to you on how you want to setup and use this shared library.

**Comment by khalifa005** [comment]
> @oscarlagatta I am doing something very similar, there isn't anything that nebular needs to support for this to work.
> 
> What i ended up doing is creating a library (`ng g lib theme` i created it as an angular library. I have a single `theme.module.ts` file that's exported by the index. This setups up any defaults i have as well as a couple other modules i use (like `angular-fontawesome`).
> 
> I then have a themes.scss file that imports my relevant themes i have, I have done quite a bit of extra work to simplify the management of properties & customization's that we are doing. Most of this is to organize the changes into a re-usable structure.
> 
> Below is an image of my directory structure. ![image](https://user-images.githubusercontent.com/967304/59221562-cba45800-8b84-11e9-85e8-7125125a7b09.png)
> 
> Then inside of my `apps/app-name/styles.scss` file, i have it reference the theme file like this:
> 
> ```css-scss
> @import '../../../libs/theme/src/themes';
> @import '~@nebular/theme/styles/globals';
> 
> $nebular-breaking-notice-enable: false;
> @include nb-install() {
>   @include nb-theme-global();
> }
> ```
> 
> This allows me to re-use the base configuration with my (currently 3) separate applications hosted in this mono-repo.
> 
> I would like to iterate that my setup is much more built out than it needs to be, you can have all your properties in the `_theme-dark.scss` and `_theme-light.scss` but we wanted to make it easier to identify where changes should be made as a whole for our platform and where individual themes can have overrides. We keep all override logic for each theme in it's respective `_theme-<name>.scss` file and we're overriding the general styles for each component in their `styles/nebular-components/_<component-name>.scss` file for management purposes.

please can you share how nebular lib used in the host app because till now i couldn't solve this

**Comment by khalifa005** [comment]
I developed a full template that uses nebular and 
the NX workspace and a demo on dynamic model federation 
with the latest angular version 
https://github.com/khalifa005/e-proc
