### ISSUE TITLE
nb-rangepicker error when locale language is not en-US

### ISSUE THREAD

**Issue by liujie20087349** [akveo/nebular#1598]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

When language is en-US, the rangepicker is OK, and the date range I selected would be inserted the input element, but after I change language to zh-cn or fr, the value I selected would not be shown on the input element.

**Expected behavior:**

It should be OK when locale language is not en-US
**Steps to reproduce:**

I reproduce this issue [here](https://github.com/liujie20087349/datepicker-issue)
**Related code:**

```
<nb-layout>

  <nb-layout-header fixed>
    <!-- Insert header here -->
  </nb-layout-header>

  <nb-layout-column>


    <div style="text-align: center;">
      <input style="width: 300px;" nbInput [nbDatepicker]="datepicker">
      <nb-datepicker #datepicker></nb-datepicker>
    </div>
    <br>
    <div style="text-align: center; ">
      <input style="width: 300px;" nbInput placeholder="Form Picker" [nbDatepicker]="formpicker">
      <nb-rangepicker #formpicker></nb-rangepicker>
    </div>


  </nb-layout-column>

  <nb-layout-footer fixed>
    <!-- Insert footer here -->
  </nb-layout-footer>

</nb-layout>
```

### Other information:

**npm, node, OS, Browser**
```
node version: 10.15.3
os: mac mojavo
browser: chorme
```

**Angular, Nebular**
```
angular: 7.2.0
nebular: 3.5.0
```

**Comment by liujie20087349** [comment]
I fix this by adding a format attribute, and install `@nebular/moment`

**Comment by liujie20087349** [comment]
just npm install `@nebular/moment` and add module `NbMomentDateModule` fix it

**Comment by yaminger** [comment]
兄弟，在哪里加的这个模块 NbMomentDateModule？  我怎么一导入就提示找不到这模块呢

**Comment by johnsnow20087349** [comment]
> 兄弟，在哪里加的这个模块 NbMomentDateModule？ 我怎么一导入就提示找不到这模块呢

后来我还是通过加上了·@nebular/date-fns·来格式化，没有使用 moment

**Comment by ghassen1khalil** [comment]
> NbMomentDateModule

After installing `@nebular/moment` and adding module `NbMomentDateModule` I got :

```
ERROR in ./node_modules/@nebular/moment/fesm5/index.js
Module not found: Error: Can't resolve 'moment' in '/Users/ghassen/Desktop/workspace/social-carpooling/social-carpooling-frontend/social-carpooling/node_modules/@nebular/moment/fesm5'

Date: 2019-08-31T14:27:28.445Z - Hash: 120bf5c485538820ea0b
4 unchanged chunks
chunk {main} main.js, main.js.map (main) 70.3 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 6.56 MB [initial] [rendered]
Time: 1980ms
ℹ ｢wdm｣: Failed to compile.
    
    ERROR in node_modules/@nebular/moment/services/moment-date.service.d.ts(3,24): error TS2307: Cannot find module 'moment'.

```

**Comment by ejthan** [comment]
I got the same issue. is there any quick fix? or do I have to install moment?

**Comment by stanciupaul** [comment]
⚠️ Issue is still present on Nebular 6.2.2 for other locales than `en-US`. Installing `@nebular/moment` and `moment` didn't fix the issue for me.
