### ISSUE TITLE
nbAuthService.onAuthenticationChange always have result even not logged-in yet

### ISSUE THREAD

**Issue by dzungdev** [akveo/nebular#16]
Hi @nnixaa , I already change to `onAuthenticationChange` in my `AuthGuard` like below code to return the Observable but it always go to `true` even I haven't logged-in. Could you please give me the hint for this login problem?

import { Observable } from 'rxjs/Observable';
import { Router, CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot } from '@angular/router';
import { Injectable } from '@angular/core';
import { NbAuthService, NbTokenService } from '@nebular/auth';

@Injectable()
export class CanActivateAuthGuard implements CanActivate {

  constructor(private router: Router, private nbAuthService: NbAuthService, 
              private tokenService: NbTokenService) {}

  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
    
    return this.nbAuthService.onAuthenticationChange().map(
      result => {
        console.log("logged-in with result", result);
        if (result) return true;
      }
    ).catch(() => {
      this.router.navigate(['/auth/login']);
      console.log("not yet logged-in")
      return Observable.of(false);
    });
    
  }

}

Best regards

**Comment by dannyrz** [comment]
me too.!
