### ISSUE TITLE
NbSelectComponent Dose not support required

### ISSUE THREAD

**Issue by abadakhshan** [akveo/nebular#1601]
How can I use **nbselectcomponent** like other input components
with support of **ngmodel** and **required** validator  and fully compatible with **form**?

**Comment by yggg** [comment]
@abadakhshan Is this a question or a bug report? `nb-select` supports both template forms (with `ngModel`) and reactive forms. Can't see any issues with the required validation. See the [docs](https://akveo.github.io/nebular/docs/components/select/overview#nbselectcomponent) for examples on select with forms usage.

**Comment by abadakhshan** [comment]
@yggg Thank you
You are right
I don't know why I could not find it.

**Comment by MincDev** [comment]
@abadakhshan Did you get this working with ReactiveForms? Its not working for me. The reactiveForm.valid ignores it and also reactiveForm.patchValue does't work on it either
