### ISSUE TITLE
Cannot find nebular documentation for Angular

### ISSUE THREAD

**Issue by AMINEAALI** [akveo/nebular#1606]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
I am not sure if it's a bug, but i can't find any nebular documentation for Angular. I only find doc for react native, but that's not what I am using.

**Expected behavior:**
Find nebular documentation for Angular

**Steps to reproduce:**
https://github.com/akveo/nebular, click on the image Angular 8 nebular.

**Comment by nilpaco** [comment]
Same here, redirects to UI Kitten docs.

**Comment by ilDon** [comment]
Same here. I think that something must have gone wrong when new docs were being uploaded.

**Comment by AMINEAALI** [comment]
On twitter :

Me : Where is nebular for Angular ? 🤔
Akveo : We really sorry for that, that's the tech problems on our side and we do our best to solve it right now.

**Comment by yggg** [comment]
Should be fixed now, sorry for the inconvenience.

**Comment by nnixaa** [comment]
Sarcastic: it's a promo campaign of Akveo's new product - React Native UI Kitten :/

**Comment by ilDon** [comment]
It's working again for me

**Comment by AMINEAALI** [comment]
Thank you it's working now
