### ISSUE TITLE
Cannot access docs of Nebular 3.5

### ISSUE THREAD

**Issue by alfredott** [akveo/nebular#1609]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

My URL is replaced again and again by the same one but with some string added. After ~5 seconds, it looks like this (but it continues growing).
`https://akveo.github.io/nebular/3.5.0/?p=/&q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/docs/components/menu/api#nbmenuitem`

**Expected behavior:**

I want to access `https://akveo.github.io/nebular/3.5.0/docs/components/menu/api#nbmenuitem`

**Steps to reproduce:**

Access `https://akveo.github.io/nebular/3.5.0/docs/components/menu/api#nbmenuitem`

### Other information:

**My OS and browser**
Windows 7, Google Chrome 74

Bye !

**Comment by yggg** [comment]
Hi @alfredott. We just added version switcher to the [docs app](https://akveo.github.io/nebular/), you can find it in the page header.
We'll host docs for the current latest version and for LTS one. Now it's `4.1.0` and `3.6.1`.

In case you need `3.5.0` specifically, you can clone Nebular repository, checkout `v3.5.0` tag, run `npm install` and then `npm run docs:serve`. Navigate to `localhost:4100` and you should see docs. To make example load faster, run `npm run ng -- build --prod`.
