### ISSUE TITLE
In all Browsers (Chrome, Safari, Firefox), nb-select component does not work properly after scrolling.

### ISSUE THREAD

**Issue by chaitrapdeshpande** [akveo/nebular#1616]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ x] bug report
* [ ] feature request

When the UI has dropdown(nb-select component) and you scroll the page and click on dropdown the UI jumping issues happens in latest Chrome, Firefox and Safari in Mac as well as in Windows.

**Current behavior:**
If the UI has dropdowns, and as long as the screen does not had to be scrolled, the components/UI will display correctly. When we start scrolling the screen and the number of elements in the dropdown is large enough to overflow the next UI then UI jumps or UI pops up which cuts the remaining UI by making it blank. This happens in all browsers in Windows. In Mac Firefox this issue does not happen.

**Expected behavior:**
1. UI should not jump.
2. Normal behaviour of dropdown is expected even though scrolling happens or even if the many items are taken in the dropdown.

**Steps to reproduce:**
1. Go to following link the same behaviour happens.
2. https://akveo.com/ngx-admin/pages/extra-components/form-inputs
3. Scroll the page.
4. Click on any drown after scrolling, the same behaviour appers.
**Related code:**

```
insert short code snippets here
```
![Screen Shot 2019-06-14 at 2 48 39 PM](https://user-images.githubusercontent.com/12884431/59501713-c06d6700-8eb9-11e9-8220-3335f575589d.png)
![Screen Shot 2019-06-14 at 2 49 17 PM](https://user-images.githubusercontent.com/12884431/59501728-c4998480-8eb9-11e9-96f3-0c6abc538d4b.png)
![Issue1](https://user-images.githubusercontent.com/12884431/59501739-ca8f6580-8eb9-11e9-9f20-31921d11f0c5.png)
![Issues2](https://user-images.githubusercontent.com/12884431/59501747-ce22ec80-8eb9-11e9-829d-acff25ab9a7e.png)

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by yggg** [comment]
Hi @chaitrapdeshpande, thanks for reporting.
Looks very similar to #1443. Issue should be gone after upgrade to Nebular `3.6.1` or `4.1.0`. 
It will be fixed in `ngx-admin` when we finish migration to Nebular 4.

Closing as fixed in Nebular.
