### ISSUE TITLE
Error : WARNING in ./node_modules/@nebular/theme/fesm5/index.js 1024:41-59 "export 'ɵɵdefineInjectable' was not found in '@angular/core'

### ISSUE THREAD

**Issue by chaitrapdeshpande** [akveo/nebular#1625]
I am getting this following error once I upgrade to Nebular 3.6.1 , **I am not able to go forward,How to resolve this.?** Do I need to upgrade Angular as well, Nothing is written is doc like that. **With Angular 7 itself how I can go forward with Nebular 3.6.1 Version?**

Following are the Warning :
WARNING in ./node_modules/@nebular/theme/fesm5/index.js 1024:41-59
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@nebular/theme/fesm5/index.js 1769:46-64
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@nebular/theme/fesm5/index.js 1024:141-149
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@nebular/theme/fesm5/index.js 1769:156-164
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@nebular/theme/fesm5/index.js 1769:189-197
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@nebular/theme/fesm5/index.js 1769:219-227
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@nebular/theme/fesm5/index.js 1769:253-261
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@nebular/theme/fesm5/index.js 1769:271-279
"export 'ɵɵinject' was not found in '@angular/core'
ℹ ｢wdm｣: Compiled with warnings.

Here is my Package.json File :
{
  "name": "nebualr-angular-latest",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.2.15",
    "@angular/cdk": "^7.2.2",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@nebular/theme": "^3.6.1",
    "core-js": "^2.5.4",
    "nebular-icons": "^1.1.0",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "~7.3.5",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@schematics/angular": "~7.2.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }
}

**Comment by inidaname** [comment]
Having same error please has anything been done about it

**Comment by benmed00** [comment]
Having the same issue, can any one help

**Comment by yggg** [comment]
Nebular 3.6 requires Angular 8+.
>Do I need to upgrade Angular as well, Nothing is written is doc like that.
No docs needed, npm will warn you about unmet peer dependencies for Nebular packages during install.

**Comment by nnixaa** [comment]
Seems resolved.
