### ISSUE TITLE
nebular login page error handling 

### ISSUE THREAD

**Issue by frankkiv** [akveo/nebular#163]
### Issue type

* [ ] bug report
* [x] feature request

### Issue description

I just follow the instructions on https://akveo.github.io/nebular/#/docs/auth/nbemailpassauthprovider
try to implement the nebular auth login.

And I change the default setting in app.module.ts 
```
// Original
token: {
    key: 'accessToken',
    getter: (module: string, res: HttpResponse<Object>) => getDeepFromObject(res.body, this.getConfigValue('accessToken')),
},

//Mine
token: {
    key: 'data',
    getter: (module: string, res: HttpResponse<Object>) => {
        if(res.body['status']==200){
            return getDeepFromObject(res.body, 'accessToken');
        }else{
            //Error handling
            return false
        }
}
```
I'm successful get the token back, and set to localstorage item auth_app_token.

Now, **my question is how to manage the error handling in login page.**
It seems like no matter what value I return back(even false), It always shows 
<img width="352" alt="2018-01-22 3 18 52" src="https://user-images.githubusercontent.com/8171187/35209429-e5fc379c-ff88-11e7-94fc-23206e02be95.png">

And I also want to know how to customized the error message.

I would greatly appreciate for any advices. 
Thank you!

**Comment by nnixaa** [comment]
Hi @frankkiv, could you provide a reproducible example, please?

**Comment by nnixaa** [comment]
Closing as no response.
