### ISSUE TITLE
Custom icons in NbMenu

### ISSUE THREAD

**Issue by pdomala** [akveo/nebular#1635]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

Unable to use custom icons in NbMenu.

It throws below error when I use my custom icon font or fontawesome.

**Related code:**

```
ERROR Error: Icon 'fas fa-user' is not registered in pack 'eva'. Check icon name or consider switching icon pack.
```

### Other information:

**Angular, Nebular**
```
"dependencies": {
    "@angular/animations": "~8.0.0",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "@nebular/bootstrap": "^4.1.0",
    "@nebular/eva-icons": "4.1.0",
    "@nebular/theme": "^4.1.0",
    "rxjs": "~6.5.2",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  }
```

**Comment by DevToKa** [comment]
I get the same error when i try to use 'nb-home' as a icon in a menu. I used a new angular project and the quick setup with 'ng add @nebular/theme'

**Comment by nnixaa** [comment]
Please check the following docs we are about to add https://github.com/akveo/nebular/blob/6f26f8d55a1417a449d9247a6138e7b9d069d916/docs/articles/guides/custom-icons.md

**Comment by xouqoa** [comment]
Do you have any recommendations for being able to mix and match icon packs declaratively? The NbMenuItem class accepts a string, but it may be helpful to change that to an object which accepts { pack: string; icon: string } or something along those lines.

Currently, if I'm setting up a menu, I can't use icons from multiple packs, unless I'm missing something.
