### ISSUE TITLE
Auth: oauth 2 provider

### ISSUE THREAD

**Issue by nnixaa** [akveo/nebular#166]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**

**Expected behavior:**

Subj, TDB

**Comment by pankamilr** [comment]
anything going on with this feature? Or how to add additional data to `POST` object in EmailPAsswordProvider?

**Comment by pankamilr** [comment]
Hi @nnixaa thanks for your reply. Do you know already when the release will be pushed to master?

**Comment by nnixaa** [comment]
@pankamilr we are trying to keep 2-weeks release schedule, though it's not always possible due to a number of reasons. I would say this feature will be released in about a month.
