### ISSUE TITLE
Theme issue after configure auth

### ISSUE THREAD

**Issue by slymnGms** [akveo/nebular#1665]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [] feature request

### Issue description
After start to apply authorization in ngx-admin app, i started install the packages, then this happened, couldn find where to resolve this issue after some attempts.

**Related code:**
import { NbIconLibraries, NbSvgIcon } from '@nebular/theme'; 

ERROR in node_modules/@nebular/eva-icons/eva-icons.module.d.ts(1,10): error TS2305: Module '"../theme"' has no exported member 'NbIconLibraries'.
node_modules/@nebular/eva-icons/eva-icons.module.d.ts(1,27): error TS2305: Module '"../theme"' has no exported member 'NbSvgIcon'.

### Other information:

**npm, node, OS, Browser**
```
Node v10.16.0
npm 6.9.2
OS: Linux(Ubuntu 18.04)
Browser: Chrome

**Angular, Nebular**
```
    "@angular/core": "^7.2.11",
    "@nebular/auth": "^4.1.0",
    "@nebular/bootstrap": "3.4.2",
    "@nebular/eva-icons": "^4.0.0-rc.8",
    "@nebular/security": "^3.4.2",
    "@nebular/theme": "^3.4.2",

**Comment by yggg** [comment]
The issue lays in package versions. All `@nebular/*` packages should have the same version. If you need `nb-icon` than you must upgrade to 4+ version. Also, Nebular 4 requires Angular version 8
