### ISSUE TITLE
nb-layout-column color doesn't work based on example provided

### ISSUE THREAD

**Issue by elucidsoft** [akveo/nebular#1666]
The example provided via the documentation here: https://akveo.github.io/nebular/docs/components/layout/examples#nblayoutcomponent

Does not work, the below snipped sets the class="colored-column-warning" and you would expect this to change background color of the column.  Instead it does absolutely nothing.  This class doesn't exist in the theme at all, I looked for it.  I got around this by creating this class manually in my scss and injecting the correct color using nb-theme but that's not mentioned ANYWHERE in the documentation, so if that's how I am suppose to do it sure would be nice.

### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Does nothing, no style is generated because class doesn't exist.

**Expected behavior:**
For it to apply correct style.

**Steps to reproduce:**
- Use snippet above on brand new project.

**Related code:**
```
<nb-layout>
  <nb-layout-header>Awesome Company</nb-layout-header>
  <nb-layout-column class="colored-column-warning">Left column</nb-layout-column>
  <nb-layout-column class="colored-column-danger">Right column</nb-layout-column>
</nb-layout>
```

### Other information:
Angular 8, Latest Nebular version

**Comment by yggg** [comment]
Thanks for reporting @elucidsoft. These color classes are part of examples helpers and they are not meant to be part of the Nebular theming system. We changed sidebar background in these examples to make them visually distinguishable.
But I agree not having all the code used for example could be confusing.

Answering your question
> if that's how I am suppose to do it sure would be nice

Yes, you should add own class with colors you need for the specific sidebar. In case you need to change the color of all sidebars, it's better to change it via `layout-background-color` theme variable.

Keeping the issue open as we need to fix it.
