### ISSUE TITLE
nb-select fullWidth, options not showing full width

### ISSUE THREAD

**Issue by pdashford** [akveo/nebular#1674]
Hi, when using the nb-select with the fullWidth directive, the options are not of the same width and show centralised on the dropdown. Could someone advise if I'm missing something

**Comment by yggg** [comment]
@pdashford I can see the issue with the transparent area on options list when select is full width:
![image](https://user-images.githubusercontent.com/6151971/61461133-c521b100-a978-11e9-89d1-70b2c9bd3eaa.png)
Fixed by #1837

>show centralised on the dropdown

Could you please elaborate on this?
