### ISSUE TITLE
Module not found: Error: Can't resolve '@nebular/auth/helpers'

### ISSUE THREAD

**Issue by maihannijat** [akveo/nebular#1675]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description
Importing `getDeepFromObject` in the components but it throws error:

> Module not found: Error: Can't resolve '@nebular/auth/helpers'

The `helpers.d.ts` exists in the location and has the line which exports the above function.

Using Nebular 4.

```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": [],
    "paths": {
      "@nebular/*": [
        "./node_modules/@nebular/*"
      ]
    }
  },
  "include": [
    "src/**/*.ts",
    "./node_modules/@nebular/**/*.ts"
  ],
  "exclude": [
    "src/test.ts",
    "src/**/*.spec.ts"
  ]
}
```

**Comment by MenchenFive** [comment]
Can confirm, we are migrating an NgxAdmin project from the old 3.6 version to the current nebular-4-based version, and, despite VSCode showing no errors, the Angular compiler can't reach @nebular/auth/helpers for some reason.

**Comment by AhsanNissar** [comment]
@nnixaa  is this bug fixed yet? I am unable to move forward with my task because of this bug. Is there any temporary fix to this bug?

**Comment by yggg** [comment]
It's not fixed yet. As a workaround, you can copy functions you need from https://github.com/akveo/nebular/blob/44225d40f8c8754c1a8fe31e3b160a651c440d27/src/framework/auth/helpers.ts#L119

**Comment by arv1989** [comment]
Is the resolved? I am still getting the same error in 4.1.2,

**Comment by maihannijat** [comment]
@arv1989 It is resolved. It works for me now.

**Comment by arv1989** [comment]
okay. thanks for the confirmation. I was trying to implement Firebase Auth with the module, I imported getDeepFromObject like this,

`import { getDeepFromObject } from '@nebular/auth/helpers';`

As it is done at [https://github.com/GianlucaRi/ngx-admin/blob/master/src/app/auth/login/login.component.ts](https://github.com/GianlucaRi/ngx-admin/blob/master/src/app/auth/login/login.component.ts) , But I get the error as 

```
Failed to compile.

./src/app/auth/login/login.component.ts
Module not found: Error: Can't resolve '@nebular/auth/helpers' in '/.../src/app/auth/login'
```

any thoughts?
@maihannijat @yggg 
I checked and confirmed that I am run-in ver 4.1.2

**Comment by yggg** [comment]
@arv1989 You need to import `getDeepFromObject` from `@nebular/auth`, not `@nebular/auth/helpers`

**Comment by arv1989** [comment]
@yggg oh sorry.. thanks!
