### ISSUE TITLE
Accordion component misplacing child icon within header

### ISSUE THREAD

**Issue by krakowski** [akveo/nebular#1678]
### Accordion component misplacing child icon within header

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Embedding an icon within the header of an accordion item results in the icon being placed underneath the expansion indicator.

**Expected behavior:**
The icon should be placed at the specified position.

**Steps to reproduce:**
Place an `nb-icon` within a `nb-accordion-item-header`.

**Related code:**
https://stackblitz.com/edit/nb-accordion-icon

![image](https://i.imgur.com/Kakim41.png)

```html
<nb-accordion-item-header>
    <nb-icon icon="checkmark-square-2" status="success"></nb-icon>
    <span>Lorem ipsum</span>
</nb-accordion-item-header>
```

**Angular, Nebular**
```
"@angular/core": "^8.0.0"
"@nebular/theme": "^4.1.0"
```

**Comment by yggg** [comment]
Thanks for reporting @krakowski. The fix (#1836) will land in the next release.
