### ISSUE TITLE
NbCheckbox: `value` is deprecated and will be removed in 5.0.0. Use `checked` instead.

### ISSUE THREAD

**Issue by BattiniSantthosh** [akveo/nebular#1752]
How to fix the below warning for a nebular multi-select option.

NbCheckbox: `value` is deprecated and will be removed in 5.0.0. Use `checked` instead.

**Comment by yggg** [comment]
It's should be fixed in `4.1.1`. Do you still see this after updating to `4.1.1.`?

**Comment by BattiniSantthosh** [comment]
am using 4.0.0 version

**Comment by yggg** [comment]
Then update please, it's not possible to modify an already published version

**Comment by skeet94** [comment]
This happens using version 4.6 too

**Comment by yggg** [comment]
It should be fixed by #1747 which is included in 4.1.1 release. I can't see the issue starting from 4.1.1. If you still see this warning, please provide a reproducible code example or [stackblitz](https://stackblitz.com/github/akveo/nebular-seed) and reopen this issue.
