### ISSUE TITLE
How to make cards resizeable with 8-way size handle

### ISSUE THREAD

**Issue by sukeshlaghate** [akveo/nebular#18]
Hello, 
I am new to angular and to Nebular UI library. The UI library is indeed very cool. Very much appreciate your work.

I was wondering how can I make the nebular card component resizable? It would be nice to be able to show 8-way resizable handles enabling user to click and drag the sides of the card.

Visually appealing style for the drag handles would be to use solid lines instead of boring boxes and a dashed line around the card component. something like the attached image

![resizable_frame_with_handles](https://user-images.githubusercontent.com/25061957/31052657-b0a60124-a6a8-11e7-8963-37a2d8eb39a6.png)

**Comment by sukeshlaghate** [comment]
Any updates on this? It would be nice feature to have resizable and draggable  cards.

**Comment by nnixaa** [comment]
Hey @sukeshlaghate, unfortunately, we don't have plans to support this at least for now. But it would be great if you contribute into Nebular with that feature 👍
