### ISSUE TITLE
Not able to apply corporate theme in my application. Can any one please help

### ISSUE THREAD

**Issue by sandeepkamathkr** [akveo/nebular#1814]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [ ] feature request

### Issue description

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by yggg** [comment]
Please add more details like what is your steps, do you have some errors, etc.
It would be helpful to know do you need to enable one prebuilt theme or multiple themes.
The most basic setup is:
1. Add `"node_modules/@nebular/theme/styles/prebuilt/corporate.css"` into `styles` array in `angular.json`.
2. Set theme via `NbThemeModule.forRoot({ name: 'corporate' })`

See [installation docs](https://akveo.github.io/nebular/docs/guides/install-nebular#manually) for more details on basic setup and [advanced setup guide](https://akveo.github.io/nebular/docs/design-system/enable-customizable-theme#enable-customizable-themes) for multiple/custom themes setup.

**Comment by sandeepkamathkr** [comment]
@yggg Thanks for your reply.
I have done the same and now its working.
