### ISSUE TITLE
Search. Cannot read property 'unsubscribe' of undefined.

### ISSUE THREAD

**Issue by dimaatkaev** [akveo/nebular#184]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report

### Issue description

**Steps to reproduce:**

* Open search playground (http://localhost:4200/#/search)
* In the address bar put the new location.
* Observe error in the console
```ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'unsubscribe' of undefined```
![cannot_read_property_ unsubscribe _of_undefined](https://user-images.githubusercontent.com/16410702/35723526-a72a9d3e-080b-11e8-8e35-9ff8ecf225a3.png)

**Expected behavior:**
No error.

**Related code:**

nebular/src/framework/theme/components/search/search.component.ts
```
 ngOnDestroy() {
    this.activateSearchSubscription.unsubscribe();
    this.deactivateSearchSubscription.unsubscribe();
    this.routerSubscription.unsubscribe();

    const componentRef = this.searchFieldComponentRef$.getValue();
    if (componentRef) {
      componentRef.destroy();
    }
  }
```

**Comment by nnixaa** [comment]
fixed

**Comment by valiaga** [comment]
i don't not resolve this problem
please help me
