### ISSUE TITLE
How to  custom login failed message?

### ISSUE THREAD

**Issue by JimmyQin** [akveo/nebular#1844]
Hi!
How to  custom login failed message?
default message is **Login/Email combination is not correct, please try again.**  
I want to change it.

**Comment by yggg** [comment]
You can change method when configuring auth strategy.
```
@NgModule({
  imports: [
   // ...
   NbAuthModule.forRoot({
         strategies: [
           NbPasswordAuthStrategy.setup({
             name: 'email',
             login: {
               defaultErrors: ['Custom message'], // <- here you can provide a custom message
             },
             // ...
           }),
         ],
         forms: {
           // ...
         },
       }), 
  ],
});
```

**Comment by JimmyQin** [comment]
> Hi @JimmyQin. You can change the message when configuring auth strategy.
> 
> ```
> @NgModule({
>   imports: [
>    // ...
>    NbAuthModule.forRoot({
>          strategies: [
>            NbPasswordAuthStrategy.setup({
>              name: 'email',
>              login: {
>                defaultErrors: ['Custom message'], // <- here you can provide a custom message
>              },
>              // ...
>            }),
>          ],
>          forms: {
>            // ...
>          },
>        }), 
>   ],
> });
> ```

thanks~

**Comment by JimmyQin** [comment]
@yggg thanks~
