### ISSUE TITLE
Modal/Dialog memory leak

### ISSUE THREAD

**Issue by beig** [akveo/nebular#1847]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Modal Components stay in memory

**Expected behavior:**
They should get destroyed

**Steps to reproduce:**
create new angular project
```
ng new test
ng add @nebular/theme
# add NbDialogModule.forRoot() in app.module
# create another component and open it with the NbDialogservice
this.dialogService.open(TestComponent);
```

take a memory snapshot with dev tools

![image](https://user-images.githubusercontent.com/2438152/61550759-a512f000-aa53-11e9-8150-248e8a276d2b.png)

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows 10
Browser: Chrome
-->
```

**Angular, Nebular**
```
    "@angular/common": "~8.1.0",
    "@nebular/theme": "^4.1.2",
```

**Comment by yggg** [comment]
Thanks for reporting @beig, I can confirm the issue.

Related code:
https://github.com/akveo/nebular/blob/3d2e4dfa9d7f061271abb313fcd5c64a48d366a7/src/framework/theme/components/dialog/dialog.service.ts#L238
Adding takeUntil(dialogRef.onClose) should be enough. Also, we need to check window component for the same problem.

**Comment by beig** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  05.08.2019.
Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [akveo/nebular] Modal/Dialog memory leak (#1847)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2019 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------
