### ISSUE TITLE
Treegrid Problem

### ISSUE THREAD

**Issue by marifnst** [akveo/nebular#1849]
Hi

i can't generate treegrid more than 2 level child, is there any suggestion regarding this problem ?

below is my console log error:
ERROR TypeError: toCheck.push is not iterable (cannot read property Symbol(Symbol.iterator))
    at NbTreeGridService.find (index.js:21523)
    at NbTreeGridService.toggle (index.js:21509)
    at NbTreeGridDataSource.toggle (index.js:21579)
    at NbTreeGridDataSource.toggleByIndex (index.js:21585)
    at NbTreeGridComponent.toggleRow (index.js:22011)
    at SafeSubscriber._next (index.js:21698)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    at SafeSubscriber.next (Subscriber.js:122)
    at Subscriber._next (Subscriber.js:72)
    at Subscriber.next (Subscriber.js:49)

fyi, i'm using ngx-admin.

it's happening also in ngx-admin website:
![Screenshot from 2019-07-23 16-58-42](https://user-images.githubusercontent.com/17808183/61703289-7c4c6c80-ad6b-11e9-803a-540fd831aab8.png)

Thanks

**Comment by rahulaparajit79** [comment]
I have also got same error. Please Fix it asap.

**Comment by rahulaparajit79** [comment]
**Got Solution**
Give empty children array if a node has no children. As children is undefined toCheck.push(undefind) generate exception.
**Give data in below format.**

data: TreeNode<FSEntry>[] = [
    {
      data: { name: 'A', kind: 'dir', size: '1', items: 2 },
      children: [{
        data: { name: 'A1', kind: 'dir', size: '1' },
        children: [{
          data: { name: 'A2', kind: 'dir', size: '1' },
          children: [{
            data: { name: 'A21', kind: 'dir', size: '1' },
            children: [{
              data: { name: 'A211', kind: 'doc', size: '1' },
              children: [],
            },
            {
              data: { name: 'A212', kind: 'doc', size: '1' },
              children: [],
            }],
          }],
        }, {
          data: { name: 'A3', kind: 'dir', size: '1' },
          children: [{
            data: { name: 'A31', kind: 'doc', size: '1' },
            children: [],
          },
          {
            data: { name: 'A32', kind: 'doc', size: '1' },
            children: [],
          },
          {
            data: { name: 'A33', kind: 'doc', size: '1' },
            children: [],
          }],
        },
        {
          data: { name: 'A4', kind: 'dir', size: '1' },
          children: [{
            data: { name: 'A41', kind: 'doc', size: '1' },
            children: [],
          },
          {
            data: { name: 'A42', kind: 'doc', size: '1' },
            children: [],
          }],
        }],
      },
      ],
    },
  ];

**Comment by shacojx** [comment]
> **Got Solution**
> Give empty children array if a node has no children. As children is undefined toCheck.push(undefind) generate exception.
> **Give data in below format.**
> 
> data: TreeNode[] = [
> {
> data: { name: 'A', kind: 'dir', size: '1', items: 2 },
> children: [{
> data: { name: 'A1', kind: 'dir', size: '1' },
> children: [{
> data: { name: 'A2', kind: 'dir', size: '1' },
> children: [{
> data: { name: 'A21', kind: 'dir', size: '1' },
> children: [{
> data: { name: 'A211', kind: 'doc', size: '1' },
> children: [],
> },
> {
> data: { name: 'A212', kind: 'doc', size: '1' },
> children: [],
> }],
> }],
> }, {
> data: { name: 'A3', kind: 'dir', size: '1' },
> children: [{
> data: { name: 'A31', kind: 'doc', size: '1' },
> children: [],
> },
> {
> data: { name: 'A32', kind: 'doc', size: '1' },
> children: [],
> },
> {
> data: { name: 'A33', kind: 'doc', size: '1' },
> children: [],
> }],
> },
> {
> data: { name: 'A4', kind: 'dir', size: '1' },
> children: [{
> data: { name: 'A41', kind: 'doc', size: '1' },
> children: [],
> },
> {
> data: { name: 'A42', kind: 'doc', size: '1' },
> children: [],
> }],
> }],
> },
> ],
> },
> ];

thanks for solution!
