### ISSUE TITLE
[MENU] Icons from differents packs

### ISSUE THREAD

**Issue by yggg** [akveo/nebular#1851]
Do you have any recommendations for being able to mix and match icon packs declaratively? The NbMenuItem class accepts a string, but it may be helpful to change that to an object which accepts { pack: string; icon: string } or something along those lines.

Currently, if I'm setting up a menu, I can't use icons from multiple packs, unless I'm missing something.

_Originally posted by @xouqoa in https://github.com/akveo/nebular/issues/1635#issuecomment-511532982_

**Comment by xouqoa** [comment]
What I did for now (as a workaround) was I added my custom icons to the base (Eva) pack.

**Comment by awtkeithlin** [comment]
I upgrade nebular from 3.4.2 to 4.1.2 but PagesComponent work not fine.
In 3.4.2 I use font fontawesome icon but 4.1.2 is broken.
![1.1](https://i.imgur.com/NNT5Rih.png)
nebular  source code diff:
![1.2](https://i.imgur.com/FM6nL0A.png)

I try this https://github.com/akveo/nebular/blob/6f26f8d55a1417a449d9247a6138e7b9d069d916/docs/articles/guides/custom-icons.md
but not work.

**Comment by aletaschner** [comment]
I'm having the same issue. Even when I register the font-awesome pack it does not work for me.

**Comment by LeanKhan** [comment]
@xouqoa how did you do that? Pls

**Comment by xouqoa** [comment]
@LeanKhan 

I created a service like this:

https://gist.github.com/xouqoa/1d916c500856e969d2017dec029616b8

Then import the service into your app module (or wherever) and call the .load() method.

After that, you can reference your custom icons from the default set.

`<nb-icon icon="icon1"></nb-icon>`
