### ISSUE TITLE
not work type="tel" in input with nbInput

### ISSUE THREAD

**Issue by shomid** [akveo/nebular#1853]
use of ngx-admin with nebular.
use of below code for get mobile of user.

    `<input nbInput fullWidth required class="text-left" type="tel" name="mobile" id="mobile"
          ngControl="mobile" [(ngModel)]="profileItem.mobile">`

but user can enter any character in textbox.

**Comment by yggg** [comment]
Hi @shomid, I copied your example into [stackblitz](https://stackblitz.com/edit/nebular-1853?file=src/app/app.component.html) and it works. Please make sure there are no errors in the browser console, `FormsModule` and `NbInputModule` are imported, etc.
Also, I can't recognize this code `ngControl="mobile"`. Is it your directive?
If you still experience the issue, please provide more details according to issue template, like the browser you use, packages version, etc.

**Comment by shomid** [comment]
> Hi @shomid, I copied your example into [stackblitz](https://stackblitz.com/edit/nebular-1853?file=src/app/app.component.html) and it works. Please make sure there are no errors in the browser console, `FormsModule` and `NbInputModule` are imported, etc.
> Also, I can't recognize this code `ngControl="mobile"`. Is it your directive?
> If you still experience the issue, please provide more details according to issue template, like the browser you use, packages version, etc.

hi @yggg,I tested example but I can enter any character ,not only char number.

**Comment by yggg** [comment]
Oh, sorry @shomid, I misunderstood the initial issue. You can enter anything since input has no validators on it ([MDN says](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel) `type="tel"` has no validation by default). You need to
