### ISSUE TITLE
No provider for NbTokenStorage

### ISSUE THREAD

**Issue by BansiPatel92** [akveo/nebular#1854]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [] feature request

### Issue description
I am trying to make custom login , forgot password and reset password facility and for that I am using Authservice from the code I copied from Framework> Auth  folder
I have copied whole Auth folder into my **App** folder and imported the NbAuthModule into app.module file. 

**Current behavior:**
I am getting following errors:
1.
NullInjectorError: StaticInjectorError(AppModule)[NbTokenService -> NbTokenStorage]: 
  StaticInjectorError(Platform: core)[NbTokenService -> NbTokenStorage]: 
    NullInjectorError: No provider for NbTokenStorage!

2.
NullInjectorError: StaticInjectorError(AppModule)[NbTokenService -> NbTokenStorage]: 
  StaticInjectorError(Platform: core)[NbTokenService -> NbTokenStorage]: 
    NullInjectorError: No provider for NbTokenStorage!
NullInjectorError: StaticInjectorError(AppModule)[NbTokenService -> NbTokenStorage]: 
  StaticInjectorError(Platform: core)[NbTokenService -> NbTokenStorage]: 
    NullInjectorError: No provider for NbTokenStorage!

**Expected behavior:**
when I open Login page it should not throw this error because I already imported required files into app.module and login.component also.

**Steps to reproduce:**

1.Copy and paste the auth folder from framework
2.Import Nbauthmodule in app.module 
3.import Nnauthservice in app.module
4.Rest of the code in login.component is as it is and run the application.

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
Chrome , Ubuntu , Latest version of Nebular, Angular , NPM and Node
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by yggg** [comment]
Hi @BansiPatel92, you don't need to copy all auth directory. Please follow the [custom auth components guide](https://akveo.github.io/nebular/docs/auth/custom-auth-components#custom-auth-components). You may copy the auth component template if you slightly modifying default Nebular components, that's all.

**Comment by skumlk** [comment]
I created auth component by following "custom auth components guide" and got the same issue. I could solve it, by adding "NbAuthModule.forRoot()" in app.module.ts, its missing in the documentation. May be this will help someone.

**Comment by dcleme17** [comment]
> I created auth component by following "custom auth components guide" and got the same issue. I could solve it, by adding "NbAuthModule.forRoot()" in app.module.ts, its missing in the documentation. May be this will help someone.

Thanks @skumlk. it worked like a charm.
