### ISSUE TITLE
NbSelect missing compareWith input similar to the native select

### ISSUE THREAD

**Issue by ahmedNY** [akveo/nebular#1858]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**
I had form thats' loads data from an API, binding an object to NbSelect (selcted)  not working for object value

**Expected behavior:**
something similar to compareWith Input specified on the  https://angular.io/api/forms/SelectControlValueAccessor

**Steps to reproduce:**

**Related code:**

myComponent.html
```
<nb-select formControlName="user" [selected]="form.value.user [compareWith]="compareById">
    <nb-option *ngFor="let usert of users" [value]="user">
        {{ user.fullName }}
    </nb-option>
</nb-select>
```

myComponent.ts
```
  users = [{id: 1, fullName: 'Foo"}, {id: 2, fullName: 'Bar'}]
  compareById(user1: User, user2: User) {
    return user1 && user2 && user1.id === user2.id;
  }
```
### Other information:

**npm, node, OS, Browser**
```
node: v10.15.3
npm: 6.4.1
OS: macOS (Mojave)
Browser: Opera Chromium
-->
```

**Angular, Nebular**
```
Angular: 8.0.0
Nebular: 4.1.2
```

**Comment by alainm23** [comment]
Some update about it?

**Comment by Tashaa78** [comment]
Any update?

**Comment by matiasah** [comment]
I need this.

**Comment by dev-alexandre** [comment]
How Can I help?

**Comment by dev-alexandre** [comment]
Please see de tread

https://github.com/akveo/nebular/issues/1858

**Comment by dev-alexandre** [comment]
Please see this tread:

https://github.com/akveo/nebular/pull/1223
