### ISSUE TITLE
[Menu] Can we expand menu in overlay without pushing main content.

### ISSUE THREAD

**Issue by mont8593** [akveo/nebular#1861]
* [ x ] feature request

Is it possible to have menu expanded in overlay mode instead of pushing the main content?

Thanks in advance :)

**Comment by ArtemRomanovsky** [comment]
hi @mont8593!
Yes, Nebular has such a possibility. What you are looking for is a sidebar with the fixed setting. See an example of the fixed sidebar here https://akveo.github.io/nebular/docs/components/sidebar/examples#nbsidebarcomponent

**Comment by MisterEd0105** [comment]
Hi,

i want the sidebar to overlay over the content AND the header.
Is that possible in any way?

thanks in advance

**Comment by mont8593** [comment]
@MisterEd0105 you can achieve this by https://akveo.github.io/nebular/docs/components/sidebar/examples#nbsidebarcomponent
and scaling up z-index for your sidebar as per need, apologies for delayed reply.
