### ISSUE TITLE
[Checkbox] Attempt to use a destroyed view: detectChanges

### ISSUE THREAD

**Issue by ciesielskico** [akveo/nebular#1879]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
`Attempt to use a destroyed view: detectChanges`

**Expected behavior:**
Don't call `detectChanges` in the component, which doesn't use OnPush detection anyway, OR implement OnPush change detection and use the change detector ref in a proper way.

**Comment by SanaeHanaoui** [comment]
i have the same issue when i try to use it inside an overlay

**Comment by yggg** [comment]
Fixed in #2236
