### ISSUE TITLE
Can not find Documenration for V3.0.0

### ISSUE THREAD

**Issue by macpatel** [akveo/nebular#1886]
### Issue type

Where can we see the old docs like for version 3.0.0 ?

* [ ] bug report
* [X] feature request

### Issue description

**Current behavior:**
There is documentation for only 3.6 & 4.1, can't find the docs for 3.0.0

**Expected behavior:**
Should be able to see docs for all the versions if there is a major change between versions.

**Steps to reproduce:**
Go to below URL:
https://akveo.github.io/nebular/

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
Node: v8.X NPM: 6.X.X
OS: Ubuntu 16.04
Browser: Chrome 76
```

**Angular, Nebular**
```
"@angular/common": "^7.0.3",
"@nebular/auth": "3.0.0",
"@nebular/bootstrap": "3.0.0",
"@nebular/security": "3.0.0",
"@nebular/theme": "3.0.0",
```

**Comment by nnixaa** [comment]
Hi @macpatel, Nebular support two last major versions. The latest 3.x version is 3.6.0. We highly recommend updating to 3.6.0 (and better to 4.x) since it contains bugfixes and improvements.
