### ISSUE TITLE
nb-select bug when at the bottom destroys footer

### ISSUE THREAD

**Issue by jagabs** [akveo/nebular#1902]
Before
![Screen Shot 2019-08-12 at 9 00 22 PM](https://user-images.githubusercontent.com/17292042/62866983-c7dbb000-bd44-11e9-8c33-70b0f48d43cf.png)

After
![Screen Shot 2019-08-12 at 9 00 14 PM](https://user-images.githubusercontent.com/17292042/62866988-c9a57380-bd44-11e9-8e51-7b1fd0da0d5e.png)

seems its extending the footer. I can provide example if cant replicate

**Comment by ArtemRomanovsky** [comment]
hi @jagabs!
This issue was fixed recently. Could you check if the issue still persists with the latest version of Nebular? If yes, could you please create a reproducible example on https://stackblitz.com/github/akveo/nebular-seed so we can see the issue

**Comment by jagabs** [comment]
so far i cant replicate it anymore. Thanks!
