### ISSUE TITLE
The dialog popup windows with NbDialogService does not have a scrollbar

### ISSUE THREAD

**Issue by alexsintoni** [akveo/nebular#1907]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
The dialog popup windows does not have a scrollbar. So, when the content of a dialog window open using the following example (example from [NbDialogService](https://akveo.github.io/nebular/docs/components/dialog/examples#nbdialogservice)
```
import { Component } from '@angular/core';
import { NbDialogService } from '@nebular/theme';
import { ScrollDialogComponent } from './components/scroll-dialog.component';

@Component({
  selector: 'nb-dialog-scroll',
  template: `
    <button nbButton (click)="openWithScroll()">With scroll</button>
    <button nbButton (click)="openWithoutScroll()">Without scroll</button>
  `,
  styleUrls: ['./dialog-common.scss'],
})
export class DialogScrollComponent {
  constructor(private dialogService: NbDialogService) {
  }

  openWithScroll() {
    this.open(true);
  }

  openWithoutScroll() {
    this.open(false);
  }

  protected open(hasScroll: boolean) {
    this.dialogService.open(ScrollDialogComponent, { hasScroll });
  }
}
```
does not have any scrollbar.

**Expected behavior:**
If the content of the dialog window is taller than the screen, I should have the scrollbar in order to read the full content.

**Steps to reproduce:**

Simply, use the code from the example and add enough content to the dialog window to overload the screen

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
no necessary

**Angular, Nebular**
Last version of Nebula 4.1.3

**Comment by xouqoa** [comment]
**hasScroll** doesn't do what you think it does, I don't think. 

Documentation for **NbDialogConfig** says:
> hasScroll | boolean | Disables scroll on content under dialog if true and does nothing otherwise.

If you need the dialog itself to have a scroll bar, try setting a `{ max-height: 95vh; }` on the root element inside the dialog.

**Comment by alexsintoni** [comment]
Hi @xouqoa 

I have tried to add to the `.scss` file of the component the following code:
```
@import '../../../../../content/scss/themes';

@include nb-install-component() {

  max-height: 95vh;

}
```

but it does not work

**Comment by xouqoa** [comment]
I am not sure what the code for your `ScrollDialogComponent` looks like in your original example.

But let's assume you have a `<nb-card></nb-card>` inside there which wraps your content. Try putting the max-height on there.

**Comment by alexsintoni** [comment]
@xouqoa 
ok I have found how to make it work so I close the ticket ;)

Thanks for the support :)

**Comment by hanalice** [comment]
but I found that it can  work beautifully only using nebular pre-defined element. If I wrap above the nb-card so on elements with div, it works no that satisfying.

**Comment by janice1015** [comment]
> @xouqoa ok I have found how to make it work so I close the ticket ;)
> 
> Thanks for the support :)

How did you solve the problem?

**Comment by janice1015** [comment]
How did you solve the problem final? I have the same problem as you，help~~
