### ISSUE TITLE
NbSelectComponent does not correctly handle boolean values.

### ISSUE THREAD

**Issue by xouqoa** [akveo/nebular#1910]
**I'm submitting a ...**

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
NbSelectComponent (or maybe NbOptionComponent) is unable to handle boolean values correctly.

**Expected behavior:**
Boolean values should be able to be selected via NgModel or FormControlName values.

**Related code:**

https://nebular-select-boolean.stackblitz.io

The top select is initialized with a boolean value, but the option isn't selected.

The middle one is initialized with a string, and it works fine.

Bottom one is a regular select with a boolean value which also works fine.

_Maybe there's a === in there somewhere instead of ==?_

### Other information:

@angular-devkit/build-angular 0.801.1
@angular/animations 8.1.1
@angular/cdk 8.0.2
@angular/common 8.1.1
@angular/compiler 8.1.1
@angular/compiler-cli 9.0.0-next.2
@angular/core 8.1.1
@angular/forms 8.1.1
@angular/platform-browser 8.1.1
@angular/platform-browser-dynamic 8.1.1
@angular/router 8.1.1
@nebular/theme 4.1.3
@types/jasmine 2.8.16
@types/jasminewd 22.0.6
@types/node 8.9.5
core-js 2.6.9
nebular-icons 1.1.0
rxjs 6.5.2
tslib 1.10.0
typescript 3.4.5
zone.js 0.9.1

**Comment by steven274** [comment]
You should use <nb-option [value]="true"></nb-option> instead of <nb-option value="true"></nb-option>
