### ISSUE TITLE
Chat dropped files double image preview

### ISSUE THREAD

**Issue by RafaelPallaresITB** [akveo/nebular#1912]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

When dropping an image to chat, the "dropped-files" div in "nb-chat-Form" shows the preview image plus and empty image placeholder. Deleting one of both deletes the image.

![imagen](https://user-images.githubusercontent.com/54269036/63258850-3b1d7e80-c27d-11e9-913c-df1896ab3f10.png)

**Expected behavior:**

When dropping an image to chat the "dropped-files" div in "nb-chat-form" should show only the preview of the image just dropped and no other extra image placeholder.

**Steps to reproduce:**

1- Open a chat view
2- Drop an image 
3- The preview and the empty placeholder both appear

**Related code:**

This bug is reproduceable in the example page of nebular chat

https://akveo.github.io/nebular/docs/components/chat-ui/examples#nbchatcomponent

### Other information:

**npm, node, OS, Browser**

Node Version 12.4.0
npm version: 6.9.0
Browser Chrome
Os Windows 10

**Angular, Nebular**

```
Angular 8.2.0
Nebular 4.1.3

**Comment by yyater97** [comment]
I think we can you css to hidden second block, write this code in style.css file

`nb-chat-form{
  .dropped-files{
    div{
      &:nth-child(2n){
        display: none;
      }
    }
  }
}`

**Comment by rijin-newage** [comment]
Preview is duplicating only for image files. For a temporary fix use this CSS style.

```css
.dropped-files > .ng-star-inserted[style] + .ng-star-inserted {
    display: none;
}
```
