### ISSUE TITLE
  ERROR in node_modules/@nebular/theme/components/datepicker/datepicker.component.d.ts(161,40): error TS2314: Generic type 'NbBasePicker<D, T, P>' requires 3 type argument(s).

### ISSUE THREAD

**Issue by techaks** [akveo/nebular#1946]
ERROR in node_modules/@nebular/theme/components/datepicker/datepicker.component.d.ts(161,40): error TS2314: Generic type 'NbBasePicker<D, T, P>' requires 3 type argument(s).

**Comment by Exiliot** [comment]
Could reproduce the same issue when tried to update to the edge versions of angular packages:
![image](https://user-images.githubusercontent.com/4901187/64423235-ac976280-d0ae-11e9-8615-cd75125ba6b8.png)

**Comment by abadakhshan** [comment]
If you have this problem with `"enableIvy"` it was an issue related to **angular compiler** that has been fixed in "9.0.0-next.14"

https://github.com/angular/angular/issues/31160

**Comment by yggg** [comment]
Closing as resolved. Thanks @abadakhshan!
