### ISSUE TITLE
 layout become messy on 2 column layout

### ISSUE THREAD

**Issue by mohammad0omar** [akveo/nebular#1956]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**

when i select the two column layout in the ngx-admin demo; the layout become messy
**Expected behavior:**

**Steps to reproduce:**

![image](https://user-images.githubusercontent.com/20974815/64944058-0b5e9800-d876-11e9-915e-5102f5c608c8.png)

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by ArtemRomanovsky** [comment]
hi @mohammad0omar! 
Could you please elaborate. What do you mean by "messy"? 🙂

**Comment by mohammad0omar** [comment]
I meant that there is some unordered content as indicated in the attached image.

**Comment by ArtemRomanovsky** [comment]
hi @mohammad0omar 
Thank you for the feedback! What do you think is the best variant to display two columns layout? By the way, we are always open for a pull request 🙂
