### ISSUE TITLE
Context Menu not working with Nebular Auth

### ISSUE THREAD

**Issue by aaronjonesii** [akveo/nebular#1960]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Context Menu in header works until redirected from NbLoginComponent or NbLogoutComponent, once redirected the context menu no longer works until the app is reloaded.

**Expected behavior:**
Context Menu in headers continually works after Logging out or Logging in.

**Steps to reproduce:**
1. Head over to the sample stackblitz project below
2. Click on Context Menu to verify it works
3. Click on Logout in the context menu
4. You will be redirected to an error
or
1. Head over to the sample stackblitz project below
2. Click on Context Menu to verify it works
3. Click on Auth in the SIdebar
4. Select Login from the Sidebar
5. Enter test credentials to test login
6. Click on Context Menu to see error

**Related code:**
StackBlitz [StackBlitz Seed Project](https://stackblitz.com/edit/angular-rar9na?embed=1&file=src/app/app.module.ts)
```
errors.ts:30 ERROR TypeError: Cannot read property 'appendChild' of null
    at NbOverlayContainerAdapter._createContainer (theme.umd.js:1165)
    at NbOverlayContainerAdapter.OverlayContainer.getContainerElement (overlay-container.ts:44)
    at NbOverlay.Overlay._createHostElement (overlay.ts:108)
    at NbOverlay.Overlay.create (overlay.ts:67)
    at NbOverlayService.create (theme.umd.js:1708)
    at NbDynamicOverlay.createOverlay (theme.umd.js:11354)
    at NbDynamicOverlay.show (theme.umd.js:11321)
    at SafeSubscriber.eval [as _next] (theme.umd.js:11563)
    at SafeSubscriber.__tryOrUnsub (Subscriber.ts:265)
    at SafeSubscriber.next (Subscriber.ts:207)
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` (v11.13.0) and `npm --version` (6.11.2)
OS: macOS Mojave
Browser: Chrome
-->
```

**Angular, Nebular**
```
   "@angular/animations": "~8.2.4",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "~8.2.4",
    "@angular/compiler": "~8.2.4",
    "@angular/core": "~8.2.4",
    "@angular/forms": "~8.2.4",
    "@angular/platform-browser": "~8.2.4",
    "@angular/platform-browser-dynamic": "~8.2.4",
    "@angular/router": "~8.2.4",
    "@nebular/auth": "^4.2.2",
    "@nebular/eva-icons": "4.2.2",
    "@nebular/theme": "^4.2.2",
    "bootstrap": "^4.3.1",
    "eva-icons": "^1.1.1",
```

**Comment by aaronjonesii** [comment]
Similar to [#1136](https://github.com/akveo/nebular/issues/1136) which was deemed resolved in [#1913](https://github.com/akveo/nebular/pull/1913) wth Nebular version 4.2.0.
I am still having this problem with Nebular 4.2.2

**Comment by aaronjonesii** [comment]
It was my `app-routing.module.ts` that was causing the problem.

Before:
```
const routes: Routes = [
  ...
  { path: 'auth',
    component: NbAuthComponent,
    children: [
      { path: '', component: NbLoginComponent },
      { path: 'login', component: NbLoginComponent },
      { path: 'register', component: NbRegisterComponent },
      { path: 'logout', component: NbLogoutComponent },
      { path: 'request-password', component: NbRequestPasswordComponent },
      { path: 'reset-password', component: NbResetPasswordComponent },
    ],
  },
  ...
];
```
After:
```
const routes: Routes = [
  ...
  { path: 'auth/login', component: NbLoginComponent },
  { path: 'auth/register', component: NbRegisterComponent },
  { path: 'auth/logout', component: NbLogoutComponent },
  { path: 'auth/request-password', component: NbRequestPasswordComponent },
  { path: 'auth/reset-password', component: NbResetPasswordComponent },
  ...
];
```

**Comment by tandacedric** [comment]
Do this in the component html file who you want to open context menu, toooltip, datepicker. 
`<nb-layout>
        <nb-layout-column>
           ... my html login here .....
        </nb-layout-column>
    </nb-layout>`
It is not an app-component.html file there, you  still also add that in your contextual file. 
It work for me

**Comment by aaronjonesii** [comment]
> Do this in the component html file who you want to open context menu, toooltip, datepicker.
> `<nb-layout> <nb-layout-column> ... my html login here ..... </nb-layout-column> </nb-layout>`
> It is not an app-component.html file there, you still also add that in your contextual file.
> It work for me

I tried that and it didn’t work for me but changing my Routes fixed the problem.

**Comment by dcruz1990** [comment]
@aaronjonesii: tried the routes fixing but then login shows **broken**, there is another solution to this?
