### ISSUE TITLE
Popover layout is cut 

### ISSUE THREAD

**Issue by amichiel** [akveo/nebular#1979]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
When  popover is positioned in a specific area of ​​the screen (for example top right), the content that is shown is cut. probably because of the arrow of parent component that is always centered

**Expected behavior:**
Popover content must be visualized uncutted 

**Steps to reproduce:**
Create new icon that open a popover which contains nebular list. Place icon on  top right of page than open popover. Popover content will be cutted

This is a video example: https://streamable.com/y887d

**Comment by ArtemRomanovsky** [comment]
Closing as duplicate #1626
