### ISSUE TITLE
Input with Icon

### ISSUE THREAD

**Issue by anthowm** [akveo/nebular#1999]
Is there a way to implement a input with nbicon inner it ?

**Comment by nektobit** [comment]
Hi, any news?

**Comment by SanaeHanaoui** [comment]
hi is there any news ?

**Comment by anthowm** [comment]
@ArtemRomanovsky @nnixaa

**Comment by carlamn22** [comment]
Hi, any news?

**Comment by louisbaclao** [comment]
Looking forward to this one

**Comment by ArtemRomanovsky** [comment]
Hello everyone, sorry for the absence, this feature is quite popular, so we include it in the next release 5.0.0 or 5.0.1

**Comment by SanaeHanaoui** [comment]
Thank you for hard work and we appreciate it

**Comment by ArtemRomanovsky** [comment]
Thanks yggg!
