### ISSUE TITLE
NbSidebarService -  compact method "is not a function"

### ISSUE THREAD

**Issue by mbayonestz** [akveo/nebular#2012]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**

When invoque the compact method in sidebar.service.ts to compact the sidebar, appears the console error "this.sidebarService.compact is not a function"
**Expected behavior:**

the sidebar will be compacted
**Steps to reproduce:**

1 - import { NbSidebarService, NbMenuItem } from '@nebular/theme/';
2 - private sidebarService: NbSidebarService
3 - invoque this.sidebarService.compact(); when click anywhere in nb-layout-column 
**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by yggg** [comment]
Which Nebular version do you use? `compact` method was added in the most recent (4.4.0) release.

**Comment by mbayonestz** [comment]
i have already made -> ng add @nebular/theme
and before that, copy all the content folder sidebar, where the new method is (6 files)
i see the method in the sidebar.service (compact(tag?: string) {
    this.compact$.next({ tag });
  })
indeed from the visual code component where im working i can get into the sidebar.service file and see that the method is there. its strange.
but im not sure where can i check the Nebular version that im using

**Comment by yggg** [comment]
You can find Nebular version in the `package.json` file, usually it in the project root directory. Search for `@nebular/theme` entry in the `dependencies` property.

**Comment by mbayonestz** [comment]
It is working, was the version problem, some files werent uploaded correctly
thank you for the fast response!!
greetings from Buenos Aires
