### ISSUE TITLE
nb-icon with font-awesome pack rendering null content on Microsoft Edge

### ISSUE THREAD

**Issue by mhartz82** [akveo/nebular#2021]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Using an nb-icon with font-awesome pack on Microsoft Edge the icon correctly appears, but after it a null content is rendered.

![rendering](https://user-images.githubusercontent.com/32393549/66909629-5ef70980-f00d-11e9-885a-52389838e152.png)

![code](https://user-images.githubusercontent.com/32393549/66909653-661e1780-f00d-11e9-894d-5516c0cb43b5.png)

**Expected behavior:**
Only the icon has to be rendered.

**Steps to reproduce:**
Register font-awesome icons like this:

```
iconLibraries.registerFontPack('font-awesome', { iconClassPrefix: 'fa', packClass: 'fas' });
```

and then use them like this:

```
<nb-icon icon="euro-sign" pack="font-awesome"></nb-icon>
```

Also your ngx-admin demo reproduces the problem: [https://akveo.com/ngx-admin/pages/ui-features/icons](https://akveo.com/ngx-admin/pages/ui-features/icons)

### Other information:

**npm, node, OS, Browser**
```
Browser: Edge
```

**Comment by yggg** [comment]
Fixed in Nebular 4.5.0 by https://github.com/akveo/nebular/issues/2043.
