### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError: nb-datepicker with filled reactive form

### ISSUE THREAD

**Issue by den1982** [akveo/nebular#2030]
I'm trying to implement a dialog with a reactive form, with dynamic form data pre initialisation. The dialog is in an sub-component, triggered from my main component.

When I try to preselect/fill the nb-datepicker component, I get this error:

I fill the formdata like this:

```
const todayDatepickerObjekt: Date = new Date('2019-10-15');
this.bookingForm = this.formBuilder.group({
      date: [{value: dateObject}, Validators.required],
```

With new Date()
`ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'status-success: false'. Current value: 'status-success: true'.`

With new Date('2019-10-15') I get this error;

`ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ng-pristine: true'. Current value: 'ng-pristine: false'.`

If I pre init the nb-datepicker component with null, everything is fine.

Here is an example:

[stackblitz.com/edit/github-lv7hp3
](http://stackblitz.com/edit/github-lv7hp3
)
Not sure if this is a bug or my fault.

**Comment by den1982** [comment]
I was able to solve the problem by first init the datepicker form control with null and after the dialog was opened, I call patchValue inside a timeout. But still no idea why I can't directly  init the control with a date object.

**Comment by ilDon** [comment]
@den1982 I'm having the same issue, can you post the code you used to solve the issue?
