### ISSUE TITLE
Set size to NbAlertComponent

### ISSUE THREAD

**Issue by RoWEN-FCUB** [akveo/nebular#2076]
The default sizes of the NbAlertComponent (tiny, small...) are all too big. Is there a way to just adjust the height of the alert? I need it to fit to the text size. Sorry if my English is not good. Thanks for any help.

**Comment by yggg** [comment]
You can customize alert size via a custom theme. See [Nebular custom theme guide](https://akveo.github.io/nebular/docs/design-system/enable-customizable-theme#enable-customizable-themes) for details. When setup complete, you can modify alert theme variables to adjust the size. There are `alert-tiny-height`, `alert-small-height`, `alert-medium-height`, `alert-large-height`, `alert-giant-height`. Here you can find a [full list of alert theme variables](https://akveo.github.io/nebular/docs/components/alert/theme#nbalertcomponent).
