### ISSUE TITLE
White space under Nb-Card

### ISSUE THREAD

**Issue by RoWEN-FCUB** [akveo/nebular#2077]
![NbCard withe space](https://user-images.githubusercontent.com/51714814/68768563-baa6b980-05f0-11ea-9c12-ddcdc8c53489.png)

I have a nb-card inside a ng-template binded to a nb-popover, and the card shows an empty white space under the card-footer. Why is that happening? This is my code:

`<nb-action [nbPopover]="new_notifications.length > 0 ? newnotif : null" nbPopoverPlacement="bottom" nbPopoverTrigger="hover" class="control-item" icon="bell-outline" badgePosition="bottom right" badgeStatus="info" [badgeText]="new_notifications.length > 0 ? new_notifications.length : null"></nb-action>`

`<ng-template #newnotif>
    <nb-card size="small">
      <nb-card-header>
        <div class="row fullWidth">
          <div class="col text-left">Notificaciones</div>
          <div class="col text-right"><span (click)="notificationsReaded()" class="btn-link" style="cursor: pointer;">Marcar como leídas</span></div>
        </div>
      </nb-card-header>
      <nb-card-body>
        <nb-card *ngFor="let notification of new_notifications; let i = index" [accent]="notification.estatus">
          <nb-card-body>
            <div class="row" style="cursor: pointer">
              <div class="col-10" [innerHTML]="notification.notificacion"></div>
              <div class="col-1 float-right"><nb-icon [options]="{animation:{type: 'zoom'}}" nbTooltip="Leída" (click)="notificationReaded(i)" icon="checkmark-outline"></nb-icon></div>
          </div>
          </nb-card-body>
        </nb-card>
      </nb-card-body>
      <nb-card-footer><span class="btn-link" style="cursor: pointer;">Ver todas</span></nb-card-footer>
    </nb-card>
  </ng-template>`

**Comment by yggg** [comment]
`nb-card` has default bottom margin. You can remove it in the component you use card via styles:
```
nb-card {
  margin-bottom: 0;
}
```
To remove it from cards everywhere, you could add style from above in the global styles (typically, `styles.css` or `styles.scss`) or via `card-margin-bottom` theme variable, if you configured [custom theming](https://akveo.github.io/nebular/docs/design-system/enable-customizable-theme#enable-customizable-themes).

**Comment by RoWEN-FCUB** [comment]
Thanks!!! That solved my problem!!
