### ISSUE TITLE
NbDatePicker input ignores DateFormat

### ISSUE THREAD

**Issue by tkitv** [akveo/nebular#2080]
### Issue type

**I'm submitting a ...**  

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
When manually typing the date into the input field, the DatePicker ignores the provided DateFormat. 
![Capture](https://user-images.githubusercontent.com/15210558/68939170-38f58e00-07a0-11ea-847a-eccb96680b7c.PNG)

Should be May 1st 2011.
When selecting the date in the datepicker, it gets displayed correctly.

![captured](https://user-images.githubusercontent.com/15210558/68940267-faad9e00-07a2-11ea-998e-197e7fde6acd.gif)

**Steps to reproduce:**
I tried globally setting the locale in app.module.ts  { provide: LOCALE_ID, useValue: "de-CH"},
using a date adapter (date-fns, moment as described in the docs), all with the same outcome.

**Comment by luischueneuien** [comment]
You can handle dateChange event and format the input value:
```

  handleDateChange($event) {
    this.form.date.setValue(this.datePipe.transform($event, 'dd/MM/yyyy'));
  }
```

**Comment by JoeOwner** [comment]
Is there any updates for this? The suggested solution does not seem to work because the dateChange event doesn't fire when manually typing the date into the input field.

**Comment by katebatura** [comment]
Hi! You can use date-fns adapter and it works. Try this: 
```
registerLocaleData(localeRu);

@NgModule({
  imports: [
    ...
    NbDatepickerModule.forRoot(),
    NbDateFnsDateModule.forRoot({format: 'dd.MM.yyyy'}),
    ...
  ],
  providers: [{provide: LOCALE_ID, useValue: 'ru-RU'}],
})
```

And we are going to fix using moment adapter for this with https://github.com/akveo/nebular/pull/2856
