### ISSUE TITLE
Runtime theme change doesn't affect nb-theme in scss.

### ISSUE THREAD

**Issue by GreedyA1** [akveo/nebular#2083]
### Issue type
* [ ] bug report
* [ ] feature request
* **[x] question**

### Issue description

**Current behavior:**
I am accessing primary color of the theme using nb-theme(color-primary-500); when I change the theme the color is still of the old theme.

**Expected behavior:**
Is there a way so that nb-theme(color-primary-500) returns updated color on theme change?

**Steps to reproduce:**
Import multiple themes ex (default, cosmic).
choose default theme NbThemeModule.forRoot({ name: 'default' }),
use theme variable nb-theme(color-primary-500) in any style.
use runtime theme switcher. this.themeService.changeTheme('cosmic');

### Other information:

**npm, node, OS, Browser**
```
npm --version 6.12.0
Windows 10
Chrome

```

**Angular, Nebular**
```
Angular 8.2.12
Nebular 4.4.0
```

**Comment by yggg** [comment]
Hi @GreedyA1. What are the classes applied to the body element? Does it have `nb-theme-cosmic`?
And also do you use the `nb-layout` component in the app? At the time, it's responsible for the theme class switch.

**Comment by GreedyA1** [comment]
the body element has nb-theme-default initially and once I change the theme it is changed to nb-theme-cosmic. Also Yes I am using nb-layout and the element I am trying to change the color of is in nb-layout-header. 

```
  .pageTitle {
    font-family: Roboto, 'Helvetica Neue', sans-serif;
    color: nb-theme(color-primary-500);
  }
```

I also tried to put it in my pageTitle in .nb-theme classes.

```
.nb-theme-corporate,
.nb-theme-dark,
.nb-theme-cosmic,
.nb-theme-default {
  .pageTitle {
    font-family: Roboto, 'Helvetica Neue', sans-serif;
    color: nb-theme(color-primary-500);
  }
}
```

but on theme change color still stays the same (of the original theme).

**Comment by yggg** [comment]
Looks fine. Did you wrap styles declaration in `nb-install-component` mixin? 
```
@include nb-install-component {
  .pageTitle {
    font-family: Roboto, 'Helvetica Neue', sans-serif;
    color: nb-theme(color-primary-500);
  }
}
```
It's required when using multiple runtime themes. See `Access with Multiples Theme Mode` section at https://akveo.github.io/nebular/docs/design-system/use-theme-variables#access-with-multiples-theme-mode.

**Comment by GreedyA1** [comment]
Thanks! That helped. I did miss that in docs.
