### ISSUE TITLE
Unexpected value 'undefined' exported by the module 'ThemeModule' ngx-admin

### ISSUE THREAD

**Issue by Sachin-Suresh** [akveo/nebular#209]
I want to customize the login auth component from the ngx admin theme for which i have installed ngx admin from the link: https://akveo.github.io/nebular/#/docs/auth/configuring-ui

After copying all the source files  to the theme folder i get error like :

**Unexpected value 'undefined' exported by the module 'ThemeModule'**

**\src\app\app-routing.module.ts**

    import { ExtraOptions, RouterModule, Routes } from '@angular/router';
    import { NgModule } from '@angular/core';
  ```
import {  
NbAuthComponent,
  NbLoginComponent,
  //NbLogoutComponent,
  //NbRegisterComponent,
  //NbRequestPasswordComponent,
  //NbResetPasswordComponent,
} from './@theme/components/auth/index';

const routes: Routes = [
  { path: 'pages', loadChildren: 'app/pages/pages.module#PagesModule' },
  {
    path: 'auth',
    component: NbAuthComponent,
    children: [
      {
        path: '',
        component: NbLoginComponent,
      },
      {
        path: 'login',
        component: NbLoginComponent,
      },      
    ],
  },
  { path: '', redirectTo: 'pages', pathMatch: 'full' },
  { path: '**', redirectTo: 'pages' },
];

const config: ExtraOptions = {
  useHash: true,
};

@NgModule({
  imports: [RouterModule.forRoot(routes, config)],
  exports: [RouterModule],
})
export class AppRoutingModule {
}
```

**src\app\@theme\components\auth\index.ts**

```
export * from './auth.component';
//export * from './auth-block/auth-block.component';
export * from './login/login.component';
//export * from './logout/logout.component';
//export * from './register/register.component';
//export * from './request-password/request-password.component';
//export * from './reset-password/reset-password.component';
```

**src\app\@theme\theme.module.ts**

`import { NbLoginComponent,NbAuthComponent } from './components/auth/index';`

Even though i have used component or children why i get this error?

**Error trace:**

Uncaught Error: Unexpected value 'undefined' exported by the module 'ThemeModule'
    at syntaxError (compiler.js:485)
    at eval (compiler.js:15239)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15237)
    at CompileMetadataResolver.getNgModuleSummary (compiler.js:15124)
    at eval (compiler.js:15222)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15200)
    at JitCompiler._loadModules (compiler.js:34255)
    at JitCompiler._compileModuleAndComponents (compiler.js:34216)

**Comment by nnixaa** [comment]
Closing as it's been a while.
