### ISSUE TITLE
Popover nbPopoverPlacement bottomLeft

### ISSUE THREAD

**Issue by Gumichocopengin8** [akveo/nebular#2094]
Hello, 

Popover nbPopoverPlacement  buttondoes not work when pop up does not have enough space, then automatically nbPopoverPlacement become right cuz right space has more space than bottom.

How can I make pop up bottom even there is not much space in bottom? 
Or can I use bottomLeft?

Thanks!

**Comment by yggg** [comment]
To prevent popover from changing position you need to set `nbPopoverAdjustment` to `noop`. Then position of the popover always be the one set via `nbPopoverPlacement`.

> Or can I use bottomLeft?

You can use any `NbPosition` for `nbPopoverPlacement`. See the possible values [here](https://github.com/akveo/nebular/blob/2e61d8d683e3621779367ac7a0bccf2316fa0061/src/framework/theme/components/cdk/overlay/overlay-position.ts#L31).

**Comment by Gumichocopengin8** [comment]
@yggg 
Thanks for tips.
Although I tried `nbPopoverPlacement ="bottom-end"`, it didnt work

**Comment by yggg** [comment]
> Although I tried nbPopoverPlacement ="bottom-end", it didnt work.

Make sure you have the latest Nebular installed, it should work fine. See [example](https://stackblitz.com/edit/nebular-2094?file=src/app/app.component.html).
There are two tooltips with `noop` adjustment and positions which don't fit the viewport.

If the issue persists, it would be great to have an stackblitz illustrating the case.

**Comment by Gumichocopengin8** [comment]
@yggg 
The version was a bit old.
After I installed the latest version, it WORKS!!!!
**Thank you very much.** I appreciate your kindness and information.
Nebular is amazing!
