### ISSUE TITLE
custom theme variables showing warnings

### ISSUE THREAD

**Issue by HansalThomas** [akveo/nebular#2130]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description
Added user-defined theme variables along with nebular theme variables inside theme file. When accessing those user-defined variables, showing warnings. Found this when running storybook.

**Current behavior:**

_WARNING: Nebular Theme: `nb-theme()` cannot find value for key `user-ui-paragraph-font-color` for theme `default`
    node_modules\@nebular\theme\styles\core\theming\_get-value.scss 59:5  nb-theme()
..........
stdin 12:3                                                           
    node_modules\@nebular\theme\styles\core\theming\_install.scss 149:7  
    node_modules\@nebular\theme\styles\core\theming\_install.scss 135:7   nb-install-global-with-scss-vars()
    node_modules\@nebular\theme\styles\core\theming\_install.scss 148:5   nb-install()
    stdin 10:1                                                            root stylesheet_

**Expected behavior:**
Should run without any warnings about theme.

**Steps to reproduce:**

_Add one non-nebular variable in theme file_
```scss
$nb-themes: nb-register-theme(
  (
    text-paragraph-2-font-weight: normal, //nebular variable
    user-ui-paragraph-font-color: #eaeaea //user defined variable
```
_access it from other files using nb-theme_
```scss
.display-heading {
    font-color: nb-theme(user-ui-paragraph-font-color);
  }
```
### Other information:

**npm, node, OS**
```
Node  : 10.16.3
npm : 6.9.0
Storybook : 5.2.6
```

**Comment by DiegoPatrocinio** [comment]
This may be a silly question, but did you add the new variable to all themes available in your app? (i.e. Default, Cosmic, Dark..)

I'm asking because sometimes when adding a new variable I forget to add it to one or more themes I have, then I get this exactly message you are seeing, but once I add it to all of them the message goes away, so it may be worth double checking it!

Example:

```
$nb-themes: nb-register-theme((
  custom-variable: #fff,
), default, default);

$nb-themes: nb-register-theme((
  custom-variable: #000,
), dark, dark);
```

**Comment by HansalThomas** [comment]
> This may be a silly question, but did you add the new variable to all themes available in your app? (i.e. Default, Cosmic, Dark..)
> 
> I'm asking because sometimes when adding a new variable I forget to add it to one or more themes I have, then I get this exactly message you are seeing, but once I add it to all of them the message goes away, so it may be worth double checking it!
> 
> Example:
> 
> ```
> $nb-themes: nb-register-theme((
>   custom-variable: #fff,
> ), default, default);
> 
> $nb-themes: nb-register-theme((
>   custom-variable: #000,
> ), dark, dark);
> ```

Thanks for the reply @DiegoPatrocinio. But my application have only one theme file and I have included my custom variable in that.

**Comment by ZQ-jhon** [comment]
> This may be a silly question, but did you add the new variable to all themes available in your app? (i.e. Default, Cosmic, Dark..)
> 
> I'm asking because sometimes when adding a new variable I forget to add it to one or more themes I have, then I get this exactly message you are seeing, but once I add it to all of them the message goes away, so it may be worth double checking it!
> 
> Example:
> 
> ```
> $nb-themes: nb-register-theme((
>   custom-variable: #fff,
> ), default, default);
> 
> $nb-themes: nb-register-theme((
>   custom-variable: #000,
> ), dark, dark);
> ```

Running well for me, thanks!
