### ISSUE TITLE
Provide link support for [nb-chat-message]

### ISSUE THREAD

**Issue by tomas-peirotti-kenility** [akveo/nebular#2134]
### Issue type

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**
When sending a message using nb-chat-message if the text contains a link it is displayed as normal text.

**Expected behavior:**
When a link is present in the message, display it as one.

**Steps to reproduce:**
1. Create a nb-chat instance  
2. Create a nb-chat-message inside
3. Set [type] from nb-chat-message as text.
4. Provide a link inside the message body.

**Comment by mehars-jalin** [comment]
Is this feature available now?

**Comment by crates** [comment]
Hey, folks. We've been waiting on this feature for about a year and a half now. It's a pretty common use-case to need to put a link into a chat, especially when designing a support bot. Is this on the road map at all? Is there anything we can do to contribute to this feature to get it included ASAP?

**Comment by crates** [comment]
@akveo / @nnixaa / @mishkolesnikov / @Tibing / @yggg / @piotrbrzuska / @SashaSkywalker / @sashaqred / @elupanov:
Sorry to tag so many people from your team, but we really need movement on this item right away.
This is an important feature for us immediately. It looks like @nielspetersen solved it a year ago. 
Is there any chance your team might be willing to quickly get this code merged to the trunk?
