### ISSUE TITLE
Context Menu: unexpectedly closes on expand child icon click

### ISSUE THREAD

**Issue by kozlovzxc** [akveo/nebular#2142]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
When we have a context menu with children elements and a user clicks on expanding icon (arrow icon after title description) then whole menu unexpectedly closes.

**Expected behavior:**
Expanding or collapsing behavior should be the same for the whole context menu element.

**Steps to reproduce:**
1. Create a context menu element
```
<button nbButton [nbContextMenu]="items">
  Click Me
</button>
```
2. Provide items
```
  items: NbMenuItem[] = [
    {
      title: "Profile",
      children: [{ title: "Profile child 1" }, { title: "Profile child 2" }]
    },
    { title: "Logout" }
  ];
```
3. Build an app and open it in browser
4. Click on "Click me" button
5. Click on "Profile" text -> profile section is expanded
6. Click on "Profile" text again -> profile section is colapsed
7. Click on arrow icon next to "Profile" text -> context menu is closed ?????

Screen Recording:
![Screen-Recording-2019-12-25-at-14 07 56](https://user-images.githubusercontent.com/6112517/71444120-3af82880-2720-11ea-872d-fe94e0ff9b0a.gif)

Sample app:
https://stackblitz.com/edit/context-menu-bug

### Other information:

**npm, node, OS, Browser**
```
Node, npm: `v12.6.0` and `6.9.0`
OS: macOS Catalina
Browser: Chrome
```

**Angular, Nebular**
```
    "@angular/animations": "~8.2.14",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@nebular/eva-icons": "4.6.0",
    "@nebular/theme": "^4.6.0",
```

**Comment by masterfaka** [comment]
same here... having implemented this theme long ago and very happy with it, I recently stumbled upon this bug.
no fixes or workarounds here... nor google yet. any help will be gratefully rewarded 💯 
NOTE: that the html element rendered its an <a> and a span+ <nb-icon> inside... click works perfectly fine unless you click the nb-icon which in the debugguer does bring the submenu child 1 out but then closes unexpectedly...
Regards

**Comment by sonic1blaster** [comment]
I use a quick solution like this:
`nb-menu .menu-items .menu-item svg {
  pointer-events: none;
}`

**Comment by katebatura** [comment]
Duplicate #2713
