### ISSUE TITLE
Option list v5 css

### ISSUE THREAD

**Issue by StavrosAnastopoulos** [akveo/nebular#2144]
### Issue type

**I'm submitting a ...** 

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Option list has no correct css

**Expected behavior:**
To have relevant / related css with rest theme

**Steps to reproduce:**
Go to nebular webpage, select v5 and click again the version selection. The list and items have incorrect css.

### Other information:
```
Browser: Chrome
```
![Capture](https://user-images.githubusercontent.com/8824406/71486531-7decf580-281f-11ea-8ba7-2f6026a22113.PNG)

**Comment by yggg** [comment]
Fixed
