### ISSUE TITLE
[NbCheckBox] checked are not being updated

### ISSUE THREAD

**Issue by vanishdark** [akveo/nebular#2150]
### Issue type

**I'm submitting a ...**

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
After click on checkbox, the current behavior is not showing the check on the box. When using the checkChanged method the value returned is false. Seems to be something with writeValue or updateValue.

**Expected behavior:**
After click on checkbox the item should be checked.

**Steps to reproduce:**
Click on checkbox, inspect value returned from checkedChange, verify that value is not the current one.

**Related code:**
-- HTML
```
<select>
  <option>
    <nb-checkbox #nbCheckbox [check]="getChecked(index, item)" (checkedChange)="nbUpdateCheckBox($event, #nbCheckBox)">Some text</nb-checkbox>
  </option>
</select>
```
--Typescript
```
getChecked(index, item) {
if (this.multipleCheckBoxList.length > 0) {
      return this.multipleCheckBoxList.find((a) => a.id === item.id);
    } else {
      return false;
    }
}
// Workaround to fix not update change on NbCheckbox
 updateNbCheckBox($event: boolean, nbCheckboxComponent: NbCheckboxComponent) {
    nbCheckboxComponent.checked = !nbCheckboxComponent.checked;
  }
```

### Other information:

```
npm: 6.13.4
nebular: 4.6.0
browser: Chrome and Firefox
node: 10.18.0
OS: Linux and Windows
```

**Angular, Nebular**
```
@angular-devkit/architect         0.803.21
@angular-devkit/build-angular     0.803.21
@angular-devkit/build-optimizer   0.803.21
@angular-devkit/build-webpack     0.803.21
@angular-devkit/core              8.3.21
@angular-devkit/schematics        8.3.21
@angular/cdk                      8.2.3
@angular/cli                      8.3.21
@ngtools/webpack                  8.3.21
@schematics/angular               8.3.21
@schematics/update                0.803.21
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
```

**Comment by ArtemRomanovsky** [comment]
hello @vanishdark! I consider the issue is referred to [check], try to change it to [value] in your code. Cause I didn't find [check] in [docs](https://akveo.github.io/nebular/docs/components/checkbox/api#nbcheckboxcomponent)
```<nb-checkbox #nbCheckbox [value]="getChecked(index, item)" (checkedChange)="nbUpdateCheckBox($event, #nbCheckBox)">Some text</nb-checkbox>```.

**Comment by vanishdark** [comment]
Hey @ArtemRomanovsky , yes it was that I change it and work like a charm!
