### ISSUE TITLE
nb-select doesnt work when using reactive forms

### ISSUE THREAD

**Issue by jagabs** [akveo/nebular#2168]
I have 2 network calls, getOneRoom and getAllRoomTypes.
get one room gives the details of the room including the id of a room type.
get all room types gives all room types.

when getAllRoomTypes is loaded first everything is fine.
when get one room is loaded first it doesnt select the selected room type id value.

it work with normal select tag in html. formControlName="roomTypeId" is assigned first when get one room is loaded. Then roomTypeList is loaded after getAllRoomTypes

```
<nb-select formControlName="roomTypeId" fullWidth placeholder="Select Room Type">
                  <nb-option *ngFor="let roomType of roomTypeList" [value]="roomType.roomTypeId">
                    {{ roomType.roomTypeName }} </nb-option>
```

I also tried using :

`this.roomForm.get("roomTypeId").setValue(this.roomTypeList[0].roomTypeId); `

`this.roomForm.patchValue({
							roomTypeId :  46
						})
`

but it doesnt work

**Comment by jagabs** [comment]
i updated to "4.6.0" and it works now

**Comment by MincDev** [comment]
@jagabs I'm struggling with this same issue. I'm using patchValue, but its not working
