### ISSUE TITLE
Allow customisation of select's optionsOverlayOffset property.

### ISSUE THREAD

**Issue by armoucar** [akveo/nebular#2175]
The new version of Eva changed the NbSelect's `option list container` offset from 0 to 8px. The only way I can think of customising this property is through inheritance, providing a new component.

Is there a way of customising this value with token strategy?

https://github.com/akveo/nebular/blob/d67dd6b4ea1871e91e5b18564076013255289a30/src/framework/theme/components/select/select.component.ts#L662

**Comment by franklinkim** [comment]
Hi, this really needs to be customisable! 

@armoucar I solved this for now using a directive

```ts
import { Directive, Host, Optional, Self } from '@angular/core';
import { NbSelectComponent } from '@nebular/theme';

@Directive({
  selector: '[appSelect]',
})
export class SelectDirective {
  constructor(
    @Host() @Self() @Optional() public host: NbSelectComponent
  ) {
    if (this.host && (this.host as any).hasOwnProperty('optionsOverlayOffset')) {
      // @ts-ignore
      host.optionsOverlayOffset = 0
    }
  }
}

```
