### ISSUE TITLE
 Style applied to a Jhipster project

### ISSUE THREAD

**Issue by Paul-Jacquit** [akveo/nebular#2177]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**

I want to use the compoment Chat from in Nebular in a project generated with Jhipster
I can add the compoment and use it in an html file but the style is not applied when running the app. I have added the import to the default theme in vendor.scss.

![image](https://user-images.githubusercontent.com/46136966/72616312-ed459900-3936-11ea-8dd1-e3cefb0e97d2.png)

**Expected behavior:**

A default theme applied for the Chat compoment.

**Steps to reproduce:**

Create a project with Jhipster, add the Chat compoment , run it.

**Related code:**

https://github.com/Paul-Jacquit/ProjetFIA/tree/chat

```
vendor.scss:
@import '~@nebular/theme/styles/prebuilt/default';
```

### Other information:

**npm, node, OS, Browser**
```
<!--
jhipsterVersion : 6.6.0
Node, npm: 12.14.1 and 6.13.4
OS: Windows (7/8/10).
Browser: Chrome/Firefox

-->
```

**Angular, Nebular**
```
Angular 8.2.14
Nebular 4.6.0
```

**Comment by diagnmaodo** [comment]
Hi, I've encountered the same issue. Fortunately, this answer
https://github.com/akveo/nebular/issues/710#issuecomment-421315806 helped me.
