### ISSUE TITLE
Chat UI - no way to set placeholder

### ISSUE THREAD

**Issue by danbete** [akveo/nebular#2181]
in Chat UI there is no option to add custom placeholder to the **nb-chat-form**  component 
and change the "No messages yet." in the **nb-chat-message** component.

### Issue type
* [ ] bug report
* [X] feature request

### Issue description

**Current behavior:**
no placeholder input

**Expected behavior:**
will have placeholder input

**Steps to reproduce:**
just run the component and try to add placeholder attribute

### Other information:

angular 8, nebular 4.5.0

**Comment by ArtemRomanovsky** [comment]
found that [comment](https://github.com/akveo/nebular/issues/1596#issuecomment-513764257), hope that helps

**Comment by danbete** [comment]
yeah this work around might work but required to to some stuff that i want to avoid (can hurt with future updates),
i will solve that with css [font size : 0 and add before with text content]  or some other way its just feel very needed
(and pretty simple to add optional input prop).

@ArtemRomanovsky  thanks for the time you took! 🥇

**Comment by cgonzalez-uy** [comment]
So, is this solved?

**Comment by Theinfinix500** [comment]
Is there any solution to this problem?

**Comment by danbete** [comment]
@cgonzalez-uy  @Theinfinix500 
there is a work around using css (hide text + insert text with :before on the element).
OR inheriting and changing the component (i will not recommend this). 

hope they will update the component to support placeholder.

**Comment by jackson1992121** [comment]
You can try with that. I solved a problem.
For example, 
<nb-chat-form (send) = "sendMessage($event)" [dropFiles] = "true" [messagePlaceholder] = "'メッセージを入力してください'"></nb-chat-form>

**Comment by jackson1992121** [comment]
I can't input multi-lined message in this nebular chat form because it's input is nbInput, not textarea.
Could anyone help me?

**Comment by smolnetim** [comment]
`noMessagesPlaceholder` works, but it's not documented yet: https://akveo.github.io/nebular/docs/components/chat-ui/api
