### ISSUE TITLE
Angular <mat-select> not working with nebular components

### ISSUE THREAD

**Issue by hanaravind** [akveo/nebular#2186]
I am trying to implement `mat-select` (angular material UI) along with the nebular components
but `mat-select` is not working when same component/module has nebular imports . if i remove imports of nebular module mat-select works .

with using nebular version `4.1.1` and version of angular material `8.2.3`
 
Here is my stackblitz workaround that you can clearly see that select dropdown is not working.
https://stackblitz.com/edit/github-ngmzqm?file=src%2Fapp%2Fhome%2Fhome.component.html

**Comment by anthowm** [comment]
In your example it works ...

**Comment by ArtemRomanovsky** [comment]
Looks like it is working 👍

**Comment by ArtemRomanovsky** [comment]
@hanaravind did you resolve the issue?

**Comment by hanaravind** [comment]
@ArtemRomanovsky  thanks for update yes i have resolved :-)

**Comment by oritpersik** [comment]
@hanaravind How did you resolve it ?
I've tried to use yours versions but it stil lnot working.

**Comment by Sachinbekre** [comment]
still facing issue
@hanaravind  how did you resolve this issue? please help me out

**Comment by hanaravind** [comment]
@Sachinbekre  Yes i have resolved the issue, moved your all imports to the root module
