### ISSUE TITLE
The viewchild `scrollableContainerRef` is `undefined` on Angular 9, Ivy

### ISSUE THREAD

**Issue by tonivj5** [akveo/nebular#2195]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
The viewchild `scrollableContainerRef` is `undefined` because it's used at constructor stage instead of ngOnInit (if static flag was `true`) or ngAfterViewInit (where viewchild is initialized really because it's marked as static `false`). For that reason, it produces this error:
![image](https://user-images.githubusercontent.com/7110786/73274039-345c4580-41e5-11ea-8666-521315d6813a.png)

**Expected behavior:**
scrollableContainerRef shouldn't be undefined.

**Steps to reproduce:**
Use a layout component with scroll.

**Related code:**
- [where scrollableContainerRef is declared](https://github.com/akveo/nebular/blob/master/src/framework/theme/components/layout/layout.component.ts#L205)
- [from this subscribe, at constructor, scrollableContainerRef will be required](https://github.com/akveo/nebular/blob/master/src/framework/theme/components/layout/layout.component.ts#L293)
- [where error happens](https://github.com/akveo/nebular/blob/master/src/framework/theme/components/layout/layout.component.ts#L393)

### Other information:

**npm, node, OS, Browser**
```
Node, npm: 13.0.1, 6.12.1
OS: Linux, Manjaro KDE
Browser: Chrome
```

**Angular, Nebular**
```
"@angular/common": "^9.0.0-rc.11",
"@angular/compiler": "^9.0.0-rc.11",
"@angular/core": "^9.0.0-rc.11",

"@nebular/auth": "^4.6.0",
"@nebular/bootstrap": "^4.6.0",
"@nebular/theme": "^4.6.0",
```

**Comment by Flyover-ArtSk** [comment]
i have the same error

**Comment by tonivj5** [comment]
It happens in v9.0.0 stable too

**Comment by davidecampello** [comment]
Hi, I'm still having this issue using "@nebular/theme": "^5.0.0-beta.8"

![Screenshot 2020-03-05 at 11 04 39](https://user-images.githubusercontent.com/21193922/75970839-39da3900-5ed1-11ea-8783-748edf1a0bce.png)

Please tell me if more informations are needed to help.
Thanks
