### ISSUE TITLE
Popover 'click' trigger issue with templateRef with Rangepicker component.

### ISSUE THREAD

**Issue by LuisMoralesMx** [akveo/nebular#2217]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
 If a popover uses a templateRef that contains a Rangepicker and the [nbPopoverTrigger] is set to **'click'** then the popover is closed as soon as you try to select dates in the Rangepicker component.

**Expected behavior:**
The popover should stay open when trying to select dates in the RangePicker and only close when clicking outside of the popover.

Note. The only way to 'fix' this is to set the [nbPopoverTrigger] to 'noop' but this is not an ideal solution since it would not close the popover when doing a click outside of the popover component.

**Steps to reproduce:**

1. Click icon to open popover (nbPopoverTrigger is set to 'click').
2. Click input field to display Rangepicker calendar.
3. Try to pick dates within Rangepicker.
4. Popover will close as soon as you try to pick a date.

**Related code:**
```
    <div class="filter-container">
      <div class="icon-filter-column" align="center">
        <nb-icon
          icon="funnel"
          [nbPopover]="datePopover"
          [nbPopoverTrigger]="'click'"
          [nbPopoverPlacement]="'top'"
        ></nb-icon>
      </div>
      <span class="column-sort draggable" (click)="sort()">Filter</span>

      <ng-template #datePopover>
        <input nbInput class="input-date" placeholder="Filter Date" [nbDatepicker]="datePicker" />
        <nb-rangepicker #datePicker startView="year" [showHeader]="true"></nb-rangepicker>
      </ng-template>
    </div>
```

### Other information:

**npm, node, OS, Browser**
```
Node: v12.13.1 
npm: 3.12.1
OS: Windows 10
Browser: Chrome/Firefox
```

**Angular, Nebular**
Angular: 9.0.0
Nebular: 4.6.0

**Comment by avnigenc** [comment]
same problem exists in nb-select.

**Comment by shreyshahh** [comment]
Have you found any solution? Same issue I have encountered just now....

**Comment by ihssanehn** [comment]
same problem, any solutions ?

**Comment by katebatura** [comment]
Duplicate #2325
