### ISSUE TITLE
Security: ability to assign multiple roles to a user

### ISSUE THREAD

**Issue by nnixaa** [akveo/nebular#222]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

**Comment by stefanwuthrich** [comment]
up vote

**Comment by ruisebastiao** [comment]
+1

**Comment by nnixaa** [comment]
Hey @stefanwuthrich, @ruisebastiao could you please share your use cases so that we can better design this feature? I presume this would be like this:
- user can have one or more roles (like `user` & `editor`)
- permissions will be merged allowing the user to do what both `user` and `editor` roles are allowed to do

**Comment by ruisebastiao** [comment]
Hello @nnixaa , in my case i have the following user schema (mongodb):

```
{
    "_id": ObjectId("5a96dafee06e0b349bbfc482"),
    "password": "",
    "email": "",
    "username": "Rui Sebastiao",
    "role": "admin",
    "units": [
        {
            "useUnitTimeZone": false,
            "chartTimezone": "",
            "_id": ObjectId("59d4c6932f695e7f8df66d2e"),
            "unitrole": "enduser",
            "unit_description": "Unit 1",
            "serialnumber": "000000001"
        },
        {
            "useUnitTimeZone": false,
            "chartTimezone": "",
            "_id": ObjectId("59d4c6932f695e7f8df66d2e"),
            "unitrole": "admin",
            "unit_description": "Unit 2",
            "serialnumber": "000000002"
        }
   ]
}

```

I have a global 'role' (root,admin,enduser) and i have a 'unitrole' in each unit of my array of units, some of this units could be added by other users and have a 'enduser' role for example). So there are some items on my page that are linked to my global role and  other items that depends of the 'unitrole' of the selected unit.

**Comment by stefanwuthrich** [comment]
Hi @nnixaa 
for my case it's enough to getRoles() as array

**Comment by ruisebastiao** [comment]
well done :+1:
