### ISSUE TITLE
Bug: Rangepicker with popover closed, not letting me picking dates

### ISSUE THREAD

**Issue by ArtemRomanovsky** [akveo/nebular#2235]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report

### Issue description
![filter](https://user-images.githubusercontent.com/55496086/74941841-c92d1a00-5404-11ea-9288-64664670b5e4.png)

I have an issue with a particular scenario with a Popover and a Rangepicker
component. I've a popover that uses a templateRef, this template contains a
Rangepicker, when I try to use the Rangepicker the popover is immediately
closed not letting me picking dates. I found this issue happens when the
*[nbPopoverTrigger]* is set to *'click'*, it seems it detects the click is
outside of the popover and this causes the popover and the template to
close.

The only way to *'fix'* this is to set the *[nbPopoverTrigger]* to 'noop'
but this is not an ideal solution since I would like to keep the advantage
of the *click trigger* that is *automatically closing the popover when
doing a click outside of the popover component*.

Is there any workaround for this?

**Comment by shreyshahh** [comment]
Have you found any solution, I have just encountered this problem?

**Comment by katebatura** [comment]
Duplicate #2325
