### ISSUE TITLE
Newbie, no ui grid ?

### ISSUE THREAD

**Issue by zerr0s** [akveo/nebular#2244]
Ho, forgive me for my bad english.

I'm trying to create from scratch my app with nebular, and I can't find anything about a system grid for the ui ?

I'm trying to align a nb-user component in the header to right. Someone could help me plz ?
```
<nb-layout-header fixed>
    <img src="/assets/logo.png" width="150" />
    <nb-user name="My Name" title="hello world" size="large" color="#cccccc"></nb-user>
  </nb-layout-header>
```

**Comment by mdragossh** [comment]
as I see from documentation there is no Grid and @nebular/bootstrap is deprecated, you can try flex-layout, but could be unexpected behavior

**Comment by zerr0s** [comment]
thanks. I will explore ngx-admin. It seems to be more complete.

**Comment by mdragossh** [comment]
ngx-admin use bootstrap for grid :)

**Comment by skol-pro** [comment]
Still no grid 3 years later ?
