### ISSUE TITLE
NbCalendarDayCellComponent_Host.ngfactory.js: date2.getFullYear is not a function

### ISSUE THREAD

**Issue by alexsintoni** [akveo/nebular#2250]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

I see this error in the development console of Chrome
```
NbCalendarDayCellComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: date2.getFullYear is not a function
    at NbNativeDateService.isSameYear (index.js?b4ac:6223)
    at NbNativeDateService.isSameMonth (index.js?b4ac:6219)
    at NbNativeDateService.isSameDay (index.js?b4ac:6215)
    at NbNativeDateService.isSameDaySafe (index.js?b4ac:4824)
    at NbCalendarDayCellComponent.get selected [as selected] (index.js?b4ac:4982)
    at Object.eval [as updateRenderer] (NbCalendarDayCellComponent_Host.ngfactory.js? [sm]:1)
    at Object.debugUpdateRenderer [as updateRenderer] (core.js?f18e:45293)
    at checkAndUpdateView (core.js?f18e:44276)
    at callViewAction (core.js?f18e:44636)
    at execEmbeddedViewsAction (core.js?f18e:44593)
```
**Expected behavior:**

No errors

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
I tried with Chrome and Firefox. Both show the same error in the console
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by tonivj5** [comment]
This error breaks completetly the datepicker, selecting the year. I think it was broken in `5.0.0`.

**Comment by tonivj5** [comment]
You can reproduce the issue using [the docs](https://akveo.github.io/nebular/docs/components/datepicker/examples#nbdatepickerdirective):
- Go to `Range showcase` example
- Select a date (today)
- Select other year (2016, for example)
- Dates doesn't show, daterange's broken
- And it shows this error (same than reported here)
![image](https://user-images.githubusercontent.com/7110786/79860038-44de1f80-83d2-11ea-8d43-d5d092e1ede7.png)

**Comment by tonivj5** [comment]
I have opened a PR fixing this issue https://github.com/akveo/nebular/pull/2330 :+1:. I think this bug was introduced in this PR https://github.com/akveo/nebular/pull/2120

**Comment by vanydiah** [comment]
![image](https://user-images.githubusercontent.com/6543101/114026616-a2e46b00-98a0-11eb-8cd6-ddbea23ff0dd.png)
it still happened in `"@nebular/theme": "6.0.0"`
