### ISSUE TITLE
Nebular 5, Nebular 4.6.0 tooltip in on nb-option in select stays on after selecting nb-option.

### ISSUE THREAD

**Issue by GreedyA1** [akveo/nebular#2258]
### Issue type

* [ x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Nebular 5, Nebular 4.6.0 tooltip in on nb-option in select stays on after selecting nb-option.
after choosing an option the tooltip stays active and goes to top left corner of webpage.

**Expected behavior:**
After select of option the tooltip should disappear like the option does.

**Steps to reproduce:**

- add nb-select to html
- add nbTooltip to nb-options in nb-select.
- click select choose option.

**Related code:**

https://stackblitz.com/edit/github-tti3eb-de3pxn

### Other information:

```
npm: 6.12.0
Node: v12.13.0
OS: Windows 10
Browser: Chrome

```

**Angular, Nebular**
```
Angular 8.8.3
Nebular 4.6.0 also on Nebular 5
```

**Comment by backciro** [comment]
There's the problem also in nebular 5.0.

My current workaround:

Not a real solution but i made my own tooltip using like this.
adjust margin-top for distance from item.

**>component.html**
```
<div class="myTooltip">
    <span class="myTooltipText"> <!--Tooltip content --> </span>
    ...
</div>

```
**>component.scss**
```
.myTooltip {
  position: relative;
  display: inline-block;
}

.myTooltip .myTooltipText {
  opacity: 0;
  visibility: hidden;
  font-size: 12px;
  width: 400px;
  pointer-events: none;
  border: 1px solid;
  padding: 0 15px;
  background: #b2d3e4;
  color: #00639e;
  text-align: justify;
  border-radius: 6px;
  margin-top: -70px;
  position: fixed;
  z-index: 999;
  overflow: visible;
  min-height: 54px;
  vertical-align: middle;
  display: inline-flex;
  transition: opacity .1s ease-in-out;
  -webkit-transition: opacity .1s ease-in-out;
}

.myTooltip .myTooltipText::after {
  content: " ";
  left: 10%;
  bottom: -10px;
  overflow: visible;
  font-size: 12px;
  width: 12px;
  color: #00639e;
  z-index: 99999;
  position: absolute;
  margin-left: -5px;
  border-width: 5px;
  border-style: solid;
  border-color: #b2d3e4 transparent transparent transparent;
}

.myTooltip:hover .myTooltipText {
  visibility: visible;
  opacity: 1;
}
```

**Comment by chirichok98** [comment]
You should use `nbTooltipAdjustment="noop"` property. It works with select options too.
