### ISSUE TITLE
AutoComplete wrong access modifiers?

### ISSUE THREAD

**Issue by Cammeritz** [akveo/nebular#2263]
### Issue type

**I'm submitting a ...**

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

When i use the AutoComplete component as shown as in the example, it gives me this error in the angular console:

> ERROR in src/app/pages/property/new-property/new-property.component.html(32,17): Directive NbAutocompleteDirective, Property 'handleInput' is protected and only accessible within class 'NbAutocompleteDirective<T>' and its subclasses.
>     src/app/pages/property/new-property/new-property.component.html(32,17): Directive NbAutocompleteDirective, Property 'handleKeydown' is protected and only accessible within class 'NbAutocompleteDirective<T>' and its subclasses.
>     src/app/pages/property/new-property/new-property.component.html(32,17): Directive NbAutocompleteDirective, Property 'handleKeydown' is protected and only accessible within class 'NbAutocompleteDirective<T>' and its subclasses.
>     src/app/pages/property/new-property/new-property.component.html(32,17): Directive NbAutocompleteDirective, Property 'handleBlur' is protected and only accessible within class 'NbAutocompleteDirective<T>' and its subclasses.

But when i have it compiled it obviously does not care about protection levels since its javascript.

**Expected behavior:**

Change the functions to public

**Steps to reproduce:**

// Outer skeleton
```
<div class="_32w _left m-lr-1">
                <!-- <input type="text" nbInput fullWidth placeholder="Location"> -->
                <!-- <nb-select placeholder="Location" fullWidth>
                    <nb-option value="Balencia">Balencia</nb-option>
                    <nb-option value="Barcelona">Barcelona</nb-option>
                </nb-select> -->
                <input
                [formControl]="inputFormControl"
                nbInput
                fullWidth
                type="text"
                placeholder="Enter value"
                [nbAutocomplete]="auto" />
                <nb-autocomplete #auto [activeFirst]="true">
                    <nb-option *ngFor="let option of filteredOptions$ | async" [value]="option">
                    {{ option }}
                    </nb-option>
                </nb-autocomplete>
            </div>
```
// Outer skeleton

Just copy pasted from here https://akveo.github.io/nebular/5.0.0-beta.x/docs/components/autocomplete/overview#nbautocompletedirective
### Other information:

**npm, node, OS, Browser**
```
Node: v10.15.3
Npm: 6.4.1
Node, npm: `node --version` and `npm --version`
OS: Win 10
Browser: Chrome v80.0.3987.132
```

**Angular, Nebular**
```
    "@nebular/eva-icons": "5.0.0-beta.8",
    "@nebular/theme": "5.0.0-beta.8",
    "eva-icons": "^1.1.3",
    "@angular/animations": "~9.0.0",
    "@angular/cdk": "~9.0.0",
    "@angular/common": "~9.0.0",
    "@angular/compiler": "~9.0.0",
    "@angular/core": "~9.0.0",
    "@angular/forms": "~9.0.0",
    "@angular/platform-browser": "~9.0.0",
    "@angular/platform-browser-dynamic": "~9.0.0",
    "@angular/router": "~9.0.0",
    "@angular-devkit/build-angular": "~0.900.0",
    "@angular/cli": "~9.0.0",
    "@angular/compiler-cli": "~9.0.0",
    "@angular/language-service": "~9.0.0",
```

**Comment by davidecampello** [comment]
same problem for me
