### ISSUE TITLE
Support Internet Explorer 11 (IE11)

### ISSUE THREAD

**Issue by Denschik** [akveo/nebular#2264]
### Issue description
**Current behavior:**
Using IE11 or above generates the below Javascript error preventing the page from loading.

> TypeError: Object doesn't support property or method 'entries'

**Expected behavior:**
Page loads in IE11 or above

**Steps to reproduce:**
Use IE11

I see this [issue ](https://github.com/akveo/nebular/issues/272), but it doesn't contents solution (or outdated)
![nebular](https://user-images.githubusercontent.com/16097522/76323690-190d4b80-62f6-11ea-94fa-2df700f6ba1b.PNG)

**Comment by yggg** [comment]
Please check, do you have an `import 'core-js/es7/object';` line at the `polyfills.ts` file? If no, add it and try to run the app again.

**Comment by Denschik** [comment]
Thanks! I solved this problem with `import 'core-js/es/object';` (core-js/**es7**/object - don't work in my version angular)
