### ISSUE TITLE
Show hyperlinks embedded in Chat message as clickable hyperlink in NbChatComponent

### ISSUE THREAD

**Issue by ankitgada** [akveo/nebular#2279]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
If the response message contains a hyperlink, the chat control renders it like plain text. Now even if the response message contains html hyperlinks, the chat control still renders in as plain text. 

**Expected behavior:**
Now I don't know if this a bug or a new message type is needed. May be there is a workaround. Any help would be wonderful.

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, : 10.15.0
OS: Windows (7/8/10). 
Browser: Chrome/Safari/Firefox
-->
```

**Angular, Nebular**
```
Angular : 8.0.0
Nebular : 4.6.0
```

**Comment by crates** [comment]
@akveo / @nnixaa / @mishkolesnikov / @tibing / @yggg / @piotrbrzuska / @SashaSkywalker / @sashaqred / @elupanov:
Sorry to tag so many people from your team, but we really need movement on this item right away.
This is an important feature for us immediately. If we issue a pull request, can we get it merged?
Let us know if we can help out with this item. It seems pretty straightforward to get it implemented.
Thank you for everything you're doing with Nebular!
