### ISSUE TITLE
NbSelect element width does not adapt correctly

### ISSUE THREAD

**Issue by matthiasunt** [akveo/nebular#2280]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
I have a row with two columns. While NbInput elements adapt properly to the column div, the NbSelect does not.

Screenshot:
![Screenshot 1](https://i.imgur.com/jxc7ZYb.png)

Parent col bounds:
![Screenshot 2](https://i.imgur.com/kYcz2zo.png)

**Expected behavior:**
The NbSelect element should adapt to the parent column div as the NbInput element does.

**Related code:**
My template:
```
 <div class="row">
        <div class="col-lg-6 col-md-12 col-sm-12">
          <div class="form-group">
            <nb-form-field>
              <nb-select [formControl]="day" placeholder="Select Day" [selected]="'Today'"
                         [shape]="componentShape" [size]="componentSize" fullWidth>
                <nb-option [value]="'Today'">Today</nb-option>
                <nb-option [value]="'Tomorrow'">Tomorrow</nb-option>
              </nb-select>
            </nb-form-field>
          </div>
        </div>
        <div class="col-lg-6 col-md-12 col-sm-12">
          <div class="form-group">
            <nb-form-field>
              <nb-icon nbPrefix icon="clock-outline" pack="eva"></nb-icon>
              <input [formControl]="time" fullWidth nbInput type="text" placeholder="Enter time"
                     [status]="elementStatus(time)" [shape]="componentShape"
                     [nbAutocomplete]="timeAutocomplete" [fieldSize]="componentSize"/>
              <nb-autocomplete #timeAutocomplete>
                <nb-option *ngFor="let t of (filteredTimeOptions$ | async)" [value]="t">
                  {{ t }}
                </nb-option>
              </nb-autocomplete>
            </nb-form-field>
          </div>
        </div>
      </div>
```

### Other information:

**npm, node, OS, Browser**
```
Node, npm: v13.6.0, 6.14.2
OS: macOS Catalina
Browser: Chrome
```

**Angular, Nebular**
```
"@angular/core": "~9.0.6",
"@nebular/theme": "^5.0.0",
```

**Comment by kdubb** [comment]
We're experiencing the same problem. There is a `min-width: 13rem` on the `.select-button` inside the `ng-select` that the `fullWidth` directive doesn't seem to override.

The workaround was to remove that `min-width` manually:

```scss
nb-select ::ng-deep {
  .select-button {
    min-width: 0;
  }
}
```

**Comment by boodahDEV** [comment]
I've the same problem and I have no idea how to solve it.   🤕 🙁🙁🙁🙁 🤕

**Comment by JDavid21051** [comment]
answer of @kdubb works for me

`nb-select.specificClass ::ng-deep {
  .select-button {
    min-width : 0;
  }
}`

specificClass = your class
thanks

**Comment by katebatura** [comment]
Hi, you can modify theme variable `select-min-width` or other variables for `nb-select` if you need (https://akveo.github.io/nebular/docs/components/select/theme). 
Use this instructions: https://akveo.github.io/nebular/docs/design-system/enable-customizable-theme#enable-customizable-themes

**Comment by kdubb** [comment]
@katebatura That is not "fixed", you are offering a workaround. The default style is *broken* and the theme itself should be fixed. You are expecting every person using the theme to find this issue and apply the workaround themselves?

What's wrong with incorporating some version of my style edit into the theme itself?
