### ISSUE TITLE
[5.0.0] Production Build breaks Styles

### ISSUE THREAD

**Issue by macchie** [akveo/nebular#2293]
### Issue type

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
NOTE: I disabled Angular Ivy since ng2-smart-table is NOT compatible with it.

So basically if you have a pretty complex project Ivy is breaking things like i said, i disabled Ivy by turning off **aot** and **buildOptimizer** in **angular.json**. That's the only way i was able to build my project using 5.0.0.

Since i updated to 5.0.0 when i compile for Production environment styles optimization must be turned off or it can cause some weird glitches.

Maybe something related to RTL or LTR formatting?

**Expected behavior:**
Correct alignment of interface elements.

**Steps to reproduce:**
Add ng-toggle in page and build for Production.

**Related code:**
This is my toggle.
```
<nb-toggle formControlName="blPreserve">Preserve?</nb-toggle>
```

### Other information:
![Screenshot from 2020-03-24 13-33-49](https://user-images.githubusercontent.com/4162997/77426385-a9f32500-6dd4-11ea-88ad-6a2a4948920b.png)
![Screenshot from 2020-03-24 13-33-45](https://user-images.githubusercontent.com/4162997/77426366-a2cc1700-6dd4-11ea-9a1b-de71e77788b3.png)
![Screenshot from 2020-03-24 13-34-44](https://user-images.githubusercontent.com/4162997/77426370-a52e7100-6dd4-11ea-988d-fc57cac9dc47.png)

**npm, node, OS, Browser**
```
Node, npm: v12.16.1, 6.13.4
OS: ZorinOS 15.2
Browser: Chrome
```

**Angular, Nebular**
Angular 9 (Ivy disabled) and Nebular 5.0.0

**Comment by macchie** [comment]
NOTE2: just noticed that **ng2-smart-table** was updated yesterday. Going to test it enabling aot & buildOptimizer and let you know.

**Comment by macchie** [comment]
NOTE3: Tested with ng2-smart-table 1.6.0 + aot + buildOptimizer, getting same results! :(

**Comment by macchie** [comment]
NOTE4: this is the only solution i found so far...

```
nb-toggle .toggle.checked .toggle-switcher {
  left: calc(100% - var(--toggle-switcher-size) - var(--toggle-border-width)) !important;
}
```

**Comment by ali-kamalizade** [comment]
I have the same issue - when running in production the toggle alignment is wrong. I am running the latest Nebular and Angular versions + Ivy enabled.

**Comment by macchie** [comment]
> I have the same issue - when running in production the toggle alignment is wrong. I am running the latest Nebular and Angular versions + Ivy enabled.

Same here right now. CSS override was the only solution to me.
