### ISSUE TITLE
Auth redirection issue

### ISSUE THREAD

**Issue by neeldebnath** [akveo/nebular#2302]
I was creating a custom auth module and when I keep auth-route.module as given in the nebular documentation it doesn't redirect to the login page and keeps showing a blank page with the arrow top. The code is below: 

```
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { NbAuthComponent } from '@nebular/auth';
import { NgxLoginComponent } from './login/login.component';

export const routes: Routes = [
    {
      path: '',
      component: NbAuthComponent,
      children: [
        {
            path: 'login',
            component: NgxLoginComponent,
        }
      ],
    },
  ];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class NgxAuthRoutingModule {
}
```

**But when I change the code like given below, then redirection works**
```
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { NbAuthComponent } from '@nebular/auth';
import { NgxLoginComponent } from './login/login.component';

export const routes: Routes = [
    {
      path: '',
      component: NbAuthComponent,
      children: [
        {
          path: '',
          component: NgxLoginComponent,
        },
        {
            path: 'login',
            component: NgxLoginComponent,
        }
      ],
    },
  ];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class NgxAuthRoutingModule {
}
```
###Am I doing any wrong? please help.

**Comment by hubatruck** [comment]
If you look closely on the source code for the Auth module you can see they use routes like in your second snippet: https://github.com/akveo/nebular/blob/a6fd98c66dcd0316dab40694a98b49068a98e69a/src/framework/auth/auth.routes.ts#L25

Your first example only works if you navigate directly to '/login' route. but the second example loads the component by accessing the '/' route.

**Comment by neeldebnath** [comment]
> If you look closely on the source code for the Auth module you can see they use routes like in your second snippet:
> 
> https://github.com/akveo/nebular/blob/a6fd98c66dcd0316dab40694a98b49068a98e69a/src/framework/auth/auth.routes.ts#L25
> 
> Your first example only works if you navigate directly to '/login' route. but the second example loads the component by accessing the '/' route.

So I was right unknowingly. 😁 Thanks for the response
