### ISSUE TITLE
NbCalendarRange not working when range attribute is declared with a @Input decorator and default values as null.

### ISSUE THREAD

**Issue by LuisMoralesMx** [akveo/nebular#2305]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**

Component **nb-calendar-range** is not working in Nebular 5.0.0 under the following scenario:

You declare a range variable with the `@Input` decorator and nulll values as:

`@Input() range: NbCalendarRange<any> = { start: null, end: null };`

This throws the following exception:

![RangeCalendarError](https://user-images.githubusercontent.com/12153955/78262797-52cd0e80-74be-11ea-8d73-634622e966e4.PNG)

The result is the component is rendered like this due to the error:

![HalfRendered](https://user-images.githubusercontent.com/12153955/78276070-bd3a7a80-74cf-11ea-88a6-70f83e90dd55.PNG)

**Note:** This was working perfectly fine under version:  4.6.0

**Expected behavior:**

Component **nb-calendar-range** should work when declaring a `@Input range` variable with defaults as null **as it was working under 4.6.0**.

**Steps to reproduce:**

1. Add a nb-calendar-range to your html template with a `[(range)]` attribute..
1. Declare a range variable with an `@Input` decorator and null as default value for `start `and `end`.
1. Component will throw an exception when you try to open it.

**Related code:**

```
<nb-calendar-range
  [(range)]="range"
  (rangeChange)="eventDates($event)"
  [startView]="month">
</nb-calendar-range>

@Input() range: NbCalendarRange<any> = { start: null, end: null };
```

### Other information:

**npm, node, OS, Browser**
```
Node: v12.13.1
Npm: 6.12.1
OS: Windows 10.
Browser: Google Chrome (Version 80.0.3987.162 (Official Build) (64-bit))
```

**Angular, Nebular**
```
Angular: 9.1.0
Nebular: 5.0.0
```

**Comment by katebatura** [comment]
Hi, you can assign an empty object or { start: null, end: null } since "@nebular/theme": "^6.2.1".
