### ISSUE TITLE
Export 'NbAutocompleteModule' was not found in '@nebular/theme'

### ISSUE THREAD

**Issue by ralcorta** [akveo/nebular#2310]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

On version 5.0 I can't import NbAutocompleteModule.

**Expected behavior:**

Import the module.

**Steps to reproduce:**

Import the module into file:
```
import {
  NbAutocompleteModule
} from '@nebular/theme';
```

**Related code:**

```
import { NgModule } from '@angular/core';
import {
  NbAutocompleteModule // <- Not found
} from '@nebular/theme';

@NgModule({
  imports: [
    // ...
    NbAutocompleteModule <- Not found
  ],
  entryComponents: [ ],
  declarations: [ ],
  providers: [ ],
})
export class UserModule { }

```

### Other information:

**Files related**
[https://github.com/akveo/nebular/blob/v5.0.0/src/framework/theme/components/autocomplete/autocomplete.module.ts](https://github.com/akveo/nebular/blob/v5.0.0/src/framework/theme/components/autocomplete/autocomplete.module.ts)

** Component Documentation**
[https://akveo.github.io/nebular/docs/components/autocomplete/overview#nbautocompletedirective](https://akveo.github.io/nebular/docs/components/autocomplete/overview#nbautocompletedirective)

**Comment by manuelsfd** [comment]
i have the same problem!

**Comment by floxcristian** [comment]
Same problem here!
