### ISSUE TITLE
Chat UI input onchange event missing. No way to detect text change.

### ISSUE THREAD

**Issue by mudassir93** [akveo/nebular#2313]
### Issue type

**I'm submitting a ...** 

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**

No method/event to detect the change in the input.

**Expected behavior:**
There must be an event which should be fired when the text is changed in the input.

**Comment by gonzalo42** [comment]
Any news on this??? I find it shocking that a basic feature such as detecting text change is not in the control

**Comment by piotrbrzuska** [comment]
@crates, CEO of something - i am not a Akveo member, i'm just a developer, who made some fix in this module. If you write that it's a rather simple thing to do, just do it and send Pull Request.
