### ISSUE TITLE
Tooltip disable feature in directive like matTooltip

### ISSUE THREAD

**Issue by anthowm** [akveo/nebular#2324]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [X] feature request

### Issue description
I'm requesting a disable feature for tooltip directive like matTooltip. Also with this feature https://github.com/akveo/nebular/issues/1687 can be handling.
**Current behavior:**

Nbtooltip don't have any feature to disable the tooltip programatically like for example matTooltip, this is for example interesting when want to tooltip when a text its ellipsis, etc.
**Expected behavior:**

```
@Directive({
  selector: '[nbTooltip][appShowIfTruncated]'
})
export class ShowIfTruncatedDirective implements OnInit {
  constructor(
    private matTooltip: MatTooltip,
    private elementRef: ElementRef<HTMLElement>
  ) {
  }

  public ngOnInit(): void {
    // Wait for DOM update
    setTimeout(() => {
      const element = this.elementRef.nativeElement;
     // this.matTooltip.disabled = element.scrollWidth <= element.clientWidth;
      this.nbTooltip.disabled = element.scrollWidth <= element.clientWidth;
    });
  }
}
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: 10.15.3 and 6.4.1
OS:  macOS (Catalina)
Browser: All
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```
Angular 8.14 and Nebular 4.6

**Comment by danbete** [comment]
did you tried to change the trigger (nbPopoverTrigger) to "noop"?

as in the docs:

nbPopoverTrigger:
NbTrigger | 
Describes when the container will be shown. Available options: click, hover, hint, focus and noop

**Comment by anthowm** [comment]
That not works in a directive
