### ISSUE TITLE
One way binding is not working

### ISSUE THREAD

**Issue by bnbs** [akveo/nebular#233]
I downloaded the ngx-admin-starter-kit and I'm trying to update a view property every 1s.  To do that I 
add some code to the DashboardComponent.

```
import { Component, ChangeDetectionStrategy, OnInit } from '@angular/core';

@Component({
  selector: 'ngx-dashboard',
  templateUrl: './dashboard.component.html'
})
export class DashboardComponent implements OnInit{

  itemCount: number = 4;

  ngOnInit(){
    setInterval(() => {
      this.itemCount++;
    }, 1000);
  }
}
```
```
<p>Your bucket list {{ itemCount }}</p>
<div class="row">  
  <nb-card>
    <nb-card-body>Hello from ngx-admin sandbox project.</nb-card-body>
  </nb-card>
</div>
```
The itemCount property is only being updated when I click somewhere. I've tried to implement this in the full ngx-admin kit and the itemCount is being updated as expected without needing to click somewhere on the screen.

**Comment by nnixaa** [comment]
Hi @bnbs, there is an issue with change detection set to `onPush` in the starter-kit, please check [this PR](https://github.com/Pterrat/ngx-admin/commit/c3e6e4c45e8d09418052550539032adcf2223935), it's quite simple to fix it. We will merge it in the next ngx-admin release.
