### ISSUE TITLE
nb-select with nb-option-group - got scroll issue on first load

### ISSUE THREAD

**Issue by AvshT** [akveo/nebular#2348]
Its only happend in the **first load and when using nb-option-group** in nb-select .
I put a picture of the prblem (taken from nebular site itself):
![image](https://user-images.githubusercontent.com/29532821/81173927-80b7de00-8fa9-11ea-85a6-a6747ca146a0.png)

Note:
Only reflect to **nb-select using nb-option-group** 
Note2: 
Its working perfectly with **nb-autocomplete**

**Comment by usalin** [comment]
Hello AvshT. Have you ever found a solution to this issue?
