### ISSUE TITLE
NbAutocomplete - Problem with disabling autocomplete input using FormControl

### ISSUE THREAD

**Issue by maciejniedzielski** [akveo/nebular#2349]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Cannot apply `disabled` attribute on input using FormControl

I try to disable form control using `form.disable()` or `inputCtrl.disable()` and the input is still enabled. It looks like directive doesn't take it into account while setting value and other attributes.

I also checked this behavior using nebular playground from repository and I still couldn't set disabled attribute.

**Expected behavior:**
When setting 'disabled' status on FormControl or Reactive Form autocomplete input should be disabled.

**Steps to reproduce:**
1. Use reactive form autocomplete in template basing docs
2. Set FormControl initial status to `field: { value: '', disabled: true }` or use `formControl.disable()` or `form.disable()`

**Related code:**

```
// This doesn't work
this.inputFormControl = new FormControl({ value: '', disabled: true });

// doesn't work either
this.inputFormControl.disable();

// this returns `true` - model has information about control `disabled` state
console.log(this.inputFormControl.disabled)
```

### Other information:

**npm, node, OS, Browser**
```
Node: v12.16.1
npm: 6.13.4
OS: Ubuntu 18.04.2 LTS
Browser: Chrome
```

**Angular, Nebular**
```
    "@angular/animations": "~9.1.0",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/forms": "~9.1.0",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0",
    "@nebular/auth": "^5.0.0",
    "@nebular/bootstrap": "^5.0.0",
    "@nebular/date-fns": "^5.0.0",
    "@nebular/eva-icons": "^5.0.0",
    "@nebular/theme": "^5.0.0",
```

**Comment by kostetskyroma** [comment]
+1

**Comment by Deepeeper** [comment]
+2

**Comment by aaron-hammond** [comment]
+3

**Comment by alekssakovsky** [comment]
+4!

**Comment by Theinfinix500** [comment]
is there any update to this issue ?
