### ISSUE TITLE
Autocomplete : setting the input form control value to null or undefined does not reset

### ISSUE THREAD

**Issue by jornetsimon** [akveo/nebular#2352]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**
When you have a the **_nbAutocomplete_** bound to a **FormControl**, setting the form control value to **null** or **undefined** does not reset the value. Only setting the value to an empty string is working.

**Expected behavior:**
The input value should be reseted, just like for a simple input with no autocomplete bound.

**Steps to reproduce:**
Set up an input and bind an [nbAutocomplete] to it. Also bind a FormControl to the input.
Then set the FormControl value (using the _setValue()_ method) to _null_ or _undefined_.

**Related code:**
StackBlitz reproduction : [https://stackblitz.com/edit/nb-autocomplete-setvalue-null](https://stackblitz.com/edit/nb-autocomplete-setvalue-null)

### Other information:
**Angular, Nebular**
```
@nebular/theme 5.0.0
@angular/core 9.1.3
```

**Comment by ericmartinezr** [comment]
I was about to open a new issue about this. Note that setting the value to `''` (an empty string) will focus the field and trigger the autocomplete, this can be solved by adding `[focusInputOnValueChange]="false"` to the element in 5.1.0, previous versions could get the nativeElement and `blur()` it.

**Comment by jornetsimon** [comment]
> setting the value to `''` (an empty string) will focus the field and trigger the autocomplete

Exactly, as shown in the StackBlitz demo
