### ISSUE TITLE
I am unable to integrate the NbAutocompleteModule module

### ISSUE THREAD

**Issue by Pibe93** [akveo/nebular#2357]
Good morning,
I can't integrate the form.
When I declare it in my PageModule import {Nbautocomplete, NbMenuModule, NbInputModule} from '@ nebular / theme' it returns the error:
Module '"/ node_modules / @ nebular / theme"' has no exported member 'Nbautocomplete'.ts (2305)

The version I'm using Nebular is 5.0.0,

Thanks for your help.

**Comment by slooock** [comment]
how you fix it?
