### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'icon-end: false'. Current value: 'icon-end: true'.

### ISSUE THREAD

**Issue by anthowm** [akveo/nebular#2363]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Get ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'icon-end: false'. Current value: 'icon-end: true', using Popover, spinner and button in nebular 4.6.0.
Can't test this in 5.0.0 because there is not stackblitz with nebular 5+ (I try to make it work but got many errors). Also this error don't occurs with version 4.1.0.

**Steps to reproduce:**
https://stackoverflow.com/questions/61769477/expressionchangedafterithasbeencheckederror-expression-has-changed-after-it-was
https://stackblitz.com/edit/github-mh5jx3

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by BenBestmann** [comment]
Same here. Any infos?

**Comment by EngineerLaroche** [comment]
Same here. Error on click of nbButton (no text) + nbIcon + nbSpinner.
