### ISSUE TITLE
[Question] How do I change nb-select width

### ISSUE THREAD

**Issue by shanerbo** [akveo/nebular#2369]
It seems like the width of nb-select is fixed
I was wondering if there is a way I can change it?

**Comment by armoucar** [comment]
I think you could use `fullWidth` directive or even customise theme variables: https://akveo.github.io/nebular/docs/components/select/theme#nbselectcomponent

**Comment by shanerbo** [comment]
> I think you could use `fullWidth` directive or even customise theme variables: https://akveo.github.io/nebular/docs/components/select/theme#nbselectcomponent

thank you!
