### ISSUE TITLE
NbAutocomplete input cannot be disabled

### ISSUE THREAD

**Issue by jornetsimon** [akveo/nebular#2371]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Inputs with nbAutocomplete directive cannot be disabled.

**Expected behavior:**
The input should be disabled, either through [disabled] or the form control disable() method.

**Angular, Nebular**
```
@angular/core 9.1.3
@nebular/theme 5.0.0
```

**Comment by kostetskyroma** [comment]
+1

**Comment by Deepeeper** [comment]
+2
