### ISSUE TITLE
Nebular CDK Proposal

### ISSUE THREAD

**Issue by Tibing** [akveo/nebular#241]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

For now nebular has many components and its amount grow quickly. So, to avoid overlapping we have to move part of the functionality to the separate module: **@nebular/cdk**
This module will contain all the code which can be shared between multiple components and help us and external developers build new parts of the nebular faster and better.

### Popover CDK
I think we can start with allocation main logic of the popover to the CDK. This step will give us the capability to build many components such as:
- popover
- context-menu
- tooltip
- toast
- dialog
- snackbar

It might look like:

![image](https://user-images.githubusercontent.com/17410089/36341831-67abc22c-1405-11e8-8283-afc6ed4676bf.png)

- IPopover: popover directive interface has to contain methods like a show, hide and toggle.
- NbPopoverService: can subscribe to the trigger events and show, hide, toggle NbPopoverContainer.
- NbPopoverContainer: basic container without UI, it can be just rendered and positioned by the popover service. This container will render passed content.
- NbTriggerService: knows how to subscribe to different events based on the different popover modes.

Then we'll be able to create different directives like mentioned above by just injecting popover service and implementing IPopover interface.

Give me your feedback, please.

**Comment by nnixaa** [comment]
@Tibing let's consider mixins as well when designing the CDK part.

**Comment by Tibing** [comment]
Sure, I'll investigate them better and if they have right to life I'll include mixins in this proposal.

**Comment by nnixaa** [comment]
Some other things to add:
- RTL support
- a11y support
- i18n support

**Comment by nnixaa** [comment]
And a bit more:
- common for components - `status` (color, primary, success, info, ect)
- common for components - `size` (small, large, etc)
