### ISSUE TITLE
Error when use  [(ngModel)] with nb-rangepicker

### ISSUE THREAD

**Issue by redplane** [akveo/nebular#2416]
#1473 # Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report

### Issue description

**Step to produce:**
- In **app.component.html**
```
<div class="card">
  <div class="card-body">

    <div class="row">
      <div class="col-6">
        <label>Time range</label>
        <input nbInput
               fullWidth
               [(ngModel)]="timeRange"
               [nbDatepicker]="formpicker">
        <nb-rangepicker #formpicker></nb-rangepicker>
      </div>
      <div class="col-6">
        {{timeRange | json}}
      </div>
    </div>
  </div>
</div>

```

- In **app.component.ts**
```
import {Component} from '@angular/core';
import {TimeRange} from '../models/time-range';

@Component({
  selector: 'nb-date-range-error',
  templateUrl: 'nb-date-range-error.component.html'
})
export class NbDateRangeErrorComponent {

  //#region Properties

  public timeRange: TimeRange;

  //#endregion

  //#region Constructor

  public constructor() {
    this.timeRange = {};
  }

  //#endregion
}

```

- In **time-range.ts**
```
export class TimeRange {

  //#region Properties

  start?: string;

  end?: string;

  //#endregion

}
```

**Expected behavior:**
- Model binding works.

**Actual behavior:**
- When **timeRange** is set to **{}**, an error is thrown: ```Cannot read property 'getFullYear' of undefined```.

**Related code:**
[https://stackblitz.com/github/alakanzam/nebular-error-report](https://stackblitz.com/github/alakanzam/nebular-error-report)

### Other information:

**npm, node, OS, Browser**
**OS**: MacOS Catalina
**Browser**: Google Chrome 83
**NPM**: 6.14.5
**Node**: v12.10.0

**Angular, Nebular**
```
 "@angular/animations": "~9.0.7",
    "@angular/cdk": "^9.0.0",
    "@angular/common": "~9.0.7",
    "@angular/compiler": "~9.0.7",
    "@angular/core": "~9.0.7",
    "@angular/forms": "~9.0.7",
    "@angular/platform-browser": "~9.0.7",
    "@angular/platform-browser-dynamic": "~9.0.7",
    "@angular/router": "~9.0.7",
    "@nebular/eva-icons": "5.1.0",
    "@nebular/theme": "^5.1.0",
```

**Comment by evtkhvch** [comment]
Hi, you have to use the following interface NbCalendarRange<Date> for your timeRange property. It should works well.

**Comment by evtkhvch** [comment]
Hi, you have to use the following generic interface with Date type argument. String type isn't supported.
https://github.com/akveo/nebular/blob/7c12874b8f41f8c9554f87919e0eb2dfa2540701/src/framework/theme/components/calendar/calendar-range.component.ts#L23 
example:
```
 export class NbDateRangeErrorComponent {

    public timeRange: NbCalendarRange<Date>;

    constructor() {
      this.timeRange = { start: new Date(), end: new Date() }
    }

}
```
