### ISSUE TITLE
Firebase Authentication - refreshing token 

### ISSUE THREAD

**Issue by gregor-srdic** [akveo/nebular#2425]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ X] bug report
* [ ] feature request

### Issue description

**Current behavior:**
When I login using NbFirebasePasswordStrategy after some time I get signed out on app refresh - it looks like token expires 

**Expected behavior:**
The token should be automaticaly refreshed and user should remain authenticated until he manually signs out

**Steps to reproduce:**
Sign in using NbFirebasePasswordStrategy, wait one day, refresh the page.

**Related code:**

### Other information:

**npm, node, OS, Browser**
```
windows 10
chrome
node 13.9.0
npm 6.13.7
```

**Angular, Nebular**
```
"@angular/core": "^9.1.11",
"@nebular/auth": "^5.1.0",
"@nebular/firebase-auth": "^5.1.0",
"firebase": "^7.15.1",
```

**Comment by mishkolesnikov** [comment]
There is a method `isAuthenticatedOrRefresh` in the NbAuthService. It
returns true if valid auth token is present in the token storage. If not, calls the strategy `refreshToken`, and returns isAuthenticated() if success, false otherwise.
Please use this method.'

**Comment by gregor-srdic** [comment]
@mishkolesnikov thanks for the answer, currently I am not manually calling anything from NbAuthService other than subscribing to the onAuthenticationChange events. Can you give me a hint where in the application lifecycle I should be calling "isAuthenticatedOrRefresh"? 
Any specific reason why this is not the default behavior? (I am specifying refreshToken=true in my bFirebasePasswordStrategyOptions)
thanks a bunch!

**Comment by vip20** [comment]
It seems like the above answer doesn't support google strategy, any work around for this @mishkolesnikov ?

`Error: 'refreshToken' is not supported by 'NbFirebaseGoogleStrategy', use 'authenticate'`
