### ISSUE TITLE
Support us button doesn't work

### ISSUE THREAD

**Issue by Tibing** [akveo/nebular#243]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Support us button doesn't work [in the demo](http://akveo.com/ngx-admin/#/pages/dashboard).

**Expected behavior:**
It's works and redirects to the GitHub.

**Steps to reproduce:**
Just open link mentioned above and click support us button.

**Comment by nnixaa** [comment]
https://github.com/akveo/ngx-admin/issues/1492
