### ISSUE TITLE
Token not being refreshed. Strategy: NbOAuth2AuthStrategy, IDP: Keycloak

### ISSUE THREAD

**Issue by aksth** [akveo/nebular#2442]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
I have my authentication setup using NbOAuth2AuthStrategy. I use Keycloak as my identity provider. The app gets authenticated and works well until the token expires. After the token expires, my token isn't being refreshed. Also, after the token is expired, authService.isAuthenticated() is returning 'true' and accessChecker.isGranted() is returning 'false'. Here, accessChecker.isGranted() is 'false' only after the token expires. I cannot see my app calling the "/token" API that I provided in the refresh strategy config. Also, what is normal behavior here? Does Nebular handle the refreshing of the token itself or do we have to implement that ourselves?

**Expected behavior:**
After the current active token expires, the app should fetch another token using the refresh token.

**Steps to reproduce:**
Use keycloak as IDP and use the NbOAuth2AuthStrategy with the following config.

**Related code:**

Strategy config:

```
strategies: [
  NbOAuth2AuthStrategy.setup({
    name: 'keycloak',
    baseEndpoint: environment.keycloakUrl,
    clientId: 'backend-service',
    clientSecret: 'some-secret',
    clientAuthMethod: NbOAuth2ClientAuthMethod.BASIC,
    authorize: {
      endpoint: '/auth',
      responseType: NbOAuth2ResponseType.TOKEN,
    },
    token: {
      endpoint: '/token',
      grantType: NbOAuth2GrantType.PASSWORD,
      class: NbAuthOAuth2JWTToken,
    },
    refresh: {
      endpoint: '/token',
      grantType: NbOAuth2GrantType.REFRESH_TOKEN,
    },
  }),
  NbPasswordAuthStrategy.setup({
    name: 'logout',
    baseEndpoint: '',
    logout: {
      endpoint: '',
      redirect: {
        success: '/auth',
        failure: '',
      },
    },
  }),
],
```

Interceptor config:

```
providers: [
    { provide: HTTP_INTERCEPTORS, useClass: NbAuthJWTInterceptor, multi: true },
    {
      provide: NB_AUTH_TOKEN_INTERCEPTOR_FILTER,
      useValue: function (req: HttpRequest<any>) {
        if (req.url === '${environment.keycloakUrl}/auth') {
            return true
          }
          if (req.url === '${environment.keycloakUrl}/token') {
            return true
          } else {
            return false
          }
      },
    },
  ],
```

### Other information:

```
Angular version: 9.1.7
Nebular version: 5.0.0
Node version: 14.4.0
Npm version: 6.14.5
OS: Linux (Ubuntu)
Browser: Chrome

**Comment by fbarajas-fmg** [comment]
Hi,

Have you tried using: authService.isAuthenticatedOrRefresh() ?

**Comment by aksth** [comment]
@fbarajas-fmg I haven't used that. I'm using authService.isAuthenticated() only.

**Comment by aksth** [comment]
Closing this. To make the nebular to refresh the token after expiring, authService.isAuthenticatedOrRefresh() should be used.

**Comment by emiletab** [comment]
@aksth How did you configure which API to use when executing the ` authService.isAuthenticatedOrRefresh()` ?
