### ISSUE TITLE
Autcomplete: don't emit when selecting from the autocomplete list

### ISSUE THREAD

**Issue by ericmartinezr** [akveo/nebular#2443]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

I have a form with an autocomplete field where the user types something and this triggers a http call. The first time (when the user is typing) returns the items that fulfill what the user typed. But a second http call is triggered when the user selects an item from the list since this action writes to the field triggering a `valueChanges`.

Is it possible to add something like `{ emitEvent: false }` when the user selects an item from the list and it gets written to the field?

**Current behavior:**

When selecting an item from the autocomplete list the field triggers a new `valueChange` with the value selected from the list.

**Expected behavior:**

When selecting an item from the autocomplete list, it would preferable not to trigger a new event to prevent new http calls or heavy tasks one can be doing in against the autocomplete. Probably customizable through a property?

The `valueChange` should trigger only when the user is typing in the field.

**Steps to reproduce:**
- Keep the network tab open
- Type anything in the field and see that it makes a http call
- Select any item from the list and see that the http call is triggered again (this one would be preferable not to happen)

**Related code:**
https://stackblitz.com/edit/nb-autocomplete-setvalue-null-szwcx5?file=src%2Fapp%2Fapp.component.ts 
(don't mind the name, it's a fork of another stackblitz and it won't let me change the name)

### Other information:

**npm, node, OS, Browser**
```
node: v12.0.0
npm: 6.9.0
OS: Windows
Browser: Chrome 83.0.4103.116 (Official Build) (64-bit)
```

**Angular, Nebular**
```
Angular 9.1.4
Nebular 5.1.0
```

**Comment by ericmartinezr** [comment]
I solved it by tracking the elements the http returns, something like

```typescript
   this.listTodos = this.form.controls.todo.valueChanges.pipe(
      debounceTime(500),
      switchMap(val => {
        if (this.knownTodos && this.knownTodos.includes(val)) {
          return of([]);
        }
        return this.http.get('todos')
        );
      }),
      tap((todos) => this.knownTodos = todos
      )
```

I would say this a valid solution, but it would be cool too if it's part of nebular. Anyway, feel free to close it if you don't plan to add such feature.

Thank you for reading :)

**Comment by katebatura** [comment]
Hi, selecting an item from the autocomplete list triggers a new `valueChange` because we need to update value in formControl. So, if you want to prevent new http call you can use your solution.
