### ISSUE TITLE
Datepicker calendar position is dynamic

### ISSUE THREAD

**Issue by adrian-lg** [akveo/nebular#2455]
# Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [x] feature request

### Issue description

**Current behavior:**
The calendar opens in all directions based on where the input is placed in the page. eg. If input is at the bottom of the page, the calendar will open on top. If it's on the top or center -> opens from the bottom of the input.

**Expected behavior:**
Be able to set a fixed position.

**Steps to reproduce:**
Add the datepicker example.

**Related code:**
```
<input nbInput placeholder="Pick Date" [nbDatepicker]="formpicker" [formControlName]="item" class="form-control">
<nb-datepicker format="EEEE, dd MMMM yyyy" #formpicker></nb-datepicker>
```

### Other information:

**Angular, Nebular**

```
"@angular/core": "^9.0.4"
"@nebular/theme": "4.1.2"
```

Please advise how to set a specific direction.

**Comment by krishnanirmal25** [comment]
@adrian-lg    THIS is happening with me also....Any solution u found.... appreciate the help
