### ISSUE TITLE
guys how to create nebular NbSidebar ? 

### ISSUE THREAD

**Issue by Ravindrakumara** [akveo/nebular#2457]
i was study nebular doc also https://akveo.github.io/nebular/docs/components/sidebar/overview#nbsidebarcomponent
i do not know  how to create cli commend for **NbSidebar**. who knows solve this help me

**Comment by anddo88** [comment]
What CLI command. I use sidebar successfully like ngx-admin and the steps in the document works for me. What exactly is the problem you're facing and what are trying to do ?

**Comment by Ravindrakumara** [comment]
i want to create  sidebar content inside. i have do menu
