### ISSUE TITLE
Error in the documentation

### ISSUE THREAD

**Issue by 003marek** [akveo/nebular#2476]
Under this link:
https://akveo.github.io/nebular/docs/auth/firebase-authentication#firebase-authentication-with-nebular-auth

Replace this:
npm i @nebular/auth @angular\firebase-auth
With this:
npm i @nebular/auth @nebular/firebase-auth

**Comment by alsaghir** [comment]
Docs needs multiple fixes. I tried to do one like eva-icons package to be installed but seems folks developers are pretty busy to merge many pull requests.
