### ISSUE TITLE
NbToastrService exception

### ISSUE THREAD

**Issue by olicooper** [akveo/nebular#2478]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report

### Issue description

**Current behavior:**
I am trying to implement an error handler which uses the NbToastrService but I am getting a console error:
![image](https://user-images.githubusercontent.com/22296715/90032263-1902e480-dcb6-11ea-890a-989d9171daa0.png)

I traced it back to here: 
https://github.com/akveo/nebular/blob/d3ba6ab42b88ded18a3285c4527372b45cc33065/src/framework/theme/components/cdk/adapter/overlay-container-adapter.ts#L30

I have tried manually providing the `NB_DOCUMENT` token in the app module providers e.g. `{ provide: NB_DOCUMENT, useExisting: DOCUMENT }` and I have injected this token in to my service and the document is available when I call the toastr service so I don't know why it won't work.

**Expected behavior:**

I would like to be able to use this service to catch errors as the app is initializing.

**Steps to reproduce:**
Call the `toastrService` in the constructor of the app component

**Related code:**

StackBlitz [Sample of the issue](https://stackblitz.com/edit/github-jphznl?file=src/app/app.component.ts)

```
  constructor(private toastrService: NbToastrService) {
    // doesn't work
    const toastRef: NbToastRef = this.toastrService.show("Message", "Doesn't work");
  }
```

### Other information:

Angular 9/10 both display this issue

**Comment by agiletuan** [comment]
Me too!

**Comment by vincent-seibus** [comment]
Same issue on angular 11 nebular 7

**Comment by JabCorp** [comment]
Any news ?
Same issue on ng12

**Comment by evtkhvch** [comment]
This error occurs when you try to invoke `toastrService.show` in `constructor` of root component (that exist `<nb-layout>`). 
In this moment layout container didn't attach yet. 
So, you should invoke `toastrService.show` when layout container has attached. ex:  in `OnInit` hook, or in a child components.
Hope it helps.
