### ISSUE TITLE
Since Nebular breaks Angular Material, please add drag/drop to the tree grid

### ISSUE THREAD

**Issue by StationedInTheField** [akveo/nebular#2493]
### Issue type

* [ ] bug report
* [x] feature request

### Issue descriptions

**Current behavior:**
Using Nebular alongside Angular Material breaks most Angular Material components, like MatSnackBar and MatTree

**Expected behavior:**
If you can't fix it, so that we can use both together, please add drag/drop functionality to the Tree Grid module.

**Related code:**
https://github.com/akveo/nebular/issues/2492

**Comment by StationedInTheField** [comment]
Actually it only moves the cdk, closing this in favor of: https://github.com/akveo/nebular/issues/2492

**Comment by bessam-haj-salem** [comment]
Is there any news about the drag and drop?
