### ISSUE TITLE
Minor issue with position argument with ToastrService

### ISSUE THREAD

**Issue by sai-github** [akveo/nebular#2497]
### Issue type

**I'm submitting a ...**

* [x] bug report

### Issue description

**Current behavior:**
I am using `NbToastrService` and after following instructions in documentation, I have below code

```
this.toastrService.show(
  msg,
  `Error`,
  { position: 'top-right', status: 'danger' }
);
```

But I get the following error
```
Type '"top-right"' is not assignable to type 'NbGlobalPosition'
```

But after changing below its fine, 
```
this.toastrService.show(
  msg,
  `Error`,
  { position: NbGlobalLogicalPosition.BOTTOM_START, status: 'danger' }
); 
```

**Expected behavior:**

Should work even when provided with valid string

**Steps to reproduce:**

My import statement in `app.module.ts` is `NbToastrModule.forRoot(),`, I am not providing any `config` is it expected to provide a default config (if so where can I find the config params

**Related code:**

If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

A sample application via StackBlitz 

[StackBlitz Reproduced](https://stackblitz.com/edit/github-vgnuew?file=src/app/home/home.component.ts)

### Other information:

**npm, node, OS**
```
Angular CLI: 10.0.7
Node: 10.22.0
OS: win32 x64

Angular: 10.0.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.7
@angular-devkit/build-angular     0.1000.7
@angular-devkit/build-optimizer   0.1000.7
@angular-devkit/build-webpack     0.1000.7
@angular-devkit/core              10.0.7
@angular-devkit/schematics        10.0.7
@angular/cdk                      10.1.3
@angular/cli                      10.0.7
@ngtools/webpack                  10.0.7
@schematics/angular               10.0.7
@schematics/update                0.1000.7
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
```

**Nebular**
```
"@nebular/theme": "^6.0.0",
```

**Browser**
```
"Chrome",
```

**Comment by ihor-protsenko-theraven** [comment]
I fixed this like this

**Comment by ihor-protsenko-theraven** [comment]
I fixed this problem like that:
`import { Component, OnInit } from '@angular/core';
import { NbToastrService, NbGlobalLogicalPosition } from '@nebular/theme';
import { LeadsService } from '../../leads.service';

@Component( {
  selector: 'ngx-login-leads',
  templateUrl: './login-leads.component.html',
  styleUrls: [ './login-leads.component.scss' ]
} )
export class LoginLeadsComponent implements OnInit {

  constructor ( private leadsService: LeadsService, private toastrService: NbToastrService ) { }

  ngOnInit (): void {
  }


  sumbit () {
    this.leadsService.login()
    this.toastrService.success( 'Login success', 'Welcome!', { position: NbGlobalLogicalPosition.BOTTOM_END, status: 'success', } )
  }

}
`

**Comment by sokol147** [comment]
Hello, using NbGlobaPosition is a preferred way to configure position. Have to provide your own string for position field and sure that the string is correct you can use type casting (as NbGlobalLogicalPosition) for you value.

`this.toastrService.show(
  msg,
  `Error`,
  { position: NbGlobalLogicalPosition.BOTTOM_START, status: 'danger' }
); `

Thank you for creating this issue, we will update our documentation to prevent such misunderstanding

> if so where can I find the config params
https://akveo.github.io/nebular/docs/components/toastr/api#nbtoastrconfig
