### ISSUE TITLE
User context menu does not show icon correctly

### ISSUE THREAD

**Issue by sukeshlaghate** [akveo/nebular#25]
Hello,
When adding icons to user context menu, it is observed that the title and icon are not correctly aligned. 
For e.g if in the header component the user menu is defined as 
  userMenu = [{ title: 'Profile', icon: 'fa fa-user fa-lg' }, { title: 'Log out' }];
then the user icon is displayed, however the title is displayed in new line. Please refer screen shot 

Request you to fix the issue.
![image](https://user-images.githubusercontent.com/25061957/31439983-e9a586ce-aeab-11e7-84bf-0d490607594d.png)

**Comment by nnixaa** [comment]
Hey @sukeshlaghate, thanks, we will fix it soon.
