### ISSUE TITLE
Uncaught TypeError of undefined of NbAdjustableConntectedPositionStrategy between Version 6.0.0 and current version 6.1.0

### ISSUE THREAD

**Issue by thetphyoaungio** [akveo/nebular#2525]
Please check and fix this issue, that I faced this  error in NbAdjustableConntectedPositionStrategy when i click on the nbActions tag or nbDatePicker components - 
![Screenshot (1)](https://user-images.githubusercontent.com/51815279/94107064-b713ce00-fe62-11ea-99da-cbaad56fad3c.png)

**Comment by charllie** [comment]
Same issue (nbdialog, datepicker, etc.)

**Comment by darken89** [comment]
me too

**Comment by qfumeau** [comment]
Same issue, all overlays down

**Comment by yggg** [comment]
Version `6.2.0` with the fix is available on npm. Please note, you also need to update `@angular/cdk` to versions `10.2.1`+.
