### ISSUE TITLE
TimePicker Error CDK with Nebular 6.1.0

### ISSUE THREAD

**Issue by darken89** [akveo/nebular#2527]
### Issue type

* [x] bug report

### Issue description

I tried to use the timepicker component but when I click on the input field I'm getting this error:
![image](https://user-images.githubusercontent.com/12048987/94253171-34077c00-ff25-11ea-8e04-ddebc1d41872.png)

and the modal appears in the position (0, 0).

In the overlay.js I saw that when is performed this instruction 
        const scrollPosition = this._viewportRuler.getViewportScrollPosition();

scrollPosition is undefined and the _viewportRules is of NbViewportRulerAdapter  type. 

I'm using these angular versions:

    "@angular/cdk": "10.1.1",
    "@angular/material": "10.1.1",

and Nebular 6.1.0

Is it a bug ? Someone could tell me how can I solve ?

 Thanks in advance

**Comment by yggg** [comment]
Duplicate of #2525. See [this comment](https://github.com/akveo/nebular/issues/2525#issuecomment-699035213) regarding the fix.
