### ISSUE TITLE
ng test: No provider for InjectionToken Document

### ISSUE THREAD

**Issue by pntme** [akveo/nebular#2535]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description
I'm using Nebular (akveo/nebular) components in my project and it's working fine, but when I wanted to test my components that are extended from Nebular components I got this error 

`NullInjectorError: R3InjectorError(DynamicTestModule)[NbDialogService -> InjectionToken Document -> InjectionToken Document]: 
  NullInjectorError: No provider for InjectionToken Document!
`
&

`NullInjectorError: R3InjectorError(DynamicTestModule)[NbThemeService -> InjectionToken Nebular Theme Options -> InjectionToken Nebular Theme Options]: 
  NullInjectorError: No provider for InjectionToken Nebular Theme Options!`

My spec code is here

```
import { async, ComponentFixture, TestBed } from '@angular/core/testing';
import { HeaderComponent } from './header.component';
import { NbSidebarService, NbMenuService, NbThemeService } from '@nebular/theme';
import { HttpClientTestingModule } from '@angular/common/http/testing';
import { InjectionToken } from '@angular/core';

describe('HeaderComponent', () => {
  let component: HeaderComponent;
  let fixture: ComponentFixture<HeaderComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ HeaderComponent ],
      imports: [HttpClientTestingModule,],
      providers: [NbSidebarService, NbMenuService, NbThemeService, {provide: InjectionToken, useValue: '', multi: true}]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(HeaderComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```

and my component code is

```
import { Component, OnDestroy, OnInit } from '@angular/core';
import { NbMediaBreakpointsService, NbMenuService, NbSidebarService, NbThemeService } from '@nebular/theme';
import { LayoutService } from '../../../@core/utils';
import { map, takeUntil } from 'rxjs/operators';
import { Subject } from 'rxjs';
import { LocalStorageService } from '../../services/local-storage.service';

@Component({
  selector: 'app-header',
  styleUrls: ['./header.component.scss'],
  templateUrl: './header.component.html',
})
export class HeaderComponent implements OnInit, OnDestroy {

  private destroy$: Subject<void> = new Subject<void>();
  userPictureOnly: boolean = false;
  user: any;
  userMenu = [{ title: 'Log out' }];
  retailer: any;

  constructor(private sidebarService: NbSidebarService,
    private menuService: NbMenuService,
    private themeService: NbThemeService,
    private ls: LocalStorageService,
    private layoutService: LayoutService,
    private breakpointService: NbMediaBreakpointsService) {
  }

  ngOnInit() {
    const { xl } = this.breakpointService.getBreakpointsMap();
    this.themeService.onMediaQueryChange()
      .pipe(
        map(([, currentBreakpoint]) => currentBreakpoint.width < xl),
        takeUntil(this.destroy$),
      )
      .subscribe((isLessThanXl: boolean) => this.userPictureOnly = isLessThanXl);

    this.user = this.ls.get('userLoginData');
    this.retailer = this.ls.get('userRetailer');
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }

  toggleSidebar(): boolean {
    this.sidebarService.toggle(true, 'menu-sidebar');
    this.layoutService.changeLayoutSize();
    return false;
  }

  navigateHome() {
    this.menuService.navigateHome();
    return false;
  }
}
```

**Comment by yggg** [comment]
Instead of providing services manually import all appropriate modules, as when providing service manually you also need to provide all its dependencies as well.
Configure the testing module to import menu, sidebar, theme, and other modules for components used in the header. It'd look something like this:
```
TestBed.configureTestingModule({
  declarations: [ HeaderComponent ],
  imports: [HttpClientTestingModule, NbThemeModule.forRoot(), NbSidebarModule.forRoot(), NbMenuModule.forRoot()],
})
```
and remove `providers: [NbSidebarService, NbMenuService, NbThemeService, {provide: InjectionToken, useValue: '', multi: true}]` line.

**Comment by pntme** [comment]
> Instead of providing services manually import all appropriate modules, as when providing service manually you also need to provide all its dependencies as well.
> Configure the testing module to import menu, sidebar, theme, and other modules for components used in the header. It'd look something like this:
> 
> ```
> TestBed.configureTestingModule({
>   declarations: [ HeaderComponent ],
>   imports: [HttpClientTestingModule, NbThemeModule.forRoot(), NbSidebarModule.forRoot(), NbMenuModule.forRoot()],
> })
> ```
> 
> and remove `providers: [NbSidebarService, NbMenuService, NbThemeService, {provide: InjectionToken, useValue: '', multi: true}]` line.

Thanks @yggg  it's worked !

**Comment by matheo** [comment]
For the record, this InjectionToken is provided just by adding `NbThemeModule.forRoot()`.
