### ISSUE TITLE
[Customization] - How to change the main nebular standard loading spinner?

### ISSUE THREAD

**Issue by diegoarndt** [akveo/nebular#2538]
### Issue type

**I'm submitting a ...**

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**

Hello everybody, I would like to know if it is somehow possible to customize the nebular standard loading spinner with a brand company logo.

This is the original one
![image](https://user-images.githubusercontent.com/26179059/94816865-c5b63400-03d2-11eb-9a95-b2a7520bb5a1.png)

**Expected behavior:**

Brand logo should show up instead of the standard loading spinner.

### Other information:

**npm, node, OS, Browser**
```

Node: 12
Npm: 6
OS: Windows 10
Browser: Chrome

```
**Angular, Nebular**
```

Angular: 10
Nebular: 6.2

```

**Comment by fdiogoc** [comment]
Just change it on INDEX.HTML
