### ISSUE TITLE
role.provider not working in production mode

### ISSUE THREAD

**Issue by RoWEN-FCUB** [akveo/nebular#2544]
This is my role.provider.ts:

import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { map } from 'rxjs/operators/map';

import { NbAuthService, NbAuthJWTToken } from '@nebular/auth';
import { NbRoleProvider } from '@nebular/security';

@Injectable()
export class RoleProvider implements NbRoleProvider {

  constructor(private authService: NbAuthService) {
  }

  getRole(): Observable<string> {
    return this.authService.onTokenChange()
      .pipe(
        map((token: NbAuthJWTToken) => {
          // console.log(token.getPayload());
          return token.isValid() ? token.getPayload()['role'] : 'guest';
        }),
      );
  }
}

It works fine while in development mode (ng serve and ng build), but when I use it in production mode (ng serve --prod and ng build --prod) I get the error:

ERROR TypeError: Object(...) is not a function
    getRole http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    value http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    set http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    xa http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    ra http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    zs http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    template http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    Xi http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    qi http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    va http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    qi http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    qi http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    va http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    qi http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    qi http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    va http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    qi http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    qi http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    qi http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    qi http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    va http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    qi http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    qi http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    Gi http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    _a http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    _a http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    value http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    value http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    next http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    value http://localhost:4200/polyfills.a9fe93f4256a69196a00.js:1
    onInvoke http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    value http://localhost:4200/polyfills.a9fe93f4256a69196a00.js:1
    value http://localhost:4200/polyfills.a9fe93f4256a69196a00.js:1
    value http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    next http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    o http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    value http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    value http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    value http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    value http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    value http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    value http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    Vd http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    onHasTask http://localhost:4200/main.c8da7df94aad960dcfeb.js:1
    value http://localhost:4200/polyfills.a9fe93f4256a69196a00.js:1
    value http://localhost:4200/polyfills.a9fe93f4256a69196a00.js:1
    value http://localhost:4200/polyfills.a9fe93f4256a69196a00.js:1
    value http://localhost:4200/polyfills.a9fe93f4256a69196a00.js:1
    b http://localhost:4200/polyfills.a9fe93f4256a69196a00.js:1
    promise callback*_ http://localhost:4200/polyfills.a9fe93f4256a69196a00.js:1
    value http://localhost:4200/polyfills.a9fe93f4256a69196a00.js:1
    onScheduleTask http://localhost:4200/polyfills.a9fe93f4256a69196a00.js:1
    value http://localhost:4200/polyfills.a9fe93f4256a69196a00.js:1
    value http://localhost:4200/polyfills.a9fe93f4256a69196a00.js:1
    value http://localhost:4200/polyfills.a9fe93f4256a69196a00.js:1
    R http://localhost:4200/polyfills.a9fe93f4256a69196a00.js:1
    P http://localhost:4200/polyfills.a9fe93f4256a69196a00.js:1
    x http://localhost:4200/polyfills.a9fe93f4256a69196a00.js:1
    r http://localhost:4200/runtime.1f7c745dcecd1542e20e.js:1
    <anonymous> http://localhost:4200/5.c3b7e62258abfb184f47.js:1

**Comment by Prefix1802** [comment]
getRole(): Observable<string> {
    return this.authService.onTokenChange()
      .pipe(
        map((token: NbAuthJWTToken) => {
          return token.isValid() ? token.getPayload()['role'] : 'guest';
        }),
      );
  }

Observable<string> = missing.

**Comment by RoWEN-FCUB** [comment]
```
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { map } from 'rxjs/operators/map';

import { NbAuthService, NbAuthJWTToken } from '@nebular/auth';
import { NbRoleProvider } from '@nebular/security';

@Injectable()
export class RoleProvider implements NbRoleProvider {

  constructor(private authService: NbAuthService) {
  }

  getRole(): Observable<string> {
    return this.authService.onTokenChange()
      .pipe(
        map((token: NbAuthJWTToken) => {
          return token.isValid() ? token.getPayload()['role'] : 'guest';
        }),
      );
  }
}
```
Still having the same error. Only in production mode. All my modules are updates. 
If I use:
`useValue: {
      getRole: () => {
        return observableOf('user');
      }`
instead of `useClass: RoleProvider` it works fine, but I really need the role provider to work.
![Sin título2](https://user-images.githubusercontent.com/51714814/95621836-5e3a5d00-0a40-11eb-9185-e16180d2deb3.png)

**Comment by RoWEN-FCUB** [comment]
Can someone help me???? I'm still stuck with this error!!!

**Comment by bdowney01** [comment]
Are there any updates? I'm facing the same issue.

**Comment by RoWEN-FCUB** [comment]
Still wating for an answer, tought I was the only with that problem.

**Comment by carloseduardovieira** [comment]
Hello @RoWEN-FCUB, I had this same problem, and the solution for me was to change the import path of the rxjs map..
**change:**
import { map } from 'rxjs/operators/map';
**for**
import { map } from 'rxjs/internal/operators/map';

**Comment by RoWEN-FCUB** [comment]
Someone in another post gave me another solution and it's working now, this is my code:

```
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { map } from 'rxjs/operators/map';

import { NbAuthService, NbAuthJWTToken } from '@nebular/auth';
import { NbRoleProvider } from '@nebular/security';
import { observable, of } from 'rxjs';

@Injectable()
export class RoleProvider implements NbRoleProvider {

  constructor(private authService: NbAuthService) {
  }

  getRole(): Observable<string> {
    /*return this.authService.onTokenChange()
      .pipe(
        map((token: NbAuthJWTToken) => {
          return token.isValid() ? token.getPayload()['role'] : 'guest';
        }),
      );*/
    let result;
    this.authService.onTokenChange().subscribe((token: NbAuthJWTToken) => {
      if (token.isValid()) {
        result = token.getPayload()['role'];
      } else {
        result = 'guest';
      }
    });
    // return observableOf(result);
    return of(result);
  }
}
```
