### ISSUE TITLE
Can't pass object data in the dialog using nebular angular

### ISSUE THREAD

**Issue by JeromeBurce11** [akveo/nebular#2550]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
 openEditUserDetails() {
    this.dialogService.open(EditUserDetailDialogComponent,{
       context:{
         data: this.userDataInfo
       }

    });
  }
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node- v10.19.0, 
OS: linux (ubuntu 20.4). 
Browser: all
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by f-ricci** [comment]
How do you consume the context data? 

context = data so you should do something like the following

in your component
```
context:{
         id: this.userDataInfo.id
       }
```

and in your template
```
{{ data.id }}
```

don't forget to declare the `let-data` input variable

**Comment by JeromeBurce11** [comment]
Thank you for the input

**Comment by andreipadolin** [comment]
Hi @JeromeBurce11 if issue is solved could you please close issue?
