### ISSUE TITLE
Array of Selected values are not working

### ISSUE THREAD

**Issue by shyamailene** [akveo/nebular#2564]
I have taken the sample code given in Nebular select document and added to ngFor for multiple records as below:

                              <div formArrayName="userSchools" id="userSchool" *ngFor="let school of userSchools().controls; let i = index;" >
                                                          <nb-select placeholder="Select Showcase" [(selected)]="selectedItem[i]">
									<nb-option-group title="Group 1">
										<nb-option value="1">Option 1</nb-option>
										<nb-option value="2">Option 2</nb-option>
										<nb-option value="3">Option 3</nb-option>
										<nb-option value="4">Option 4</nb-option>
									  </nb-option-group>
								
									  <nb-option-group title="Group 2">
										<nb-option value="21">Option 21</nb-option>
										<nb-option value="22">Option 22</nb-option>
										<nb-option value="23">Option 23</nb-option>
										<nb-option value="24">Option 24</nb-option>
									  </nb-option-group>
								
									  <nb-option-group title="Group 3">
										<nb-option value="31">Option 31</nb-option>
										<nb-option value="32">Option 32</nb-option>
										<nb-option value="33">Option 33</nb-option>
										<nb-option value="34">Option 34</nb-option>
									  </nb-option-group>
								  </nb-select>						
                                                   </div>

In TS:
selectedItem = ['2','24'];
Default selection is not working.

**Comment by chirichok98** [comment]
@shyamailene something wrong in your code.

For select with multiple values you need to set `multiple` flag to `nb-select`.

Ex: `<nb-select placeholder="Select Showcase" multiple [(selected)]="selectedItem">`
