### ISSUE TITLE
NbThemeService can't find the new theme

### ISSUE THREAD

**Issue by YSOUZAS** [akveo/nebular#2573]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
I am creating a theme based on the default, after registering the theme, I need to use the getJsTheme function of NbThemeService, however it always says that my theme is not registered.

**Expected behavior:**
Being able to access all variables with the return of the observable

**Steps to reproduce:**

1. Register a new theme
2. Register the NbThemeModule.forRoot ({name: 'myTheme'}),
3. try to access variables using getJsTheme through NbThemeService

**Related code:**

https://stackblitz.com/edit/github-96flhv
https://github-96flhv.stackblitz.io

```
themes.scss
$nb-themes: nb-register-theme(
  (
    color-bg: #4ca6ff
  ),
  "myTheme",
  default
);

app.module.ts
NbThemeModule.forRoot({ name: 'myTheme' }),

home.ts
this.themeService.getJsTheme().subscribe(variables => {
   console.log(variables);
});

console:
NbThemeConfig: no theme 'myTheme' found registered.
```

### Other information:

**npm, node, OS, Browser**
```
Node: 12.6.0
Npm: 6.14.7
OS: Windows 10
Browser: Chrome
```

**Angular, Nebular**
```
Nebular: 6.2.1
Angular: 10.1.5
```

**Comment by evtkhvch** [comment]
I guess, this is the correct behavior. If you wanna use `NbThemeService.getJsTheme` function you should register your theme via `NbJSThemesRegistry.register`. 
`NbThemeService.getJsTheme` returns `Observable<NbJSThemeOptions>` where you can find theme variables.
See docs: https://akveo.github.io/nebular/docs/services/jsthemesregistry#nbjsthemesregistry
Hope it helps

**Comment by LucCADORET** [comment]
It would be nice to have documentation for "js themes", the way it works is not documented, and opaque.

I am trying to setup a conditional theming based on the URL of my website, I thought `NbJSThemeOptions` would be a great candidate for that, and I tried to change the `variables.bg3` value from the theme I want to override, but it doesn't work, in the `forRoot`function of `ModuleWithProviders` (as provided in the official example dashboards with 4 default themes)
So if I try to create a whole new theme, but with keeping the "js theme" from the theme I wanna derivate from ('corporate'), I try to make the new `NbJSThemeOptions` like so:
`export const CUSTOM_THEME = {
  name: 'mynewTheme',
  base: 'corporate',
  variables: {
... // what should happen here ? should it take variable from "base" theme ?
}
}`
But it doesn't take the "base" variables from "corporate".
