### ISSUE TITLE
Auth: refresh token interceptor 

### ISSUE THREAD

**Issue by nnixaa** [akveo/nebular#260]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

https://www.intertech.com/Blog/angular-4-tutorial-handling-refresh-token-with-new-httpinterceptor/

**Comment by matheus2740** [comment]
Hey @nnixaa I was looking into how to refresh the user token from time to time, what is the current best way to do this? I couldn't find anything in the docs. I'm using NbAuthModule and NbAuthJWTToken. I'm not intecting the tokens into my http calls, I'm just subscribing authService.onTokenChange() on my services and getting the token this way.
