### ISSUE TITLE
react-native @ui-kitten

### ISSUE THREAD

**Issue by abaidbutt** [akveo/nebular#2602]
![kitten](https://user-images.githubusercontent.com/49604057/100696534-982b3e00-33b5-11eb-8a38-2174f31995e4.png)

### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by artyorsh** [comment]
Hi @abaidbutt 
Please open an issue in a [proper repository](https://github.com/akveo/react-native-ui-kitten/issues/new/choose). Also, please give at a detailed explanation. Thanks.
