### ISSUE TITLE
NbAutocomplete Add typeaheadOptionsLimit

### ISSUE THREAD

**Issue by tim6400** [akveo/nebular#2609]
**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [X ] feature request

### Issue description

**Current behavior:**
Right now we have no options to limit the display of the options, so if we have a very big list we can see performence issue

**Expected behavior:**
Implement a OptionsLimit property so we can configure how much options we see on the screen like we see in ngx-bootstrap: https://valor-software.com/ngx-bootstrap/#/typeahead - typeaheadOptionsLimit

**Comment by katebatura** [comment]
Hi, you can limit the displayed options using slice pipe. For example: 
```
<nb-autocomplete #auto (selectedChange)="onSelectionChange($event)">
      <nb-option *ngFor="let option of filteredOptions$ | async | slice:0:20" [value]="option">
        {{ option }}
      </nb-option>
    </nb-autocomplete>
```
