### ISSUE TITLE
NbTimePickerDirective: Should persist initial time set via a FormControl on focus -> unfocus

### ISSUE THREAD

**Issue by mtoksen** [akveo/nebular#2629]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Upon unfocusing a time field set with an initial time, the time is set time is reset and removed.

**Expected behavior:**
Upon unfocusing a time field set with an initial time, the initial time persists until a new time it actively set by the user.

**Steps to reproduce:**
This can easily be reproduced in the official examples under NbTimePickerDirective:

1. Go to the example field for the Form Control. An initial time should already be set.
2. Focus the field by clicking inside it. The Time Picker should now show.
3. Unfocus the field by clicking outside the Time Picker. The field is now blanked with a placeholder showing.

**Related code:**
See the official example for Form Control.
**Before focus:**
![billede](https://user-images.githubusercontent.com/58517050/102750329-e9e83800-4365-11eb-9236-8071e9b1204f.png)

**On focus without actively selecting a time and not pressing "OK":**
![billede](https://user-images.githubusercontent.com/58517050/102750374-ff5d6200-4365-11eb-814f-2cb508365b35.png)

**After unfocus without selecting a time and not pressing "OK":**
![billede](https://user-images.githubusercontent.com/58517050/102750419-0b492400-4366-11eb-9fc1-8cb34d09b7fc.png)

### Other information:

**npm, node, OS, Browser**
Browser: Reproduced in Chrome, Edge and Firefox on Windows 10 64bit.

**Angular, Nebular**
```
"@angular": "~10.2.3",
"@nebular": "~6.2.1"
```

**Comment by edson7th** [comment]
I have the same problem. Did you find a solution?
