### ISSUE TITLE
Menu: error when navigating to page without menu and then back to previous page

### ISSUE THREAD

**Issue by nnixaa** [akveo/nebular#263]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

throws error 
![image](https://user-images.githubusercontent.com/230527/36536510-3b85cb20-17de-11e8-9e62-41716b7c801c.png)

**Expected behavior:**

no error
**Steps to reproduce:**

on ngx-admin
1. go the dashboard
2. open auth menu
3. click on login page
4. fill the form, click on login
5. get redirected to the dashboard with the error in the browser console

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```
nebular rc5, rc6

**Comment by nnixaa** [comment]
@yggg when you have a spare minute

**Comment by prmces** [comment]
Hello Guys!!!

Just an FYI I had the same issues testing the starter-kit.

When navigating to any auth page, and with a browser back, that error appear.

Maybe would be good to have close butttons for the login pages...

Cya

Paulo

**Comment by nnixaa** [comment]
https://github.com/akveo/ngx-admin/issues/1587
