### ISSUE TITLE
please publish v7.0.0-beta.2

### ISSUE THREAD

**Issue by n0mer** [akveo/nebular#2631]
@yggg Sergey, can you please publish beta2 with firebase 8 (#2584)?

**Comment by yggg** [comment]
Done

**Comment by n0mer** [comment]
Thank you.

**Comment by bboydflo** [comment]
is there a changelog of what went inside that release? the reaason is that I get some issues when updating from beta.1 to beta.2. I get some issues when I run the tests, something regarding circular dependencies and also snapshots seem to change. The UI looks and seems to work correctly though.

So I would appreciate very much if you can point me to a place where I can see what changes were pushed into beta.2 release. Thanks
