### ISSUE TITLE
Error compiling angular 11 application using nebular auth + firebase

### ISSUE THREAD

**Issue by RezaRahmati** [akveo/nebular#2636]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Project doesn't compile with below error

![image](https://user-images.githubusercontent.com/10086092/103486176-deffbf80-4dc9-11eb-8d38-790e49994cfc.png)

**Expected behavior:**
Project compiles successfuly

**Steps to reproduce:**
Create a new angular project
Add @angular/fire
Add @nebular/auth
Add @nebular/firebase-auth
ng serve

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```
npm 6.14.10
**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```
"@angular/common": "~11.0.5",
"@angular/compiler": "~11.0.5",
"@angular/core": "~11.0.5",
"@angular/fire": "^6.1.4",
"@nebular/auth": "^6.2.1",
"@nebular/firebase-auth": "^6.2.1",
"firebase": "^7.0 || ^8.0",
"@nebular/theme": "^6.2.1",

**Comment by RezaRahmati** [comment]
The issue is resolved in 7.0.0-beta.2

**Comment by gorourke** [comment]
Thanks RezaRahmati,

I've installed 
npm i @nebular/auth@7.0.0-beta.2
npm i @nebular/firebase-auth@7.0.0-beta.2

and no longer get the 'no exported member' error but when I specify the auth strategy to be 'NbFirebasePasswordStrategy' I now get the following error 'NullInjectorError: No provider for NbFirebasePasswordStrategy'

The firebasePassword strategy is imported

from app.module.ts
import { NbFirebasePasswordStrategy } from '@nebular/firebase-auth';

And if I revert back to the standard 'NbPasswordAuthStrategy' stragey all loads fine, without issue.

Any ideas?

Thank you.

**Comment by RezaRahmati** [comment]
@gorourke yeah I was getting same error and resolved, please make sure you have this in your app.module,

```		
                 AngularFireModule.initializeApp(environment.firebase),
		AngularFireAuthModule,
		
		NbFirebaseAuthModule,
		NbAuthModule.forRoot({ ...defaultAuthSettings }),
```

**Comment by gorourke** [comment]
Perfect. Thank you so much. What's the usual timeframe for changes like this to come out of beta?
