### ISSUE TITLE
Docs: add example how to handle click on context menu

### ISSUE THREAD

**Issue by nnixaa** [akveo/nebular#265]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description
Subj.

**Comment by weijyewang** [comment]
Hi, is this implemented?

**Comment by Tibing** [comment]
Hi @weijyewang, this is already implemented. As you can see in the [docs](https://akveo.github.io/nebular/#/docs/components/context-menu) - context menu can receive *nbContextMenuTag*. Then you can subscribe to the menu events through [menu service](https://akveo.github.io/nebular/#/docs/components/menu#NbMenuService) and handle only events with context menu tag.
We'll add this in the documentation as soon as possible.

**Comment by weijyewang** [comment]
is there any code snipet i can refer to?

**Comment by lorentzyip** [comment]
Hi @Tibing. I've just checked the source of 2.0.0 rc6 bundled with ngx-admin. Seems nbContextMenuTag has been removed from the context-menu.directive?

**Comment by phillipgclarke** [comment]
Here's a code snippet of how I handled the click event on the user context menu in the header component @weijyewang @lorentzyip 

` this.menuService.onItemClick()
      .subscribe((event: NbMenuBag) => {
        if (event.item.title === 'Log out') {
          this.authService.logout('email');
        }
      });
`
