### ISSUE TITLE
NbTimePicker

### ISSUE THREAD

**Issue by usmanshani92** [akveo/nebular#2650]
#nebular 
![tp](https://user-images.githubusercontent.com/26071027/105045223-86146600-5a1c-11eb-98dc-d6cce7a59679.png)

I want to show time on Nbtimepicker.

![image](https://user-images.githubusercontent.com/26071027/105045349-acd29c80-5a1c-11eb-89d0-ebe6582ae934.png)
I also use this time format but not showing time.
Please guide me.
Thanks

**Comment by unumtresocto** [comment]
Is this still actual?
The issue here seem to be that you are trying to pass string as a value, whereas `timepicker` expects `Date` instance by default.
Consider using `NbDateFnsDateModule` or `NbMomentDateModule`  modules for working with timepicker =)

**Comment by an-mandarsonawane** [comment]
The issue still persists. Does anyone have any ideas about it?
