### ISSUE TITLE
Issue with Nb-select multiple control

### ISSUE THREAD

**Issue by varmamkm** [akveo/nebular#2660]
### Issue type

Issue with (selected) while using nb-select multiple

* [x] bug report

### Issue description

**Current behavior:**
I am using the nb-select multiple options to select multiple items and show them back after the screen loads. Unfortunately, I am not able to bind the selected.

**Expected behavior:**
Since it is multiple options I am sending an array of selected options and it should show them on screen

**Steps to reproduce:**

**Related code:**
```
<nb-card>
  <nb-card-header>Hello World</nb-card-header>
  <nb-card-body>
      <nb-select
        [(selected)]="selectedItems"
        multiple
        placeholder="Multiple Select"  >
        <nb-option *ngFor="let project of dropdownList" [value]="project.item_id">
          {{ project.item_text}}
        </nb-option>
      </nb-select>
    </nb-card-body>
  </nb-card>
```

```
dropdownList = [];
selectedItems = [];

ngOnInit() {
    this.dropdownList = [
      { item_id: 1, item_text: 'A' },
      { item_id: 2, item_text: 'B' },
      { item_id: 3, item_text: 'C' },
      { item_id: 4, item_text: 'D' },
      { item_id: 5, item_text: 'E' }
    ];
    this.selectedItems = [
      { item_id: 3, item_text: 'C' },
      { item_id: 4, item_text: 'D' }
    ];
}
```

Here is the url for sample code [stackbliz](https://stackblitz.com/edit/github-wh14ma?file=src/app/home/home.component.html)

**Comment by PolarbearDK** [comment]
You have [value]="project.item_id" on options and that value is what selectedItems must match:
`this.selectedItems = [3, 4];`
Your stackblitz already reflect this. Plz close issue.

**Comment by subakarank** [comment]
if you use object as value and selected item is array of objects 
```
this.selectedItems = [
      { item_id: 3, item_text: 'C' },
      { item_id: 4, item_text: 'D' }
    ];
```

```
<nb-select
        [(selected)]="selectedItems"
        multiple
        placeholder="Multiple Select"  >
        <nb-option *ngFor="let project of dropdownList" [value]="project">
          {{ project.item_text}}
        </nb-option>
      </nb-select>
```
then it is not selected
