### ISSUE TITLE
NbDatepicker - get invalid date value

### ISSUE THREAD

**Issue by christianbayer** [akveo/nebular#2670]
### Issue type

**I'm submitting a ...**

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
The value of the input is only updated when a valid date is typed or selected through the datepicker. Otherwise, if a invalid date or invalid char is typed, the value is set to null.

**Expected behavior:**
The value should be always set to the current state of the input, not only when a valid date is selected. If I type "ABC" on the input, I expect the value of the input to be "ABC", not "null" (invalid date should be handled by the form validator).

**Steps to reproduce:**
Insert anything in the input binded to a datepicker, and see the output value.

**Related code:**
https://stackblitz.com/edit/github-r4cprj?file=src%2Fapp%2Fapp.component.html

**Comment by katebatura** [comment]
Hi, if you use forms the value of the formControl must be `Date` or `null`. You can get what you have typed from `input.nativeElement.value`.
