### ISSUE TITLE
nb-option with ng-template

### ISSUE THREAD

**Issue by RoWEN-FCUB** [akveo/nebular#2672]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [X ] feature request

### Issue description

Is there a way to place an icon inside a nb-option? I have readed the docs and can't find a way to do this. May be with ng-template?

Thanks for any help.

**Comment by evtkhvch** [comment]
Sure, you should  insert an icon inside `nb-option`. It's works great
example: 
```
<nb-option>
  <nb-icon icon="star"></nb-icon>
  <span>option name</span>
</nb-option>
```
