### ISSUE TITLE
I have problem import NbAutocompleteModule from '@nebular/theme';

### ISSUE THREAD

**Issue by slooock** [akveo/nebular#2677]
Module '"../../../../node_modules/@nebular/theme"' has no exported member 'NbAutocompleteModule'.

**Comment by RoWEN-FCUB** [comment]
This works for me:

```
import { NbAutocompleteModule} from '@nebular/theme';
.....
imports: [
    NbAutocompleteModule
]
```

**Comment by andreipadolin** [comment]
Hi @slooock could you please check it again, seems issue is fixed.

**Comment by katebatura** [comment]
@slooock Are there any changes? Cause it seems like it's all fixed now.
