### ISSUE TITLE
Configuring Auth UI Question

### ISSUE THREAD

**Issue by oldpirate** [akveo/nebular#268]
Hi,
i'm trying to customize the login page, i follow the guide at: [https://akveo.github.io/nebular/#/docs/auth/configuring-ui](url)

but i need to access to config property of auth module,

like _forms.login.redirectDelay_ or _forms.login.provider_

in the import,  i dont be able to find in the auht module,  NB_AUTH_OPTIONS.

like you explain in the guide i dont wont to copy all auth module folder but only the component folder that i wont to customize.

where i can access to the auth options?

Thanks in advice,

**Comment by nnixaa** [comment]
Hi @oldpirate, you can just import the `NB_AUTH_OPTIONS` from `@nebular/auth` and use it the exactly the same way as here https://github.com/akveo/nebular/blob/master/src/framework/auth/components/login/login.component.ts#L123

**Comment by oldpirate** [comment]
thanks nixxa,
I have tried but it is not exported in version 2.0.0 rc5

package.json
 _"dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@nebular/auth": "^2.0.0-rc.5",
    "@nebular/theme": "^2.0.0-rc.5",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0",
    "bootstrap": "^4.0.0",
    "core-js": "^2.4.1",
    "nebular-icons": "^1.0.6",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },_

auth.options.d.ts

import { InjectionToken } from '@angular/core';
export interface NbAuthOptions {
    forms?: any;
    providers?: any;
}
export interface NbAuthProviders {
    [key: string]: any;
}
export declare const defaultSettings: any;
export declare const NB_AUTH_OPTIONS_TOKEN: InjectionToken<NbAuthOptions>;
export declare const NB_AUTH_USER_OPTIONS_TOKEN: InjectionToken<NbAuthOptions>;
export declare const NB_AUTH_PROVIDERS_TOKEN: InjectionToken<NbAuthProviders>;
export declare const NB_AUTH_TOKEN_WRAPPER_TOKEN: InjectionToken<NbAuthProviders>;
export declare const NB_AUTH_INTERCEPTOR_HEADER: InjectionToken<NbAuthProviders>;


I missed something?

**Comment by nnixaa** [comment]
ah yes, you either need to update to `rc.6` (as docs are referring to the latest version) or use it by the old name `NB_AUTH_OPTIONS_TOKEN`.

**Comment by oldpirate** [comment]
perfect,
i've updated to the rc.6 but now i've a import problem with NbAuthResult  from @nebular/auth seems not exported.

**Comment by nnixaa** [comment]
export it form the `@nebular/auth` path.

**Comment by oldpirate** [comment]
perfect, all seems work i need only refresh the editor and the server.

thanks for the assistance,

and good work

**Comment by nnixaa** [comment]
👌
