### ISSUE TITLE
Nebular common Header and Footer

### ISSUE THREAD

**Issue by khashashin** [akveo/nebular#2691]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Putting `<router-outlet> </router-outlet>` inside `<nb-layout>` prevents appearance of any content. Since there is no error it is very difficult to figure out why this happens

**Expected behavior:**
To be able to implement reusable Header, Footer it should display the content in the way that Angular does.

```
import { Component } from '@angular/core';

@Component({
	selector: 'app-root',
	template: `<nb-layout>
		<app-header></app-header>
		<router-outlet> </router-outlet>
		<app-footer></app-footer>
	</nb-layout>`,
})
export class AppComponent {}
```

**Steps to reproduce:**
 - Create Common Header and Footer
 - Put the content inside `nb-layout` tag

```
import { Component } from '@angular/core';

@Component({
	selector: 'app-root',
	template: `<nb-layout>
		<app-header></app-header>
		<router-outlet> </router-outlet>
		<app-footer></app-footer>
	</nb-layout>`,
})
export class AppComponent {}
```

A sample application via GitHub

StackBlitz [StackBlitz Seed Project](https://stackblitz.com/edit/nebular-common-header-footer)

### Other information:

**npm, node, OS, Browser**
```
Node, npm: `node v12.0.0` and `npm 6.9.0`
OS: Windows (10)
Browser: Chrome
```

**Angular, Nebular**
```
"@angular/core": "~11.2.3",
"@nebular/theme": "^7.0.0",
```

**Comment by evtkhvch** [comment]
`<nb-layout>` is required that all child components like `<nb-layout-column>`, `<nb-layout-footer>` should be placed inside.
See docs: https://akveo.github.io/nebular/docs/components/layout/overview#nblayoutcomponent

Basically you can implement something like this: 
```
<nb-layout>
  <nb-layout-header>
    <app-header></app-header>
  </nb-layout-header>
  <nb-layout-column>
    <router-outlet> </router-outlet>
  </nb-layout-column>
  <nb-layout-footer>
    <app-footer></app-footer>
  </nb-layout-footer>
</nb-layout>
```
Hope it helps.

**Comment by NathanSavageKaimai** [comment]
what if in a child component I want multiple columns?
