### ISSUE TITLE
NbWindow - passing data when closing

### ISSUE THREAD

**Issue by ALapaque** [akveo/nebular#2696]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**

I'm using the nbWindow components to enable the user to do multitasking while he's working, so my nbWindow can be a form or things that they can reduce if they need to do something else fast. But the main problem of that is I can't pass anything the close action, so actually I've got to refresh my datatables if they're doing an edit or an add and so...

**Expected behavior:**

That would be great if on the close action we could pass a data like you did for the NbDialog

**Steps to reproduce:**

**Related code:**

```
DIALOG EXAMPLE :

this.dialogService.open(DialogNamePromptComponent)
      .onClose.subscribe(name => name && this.names.push(name));

EXPECTED :

this.windowService.open(DialogNamePromptComponent)
      .onClose.subscribe(name => name && this.names.push(name));

```

### Other information:

**npm, node, OS, Browser**
```
Node : 12.16.3
OS: Windows 10
```

**Angular, Nebular**
```
"@nebular/eva-icons": "7.0.0",
"@nebular/theme": "^7.0.0",
```

**Comment by djbreen7** [comment]
When will a release be created with this feature? It doesn't appear to have been included in 9.0.0
