### ISSUE TITLE
SidebarService.getSidebarState() have an error : connectable.connect() not function

### ISSUE THREAD

**Issue by vincent-seibus** [akveo/nebular#2698]
Hello Everyone,

### Issue type
I'm submitting a bug report

### Issue description

**Current behavior:**
I try to use the method getSidebarState() of the SidebarService and I have got an error at runtime : 
ERROR TypeError: connectable.connect is not a function 

And the subscription fails of course so I cannot retrieve the SidebarState as wanted .

**Steps to reproduce:**
execute this code 
```javascript
this.sidebar.getSidebarState('menu-sidebar').pipe(mergeMap(state => {
        if (state === 'expanded' ) {
          return this.sidebar.getSidebarResponsiveState();
        }
        return of(null);
      })).subscribe(responsiveState => {
        if (responsiveState === 'mobile') {
          this.sidebar.toggle();
        }
      });
```

### Other information:

Chrome : last version
Nebular theme : 7.0.0
Angular  11.2

Thank you for your help.
Nebular is great :) !

**Comment by vincent-seibus** [comment]
Also , I have got the same issue with getSidebarResponsiveState().

**Comment by nolawi** [comment]
Same issue

**Comment by davidhm117** [comment]
same issue

**Comment by sidsaxena0** [comment]
Hi, i am also facing same issue but i have figured out a way to resolve this you can add #sideBar on you sidenav and then get it in your ts file using `  @ViewChild('sideBar', {static: false}) sideNav: NbSidebarComponent ;` then in your `ngAfterViewInit `subscribe for state events like this `this.sideNav?.stateChange.subscribe(data => {
      console.log('state', data);
    });`

Hope it will help with your problem, i was able to resolve my problem using above. 

Thanks

**Comment by vincent-seibus** [comment]
Thanks @sidsaxena0, it is a workaround that can be helpful but if you need access to the menu instance in another component you will have to recreate the whole sidebarService... it would be easier to fix this bug I suppose.
