### ISSUE TITLE
Tag Component Text Capitalization

### ISSUE THREAD

**Issue by vatsalkgor** [akveo/nebular#2699]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**
When tag component to show emails, text is capitalised which looks weird for emails. 

**Expected behavior:**
This should be optional value with default true so users can disable it whenever they want. 

**Steps to reproduce:**
Go to the documentation of Tag, and type in an email address, the tag associated will be capitalised. 

**Related code:**
Let me know if you want a PR for this.

**Comment by vatsalkgor** [comment]
Current work around:

```css
nb-tag {
    text-transform: none;
}
```

**Comment by andreipadolin** [comment]
Hi @vatsalkgor you can modify existing theme. https://akveo.github.io/nebular/docs/design-system/enable-customizable-theme#enable-customizable-themes

Needed values can be found here:

https://github.com/akveo/nebular/blob/daadbe596d0d1fe1bd3ecd5b1c0561e279d92248/src/framework/theme/components/tag/_tag.scss#L20

and here:

https://github.com/akveo/nebular/blob/daadbe596d0d1fe1bd3ecd5b1c0561e279d92248/src/framework/theme/styles/themes/_mapping.scss#L2603
