### ISSUE TITLE
Demo of Icons

### ISSUE THREAD

**Issue by ketimaBU** [akveo/nebular#27]
Where can visualize the icons ?

**Comment by nnixaa** [comment]
Hey @ketimaBU, the full list is here http://akveo.com/ngx-admin/#/pages/ui-features/icons

**Comment by thovo** [comment]
@nnixaa Your link didn't display all the icons, just a subset of these icons, the link went to a npm package which didn't help. A small demo with full list of icons would be very appreciated.

**Comment by danshou** [comment]
@thovo @ketimaBU here you can check all of the icons:  [icons in nebular github repo.](https://github.com/akveo/nebular/tree/master/src/framework/icons/src/icons)
There are ~87-88 and displayed in the page, the same number.

The confusion here is the button that says "See all Nebular icons" which might imply that there are more icons. That button was clearly made for the other icon sections (fontawesome that has many more icons) (@nnixaa).

**Comment by nnixaa** [comment]
@danshou thanks, you are completely right, we should remove that title and it is misleading.

**Comment by eeskildsen** [comment]
Now that Akveo has deprecated nebular-icons in favor of Eva, the above links are broken. For anyone still using nebular-icons, I created a quick-and-dirty reference page here:

https://eeskildsen.github.io/nebular-icons-reference/

**Comment by mohammad0omar** [comment]
hey, https://eeskildsen.github.io/nebular-icons-reference/ dont work

**Comment by eeskildsen** [comment]
> hey, https://eeskildsen.github.io/nebular-icons-reference/ dont work

Thanks for the heads-up, @mohammad0omar. I made a note to fix it. I should be able to get to it this weekend.

**Comment by mohammad0omar** [comment]
Perfect, this was a good reference, let me know if I can help.

**Comment by eeskildsen** [comment]
@mohammad0omar It should be back up now. Let me know if you have any issues accessing it.

https://eeskildsen.github.io/nebular-icons-reference/

**Comment by mohammad0omar** [comment]
![image](https://user-images.githubusercontent.com/20974815/82928845-732fbb80-9f8b-11ea-8f0c-ea933d73726b.png)

**Comment by eeskildsen** [comment]
@mohammad0omar Have you tried flushing your DNS cache?

**Comment by mohammad0omar** [comment]
It works finally, and yep i've already tried.
Thank you eeskildsen
