### ISSUE TITLE
Nebular Popover closes when used with Nebular Date picker

### ISSUE THREAD

**Issue by deepender87** [akveo/nebular#2702]
Hi Guys

I am facing a issues with nebular popover, I am using popover to show the UI as a template reference. In that template I am having a date picker. As I select a date from the date picker. It closes the date picker as well as the popover.
Please help me on this, how I can handle this.

**Comment by deepender87** [comment]
Similar kind of issue is here as well.

[issue 2325](https://github.com/akveo/nebular/issues/2325)

**Comment by deepender87** [comment]
I have handled everything manually only. 
Sad, someone should have fixed this in a proper way in nebular

**Comment by katebatura** [comment]
Closing as duplicate of #2325
