### ISSUE TITLE
[Violation] 'click' handler took 11539ms

### ISSUE THREAD

**Issue by arpansac** [akveo/nebular#2705]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Having more than 100 nb-selects on one page (all independent, to update the status of each row they represent). They give the following error:
`[Violation] 'click' handler took 11539ms`
It make all the clicks on the whole page go slow

**Expected behavior:**
Should work smooth, like it looks in the documentation

**Steps to reproduce:**
Create a nebular page, put about 100 nb-select in it and see.

**Related code:**
This is the code: https://github.com/commudle/commudle-ng/blob/development/projects/commudle-admin/src/app/feature-modules/sys-admin/components/labs/labs.component.html

**Angular, Nebular**
```
Angular 11
Nebular 7
```

Thanks, you guys are awesome!

**Comment by evtkhvch** [comment]
This issue similar to #1467. It fixed in #2837
