### ISSUE TITLE
incorrect behavior when entering data

### ISSUE THREAD

**Issue by alekssakovsky** [akveo/nebular#2712]
when I use other timezone (fror example Brazil (-3)), there is an automatic deletion of one day!
![bug](https://user-images.githubusercontent.com/39739131/114157270-24350f80-992c-11eb-97d1-9727591996bb.png)

**Comment by unumtresocto** [comment]
If I understand correctly - issue occurs when user tries to type date manually into the input field.

If this is the case, then:
By default (and in examples as well) JS `Date` API is used for datepicker, hence `Date.parse `is sued to parse strings into dates.  Unfortunately, if YYYY-MM-dd format is used, then JS assumes that date is being provided in shorthanded ISO8601 format with UTC+0 timezone, which causes this issue.
You can try using one of existing datepicker adapters (see _**Formatting Issue**_ article [here](https://akveo.github.io/nebular/docs/components/datepicker/overview#nbdatepickerdirective)) or try providing your custom adapter.
