### ISSUE TITLE
angular 12 error - '_viewRepeater' in type 'NbTable<T>' is not assignable to the same property in base type 'CdkTable<T>'

### ISSUE THREAD

**Issue by xmlking** [akveo/nebular#2742]
after upgrading to angular 12 I am getting following error

![image](https://user-images.githubusercontent.com/627951/118419513-12543400-b671-11eb-98d1-27071b12fc60.png)

**Comment by brandart** [comment]
any progress on this?

**Comment by dhruvchauhan** [comment]
We are also facing this issue. Nice to have a quick fix for this.

**Comment by 3DtuningProduction** [comment]
Use  "skipLibCheck": true, in tsconfig

**Comment by guilhermebentomarques** [comment]
same here

**Comment by RoWEN-FCUB** [comment]
Hello. I was facing the same error here. I downgraded @angular/cdk to version 11.0.0 and the error desappear. Seems to be a compatibility problem.
