### ISSUE TITLE
how to assign form control name in nebbular autocomplete

### ISSUE THREAD

**Issue by SoumyaApril15** [akveo/nebular#2756]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [ ] feature request

### Issue description

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by andreipadolin** [comment]
Hi @SoumyaApril15 you can look at example here: https://akveo.github.io/nebular/docs/components/autocomplete/overview#nbautocompletedirective

And here https://github.com/akveo/nebular/blob/master/src/playground/with-layout/autocomplete/autocomplete-form.component.ts

Does this helps to you?

**Comment by andreipadolin** [comment]
Closed as Nebular don't have issue.
