### ISSUE TITLE
How to assign form control name in nebular autocomplete Reactive form I am using 

### ISSUE THREAD

**Issue by SoumyaApril15** [akveo/nebular#2757]
![Error](https://user-images.githubusercontent.com/81734964/120653519-5f703c80-c49e-11eb-8b92-865797795a86.PNG)

### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [ ] feature request

### Issue description

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by andreipadolin** [comment]
Could please look at this example. https://stackblitz.com/edit/github-xejgyh?file=src/app/app.component.ts
Also seems root cause of this issue is missed module import, please check:    ` FormsModule,  ReactiveFormsModule,`

**Comment by andreipadolin** [comment]
Also this ticket can be useful https://github.com/akveo/nebular/issues/2703
