### ISSUE TITLE
nb-select : cannot make as selected if the value is object 

### ISSUE THREAD

**Issue by subakarank** [akveo/nebular#2771]
### Issue type

* [ ] bug report

### Issue description

Issue description
Current behavior:
I am using the nb-select multiple options to select multiple items and show them back after the screen loads. Unfortunately, I am not able to bind the selected.

### value is object 

Expected behavior:
Since it is multiple options I am sending an array of selected options and it should show them on screen

Steps to reproduce:

Related code:

```
<nb-card>
  <nb-card-header>Hello World</nb-card-header>
  <nb-card-body>
      <nb-select
        [(selected)]="selectedItems"
        multiple
        placeholder="Multiple Select"  >
        <nb-option *ngFor="let project of dropdownList" [value]="project">
          {{ project.item_text}}
        </nb-option>
      </nb-select>
    </nb-card-body>
  </nb-card>
```
```
dropdownList = [];
selectedItems = [];

ngOnInit() {
    this.dropdownList = [
      { item_id: 1, item_text: 'A' },
      { item_id: 2, item_text: 'B' },
      { item_id: 3, item_text: 'C' },
      { item_id: 4, item_text: 'D' },
      { item_id: 5, item_text: 'E' }
    ];
    this.selectedItems = [
      { item_id: 3, item_text: 'C' },
      { item_id: 4, item_text: 'D' }
    ];
}
```

**Angular, Nebular**
```
If value is not  object then works. 
```

**Comment by katebatura** [comment]
Hi, you can find the answer here https://github.com/akveo/nebular/issues/2543#issuecomment-746699269
