### ISSUE TITLE
angular 12 error: Class 'NbTable<T>' incorrectly extends base class 'CdkTable<T>'

### ISSUE THREAD

**Issue by oritpersik** [akveo/nebular#2774]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
after upgrading my app to angular 12 i get this error on build: node_modules/@nebular/theme/components/cdk/table/table.module.d.ts:14:22 - error TS2415: Class 'NbTable<T>' incorrectly extends base class 'CdkTable<T>'.
  Property '_viewRepeater' is optional in type 'NbTable<T>' but required in type 'CdkTable<T>'.

**Expected behavior:**
fix _viewRepeater optional field to be required

### Other information:

**npm, node, OS, Browser**
```
Node: v14.17.0, npm: 6.14.13
OS: Linux
Browser: Chrome - Version 90.0.4430.212 (Official Build) (64-bit)
```

**Angular, Nebular**
```
Angular: 12.0.5
Nebular: 7.0.0

```

**Comment by gasolanki120** [comment]
hi 
I am getting same error.

Did you get it resolve?

**Comment by oritpersik** [comment]
yes,
the new version ^8.0.0 complies with angular 12.

**Comment by gasolanki120** [comment]
So I need to use nebular 8 version?

**Comment by oritpersik** [comment]
yes.
   "@nebular/auth": "^8.0.0",
    "@nebular/eva-icons": "^8.0.0",
    "@nebular/security": "^8.0.0",
    "@nebular/theme": "^8.0.0",

**Comment by gasolanki120** [comment]
Thanks
Let me try it.

**Comment by gasolanki120** [comment]
It works
Thanks

**Comment by andreipadolin** [comment]
Closing as resolved
