### ISSUE TITLE
base64 user profile picture

### ISSUE THREAD

**Issue by bnbs** [akveo/nebular#279]
I'm building a website and when the user click on register I save the data like username, password and base 64 profile picture at the database.
How can I load this base64 profile picture in `<nb-user></ng-user>`?

**Comment by nnixaa** [comment]
Hi @bnbs, please check the documentation here https://akveo.github.io/nebular/#/docs/components/user-avatar#NbUserComponentInputs

**Comment by chnbz** [comment]
This link is unfortunately not leading anywhere anymore. And I can't figure out how it works checked the doc :(

**Comment by yggg** [comment]
@chnbz Sorry for the inconvenience, here is updated link https://akveo.github.io/nebular/docs/components/user-avatar/
You're looking for `picture` input.

We have base64 image example on the user docs page. You can see example source code by clicking on `<>` button on the top right of the example block (see screenshot below).
![image](https://user-images.githubusercontent.com/6151971/62859709-93490380-bd06-11e9-89d0-92b0a3615d51.png)

Also, there is `API` tab on the right, where you can find all component inputs. `picture` input description has mentioned base64 usage.
![image](https://user-images.githubusercontent.com/6151971/62860136-deafe180-bd07-11e9-9e64-1006fb21c116.png)

**Comment by chnbz** [comment]
Thank you soooooo much for explaining this to me, I didn't realize ❤️
