### ISSUE TITLE
ng add fails if using .sass styles extention

### ISSUE THREAD

**Issue by parth181195** [akveo/nebular#2798]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
ng add fails if u are using .sass for angular projects

**Expected behavior:**
the schematics should work no mater the style files extension is .scss/sass

**Steps to reproduce:**
create a angular project with .sass as styles extension then try a ng add @nebular/theme

**Comment by evtkhvch** [comment]
Unfortunately we support only .scss
If the project uses .sass files it'll throw the error. Because we can't use .scss syntax in the .sass Angular project
You have to migrate to .scss if you want to use customizable theme
