### ISSUE TITLE
I‘m submitting a bug report for ngb-pagination of (bootstrap)

### ISSUE THREAD

**Issue by JohnnyXuPeng** [akveo/nebular#280]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description
missing the auto generate tag 'ng_content**' for ngb-pagination directive
**Current behavior:**
![image](https://user-images.githubusercontent.com/11940800/36713246-a96a671c-1bc7-11e8-836f-82f788dff16b.png)

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
<ngb-pagination class="d-flex justify-content-center custom-pager" [collectionSize]="120" [(page)]="page" [maxSize]="5" [rotate]="true" [boundaryLinks]="true"></ngb-pagination>
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by nnixaa** [comment]
Hi @JohnnyXuPeng, I don't think this is related to Nebular itself, please check with the https://github.com/ng-bootstrap/ng-bootstrap project.
