### ISSUE TITLE
I can't use the NbWindowRef class to close the window Nebular

### ISSUE THREAD

**Issue by Rafael-Evangelista** [akveo/nebular#2824]
R3InjectorError(AppModule)[NbWindowRef -> NbWindowRef -> NbWindowRef])

app.modules.ts 
NbWindowModule.forRoot(),
NbWindowModule.forChild(),
the documentation is a bit flawed I couldn't progress....

**Comment by chirichok98** [comment]
@Rafael-Evangelista 
You should use in your AppModule import with NbWindowModule.forRoot().

After that you inject service in component via `private windowService: NbWindowService` at constructor.

To open modal you call `this.windowService.open(SomeComponent, { title: `Title` })`, it returns `NbWindowRef`.

Docs about `NbWindowRef` can be found [here](https://akveo.github.io/nebular/docs/components/window/api#nbwindowservice)

example with auto-close after 3 seconds:
.ts
`
openWindow() {
    const windowRef = this.windowService.open(SomeComponent, { title: `Auto Close` });

    setTimeout(() => { windowRef.close() }, 3000);
  }
`
