### ISSUE TITLE
I need to remove "now" button from NbDateTimePicker. 

### ISSUE THREAD

**Issue by harsh-tukadiya** [akveo/nebular#2833]
* [ ] bug report
* [X] feature request

### Issue description
**Expected behavior:**
I want to remove "now" button from nb data time picker, is there any way I can remove that button
![image](https://user-images.githubusercontent.com/59006734/129720912-36752eeb-6ff4-4a12-a322-9eb96744743e.png)

**Comment by evtkhvch** [comment]
Duplicate of #2845
