### ISSUE TITLE
Commit 10 days ago broke Auth Documentation.Commit in issue.

### ISSUE THREAD

**Issue by DaniVSainz** [akveo/nebular#284]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ X] bug report
* [ X] feature request

### Issue description

**Current behavior:**
Outdated website docs/github repo article causes issues.**Commit where change was implemented is listed at bottom of this issue with its respective comment.**

Current documentation on https://akveo.github.io/nebular/#/docs/auth/getting-user-token & https://github.com/akveo/nebular/blob/c8273da500bfd6315be42be9427fa9e477e83778/docs/articles/auth-token.md instructs 
using 
```typescript
import { NB_AUTH_TOKEN_WRAPPER_TOKEN, NbAuthJWTToken } from '@nebular/auth';
```
This gives the current issue
```typescript
[ts] Module '"c:/code/TEST-REPOS-DELETE-AT-WILL/ngx-admin/node_modules/@nebular/auth/index"' has no exported member 'NB_AUTH_TOKEN_WRAPPER_TOKEN'.
```

# According to comments in one of the commits 
BREAKING CHANGES:
1) `NB_AUTH_TOKEN_WRAPPER_CLASS` renamed to `NB_AUTH_TOKEN_CLASS` and you should use `useValue` instead of `useClass` when providing a token:
`{ provide: NB_AUTH_TOKEN_WRAPPER_TOKEN, useClass: NbAuthJWTToken },` to `{ provide: NB_AUTH_TOKEN_CLASS, useValue: NbAuthJWTToken },`

**nnixaa committed 10 days ago  Verified
1 parent 78f699c commit c8273da500bfd6315be42be9427fa9e477e83778**

**Comment by corbetmw** [comment]
The documentation still says to use `NB_AUTH_TOKEN_WRAPPER_CLASS `.

**Comment by nnixaa** [comment]
yeah, we will update it with the next release.
