### ISSUE TITLE
Add a reset() method on the NbAutocompleteComponent

### ISSUE THREAD

**Issue by hsq125** [akveo/nebular#2840]
### Issue type

* [ ] bug report
* [x] feature request

### Issue description

**Expected behavior:**

It would be very usefull to have a reset() method on the NbAutocompleteComponent. It is common to have a 'reset form' or 'clear form' button. So far, NbAutocompleteComponent can not be enrolled in clear.

(Great component by the way)

Thanks a lot !

**Comment by katebatura** [comment]
If you don't use FormControl, you need to do
`this.input.nativeElement.value = '';
  this.filteredOptions$ = this.getFilteredOptions(this.input.nativeElement.value);`
to reset autocomplete. 
Or, if you use FormControl `this.inputFormControl.setValue('')`.
