### ISSUE TITLE
NbRangepickerComponent: range is still active when you reset input throw template reference

### ISSUE THREAD

**Issue by evtkhvch** [akveo/nebular#2849]
### Issue type

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
The range is active when u invoke `reset` method

**Expected behavior:**
The range isn't active when u invoke `reset` method

**Steps to reproduce:**
1. Insert related code
2. Click on input and select range
3. Click on the reset button
4. Click on input

**Related code:**

view:
```
<input #input nbInput [formControl]="dateRange" [nbDatepicker]="formpicker">
<nb-rangepicker #formpicker></nb-rangepicker>

<button (click)="reset()">reset</button>
```
model:
```
@ViewChild('input') input: ElementRef | undefined;

reset() {
  this.input.nativeElement.value = '';
}
```

### Other information:

```
Node 14.17.4
OS: macOS Big Sur
Browser: Chrome
```

**Angular, Nebular**
```
@angular/cdk: 12.0.4
@nebular/theme: 8.0.0
```

**Comment by solodkui** [comment]
There is no method to reset the selected date in the calendar, it must always be selected at least "start"!
