### ISSUE TITLE
route-tabset.component routerLinkActiveOptions

### ISSUE THREAD

**Issue by dpollastrini** [akveo/nebular#287]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x ] feature request

### Issue description
Child routes do not display parent route-tabset tab as "active". The template for route-tabset.component hard-codes the routerLinkActiveOptions as '{exact: true}'.  Consequently, when the content of the route-tabset router-outlet contains nested router-outlet with child routes, the route-tabset tab no longer appears "active" when a child route is active.  It may be desirable to either change the routerLinkActiveOptions value to '{exact: false}', or even better, accept the options as input.

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by SidaouiBilel** [comment]
Yep, I have the same problem. Any fix?

**Comment by psamzy** [comment]
any fix, here?

**Comment by chirichok98** [comment]
@dpollastrini, @SidaouiBilel, @matzrm 

`nb-route-tabset` component has `@Input()` property for setting `routerLinkActiveOptions`.


```@Input() activeLinkOptions: RouterLinkActive['routerLinkActiveOptions'] = { exact: true };```
