### ISSUE TITLE
Tab Set Titles as Icons

### ISSUE THREAD

**Issue by krisklosterman** [akveo/nebular#288]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [X ] feature request

### Issue description

**Current behavior:**

Not Implemented

**Expected behavior:**

Ability to use an ICON as a tabTitle instead of just text
AND OR
if screen size becomes small, the ability to have it auto switch to an ICON.

**Comment by zhaoyipeng** [comment]
I think this feature is cool, and can add close button in tabtitle?

**Comment by Caspain** [comment]
What is the status on this?
