### ISSUE TITLE
nbTooltipTrigger not working

### ISSUE THREAD

**Issue by mendykatz111** [akveo/nebular#2892]
Hello,
nbTooltipTrigger not seems to be working on any trigger option, tried in version 7 and 8.

**Comment by katebatura** [comment]
Hi, could you please add a stackblitz to illustrate your issue because it seems to be working ok. Please, make sure you use `NbTrigger` type as value instead of `string` type (example: `[nbTooltipTrigger]="NbTrigger.HOVER"`).

**Comment by mendykatz111** [comment]
It works, I was using a string.
tnx.
