### ISSUE TITLE
NbWindowControlButtonsConfig does not have option to hide the close button

### ISSUE THREAD

**Issue by apappas1129** [akveo/nebular#2894]
`NbWindowControlButtonsConfig` should also have the option to hide the `x` button at the top right.

Right now, I am forced to write

```
::ng-deep {
   nb-window {
        nb-card-header {
            .buttons {
                // Only way to remove NbWindow's close button
                display: none !important;
            }
        }
    }
}
```

Please update so that we have

```
export interface NbWindowControlButtonsConfig {
    minimize: boolean;
    maximize: boolean;
    fullScreen: boolean;
    close: boolean; // <---   we need this
}
```

**Comment by apappas1129** [comment]
I prefer Window over Dialog also because of how you write handling of the `context`. The two have it done very differently. I don't want to have inconsistent code regarding how data/context is handled for my pop-ups so I am sticking with `Window` since it's basically just a dialog with already implemented `Card`, Optional pop-up features like minimize, and the Injection of Context is neat.

**Comment by khalifa005** [comment]
Fixed when minimizing window the component won't get destroyed.
had to override the nb window files 
![image](https://github.com/user-attachments/assets/e11bdf88-822e-4df0-919e-eb1a58efab97)
in window component.css
![image](https://github.com/user-attachments/assets/332d721a-ee07-4bf5-ac3c-56010581a81c)

and in the component 
![image](https://github.com/user-attachments/assets/81133470-2aed-4fe8-9bf5-626ebb52411b)

too late but i had to do it and also updated ngx admin to work with angular 18 and also can work with angular matrial
