### ISSUE TITLE
NbActionComponent or nb-action has no options for href

### ISSUE THREAD

**Issue by caciocode** [akveo/nebular#29]
When the NBActions component is used in a module there is no way of setting the onclick event and there href link just stays blank.

```
                    <nb-actions size="medium pull-right">
                      <nb-action icon="fa fa-download" (click)="handleShowProductBtn(product)"></nb-action>
                        <nb-action icon="nb-gear"></nb-action>
                    </nb-actions>
```

**Comment by caciocode** [comment]
Sorry, The issue was with my app for on click. I think it would be nice to have the href option. Although I don't think very necessary so this issue can be closed.

**Comment by caciocode** [comment]
I see this has been tagged enhancement;

Maybe there should also be a way to set the title such that a title is displayed when you hover over the icons.

**Comment by nnixaa** [comment]
Closing as we decided to not add this logic inside Nebular, as `nb-action` can accept any content inside which includes a link. And there is not much sense to duplicate `routerLInk` functionality.

**Comment by Tom4U** [comment]
> 
> 
> Closing as we decided to not add this logic inside Nebular, as `nb-action` can accept any content inside which includes a link. And there is not much sense to duplicate `routerLInk` functionality.

There is much sense. Of course we could add our own nodes into `nb-action`, but we would have to recreate everything from scratch for links and badges. This just doesn't makes sense. Better provide a `href` (use href for a-tag) and `link` (use routerLink for a-tag) attribute (maybe even with title) as `@Input()` and use them inside the component's template instead.

If you would provide better DEV docs, I could implement it. But I don't even get `start:wp` running and my time's short.

**Comment by Tom4U** [comment]
Ok, got it up and running and therefore can provide the changed code:
#1046 
@nnixaa
