### ISSUE TITLE
Change Chat Ui theme variables

### ISSUE THREAD

**Issue by Johnny-AM** [akveo/nebular#2901]
I'm trying to change with the default options but it won't seem to work. For example, I want to change the text message bubble color. In the website it says that it is related to chat-message-background but how am I able to set its color from my scss file in my component?

### Issue type

**I'm submitting a ...**  (check one with "x")

* [ X] bug report
* [ ] feature request

### Issue description

**Current behavior:**
I tried inspecting on the browser to find the related class name and change it manually but it didn't work

**Expected behavior:**
The goal is to be able to set attributes such as chat-message-background, chat-message-text-color ...

**Related code:**
I tried putting this in my scss:
nb-chat-message.reply nb-chat-message-text .text {
    background: #ff6358;
}

**Comment by katebatura** [comment]
Hi! You can read how to modify theme variables here https://akveo.github.io/nebular/docs/design-system/enable-customizable-theme#enable-customizable-themes. Or, if you need to changes just in your component css, you should use css selectors like in your related code. Sometimes you need `!important` to override property.
