### ISSUE TITLE
Add JWT header to requests only if a token is set

### ISSUE THREAD

**Issue by Darkheir** [akveo/nebular#293]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
When the JWT token doesn't exist the Authorization is still added by the interceptor as follow: `Authorization:Bearer null` 

**Expected behavior:**
The Header shouldnot be added if no JWT token is present

**Steps to reproduce:**
Setup the NbAuthJWTInterceptor and send an http request

**Related code:**
In `NbAuthJWTInterceptor` the following code 
```
if (token) {
    const JWT = `Bearer ${token.getValue()}`;
    ...
```
should be changed to
```
if (token.isValid()) {
    const JWT = `Bearer ${token.getValue()}`;
    ...
```

**Comment by nnixaa** [comment]
@Darkheir merged! Thanks for your contribution.
