### ISSUE TITLE
Error: ASSERTION ERROR: It looks like Component factory was provided as the first argument and an options object as the second argument. This combination of arguments is incompatible. You can either change the first argument to provide Component type or change the second argument to be a number 

### ISSUE THREAD

**Issue by MahlaAlimo** [akveo/nebular#2959]
### Issue type

**I'm submitting a bug report after upgrading to Angular 13 and Nebular 8.0.0

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

I upgraded to Angular 13 and now NbWindowService gives me assertion error as bellow, although it was working before upgrade (with Angular@10 and Nebular/theme@6.2.1):  
![image](https://user-images.githubusercontent.com/64589426/143430595-9daa81ba-0473-4246-b6f4-3275778e2158.png)

**Expected behavior:**

Open the window without error!

**Steps to reproduce:**

**Related code:**

Sample code can be found bellow, where `WindowDialogComponent` is imported and has `NbWindowRef` in its constructor.

![image](https://user-images.githubusercontent.com/64589426/143432796-5b9c7cab-1a8e-4aed-ad17-5db6196e2c77.png)

### Other information:

**npm, node, OS, Browser**
```

Node: v16.13.0, npm: 8.1.0  
OS: Linux (Ubuntu 18)
Browser: Chrome/Firefox/

```

**Angular, Nebular**
```
Angular 13
Nebular 8.0.0
```

**Comment by yggg** [comment]
Nebular 9 with Angular 13 support released and available on npm.
