### ISSUE TITLE
Binding search input with data (i.e: REST WS)

### ISSUE THREAD

**Issue by fongios** [akveo/nebular#297]
I am having trouble finding the search service and way to bind data with the main search bar of the UI.

I see that for the table search there is for instance a smart-table-service.ts file where i can bind data but i cant find this for the search bar... I would just like to trigger an API call using main search bar input as a param and store data in this to share between my components.

**Comment by nnixaa** [comment]
Hi @fongios, have you tried using `NbSearchService` to communicate with the search control? More details https://akveo.github.io/nebular/#/docs/components/search#NbSearchService.

**Comment by fongios** [comment]
cant find the service .ts file of this one?

**Comment by nnixaa** [comment]
Hi @fongios, have you find it?
