### ISSUE TITLE
Default input size & form-control

### ISSUE THREAD

**Issue by gael-ft** [akveo/nebular#299]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

The css class `form-control-sm` (or `form-control-lg`) is not working. Inputs with these classes have same size than any input with `form-control` class.

**Expected behavior:**

Inputs with these classes should resize (smaller or bigger than the same input without these classes)

**Steps to reproduce:**

I just followed your own steps to customize Auth UI components (see [here](https://akveo.github.io/nebular/#/docs/auth/configuring-ui)) and try to add *(not replace)* `form-control-sm` to one of the inputs of the login page (for example)

**More generally**
In fact, I am trying to reset the default size of inputs to a smaller size.
Something like :
1. Your `form-control-sm` is my `form-control`
1. Your `form-control` is my `form-control-lg`
1. I set a new `form-control-sm`

I want to use `form-control-lg` in auth pages, *so the visual will be exactly the same* but use `form-control` (almost) everywhere else.

To do so, Nebular Theme only provides two Sass variables we can touch:
1. form-control-lg-padding
1. form-control-sm-padding

The default `form-control` padding is hardcoded [at line 15](https://github.com/akveo/nebular/blob/master/src/framework/theme/styles/global/bootstrap/_forms.scss).

So In my *styles.scss* I wrote something like (see below) but I'm not feeling conformtable since fficial bootstrap lib provides these classes but it seems that they are not working through Nebular.
```sass
// install the framework and custom global styles
@include nb-install() {

  // framework global styles
  @include nb-theme-global();
  @include nb-auth-global();

  // loading progress bar
  @include ngx-pace-theme();

  // custom styles
  .form-control {
    padding: nb-theme(form-control-padding); // I personnally introduced this variables in my theme.scss (its value equals your form-control-sm-padding)

    &.form-control-lg {
      padding: nb-theme(form-control-lg-padding); // I reset its value to the hardcoded value (in _forms.scss) in my theme.scss
    }

    &.form-control-sm {
      padding: nb-theme(form-control-sm-padding); // ...
    }
  }
  // ...
};
```

**Related code:**

Snippet of my theme.scss
```sass
$nb-themes: nb-register-theme((
  // Nebular framework variables
  // ------------------------------
  btn-padding-y-lg: 0.625rem,
  btn-padding-x-lg: 1.25rem,
  btn-padding-y-md: 0.5rem,
  btn-padding-x-md: 0.75rem,
  btn-padding-y-sm: 0.25rem,
  btn-padding-x-sm: 0.5rem,

  font-main: Roboto,
  font-secondary: Exo,

  form-control-lg-padding: 0.75rem 1.125rem,
  form-control-padding: 0.375rem 0.75rem,
  form-control-sm-padding: 0.25rem 0.5rem,

  layout-content-width: 1400px,

  sidebar-header-gap: 1rem,
  sidebar-header-height: initial,
  sidebar-width: 14rem,

  tabs-padding: 0.75rem,
  // ------------------------------
  // ...
```

### Other information:

**npm, node, OS, Browser**
Node: v8.9.0
npm: 5.6.0
macOS Sierra
Browser: Chrome

**Angular, Nebular**
Angular: ~5.2.8
Nebular: ~2.0.0-rc.6

By the way, thank you very much for the framework 👍

**Comment by dedpnd** [comment]
@gael-ft do I understand correctly that you made the theme more minimalist?
If so, you can share your `styles.scss` and `theme.scss`

**Comment by JairoMarques** [comment]
Nice work! Could you share it?

**Comment by nnixaa** [comment]
More variables added for size control in 4.0.
