### ISSUE TITLE
NbAutocomplete is not working on nebular 9.0.0

### ISSUE THREAD

**Issue by hexdecimal16** [akveo/nebular#2991]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Nbautocomplete is not working on nebular 9.0.0 and angular 13. The issue is that the dropdown is not shown until user clicks the input again, 
**Expected behavior:**
Suggestion dropdown should show as the user types letter.

**Steps to reproduce:**
Initialise an angular project with version 13 and nebular 9.0.0 and try to use nbautocomplete where filtering is done serverside.
### Other information:

**npm, node, OS, Browser**
```
node: v16.13.1
npm: 8.2.0
```

**Angular, Nebular**
```
"dependencies": {
    "@angular/animations": "~13.0.3",
    "@angular/cdk": "^13.0.3",
    "@angular/common": "~13.0.3",
    "@angular/compiler": "~13.0.3",
    "@angular/core": "~13.0.3",
    "@angular/forms": "~13.0.3",
    "@angular/localize": "^13.0.3",
    "@angular/platform-browser": "~13.0.3",
    "@angular/platform-browser-dynamic": "~13.0.3",
    "@angular/platform-server": "~13.0.3",
    "@angular/router": "~13.0.3",
    "@apollo/client": "^3.5.5",
    "@fortawesome/fontawesome-free": "^5.15.4",
    "@nebular/eva-icons": "9.0.0",
    "@nebular/theme": "^9.0.0",
    "@ng-bootstrap/ng-bootstrap": "^12.0.0-beta.4",
    "@ngneat/hot-toast": "^4.0.0",
    "@ngneat/overview": "^3.0.0",
    "@nguniversal/express-engine": "^13.0.1",
    "angular2-multiselect-dropdown": "^5.0.4",
    "angular2-smart-table": "^2.0.8",
    "apexcharts": "^3.31.0",
    "apollo-angular": "^2.6.0",
    "aws-amplify-angular": "^6.0.26",
    "bootstrap": "^4.6.0",
    "eva-icons": "^1.1.3",
    "express": "^4.15.2",
    "graphql": "^16.0.1",
    "i": "^0.3.7",
    "jquery": "^3.6.0",
    "lodash-es": "^4.17.21",
    "lottie-web": "^5.8.1",
    "ng-apexcharts": "^1.6.0",
    "ng-validate-equal": "^6.0.1",
    "ng2-completer": "^9.0.1",
    "ngx-guided-tour": "^1.1.11",
    "ngx-lottie": "^8.0.1",
    "ngx-pagination": "^5.1.1",
    "npm": "^8.2.0",
    "popper.js": "^1.16.1",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.1",
    "unique-names-generator": "^4.6.0",
    "zone.js": "~0.11.4"
  },
```

**Comment by katebatura** [comment]
Hi! Please, make sure that it is not your case: https://github.com/akveo/nebular/pull/2852#issue-985043533. 
If it's not, could you provide Stackblitz example, please.

**Comment by gun2rin** [comment]
> Hi! Please, make sure that it is not your case: [#2852 (comment)](https://github.com/akveo/nebular/pull/2852#issue-985043533). If it's not, could you provide Stackblitz example, please.

Hi! Start to enter any symbols in filed. Nothing happens. Then click on the field and you will see options
[stackblitz](https://angular-ivy-drqc5g.stackblitz.io)

**Comment by katebatura** [comment]
> Hi! Try start to enter any symbols in field. 3 or 4 symbols. Nothing happens. Then click on the field and you will see options [stackblitz](https://stackblitz.com/edit/angular-ivy-drqc5g?file=src/app/app.component.ts)

You should use `startWith` RxJS operator when you subscribe to formControl valueChanges to make it work: 
```ts
this.terms$ = this.inputFormControl.valueChanges.pipe(
  startWith(''),
  switchMap((term: string) => this.searchTerms(term))
);
```

**Comment by Nikitas-io** [comment]
> You should use startWith RxJS operator when you subscribe to formControl valueChanges to make it work

@katebatura This solution **does NOT work**. My app was working as expected before upgrading to nebular 9.0.0, but now it has the bug that @hexdecimal16 described. I've tried using `startWith('')` in my pipe but I still need to click inside the field for the options to appear after I type something, or I need to type something again (type something new after my first type event), and only then the options will appear. This is REALLY annoying and buggy functionality.

**Comment by Nikitas-io** [comment]
@katebatura So today I updgraded @nebular/theme to version 10.0.0 and to my great dissapointment I realized that this bug has not yet been fixed... To make things simpler for you I decided to make **a video showcasing the bug that I descibed in detail in my previous comment on this thread**. Here it is:
![Autocomplete-bug](https://user-images.githubusercontent.com/22666742/209252239-18446853-1c4a-41d7-88a8-382f71bc6c57.gif)

As you can see, every keystroke is always one step behind the autocomplete results. PLEASE... can someone fix this??

**Comment by galvinm** [comment]
Same here with @nebular/theme version 10.0.0
