### ISSUE TITLE
Error customizing UI components for auth module

### ISSUE THREAD

**Issue by Coolpix** [akveo/nebular#301]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description
I have followed the steps to change the UI components and im getting an error because "router-outlet" is not a know element. It seems that you need to import the RouterModule inside the ThemeModule.

**Current behavior:**

App doesnt load and there's an error in the console

**Expected behavior:**

App Load correctly loading the new components

**Steps to reproduce:**

1 - Copy the resources from auth components
2 - Rename classes and selectors for new components
3 - Import the new components inside theme.module
4- Change the routes inside app-routing.module.ts with the new components
5 - Transpile the app
6 - Trying to load main page
7 - App doesnt load and there's a bug in console 
`'router-outlet' is not a known element:
1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("rd-body>
            <div class="flex-centered col-xl-4 col-lg-6 col-md-8 col-sm-12">
              [ERROR ->]<router-outlet></router-outlet>
            </div>
          </nb-card-body>
"): ng:///ThemeModule/NgxAuthComponent.html@6:14`

### Other information:

**npm, node, OS, Browser**
Chrome and firefox latest version

**Angular, Nebular**
 Angular 5 and Nebular latest version using ngx-admin

**Comment by nnixaa** [comment]
Hi @Coolpix, have you tried adding RouterModule to your module?

**Comment by Coolpix** [comment]
Yes, as i say in the description, RouterModule must be imported in you module, but i think it should be as a step in the documentation :)

**Comment by nnixaa** [comment]
@Coolpix, right, I misread the description, sorry :)

**Comment by nnixaa** [comment]
Hi @cyrilselasi, please take a look at this article https://github.com/akveo/nebular/blob/master/docs/articles/auth-custom-ui.md. You are just missing the router module import. Closing this issue as it's been fixed in docs.
