### ISSUE TITLE
Disabled nb-select not fully disabled

### ISSUE THREAD

**Issue by camboui** [akveo/nebular#3036]
### Issue type

**I'm submitting a ...

* [x] bug report
* [ ] feature request

### Issue description
Disabled nb-select component shouldn't do anything on click. But it does open the dropdown and allows value change when cliking on the button displayed value.
Note : Same thing happens when component is disabled through Form group.

**Expected behavior:**
Disabled nb-select component status should be fully disabled.

**Steps to reproduce:**
Use code available on the official documentation associated to : https://akveo.github.io/nebular/example/select/select-disabled.component 
Click on the disabled button displayed value.
See that the dropdown opens

**Related code:**
```
<nb-select disabled placeholder="Disabled">
      <nb-option value="1">Option 1</nb-option>
      <nb-option value="2">Option 2</nb-option>
      <nb-option value="3">Option 3</nb-option>
      <nb-option value="4">Option 4</nb-option>
    </nb-select>
```

**Angular, Nebular**
```
Angular 13, Nebular 9
```

**Comment by rajsaha** [comment]
Facing the same issue as well. I'm using `nb-select` with angular reactive forms. Tried disabling the dropdown with `this.form.get('control').disable()` and it does visually show that it's disabled. However, if you click on the text bit, the dropdown opens up.

**Comment by sazalihisham88** [comment]
Any workaround before this fix get released?

**Comment by rajsaha** [comment]
> Any workaround before this fix get released?

You can add this to global styles in your project. Worked for me.

`nb-select {
  button:disabled {
    span {
      pointer-events: none;
    }
  }
}`

**Comment by sazalihisham88** [comment]
@rajsaha 

Cool. It works. Thanks
