### ISSUE TITLE
NbMenu - bug when adding new items.

### ISSUE THREAD

**Issue by seanbotha123** [akveo/nebular#307]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**
When adding a new child item to a menu, the siblings get moved down and out of the wrapper.

**Expected behavior:**
Do not move the item out of the wrapper, rather expand wrapper to keep showing all menu items.

**Steps to reproduce:**
https://angular-8x61bv.stackblitz.io/ - click on `ADD NEW` button. Observe how `Child Item 2` gets moved out of the view.

code - https://stackblitz.com/edit/angular-8x61bv

**Comment by nnixaa** [comment]
Hi @seanbotha123, many thanks for reporting!

**Comment by nnixaa** [comment]
Have to postpone it until the new menu component release.
