### ISSUE TITLE
scss error

### ISSUE THREAD

**Issue by DanielGabbay** [akveo/nebular#3115]
https://github.com/akveo/nebular/blob/cea9263656b5bfc95dcaa8b24f921785ee31932b/src/framework/theme/components/layout/_layout.component.theme.scss#L99

STACK:

./src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected whitespace.
   ╷
99 │     @media screen and(min-width: $layout-window-mode-max-width + 150px) {
   │                      ^
   ╵
  node_modules/@nebular/theme/components/layout/_layout.component.theme.scss 99:22  @forward
  node_modules/@nebular/theme/styles/global/_components.scss 7:1                    @use
  node_modules/@nebular/theme/styles/_globals.scss 9:1                              @import
  src/styles.scss 2:9                                                               root stylesheet

**Comment by sengirab** [comment]
Came to create a new issue about this. Seems this issue is already created; +1

**Comment by SharyZ** [comment]
I have this error too. Has this issue been resolved?

**Comment by tomek550** [comment]
When can we expect this to be merged and on NPM? All releases are blocked due to this error :/

**Comment by sengirab** [comment]
@tomek550 Take a look at #3098, there are some fixes in there which will allow you to release :)

**Comment by sashaqred** [comment]
Should be fixed in [9.1.0-rc.7](https://www.npmjs.com/package/@nebular/theme/v/9.1.0-rc.7)
