### ISSUE TITLE
Redirect after register instead of receiving token and login

### ISSUE THREAD

**Issue by fadifannoun** [akveo/nebular#318]
### Issue type
* [ ] bug report
* [x ] feature request

### Allow to redirect after registration instead of direct login

**Current behavior:**
Currently, after register it is required to provide the token from back-end

**Needed behavior:**
Is it possible to allow redirect to login page after registration in case of success instead of requiring token ?

**Comment by nnixaa** [comment]
Hi @fadifannoun, this is a good point! Unfortunately, the only way now is to define your custom provider inherited from email-pass provider. Then you will be able to adjust the logic as you described. 
I believe we can add this also as a configuration into Nebular.

**Comment by nnixaa** [comment]
https://github.com/akveo/ngx-admin/issues/1584

**Comment by macpatel** [comment]
instead of passing token in register response from backend, pass empty or don't pass 'token', it will redirect it to login page, if you have authguard in place.

**Comment by nnixaa** [comment]
@fadifannoun, @macpatel since the next release `failWhenNoToken` option will be available per a method (login/register/refresh-token) for `NbAuthPasswordStrategy`. So that you can make that token check optional.
