### ISSUE TITLE
Release frequency

### ISSUE THREAD

**Issue by Xstoudi** [akveo/nebular#32]
Hey!
Just fixed #30 but I have a question now: when are you going to release this modification?

**Comment by nnixaa** [comment]
@Xstoudi we don't have a strict release plan for now, as this project is OS and depends on the community requests too. The way I see it we will release this fix in upcoming weeks. In the meantime, you can work with the project through npm link or publish it under your account  (check out the Release section in this document for more details https://github.com/akveo/nebular/blob/master/DEV_DOCS.md).

**Comment by Xstoudi** [comment]
Thanks!

**Comment by nnixaa** [comment]
no problem :)
