### ISSUE TITLE
Popover doesn't hide

### ISSUE THREAD

**Issue by ESadouski** [akveo/nebular#326]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description

Popover doesn't hide

**Steps to reproduce:**

Open poper -> go to the other menu item -> popever is still exist

![popever](https://user-images.githubusercontent.com/9255839/37920851-aec6c9a2-3130-11e8-9452-66c898646978.png)

**Comment by tiposaurio** [comment]
the same thing happens to me ... when it passes to another component it remains open
![error](https://user-images.githubusercontent.com/1747965/40124208-a90e7084-58ed-11e8-9c83-6a8923b685cf.png)

**Comment by hosseinGanjyar** [comment]
@Tibing heyyyyyyyyyyyyyyyyyyyyyyyyyyyyy...Why did you close this issue, without any answer.
