### ISSUE TITLE
Urgent Issue 

### ISSUE THREAD

**Issue by lakstap** [akveo/nebular#328]
Argument `$map1` of `map-merge($map1, $map2)` must be a map

**Comment by nnixaa** [comment]
Hey @lakstap, please post your package.json package-lock.json, npm and node version so that we can check.

**Comment by irshadnilam** [comment]
> i had this same problem with an anduglar 7.x project

Hi, did you find a solution? I am having the same problem. 
Thanks

**Comment by nnixaa** [comment]
Can someone consolidate a reproducible example? Otherwise, it seems impossible to guess.

**Comment by irshadnilam** [comment]
Node Version - v11.6.0
NPM Version - 6.5.0-next.0
Ubuntu 18.04.1 LTS
Angular CLI Version - 7.2.3

1. `ng new project` (use routing, use scss)
2.  `cd project`
3. `ng serve` (success)
4. `ng add @nebular/theme` (corporate, yes, yes)
5. `ng serve` (success)
6. Following [this guide](https://akveo.github.io/nebular/docs/auth/installation) to add auth
7. Final step : Enable Styles - I've added the `@import '~@nebular/auth/styles/all';` and `@include nb-auth-global();` in styles.scss file

**styles.scss before**
```
@import 'themes';

@import '~@nebular/theme/styles/globals';


@include nb-install() {
  @include nb-theme-global();
};
```
**styles.scss after**
```
@import 'themes';

@import '~@nebular/theme/styles/globals';
@import '~@nebular/auth/styles/all';

@include nb-install() {
  @include nb-theme-global();
  @include nb-auth-global();
};
```
8. `ng serve` (fail) - error mentioned by original poster

Am I missing anything?

**Comment by aucros** [comment]
Hi,
I have same problem.
node.js 10.15.0.

following your guide to install theme in a new project by guide "Add into existing project" and addin auth module by your Auth installation guide, after i add the code:
`@import '~@nebular/auth/styles/all'; // or @import '~@nebular/auth/styles/{theme-name}';

// ... 

@include nb-install() {
  @include nb-theme-global();
  @include nb-auth-global(); // append the install mixin inside of the nb-install
};`

as in the step "Enable Styles" of this guide, if i try to compile the project by "npm start" command, i have the same error:

`Failed to compile.

./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
           ^
      Argument `$map1` of `map-merge($map1, $map2)` must be a map
      in C:\ANGULAR4_PROJECTS\DELECTUS\NEWFE\DELECTUS\node_modules\@nebular\theme\styles\_theming.scss (line 64, column 13)`

> Node Version - v11.6.0
> NPM Version - 6.5.0-next.0
> Ubuntu 18.04.1 LTS
> Angular CLI Version - 7.2.3
> 
> 1. `ng new project` (use routing, use scss)
> 2. `cd project`
> 3. `ng serve` (success)
> 4. `ng add @nebular/theme` (corporate, yes, yes)
> 5. `ng serve` (success)
> 6. Following [this guide](https://akveo.github.io/nebular/docs/auth/installation) to add auth
> 7. Final step : Enable Styles - I've added the `@import '~@nebular/auth/styles/all';` and `@include nb-auth-global();` in styles.scss file
> 
> **styles.scss before**
> 
> ```
> @import 'themes';
> 
> @import '~@nebular/theme/styles/globals';
> 
> 
> @include nb-install() {
>   @include nb-theme-global();
> };
> ```
> **styles.scss after**
> 
> ```
> @import 'themes';
> 
> @import '~@nebular/theme/styles/globals';
> @import '~@nebular/auth/styles/all';
> 
> @include nb-install() {
>   @include nb-theme-global();
>   @include nb-auth-global();
> };
> ```
> 1. `ng serve` (fail) - error mentioned by original poster
> 
> Am I missing anything?

i have the same error at the same step!

Node Version - v10.15.0
NPM Version - 6.4.1
Angular CLI Version - 7.2.3

**Comment by irshadnilam** [comment]
I changed the order of imports and the error is gone.
```
@import '~@nebular/auth/styles/all';
@import 'themes';

@import '~@nebular/theme/styles/globals';


@include nb-install() {
  @include nb-theme-global();
  @include nb-auth-global();
};
```
I am not sure what's the reason behind it. 
@aucros give this a try.

**Comment by irshadnilam** [comment]
@nnixaa 
Hi, do you have any theories regarding this?
Do the order of the imports matter?

Thanks.
