### ISSUE TITLE
Mixins may not be defined within control directives or other mixins

### ISSUE THREAD

**Issue by Mc128k** [akveo/nebular#339]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

Crashes when compiling, with the message:

```
ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/app/@theme/styles/styles.scss
Module build failed: 
  @mixin hover-checked-border($color) {
        ^
      Mixins may not be defined within control directives or other mixins.
      in /Users/.../node_modules/@nebular/theme/styles/global/bootstrap/_custom-forms.scss (line 8, column 10)
```

**Expected behavior:**

the app should compile

**Steps to reproduce:**

Not sure here, it happened after messing with the packages organization. I am posting here because it seems like a valid bug, as sass shouldn't allow nested mixins (I'm not an expert, I just read [this](https://github.com/sass/libsass/issues/2030))

### Other information:

**Angular, Nebular**
```
Angular 5.2.9
Nebular 2.0.0-rc.6
```

Please delete this issue if the nested mixin code is valid indeed.

**Comment by helxsz** [comment]
Having the same problem here.

> Angular 5.2.6
> Nebular 2.0.0-rc.6

**Comment by nnixaa** [comment]
Hey Guys, thanks for reporting. It's been fixed already and will be released this week. Here's a workaround for the time being https://github.com/akveo/nebular/issues/316#issuecomment-376383942.

**Comment by andreidiaconescu** [comment]
Hello,
Can you please release the fix if possible, we would greatly need it.
Thank you !

**Comment by jaysturm** [comment]
Wondering about the status of this fix?    The workaround doesn't fix everything for me.   after building with node-sass@4.8.1 I get the following =>

ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/app/@theme/styles/styles.scss
Module build failed:
undefined
                   ^
      Argument `$color` of `lighten($color, $amount)` must be a color

Backtrace:
        node_modules/@nebular/theme/components/checkbox/_checkbox.component.theme.scss:13, in function `lighten`

**Comment by nnixaa** [comment]
Hi @jaysturm, please stop posting comments into every closed issue you found related as you are creating a lot of notification's noise for a lot of people. Please consider creating a new one with a description of your setup and reproducible examples. Thanks.

**Comment by jaysturm** [comment]
@nnixaa no problem, I have removed my other comments.   So you would like me to create a new issue on something that you are considering fixed?  I was simply wondering when your fixes were planned to be released.   I will open a new issue, thanks.

**Comment by Suyashjc** [comment]
npm i node-sass@4.8.1 this should solve the problem make sure your node version is below 10
