### ISSUE TITLE
has no exported member 'NB_AUTH_TOKEN_WRAPPER_TOKEN'

### ISSUE THREAD

**Issue by alpcoskun** [akveo/nebular#356]
### Issue type

**I'm submitting a ...**  

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

```
'@nebular/auth' has no exported member 'NB_AUTH_TOKEN_WRAPPER_TOKEN'
```
**Expected behavior:**

I was following [docs](https://akveo.github.io/nebular/#/docs/auth/getting-user-token)

### Other information:

**Angular, Nebular**
```
 angular: "~5.2.6",
 nebular: "2.0.0-rc.6",
```

**Comment by nnixaa** [comment]
Hi @alpcoskun,  there is an error in the docs, the token was renamed in the latest rc-6, please check this section for more details https://github.com/akveo/nebular/blob/master/CHANGELOG.md#breaking-changes.
