### ISSUE TITLE
how to set default theme to light instead of cosmic?

### ISSUE THREAD

**Issue by wilson-young** [akveo/nebular#36]

**Comment by blankstar85** [comment]
Hey @wilson-young 

You set the default theme under src>app>theme>theme.module.ts Line 77, set name default ex:

`const NB_THEME_PROVIDERS = [
  ...NbThemeModule.forRoot(
    {
      name: 'default',
    },`

**Comment by wilson-young** [comment]
Thanks @blankstar85
