### ISSUE TITLE
How to refresh JWT token?

### ISSUE THREAD

**Issue by matheus2740** [akveo/nebular#362]
I was looking into how to refresh the user token from time to time, what is the current best way to do this? I couldn't find anything in the docs. I'm using NbAuthModule and NbAuthJWTToken. I'm not injecting the tokens into my http calls, I'm just subscribing authService.onTokenChange() on my services and getting the token this way, and using it only when needed.
I need to refresh the JWT token from time to time to avoid the user being logged out. By the nature of JWT it's not a very good idea to have long-lived tokens.

**Comment by nnixaa** [comment]
The issue is resolved.
