### ISSUE TITLE
NB tablet 

### ISSUE THREAD

**Issue by pjyoti1235** [akveo/nebular#364]
Hi, i wanted to intercept the tab switching i.e. when i click on a tab i want a popup to come with two options ok and cancel and when i click on cancel the tab should not change.!!

### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [ ] feature request

### Issue description

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by nnixaa** [comment]
Let's keep track there https://github.com/akveo/nebular/issues/305
