### ISSUE TITLE
Tablet Size Sidebar Doesn't show when Expanded = True

### ISSUE THREAD

**Issue by brgaulin** [akveo/nebular#369]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
When expanded: true on a menu item, but we are on an iOS or Android Tablet(or safari on mac at about tablet size), and you click the hamburger at the top left to expand the menu from icons -> text, the auto-expanded menu is empty, and can't be expanded

**Expected behavior:**
Once you click the hamburger: the menu is automatically expanded and you see the sub-elements

**Steps to reproduce:**
Clone ngx-admin.
Set one of the items to expanded: true in pages-menu.ts
Open in Safari on OSX, or on an iPad/Android Tablet
Try and view the contents of that menu

**Related code:**

### Other information:

**npm, node, OS, Browser**
```
Node, npm: v9.4.0 and 5.6.0
OS: macOS High Sierra / iOS / Android
Browser: Safari on OSX/Safari, Chrome on Android
```

**Angular, Nebular**
```
Angular: 5.1.3
Nebular: 2.0.0-rc6
```

**Comment by brgaulin** [comment]
Screenshot:
<img width="919" alt="369" src="https://user-images.githubusercontent.com/4007825/38899347-8f2fa0a0-4265-11e8-9e35-0c35d16fea94.png">

**Comment by nnixaa** [comment]
@brgaulin thanks for reporting!
