### ISSUE TITLE
Can't display more than 7 sub-menu items in sidebar.

### ISSUE THREAD

**Issue by Safo91** [akveo/nebular#374]
As the title reads, I can't seem to display more than 7 sub-items in the sidebar menu, is this a known issue? Any variable I can modify to make it scrollable/change size?

**Comment by Safo91** [comment]
Apologies, I will do so in future issues. How should I update my nebular
without scrapping my current project?

**Comment by nnixaa** [comment]
@Safo91 basically you need to install a new version with `npm i @nebular/theme@_VERSION_`, and then go through a list of changes here https://github.com/akveo/nebular/blob/master/CHANGELOG.md and update your code accordingly. Hope this helps!
