### ISSUE TITLE
Clear token on logout

### ISSUE THREAD

**Issue by jarredszabadi** [akveo/nebular#38]
Hello,

After reading through the docs I'm not sure how to clear my auth token when a user presses logout. In my case there is no need to hit an endpoint when a user logs out...simply redirect to login page and clear the auth token.

Thank you

**Comment by jarredszabadi** [comment]
Premature ask. Copied source files and will modify my settings there.

**Comment by nsankaranarayanan** [comment]
Is this possible without copying the source files?

**Comment by jarredszabadi** [comment]
I don't believe so but it made sense for me to copy the auth files as I did some extra customizations.

BUUTTT

by looking at their source code in token.service.ts you can see that the token is stored in local storage with a key 'auth_app_token'.

Should you want you can clear the token yourself when a user logs out in your app localStorage.removeItem('auth_app_token');

**Comment by nnixaa** [comment]
@jarredszabadi, @nsankaranarayanan you can just set the logout endpoint to empty string and it won't hit the endpoint and simply clear the token:

```
providers: {
      email: {
        ...
        config: {
          logout: {
            endpoint: '',
          },
        },
      },
    },
```

**Comment by jarredszabadi** [comment]
mmmmmm so much better. thanks

**Comment by ynotLeft** [comment]
I'm trying to use logout method in both NbEmailPassAuthProvider and my custom provider. 
Maybe I am missing something, but NbAuthService aways skips code inside swithMap() 

<img width="1661" alt="screen shot 2018-03-06 at 3 48 16 pm" src="https://user-images.githubusercontent.com/7753483/37035909-b1b9e386-2156-11e8-8dcf-69433ff181f9.png">


I get the Observable form NbEmailPassAuthProvider (test1). Then the pipe and switchMap are skipped and I go right to the test2. 
So token is not being deleted and I am not redirected.

**Comment by dedpnd** [comment]
@ynotLeft 
Maybe you won't reach the end point?
Try adding this to `core.module.ts`

![image](https://user-images.githubusercontent.com/18037236/38247655-bc63872a-374e-11e8-9c9e-8bf357741c55.png)

**Comment by netchon** [comment]
Hi guys,
you can inject the NbTokenService and clear the data with  this.nbTokenService.clear();   like this:

 constructor(private sidebarService: NbSidebarService
              private nbTokenService:NbTokenService) {
}

logout(){
 this.nbTokenService.clear()
}

**Comment by jasonvuriker** [comment]
```
export class NgxLoginComponent extends NbLoginComponent implements OnInit {
  ngOnInit() {
    this.token.clear();
  }

  get token(): NbTokenService {
    return InjectorHelper.injector.get(NbTokenService);
  }
}

```

**Comment by babgev** [comment]
The logout method returns an `observable`, so you need to `subscribe `to it to call it.
