### ISSUE TITLE
vertical/horizontal steppers

### ISSUE THREAD

**Issue by ruisebastiao** [akveo/nebular#386]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [X ] feature request

### Issue description

Do you intend to implement vertical/horizontal steppers in the future?:

https://material.io/guidelines/components/steppers.html#

**Comment by ruisebastiao** [comment]
sorry this #336 answer my question

**Comment by nnixaa** [comment]
Hey @ruisebastiao, Stepper is already in master and will be released in the next version!
