### ISSUE TITLE
How to disable a nb-tab

### ISSUE THREAD

**Issue by ruisebastiao** [akveo/nebular#387]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [ ] feature request
* [ x] question

Is there any way to disable a `nb-tab`?

**Comment by nnixaa** [comment]
Hi @ruisebastiao, unfortunately, there is no such feature out of the box.

**Comment by i-hamza** [comment]
@ruisebastiao any luck

**Comment by jashanbhullar** [comment]
Anybody know how to do it?

**Comment by nnixaa** [comment]
planned for 3.2.0
