### ISSUE TITLE
Access token inside provider

### ISSUE THREAD

**Issue by jarredszabadi** [akveo/nebular#39]
Hello,

I've copied the auth source files into my project because I need to do some extra customizations. How do i access the token inside of a provider? I'd like to append the JWT to my headers when I request a new password. Clearly I'm misunderstanding something as I've tried to use this.getConfigValue(token.getter) to get the observable of the token but I'm stuck here.

Thank you!

**Comment by nnixaa** [comment]
Hi @jarredszabadi, sorry it's been some time and you probably resolved your issue, but for anyone facing a similar issue - you can just use angular interceptor concept to append any additional data into http requests.
