### ISSUE TITLE
Integrating another design system with nebular 

### ISSUE THREAD

**Issue by kiranchowdhury** [akveo/nebular#399]
Hello,

First of all, thank you so much for creating such a great starter kit. This is amazing.  I am working on project to rewrite a legacy UI in angular. And I want to use the nebular starter kit. However, one of the requirement is to follow my company's design standards which is Carbon Design System (http://carbondesignsystem.com/). I understand this is very specific requirement and not an nebular issue, but I will greatly appreciate if you can give me some advise how I can integrate Crabon Design with nebular.
Best Regards!
Kiran

**Comment by kiranchowdhury** [comment]
Hi There - Another question, how can I integrate a different font say ibm-plex (https://github.com/IBM/plex) font instead of Roboto in nebular ?

**Comment by nnixaa** [comment]
Hey @kiranchowdhury, please check the following links:
https://akveo.github.io/nebular/#/docs/concepts/theme-system 
https://akveo.github.io/nebular/#/docs/themes/default

Basically using Nebular Theme System you can rewrite quite a lot from the look&feek standpoint using variables provided. Same goes for your question about the font - just load the font and apply it using `font-family: MyFontFamily`. 

Hope this helps!

**Comment by kiranchowdhury** [comment]
Yeah, I have successfully integrated it.. thanks for your help.
