### ISSUE TITLE
Horizontal Menu

### ISSUE THREAD

**Issue by kiranchowdhury** [akveo/nebular#409]
Hello There - Is there a way to display the Menus (nb-menu) horizontally in the nb-header ? When I content project the the nb-menu items in nb-header component, it display the menu items as a vertical list.
The app I am developing does not have a sidebar requirement.. so my layout consists only header and main content area. From the responsiveness perspective, the menus will be under the hamburger icon when the app runs on a smaller device..

**Comment by nnixaa** [comment]
Hi @kiranchowdhury, there is no such option out of the box. You can adjust styles of nb-menu using css overrides in your project.

**Comment by kiranchowdhury** [comment]
Okai .. thanks.

**Comment by dmghutake** [comment]
Hi Nnixa, could you please give me a pointer or example how do I override style of nb-menu using ccs in my project?

**Comment by bryemye** [comment]
@dmghutake you just edit nb-menu (not .nb-menu).

**Comment by gitSambhal** [comment]
@dmghutake were you able to make it horizontal?

**Comment by terryk01** [comment]
Has anyone got a code example of a functional horizontal navbar? - I am trying to build a website (navbar) with bundled app (sidebar) ?

**Comment by dlarchikov** [comment]
> Maybe this could be an API variable for the component with a direction `horizontal` or `vertical`.

It's good idea.

**Comment by janice1015** [comment]
> Has anyone got a code example of a functional horizontal navbar? - I am trying to build a website (navbar) with bundled app (sidebar) ?

I have the same problem as you. Have you solved it? Can you refer to it
