### ISSUE TITLE
Add badge to nb-action

### ISSUE THREAD

**Issue by gentle9** [akveo/nebular#41]
I have the email and notification icons in the header. Is it possible to add a small badge to the icons?
For example a badge on the email with the number of new messages.

**Comment by gentle9** [comment]
This can be closed. I solved it by adding a custom action like this. 

```
  <nb-action class="control-item">
    <i class="nb-email"><div *ngIf="messageCount > 0" class="badge">{{messageCount}}</div></i>
  </nb-action>
```

**Comment by nnixaa** [comment]
Yes, this could be resolved like this, but I believe it would be great to have this out of the box. Let's keep it open.

**Comment by nnixaa** [comment]
Done rc.5.
