### ISSUE TITLE
Display nbContextMenu on right-click or dynamically (in TS code)

### ISSUE THREAD

**Issue by morizmartiner** [akveo/nebular#410]
### Issue type

**I'm submitting a ...**

* [] bug report
* [x] feature request

### Issue description

**Current behavior:**
I could not figure out how to display a nbContextMenu through TypeScript code or when right-clicking. 

**Expected behavior:**
Display nbConextMenu through TypescriptCode or when right-clicking. Is there a way to display a context menu with TypeScript code in the current version of @nebular/theme?

### Other information:

**npm, node, OS, Browser**
```
Node, npm: v10.0.0
OS: macOS HIgh Sierra
Browser: Chrome
```

**Angular, Nebular**
```
@nebular/theme: 2.0.0-rc.6
```

**Comment by nnixaa** [comment]
@Tibing could you check?
