### ISSUE TITLE
User Menu: close automatically when selecting an item

### ISSUE THREAD

**Issue by nnixaa** [akveo/nebular#423]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

https://github.com/akveo/ngx-admin/issues/1674

**Comment by muysewinkel** [comment]
I believe this happening for all instances of nbContextMenu

**Comment by muysewinkel** [comment]
No it is fixed.

Upgrade to 
"@nebular/theme": "^2.0.0-rc.9",

and it is fixed

**Comment by blankstar85** [comment]
My bad, I assumed ngx-admin was keeping up with the nebular releases, but I now see it is at rc2. I've updated to rc9, thanks! shouldn't this get closed then?

**Comment by blankstar85** [comment]
update: OK, I've narrowed down the behavior, but this may be over my head (I've been digging around). Closing the menu works when the link parameter isn't there. So in my example above the log out item works perfectly, however the profile item with the link doesn't. The router will navigate to the profile page, but the menu will remain open. Does the router navigation destroy the subscribed onItemClicked event?

**Comment by ma7euus** [comment]
I "solved" this the problem with:
`
userMenu: NbMenuItem[] = [
        {title: 'Profile', data: {path: '/profile'}},
        {title: 'Logout', data: {path: '/logout'}}
    ];

ngOnInit() {
     this.nbMenuService.onItemClick()
            .pipe(
                filter(({tag}) => tag === 'user-menu'),
                map((item) => item),
            )
            .subscribe(({item}) => {
                    this.router.navigateByUrl(item.data.path);           
     });`
}
