### ISSUE TITLE
clear contextMenu emitted events

### ISSUE THREAD

**Issue by muysewinkel** [akveo/nebular#426]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
I have a component (actionBar) which I pass an array of actions. Each action results in a nb-action entry with a context menu.

example action array with one example:
```
[
            {
                "icon" : "nb-plus",
                "contextMenu" : [
                    { 
                        "title": 'Add ',
                        "queryParams": 
                             {"action": "add"}
                    },
                    { 
                        "title": 'remove',
                        "queryParams": 
                            {"action": "remove"}
                    }
                ],
                "menuTag" : "menu1"
            }
]
```
I'm reusing this component on several pages.
On the pages components, I am subscribing to events emitted by the nbMenuService and log to the console each time an event is emitted.

```
this.subscription = this.menuService.onItemClick().subscribe(      
            data=>{ console.log(JSON.stringify(data))}
)
```

Everytime I navigate to a component which is listening to events emitted by the nbMenuService, I get the last event again.

I tried unsubscribing in the ngOnDestroy method but that did not help

```
ngOnDestroy(){
        this.subscription.unsubscribe();
    }
```

### Other information:

**Angular, Nebular**
```   
 "@nebular/auth": "^2.0.0-rc.7",
    "@nebular/security": "^2.0.0-rc.7",
    "@nebular/theme": "^2.0.0-rc.7",
```

```

**Comment by muysewinkel** [comment]
I believe this is caused by ReplaySubject.
This is emitting the event also when new subscribers subscribe to the event.

I have currently worked around it by setting a timestamp generetad by the component in the menuTag 
if the timestamp in the tag of the generated event does not match the one from the component, I ignore the event.

**Comment by Tibing** [comment]
Fixed By https://github.com/akveo/nebular/pull/724
