### ISSUE TITLE
nbContextMenu

### ISSUE THREAD

**Issue by muysewinkel** [akveo/nebular#429]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
If a nbContextMenu is opened and a user chooses another page in the menu generated by the pages-menu/pages-routing.module the nbContextMenu stays open on the newly loaded page.
It does not matter if the user selected an option in the context menu first.

The context menu can only be closed by refreshing the page.

This is probably related to issue #423 (User Menu: close automatically when selecting an item)

**Expected behavior:**
The context menu should close on the next click of the user (in or outside the context menu)
![screen shot 2018-05-18 at 22 28 21](https://user-images.githubusercontent.com/5213996/40256580-3af65e22-5aeb-11e8-9898-530fd1e87315.png)

**Comment by pellyadolfo** [comment]
Thanks for this fix. How should I upgrade nebular to get this fix into my project? Thanks

**Comment by nnixaa** [comment]
Hi @pellyadolfo, this will be released in the next rc.
