### ISSUE TITLE
Is there any built in "Loading spin" for data loading?

### ISSUE THREAD

**Issue by Smilefounder** [akveo/nebular#44]
I can not found any "loading spin" component for data loading.
Do we have any that we can use for now?

Thanks.

**Comment by Smilefounder** [comment]
Sorry, I just found https://akveo.github.io/nebular/#/docs/services/spinnerservice but not sure how to use it yet...

**Comment by blankstar85** [comment]
There was also a PR adding Pace.js for a loading bar. https://github.com/akveo/ngx-admin/pull/1319

**Comment by jarredszabadi** [comment]
I've also used the ng-progressbar package which works fine. you'll have to remove the spinner from index.html if you're using ngx-admin though

**Comment by blankstar85** [comment]
Not sure you would want to do that as you would loose the beginning loading screen. I'm using both. The spinner for the first load and the progress bar for in app loading

**Comment by jarredszabadi** [comment]
do you have solution for hooking up pace to your http requests? i was having issues with that approach, that's why i brought in ng-progress

**Comment by blankstar85** [comment]
@jarredszabadi I haven't gotten to worrying about that just yet, I'm still building out my forms and pages, as well as working on getting the authentication working right, I see nixxa added a pr to merge his updated auth docs, so i'm looking at that now.  I found this for pace and stored it in my list of items to get to. I haven't tested, and i'm not sure where to put this just yet, but maybe it will help you get started. https://stackoverflow.com/questions/42236286/pace-track-http-requests-in-angularjs

**Comment by jarredszabadi** [comment]
Thanks @blankstar85 

In the meantime I added ng-progress and got it working with the spinner. ng-progress is solid in that there's no configuration needed to have it show when you perform a web request. Much like you when the other stuff on my to do list is done I'll come back to getting pace working.

**Comment by blankstar85** [comment]
@jarredszabadi np, i'll post what i find here if I get to it before you. looking around real quick it appears it needs to be above the html script import. so maybe in the index file at the start of the head section, since angular cli takes care of adding all the import statements later.

**Comment by nnixaa** [comment]
Closing as it's added to component plans https://github.com/akveo/nebular/issues/336
