### ISSUE TITLE
_this.getConfigValue is not a function using email provider

### ISSUE THREAD

**Issue by Behnam-r** [akveo/nebular#45]
I encountered this error by when trying to login using email provider.
Initially the login form just say "Oops... Something went wrong" without any console output. But I could trace the problem to email provider's authenticate method. Here is the stack trace:
`
TypeError: _this.getConfigValue is not a function
at getter (http://localhost:4200/main.bundle.js:2506:200)
at MapSubscriber.project (http://localhost:4200/vendor.bundle.js:1357:203)
at MapSubscriber.webpackJsonp.../../../../rxjs/operator/map.js.MapSubscriber._next (http://localhost:4200/vendor.bundle.js:37170:35)
at MapSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next (http://localhost:4200/vendor.bundle.js:33797:18)
at MapSubscriber.webpackJsonp.../../../../rxjs/operator/map.js.MapSubscriber._next (http://localhost:4200/vendor.bundle.js:37176:26)
at MapSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next (http://localhost:4200/vendor.bundle.js:33797:18)
at FilterSubscriber.webpackJsonp.../../../../rxjs/operator/filter.js.FilterSubscriber._next (http://localhost:4200/vendor.bundle.js:36777:30)
at FilterSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next (http://localhost:4200/vendor.bundle.js:33797:18)
at MergeMapSubscriber.webpackJsonp.../../../../rxjs/operator/mergeMap.js.MergeMapSubscriber.notifyNext (http://localhost:4200/vendor.bundle.js:37600:30)
at InnerSubscriber.webpackJsonp.../../../../rxjs/InnerSubscriber.js.InnerSubscriber._next (http://localhost:4200/vendor.bundle.js:32852:21)"
`

**Comment by igorls** [comment]
Same error happening here!

**Comment by dannyrz** [comment]
me too!  how to fix it ? can anyone help me??

**Comment by nnixaa** [comment]
Hey Guys, could you please share a complete reproducible example?

**Comment by dannyrz** [comment]
App.module.ts
//auth-vz1 is renamed from folder auth for debug

/**
 * @license
 * Copyright Akveo. All Rights Reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 */
import { APP_BASE_HREF } from '@angular/common';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NgModule } from '@angular/core';
import { HttpModule } from '@angular/http';
import { CoreModule } from './@core/core.module';

import { AppComponent } from './app.component';
import { AppRoutingModule } from './app-routing.module';
import { ThemeModule } from './@theme/theme.module';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';

import { NbEmailPassAuthProvider, NbAuthModule } from '@nebular/auth-vz1';
import { NB_AUTH_TOKEN_WRAPPER_TOKEN, NB_AUTH_OPTIONS_TOKEN, NbAuthJWTToken } from '@nebular/auth-vz1';
import { getDeepFromObject } from '@nebular/auth-vz1/helpers';



@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    HttpModule,
    AppRoutingModule,

    NgbModule.forRoot(),
    ThemeModule.forRoot(),
    CoreModule.forRoot(),
    NbAuthModule.forRoot({
      providers: {
        email: {
          service: NbEmailPassAuthProvider,
          config: {
            baseEndpoint: 'http://localhost:53094',
            login: {
              alwaysFail: false,
              rememberMe: true,
              endpoint: '/api/Auth/Login',
              method: 'post',
              redirect: {
                success: '/',
                failure: null,
              },
              defaultErrors: ['Login/Email combination is not correct, please try again.'],
              defaultMessages: ['You have been successfully logged in.'],
            },
            register: {
              alwaysFail: false,
              rememberMe: true,
              endpoint: '/api/auth/register',
              method: 'post',
              redirect: {
                success: '/',
                failure: null,
              },
              defaultErrors: ['Something went wrong, please try again.'],
              defaultMessages: ['You have been successfully registered.'],
            },
            logout: {
              alwaysFail: false,
              endpoint: '/api/auth/logout',
              method: 'delete',
              redirect: {
                success: '/',
                failure: null,
              },
              defaultErrors: ['Something went wrong, please try again.'],
              defaultMessages: ['You have been successfully logged out.'],
            },
            requestPass: {
              endpoint: '/api/auth/request-pass',
              method: 'post',
              redirect: {
                success: '/',
                failure: null,
              },
              defaultErrors: ['Something went wrong, please try again.'],
              defaultMessages: ['Reset password instructions have been sent to your email.'],
            },
            resetPass: {
              endpoint: '/api/auth/reset-pass',
              method: 'put',
              redirect: {
                success: '/',
                failure: null,
              },
              resetPasswordTokenKey: 'reset_password_token',
              defaultErrors: ['Something went wrong, please try again.'],
              defaultMessages: ['Your password has been successfully changed.'],
            },
            token: {
              **_//key: 'data.token',
              //getter: function (module, res) { return getDeepFromObject(res.body, _this.getConfigValue('token.key')); },_** HERE SHOWS THE ERROR
              key: 'Value', // 改为后台返回的值
              getter: (module: string, res: HttpResponse<Object>) => {
                // debug by zhurizhao //console.log( res.body );
                return getDeepFromObject(res.body, 'Value');
              },
            },
            errors: {
              key: 'data.errors',
              getter: (module: string, res: HttpErrorResponse) => getDeepFromObject(res.error,
                this.getConfigValue('errors.key'),
                this.getConfigValue(`${module}.defaultErrors`)),
            },
            messages: {
              key: 'data.messages',
              getter: (module: string, res: HttpResponse<Object>) => {
                // debug by zhurizhao
                // console.log(this);
                // 可能时官方的一个BUG先注释掉
                // getDeepFromObject(res.body,
                //   this.getConfigValue('messages.key'),
                //   this.getConfigValue(`${module}.defaultMessages`));
                let defaultMessages = '';
                if ( module === 'login') {
                  defaultMessages = '登陆成功,正在跳转..';
                }
                return getDeepFromObject(res.body, 'data.messages', defaultMessages);
              },
            },
          },
        },
      },
    }),

  ],
  bootstrap: [AppComponent],
  providers: [
      NbAuthJWTToken,
    { provide: APP_BASE_HREF, useValue: '/' },
    { provide: NB_AUTH_TOKEN_WRAPPER_TOKEN, useClass: NbAuthJWTToken },
  ],
})
export class AppModule {
}

**Comment by migueldelgado** [comment]
Same issue with me, I get cannot find name 'getDeepFromObject' and also getConfigValue doesnt exist.

const NB_CORE_PROVIDERS = [
  ...DataModule.forRoot().providers,
  ...NbAuthModule.forRoot({
    providers: {
      email: {
        service: NbEmailPassAuthProvider,
        config: {
          delay: 3000,
          baseEndpoint: 'http://laravel.dev',
          login: {
            endpoint: '/api/login',
            method: 'post',
            rememberMe: false,
            redirect: {
              success: '/',
              failure: null
            },
            defaultErrors: ['Email/Password combinacion incorrecta, porfavor intenta denuevo'],
            defaultMessages: ['Haz entrado correctamente'],
          },
          logout: {
            alwaysFail: false,
            endpoint: '/api/logout',
            method: 'delete',
            redirect: {
              success: '/auth/login',
              failure: null,
            },
            defaultErrors: ['Algo salio mal porfavor intenta denuevo'],
            defaultMessages: ['Has salidos correctamente de la aplicacion'],
          },
          requestPass: {
            endpoint: '/api/auth/request-pass'
          },
          resetPass: {
            endpoint: '/api/auth/reset-pass'
          },
          token: {
            key: 'data.token',
            getter: (module: string, res: HttpResponse<Object>) => getDeepFromObject(res.body, 
              this.getConfigValue('token.key')),
          },
        },
      },
    },
  }).providers,
  AnalyticsService,
];

**Comment by nnixaa** [comment]
Okay, there is a problem with using `getConfigValue` outside of the AuthModule, as it will be executed in the current context, and of course, you don't have it in you `module`. I believe in this case the simplest way would be to not specify the methods you don't need to overwrite, like `getter: (module: string ...`.

**Comment by nsankaranarayanan** [comment]
I had the same issue as @migueldelgado.
I resolved it by adding the below line.
import { getDeepFromObject } from '@nebular/auth/helpers';

**Comment by issacvp** [comment]
Hi All,

I also had the same issue and resolved by below steps.

1. 

First make sure that the back end service returns the success response as below 
**{
  data : {
       token : <token value>
  }
}**


2. 

Then change the configuration in app.module.ts 

**Effectively I replaced ' this.getConfigValue('token.key')'    to 'data.token'**    (Which is actually the method supposed to do, I think)


**From 
-----**

token: {
              key: 'data.token',
              getter: (module: string, res: HttpResponse<Object>) => getDeepFromObject(res.body,
                this.getConfigValue('token.key')),
            },

**To
----**

token: {
              key: 'data.token',
              getter: (module: string, res: HttpResponse<Object>) => getDeepFromObject(res.body,
                'data.token'),
            },

**Take care of all the  getConfigValue() in app.module.ts**


Good luck all.
