### ISSUE TITLE
How to update user info on HeaderComponet

### ISSUE THREAD

**Issue by Bangood** [akveo/nebular#453]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**
The headerComponent include user info which i get from token, when I change the token in other component(ProfileComponent), the headerComponent didn't change.

**Expected behavior:**
I change the user info in ProfileComponet, and refresh the token. I hope the HeaderComponent's user info UI should rerender.

**Steps to reproduce:**

**Related code:**

`HeaderComponent:`
```
this._authService.onTokenChange()
      .subscribe(($token: NbAuthJWTToken) => {
        this.user = $token ? $token.getPayload() : {};
      });
```
`ProfileComponent:`
```
 this._userService.updateUser(this.user)
            .then($res => {
                    this._nbTokenService.set($res);
                    this._nbTokenService.tokenChange();
                    this.popupVisible = false;
            });
```

**Comment by nnixaa** [comment]
Hi @Bangood, could you please post a reproducible example to https://stackblitz.com/?

**Comment by Bangood** [comment]
Hi @nnixaa , thanks for your response, this is the brief example: https://stackblitz.com/edit/angular-occx3e

**Comment by nnixaa** [comment]
Hey @Bangood, I looked at your example and it uses an outdated rc.5 version of the Auth module. Please update to the latest rc.8. The API changed a bit since rc.5 so /CHANGELOG.md should be a good help. Here is a working example https://stackblitz.com/edit/angular-1gkctq?file=src%2Fapp%2Fapp.component.ts.

**Comment by Bangood** [comment]
hey @nnixaa , it's a good solution, thanks for your help!
