### ISSUE TITLE
problem nebular auth 

### ISSUE THREAD

**Issue by EvgenyProkopovich** [akveo/nebular#463]
![image](https://user-images.githubusercontent.com/39822739/40827486-5a62f0fe-6586-11e8-96ab-21087c6b7d35.png)
Who faced such a problem?

**Comment by nnixaa** [comment]
Hi @EvgenyProkopovich, most likely the auth module is configured incorrectly on your side. Please post a reproducible example to http://stackblitz.com.

**Comment by EvgenyProkopovich** [comment]
[test1.zip](https://github.com/akveo/nebular/files/2062226/test1.zip)

could not start in the editor, if you can look please in the archive

**Comment by nnixaa** [comment]
Hey @EvgenyProkopovich, the issue is that you copied sources from the master branch (which has the latest changes) but Nebular package in its turn is rc.8. Just copy the components from the rc.8 tag and it's going to be fine https://github.com/akveo/nebular/tree/2.0.0-rc.8

**Comment by guilnorth** [comment]
@nnixaa Perfect, it worked. Thanks!

**Comment by manusisnova** [comment]
@nnixaa it worked great, thanks for your help!
