### ISSUE TITLE
Context menu is not hidden when user clicks an item. 

### ISSUE THREAD

**Issue by nabeelriaz1001** [akveo/nebular#465]
**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
I have a logout button in context menu. Context menu is not hidden when I click it. 

**Expected behavior:**
 Context menu should hide.

**Comment by gtame** [comment]
Me too.

**Comment by nnixaa** [comment]
Duplicate of https://github.com/akveo/nebular/issues/423
