### ISSUE TITLE
how to add a badge on the NbMenuComponent

### ISSUE THREAD

**Issue by jinxiu3939** [akveo/nebular#467]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**

can not add badge on NbMenuComponent
**Expected behavior:**

**Steps to reproduce:**

I try to add nb-badge in the title of the nb-menu items ,but it is not working, and show the html text not show the component.
**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by nnixaa** [comment]
Hey @jinxiu3939, unfortunately, there is no way to do this now, unless you copy over the menu component and manually modify its template. Hopefully, we see this feature in a new version of the menu component, which is planned but has no clear release date for now.

**Comment by ruisebastiao** [comment]
+1

**Comment by marlonoso** [comment]
New in Angular. How can one do this?:  unless you copy over the menu component and manually modify its template

**Comment by seanbotha123** [comment]
Hi,

I am looking for something similar, I need to add a button onto the item like so:
![image](https://user-images.githubusercontent.com/5496698/44033068-7ab704be-9f09-11e8-9a92-b27593d58df6.png)

**Comment by jinxiu3939** [comment]
Looking forward to the new version.

**Comment by sprakash1** [comment]
![capture](https://user-images.githubusercontent.com/1481342/49421337-675ba280-f7b5-11e8-98c6-72895da90f5c.PNG)
im also looking for it. plz reply

**Comment by Steven4294** [comment]
bump!

**Comment by jinxiu3939** [comment]
Oh, sorry, I can not find a solution. Maybe the next version can get it.

发送自 Windows 10 版邮件应用

发件人: Steven Petteruti
发送时间: 2018年12月13日 5:38
收件人: akveo/nebular
抄送: jinxiu3939; State change
主题: Re: [akveo/nebular] how to add a badge on the NbMenuComponent (#467)

bump!

**Comment by RezaRahmati** [comment]
Is there any way to add some actions to menu item, like a plus button?
