### ISSUE TITLE
Cannot Bind to nbContextMenu After Upgrading to 2.0.0-rc.7

### ISSUE THREAD

**Issue by nsankaranarayanan** [akveo/nebular#480]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description
I followed the instructions to upgrading from rc.5 to rc.7 and made all the necessary changes.
I changed to the nbContextMenu directive as per the instructions

`    <nb-user [nbContextMenu]="userMenu" [name]="user?.email" [picture]="user?.picture"></nb-user>
`
Now I am getting this error.
```
Can't bind to 'nbContextMenu' since it isn't a known property of 'nb-user'.
1. If 'nb-user' is an Angular component and it has 'nbContextMenu' input, then verify that it is part of this module.
2. If 'nb-user' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  [class.left]="position === 'inverse'">
  <nb-action>
    <nb-user [ERROR ->][nbContextMenu]="userMenu" [name]="user?.email" [picture]="user?.picture"></nb-user>
  </nb-action>
"): ng:///ThemeModule/HeaderComponent.html@16:13
```

**Current behavior:**
The nbContextMenu directive is giving an error  after the upgrade.

**Expected behavior:**
It should work as expected.

**Steps to reproduce:**
- Upgrade to 2.0.0-rc.7
- Follow the upgrade instructions.

**Related code:**

```
<nb-user [nbContextMenu]="userMenu" [name]="user?.email" [picture]="user?.picture"></nb-user>
```

### Other information:

**npm, node, OS, Browser**
```
Node, npm: Node - v9.3.0, NPM - 6.0.0
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?): Windows 10
Browser: Chrome
```

**Angular, Nebular**
```
Angular: 5.1.0
Nebular: 2.0.0-rc.7
```

**Comment by nnixaa** [comment]
Hi @nsankaranarayanan, it looks like you still need to import `NbContextMenuModule` into your module.

**Comment by nsankaranarayanan** [comment]
I imported the NbContextMenuModule and still the same error.

**Comment by oshodi** [comment]
Hello @nnixaa I'm experriencing the same thing too. Upgraded to rc.7 as instructions said like @nsankaranarayanan

**Comment by oshodi** [comment]
Hi,
Think I found the solution.

When you upgrade, you need to add NbContextMenuModule to your const NB_MODULES = [ in your src\app\@theme\theme.module.ts.

**Comment by nsankaranarayanan** [comment]
@oshodi Your solution works.
