### ISSUE TITLE
Sidebar drawn under cards

### ISSUE THREAD

**Issue by jarredszabadi** [akveo/nebular#49]
<img width="1680" alt="screen shot 2017-10-27 at 11 19 42 pm" src="https://user-images.githubusercontent.com/3138299/32130827-7296afb2-bb6d-11e7-843b-ee849a4ac0a8.png">

Steps to reproduce:
1) When the page loads for the first time the issue does not exist. The sidebar can be opened and closed without being hidden behind the cards.

2) When refreshing the data the graphs are redrawn inside the cards. After this happens then the issue will occur. Opening and closing the menu will then hide the menu behind the cards.

3) Navigating to a new page after performing step 2 above does not correct the issue. The browser tab has to be refreshed to fix it.

4) Currently my cards are put inside one of the grid templates i.e. col-md-12. If I use anything other than 12 then the issue will never occur either. I.e. as long as i go <div class="col-<11 or lower"><nb-card></nb-card></div> then the sidebar is fine.

**Comment by nnixaa** [comment]
Hey @jarredszabadi, what Nebular version are you on?

**Comment by jarredszabadi** [comment]
Hi @nnixaa thanks for your help. I've tried updating @nebular/theme to rc3 (I was using rc2) but not I have the following issue when running the app

`File to import not found or unreadable: ~bootstrap/scss/functions.
Parent style sheet: /usr/src/app/node_modules/@nebular/theme/styles/global/bootstrap/_bootstrap.theme.scss
in /usr/src/app/node_modules/@nebular/theme/styles/global/bootstrap/_bootstrap.theme.scss (line 8, column 1)
@ ./src/app/@theme/styles/styles.scss 4:14-214`

I'll continue to work at it but if you've seen this issue before please let me know if there's a solution!
Thanks again

**Comment by jarredszabadi** [comment]
All good, I didn't see that I needed up to update bootstrap to beta2 as well. Thank you!
