### ISSUE TITLE
anth:how to get response from backend

### ISSUE THREAD

**Issue by jomalonejia** [akveo/nebular#5]
in nebular/auth:
if login success , the backend would return a token , how can i get the token or other response?

**Comment by nnixaa** [comment]
Hey @jomalonejia, I updated the documentation on the `NbAuthToken` service with provides you with access to the stored token https://akveo.github.io/nebular/#/docs/auth/nbtokenservice. Let me know if this helps.

**Comment by jogamod** [comment]
How to get other data from server response? Example: i want "user" from this json response ->{"token":"573bc352fd093609234a610782edd3f2fa393ef3","user":{"url":"http://localhost:8000/api/users/7/","username":"foo","email":"example@yahoo.com","first_name":"A","last_name":"B"}}

**Comment by jomalonejia** [comment]
@nnixaa  Hi  nnixaa it worked ,  i can get the stored token . thanks a lot .

**Comment by jomalonejia** [comment]
@jogamod  
i can get the response by this way,
but i dont know if this is a correct  callback function

messages: {
              key: 'data.messages',      
              getter: (module: string, res: HttpResponse<Object>) => {
                 console.log(res.body);
              }
            },

**Comment by jogamod** [comment]
@jomalonejia 
I don't want console.log() (also doesn't work), i want to store this data in some global variable which will be logged in user, but it gives me error "ERROR in Error encountered resolving symbol values statically. Function calls are not supported. "

**Comment by nnixaa** [comment]
@jogamod, @jomalonejia currently there is no out of the box way to get a complete result of  auth http requests, but you can simply use Angular Http Interceptors to intercept any request and modify or store a call result, check out this article https://alligator.io/angular/httpclient-interceptors/
in your interceptor you can call the `do` function:
```
return next.handle(req).do(evt => {
      if (evt instanceof HttpResponse) {
        // here you can get the body from evt and store it 
      }
    });
```
