### ISSUE TITLE
Sidebar - Incorrect highlighting

### ISSUE THREAD

**Issue by jarredszabadi** [akveo/nebular#50]
<img width="1680" alt="screen shot 2017-10-27 at 11 29 02 pm" src="https://user-images.githubusercontent.com/3138299/32130881-acae0d0c-bb6e-11e7-992b-ce6dd11a595f.png">

Whenever the use selects the sidebar options "Equipment Drill Down" the sidebar also highlights "Equipment" in white. The issue does not happen for any other item. I've also tried changing the order of the items and adding new items but those two options appear to be linked. Thought maybe it had something to do with the same words being in each item but that's not the case.

**Comment by nnixaa** [comment]
Hey @jarredszabadi, could you provide your menu config, please?

**Comment by jarredszabadi** [comment]
`import { NbMenuItem } from 'nebular/theme';

export const MENU_ITEMS: NbMenuItem[] = [
  {
    title: 'At A Glance',
    icon: 'ion-home',
    link: '/pages/at-a-glance',
    home: true,
  },
  {
    title: 'ANALYTICS',
    group: true,
  },
  {
    title: 'Manufacturers',
    icon: 'ion-briefcase',
    link: '/pages/manufacturers',
  },
  {
    title: 'Equipment',
    icon: 'ion-document-text',
    link: '/pages/equipment',
  },
  {
    title: 'Gym Capacity',
    icon: 'ion-podium',
    link: '/pages/gym_capacity',
  },
  {
    title: 'Gym Management',
    icon: 'ion-battery-half',
    link: '/pages/gym_management',
  },
  {
    title: 'Manufacturer Drill Down',
    icon: 'ion-arrow-graph-up-right',
    link: '/pages/manufacturer_drill_down',
  },
  {
    title: 'Equipment Drill Down',
    icon: 'ion-arrow-graph-up-left',
    link: '/pages/equipment_drill_down',
  },
];
`

***had to remove the @ from the nebular/theme import for it to show up in the post on github.

**Comment by darklinki** [comment]
Could you add your routes also ? I tried to verify it by having 2 menu items like:
-staff
-staff_list

And did not got the same result.

**Comment by jarredszabadi** [comment]
`import { RouterModule, Routes } from 'angular/router';
import { NgModule } from 'angular/core';

import { PagesComponent } from './pages.component';
import { AtAGlanceComponent } from './at_a_glance/at_a_glance.component';
import { ManufacturerComponent } from './manufacturer/manufacturer.component';
import { EquipmentComponent } from './equipment/equipment.component';
import { GymCapacityComponent } from './gym_capacity/gym_capacity.component';
import { GymManagementComponent } from './gym_management/gym_management.component';
import { ManufacturerDrillDownComponent } from './manufacturer_drill_down/manufacturer_drill_down.component';
import { EquipmentDrillDownComponent } from './equipment_drill_down/equipment_drill_down.component';

const routes: Routes = [{
  path: '',
  component: PagesComponent,
  children: [
  {
    path: 'at-a-glance',
    component: AtAGlanceComponent,
  },
  {
    path: 'manufacturers',
    component: ManufacturerComponent,
  },
  {
    path: 'equipment',
    component: EquipmentComponent,
  },
  {
    path: 'gym_capacity',
    component: GymCapacityComponent,
  },
  {
    path: 'gym_management',
    component: GymManagementComponent,
  },
  {
    path: 'manufacturer_drill_down',
    component: ManufacturerDrillDownComponent,
  },
  {
    path: 'equipment_drill_down',
    component: EquipmentDrillDownComponent,
  },
  {
    path: '',
    redirectTo: 'at-a-glance',
    pathMatch: 'full',
  }],
}];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class PagesRoutingModule {
}
`

**Comment by bobvann** [comment]
Similar problem here. Started occurring some days ago.
Whenever I click a sidebar menu item, other items do not get unselected so after a while I have all items selected ("a" has "active" class).
With rc3 if I clicked 2 times, it worked. Now with rc5 they are still selected.

:+1:

**Comment by nnixaa** [comment]
Closing as it's been a while and similar issues have been fixed.
