### ISSUE TITLE
rxjs Compatibility errors Upgrading to 2.0.0-rc.9

### ISSUE THREAD

**Issue by ksavidetove** [akveo/nebular#514]
### Issue type

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Hi

I can't install the latest version nebular/auth or security since they need rxjs@~5.5.5 and angular 6, when angular 6 is using rxjs@^6.x.x

**Expected behavior:**

nebular/auth and security should have rxjs@^6.x.x in their peer dependencies

**Steps to reproduce:**

npm install

### Other information:

OS: Linux
npm: 3.10.10
node: 10.4.1

**Comment by nnixaa** [comment]
Hey @ksavidetove, thanks for reporting! This is an unfortunate mistake in the `package.json` file. Real required version is `6+`, so for now you can just ignore the peer dependency warning. We will fix this in the upcoming release.
