### ISSUE TITLE
nbPasswordAuthStrategy

### ISSUE THREAD

**Issue by devcrmbmp812** [akveo/nebular#529]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] feature request

### Issue description

**Current behavior:**

I get the errors like the following when I tried to log in .
I used nbPasswordAuthStrategy , my back-end api has already been succeeded on postman,
but when I tried on ngx-admin login front-end, it is like this.
password-strategy.js:313 NbEmailPassAuthProvider:
                          Token is not provided under 'data.token' key
                          with getter 'function (module, res, options) {
                return Object(_helpers__WEBPACK_IMPORTED_MODULE_2__["getDeepFromObject"])(res.body, options.token.key);
            }', check your auth configuration.
so, I checked the opened and closed issues here, but no any special one for it.

**Expected behavior:**

I want to get the token from the backend.
Is there any resolution for getting the token after log in?

**Steps to reproduce:**

**Related code:**

http://prntscr.com/jzr7ic

```
insert short code snippets here
```
http://prntscr.com/jzr79y
### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by nnixaa** [comment]
Hey @devcrmbmp812, have you checked the [Getting user token](https://akveo.github.io/nebular/docs/auth/getting-user-token) article on the documentation?
