### ISSUE TITLE
nb-sidebar does not display NbMenuItem children

### ISSUE THREAD

**Issue by denisobrienirl** [akveo/nebular#532]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report (at least it seems so)

### Issue description

**Current behavior:**
It's a tough one to explain in English, but here is my best attempt at it...

nb-sidebar does not display NbMenuItem children if initiated with state="compacted" and returned to from any auth pages(login, password reset, etc...)
NOTE: This issue does not occur if state="compacted" in NOT used.

**Expected behavior:**
NbMenuItem children should be displayed.

**Steps to reproduce:**
No English can explain this, here are some breadcrumbs and an animated gif :)

**With state="compacted"**
Dashboard loaded --> Sidebar expanded --> Auth group expanded --> Login selected --> Browser 'Go Back' button clicked --> Observing that no children exist for Auth menu group.
![peek 2018-06-28 06-43](https://user-images.githubusercontent.com/38887189/42015715-5b8c992e-7aa0-11e8-81a5-9927062d7e8f.gif)

**Without state="compacted"**
Dashboard loaded --> Auth group expanded --> Login selected --> Browser 'Go Back' button clicked --> Observing that children items are present in Auth menu group.
![peek 2018-06-28 06-45](https://user-images.githubusercontent.com/38887189/42015788-a94e891a-7aa0-11e8-8cb7-33155e482a5c.gif)

**Related code:**
sample.layout.ts
```
<nb-sidebar class="menu-sidebar"
                   tag="menu-sidebar"
                   state="compacted"
                   responsive
                   [end]="sidebar.id === 'end'">
```

### Other information:

**npm, node, OS, Browser**
```
Node: v10.5.0
NPM: 6.0.1
OS: Ubuntu 18.04 LTS
Browser: Chrome Version 67.0.3396.87 (Official Build) (64-bit)
```

**Angular, Nebular**
```
"@angular/core": "6.0.0",
"@nebular/auth": "2.0.0-rc.9",
"@nebular/security": "2.0.0-rc.9",
"@nebular/theme": "2.0.0-rc.9",
```

**Comment by nnixaa** [comment]
Hi @denisobrienirl, thanks for reporting! Yes, we can see it (probably related to https://github.com/akveo/nebular/issues/444). Should be fixed in the next rc.
