### ISSUE TITLE
how to get refresh_token in interceptor?

### ISSUE THREAD

**Issue by EvgenyProkopovich** [akveo/nebular#537]
![image](https://user-images.githubusercontent.com/39822739/42081706-cd3e9be6-7b8e-11e8-9fac-2dd545859855.png)
![image](https://user-images.githubusercontent.com/39822739/42081737-e22a6bca-7b8e-11e8-877e-791cd02fb4e5.png)
![image](https://user-images.githubusercontent.com/39822739/42101841-070eda96-7bcd-11e8-8330-d5581c3b363f.png)
![image](https://user-images.githubusercontent.com/39822739/42081817-180c14dc-7b8f-11e8-88c0-1df615661595.png)
whether it is possible as that using NbPasswordAuthStrategy to receive refresh_token?

**Comment by nnixaa** [comment]
Hey @EvgenyProkopovich, yes, it is. The only thing, in your strategy configuration you used `NbAuthSimpleToken` when in your interceptor you used `NbAuthOAuth2Token`. 
Just fox your strategy config and it should be fine.

**Comment by EvgenyProkopovich** [comment]
@nnixaa , I changed the class NbAuthSimpleToken to NbAuthOAuth2Token in my strategy settings, but the error did not disappear
![image](https://user-images.githubusercontent.com/39822739/42101782-d2d1d166-7bcc-11e8-834b-543544407ed4.png)

**Comment by nnixaa** [comment]
Hey @EvgenyProkopovich, there is no need to inject the token itself, you can inject the `NbTokenService` and get the token from there.
