### ISSUE TITLE
How to register click on an action item component?

### ISSUE THREAD

**Issue by fransyozef** [akveo/nebular#544]
Is there an example how you can register a click even on an action item component (https://akveo.github.io/nebular/docs/components/actions/overview#nbactionscomponent) ?

I've tried

`<nb-action icon="ion-edit" (click)="myfunction()"></nb-action>`

but that doesn't work.

**Comment by fransyozef** [comment]
Never mind .. I had the wrong .ts file. 

`(click)=`

does works

**Comment by ezequiel88** [comment]
Not working for me
```
            <nb-actions size="small">
              <nb-action icon="fa fa-plus" (click)="newCliente()"></nb-action>
            </nb-actions>
```

**Comment by alokraj68** [comment]
Will routerlink work with this?
