### ISSUE TITLE
No mixin named nb-install

### ISSUE THREAD

**Issue by suku-h** [akveo/nebular#545]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
I followed the steps mentioned in the [installation guide](https://akveo.github.io/nebular/docs/auth/introduction#auth-module) for the auth module. But this results in the following error:
`Module build failed: 
@include nb-install() {
        ^
      No mixin named nb-install
` 

**Expected behavior:**
  No error should result when the steps were followed

**Steps to reproduce:**
  Newly created project in angular 6 using angular-cli
  then following the steps for [nebular auth installation
](https://akveo.github.io/nebular/docs/auth/installation#installation)
### Other information:

**npm: 6.1.0 , node: 8.11.3, OS: Ubuntu-16.04, Browser: Firefox**

**Angular, Nebular**
Angular: 6.0.3
Nebular Auth: 2.0.0 rc.9

**Comment by suku-h** [comment]
Solved this issue.

**The documentation for nebular auth is not updated!!**
 
**Angular.json**

```
build: {
   styles: [
              "src/styles.scss",
              "node_modules/bootstrap/dist/css/bootstrap.css",
              "node_modules/@nebular/theme/styles/prebuilt/corporate.scss"
            ]
}

...

test: {
   styles: [
              "src/styles.scss",
              "node_modules/bootstrap/dist/css/bootstrap.css",
              "node_modules/@nebular/theme/styles/prebuilt/corporate.scss"
            ]
}
```

***styles.scss***

```
@import '~@nebular/theme/styles/prebuilt/corporate'; 
@import '~@nebular/auth/styles/all';

@include nb-install() {
  @include nb-theme-global();
  @include nb-auth-global(); 
};
```

**Comment by tanzeelrana** [comment]
Login form does not show when I navigate to http://localhost:4200/#/auth/login

**Comment by toddhd** [comment]
Thank you suku-h, that worked for me as well.
