### ISSUE TITLE
Access token is not stored after login

### ISSUE THREAD

**Issue by aloxiao** [akveo/nebular#55]
Hi,
I make it docs/articles/auth-guard.md.
At app-routing.module.ts

{
path: 'pages',
canActivate: [AuthGuard], //add line
loadChildren: 'app/pages/pages.module#PagesModule' },
}
...
Result cosole.log(result); //line 53 in login.component.js
NbAuthResult {success: true, response: HttpResponse, redirect: "/", errors: Array(1), messages: Array(1), …}

However, page not nagivator to "pages/dashboard". If i hidden line canActivate then I can access dashboard but deafault load login.
Where is error?
Pleases help me!
(My english is not so good).

**Comment by nnixaa** [comment]
Hello @aloxiao, we would need much more details on this, are you using ngx-admin? Which provider are you using? Could you provide a reproducible example?

**Comment by aloxiao** [comment]
Dear Nnixaa,
I am begin Github and Angular 4, i can not upload Github.
I give link my project (Note: i am not user email login, i am use account( number : etc 216456)
https://drive.google.com/file/d/1xJ1X7LTd6wu_g15emuzxqHQjG5OgIkIj/view?usp=sharing

I use ngx-admin, i clone ngx-admin 5 day ago when new update Auth (link https://github.com/akveo/nebular/blob/master/docs/articles/auth-concepts-install.md) .

Thanks you for your reply.

**Comment by woodm1** [comment]
Same issue here. My token is in the header of the response from the server - do I need to change the token config from this:

token: {
              key: 'data.token',
              getter: (module: string, res: HttpResponse<Object>) => getDeepFromObject(res.body,
                this.getConfigValue('token.key')),
            }

to something else? I've tried debugging it through but can't work out what I need to change to specifically tell it where to find the token.

**Comment by janabimustafa** [comment]
You need to have your response structured as such { "data": { "token": "token_value" } }. You can also try to change the token.key from 'data.token' to just 'token' in your auth config. 

-Mustafa

**Comment by aloxiao** [comment]
Dear @janabimustafa,

Where is config? Thanks!

**Comment by janabimustafa** [comment]
Mine is in "src\app\@core\core.module.ts" (using ngx-admin). 
There you can change the token as follows:
```typescript
const NB_CORE_PROVIDERS = [
  ...DataModule.forRoot().providers,
  ...NbAuthModule.forRoot({
    providers: {
      email: {
        service: NbEmailPassAuthProvider,
        config: {
          baseEndpoint: '/api',
          token: {
            key: 'token',
          },
          ...
```

**Comment by blankstar85** [comment]
@janabimustafa you beat me to it. I had located this yesterday. Basically if you follow the new auth guide you just need to update the token key in the provider that you created. So this should be a file that you created in your instance and added to the module.

**Comment by woodm1** [comment]
I ended up hacking the authenticate method in email-pass-auth provider to get it out of the body, so it doesn't need to use getConfigValue() for the token. Will have a look at refactoring it properly at some point! Thanks for the help.

**Comment by mushinz** [comment]
I also have problem with this.

Token comes from response.body.token, and cant access it
