### ISSUE TITLE
opaque token not compatible with angular 4

### ISSUE THREAD

**Issue by ciacco85** [akveo/nebular#56]

**Comment by nnixaa** [comment]
Hey @ciacco85 could you please elaborate?

**Comment by ciacco85** [comment]
Sorry i made a mistake! The problem is with angular 5! They have deprecated opaque token that you use in negular theme! In fact it doesn t build anymore!

Il giorno 04 nov 2017, alle ore 16:31, Dmitry Nehaychik <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Hey @ciacco85<https://github.com/ciacco85> could you please elaborate?

**Comment by nnixaa** [comment]
https://github.com/akveo/nebular/blob/master/CHANGELOG.md#200-rc4-2017-12-31-christmas_tree
