### ISSUE TITLE
Style conflicts with DevExtreme

### ISSUE THREAD

**Issue by EatonZ** [akveo/nebular#561]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Nebular styles are bleeding into a 3rd party component, the DevExtreme Data Grid.

**Expected behavior:**
Nebular styles should not be influencing the look and behavior of the grid at all. [This page](https://github.com/akveo/nebular/blob/master/docs/articles/concept-ui-kit.md) states 3rd party components are encouraged, so this doesn't seem like something that should be happening.

I did try Shadow DOM to isolate the grid, and that did solve the issue, but it turns out the grid isn't compatible with Shadow DOM (scrolling breaks), so it was only half a fix.

**Steps to reproduce:**
Run the sample. Inspect element down to this and you can see Nebular is erroneously adding padding and fonts to a non-Nebular element:
![img](https://user-images.githubusercontent.com/3020941/42712521-020f33cc-86ba-11e8-95f0-1bec10421f05.png)

**Related code:**
I put together a sample for you. Download and run in your favorite IDE.
[Sample.zip](https://github.com/akveo/nebular/files/2194110/Sample.zip)

It looks like the problematic Nebular styling is [here](https://github.com/akveo/nebular/blob/89d429dfd0e42cfdd0d0400d070a8dd1d82386ce/src/framework/theme/components/route-tabset/_route-tabset.component.theme.scss#L17).

**Important Note:**
There may be other styling issues with Nebular and DevExtreme components. This is just one example of a visible issue, but there may be more that could be affecting the components in hidden ways.

### Other information:

**npm:** 6.1.0
**node:** 10.6.0
**Browser:** Chrome 67 on Windows 10 1803

**Angular:** 6.0.9
**Nebular:** 2.0.0-rc.9

**Comment by nnixaa** [comment]
Hey @EatonZ, this is clearly a bug in the Nebular tabs. Thanks for the report.

**Comment by xavidram** [comment]
Good Morning, 

This issue still seems to persist.

![image](https://user-images.githubusercontent.com/1348719/54621190-5b7ab000-4a35-11e9-8b8c-c8d6248ec7cb.png)

![image](https://user-images.githubusercontent.com/1348719/54621201-60d7fa80-4a35-11e9-8385-0b2d07c99f7b.png)
