### ISSUE TITLE
Logout redirect not working

### ISSUE THREAD

**Issue by HMubaireek** [akveo/nebular#567]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description
I'm using ngx-admin template, I've changed the strategy from dummy to oath2 using the following code as in the guides:

```
    strategies: [
      NbOAuth2AuthStrategy.setup({
        name: 'auth0',
        clientId: '861454901445-1d6idq52mlgh67mt3mhbqb3gdlloae79.apps.googleusercontent.com',
        clientSecret: '',
        authorize: {
          endpoint: 'https://accounts.google.com/o/oauth2/v2/auth',
          responseType: NbOAuth2ResponseType.TOKEN,
          scope: 'https://www.googleapis.com/auth/userinfo.profile',
          redirectUri: 'http://localhost:4200/auth/callback',
        },
        redirect: {
          success: '/pages/dashboard',
        }
      }),
    ],
    forms: {
      logout: {
        redirectDelay: 0,
        strategy: 'auth0',
      }
    }

```

**Current behavior:**
I navigate to /auth/logout to logout but the page remains in the logout component and never redirects.

**Expected behavior:**
To redirect as setup in the strategy config

**Steps to reproduce:**
Run ngx-admin template and change strategy to oath2

### Other information:

**npm, node, OS, Browser**
```
Node, 5.6
OS: Windows 10
Browser: Chrome
```

**Angular, Nebular**
```
Angular 6, Nebular rc.9
```

**Comment by nnixaa** [comment]
Hi @HMubaireek, is there any error in the console?

**Comment by nnixaa** [comment]
Hi @HMubaireek, have you resolved the issue?

**Comment by drav96** [comment]
Just call 
`this.router.navigate(['admin/auth/logout']);`

when pressing logout button and thi will do the trick

**Comment by JulidaRocks** [comment]
The logout redirect does not work in my project, too. `result.getRedirect()` returns undefined (result is NbAuthResult). Where can I configure the logout redirect? Using the redirectUri config in forms/logout does not work. Neither does the configuration of a logout redirect uri in the Azure AD App registration (I'm using OAuth2 with Azure AD).

**Comment by NoSouls** [comment]
Same here

**Comment by faisal-zulfiqar** [comment]
Weirdly enough, adding a link attribute to the menu item made logging out work without any issue.

`userMenu: NbMenuItem[] = [ { title: 'Log out', link: '/auth/logout' } ];`
