### ISSUE TITLE
Auth UI customization very complicated

### ISSUE THREAD

**Issue by lfagundes** [akveo/nebular#574]
### Issue type

**I'm submitting a ...** 
* [X] proposal (will send pull request with code and docs if accepted)
* [ ] bug report
* [ ] feature request

### Issue description

**Current behavior:**

Configuration of auth screens is very complicated. To put a simple logo in login screen documentation suggests you copy a lot of code com Nebular components, which will likely break things in future when those components are updated in Nebular. 

**Expected behavior:**
Instead of copying component code from Nebular project, it's simpler to create a new component that extends NbLoginComponent. It's as simple as:

```
import { Component } from '@angular/core';
import { NbLoginComponent } from '@nebular/auth';

@Component({
    selector: 'nb-login',
    templateUrl: 'login.component.html',
})
export class LoginComponent extends NbLoginComponent {}
```
Then you are free to write any html code in login.component.html, and can use Nebular's one as base.

This is even a nice way to configure things like redirectDelay:
```
export class LoginComponent extends NbLoginComponent {
    redirectDelay: number = 500;
}
```
One issue in using Nebular's template is that the `<nb-auth-block>` causes error, because NbAuthBlockComponent can't be imported to local scope (it's already imported by Nebular). This extension method of configuring interface would be easier if this doesn't exist (and btw, what is it for? Apparently it's just a placeholder for non-implemented stuff).

If this sounds nice, I will send a pull request with:
* updated docs to use extension as a method of configuring layout
* put html code of auth components in separate file, so that it's easier for developers to copy
* remove the nb-auth-block so things work out of the box

Is this reasonable?

**Comment by nnixaa** [comment]
Hey @lfagundes, thanks for your suggestions. I cannot say these are unreasonable, however, we have to move carefully here as a lot of people already using the components the way they are and we don't want to introduce a lot of breaking changes. So let's move one change at a time.
I believe separate files for auth templates would be a good start. Then we can discuss the other changes here. 

What do you think?

**Comment by Prefix1802** [comment]
Hi Nnixaa,

I have to comment on your statement "we don't want to introduce a lot of breaking changes.".

Recently you introduced some changes in Nebular, login.component.ts that breaks the possibility to make a custom login page. Is it possible you could fix it?

With kind regards,

Clyde

**Comment by lfagundes** [comment]
Hi,

Sorry for the delay, just got back from vacations. 

That seems okay to me. So, I'll work on a pull request and document the way I did, using current code, on how to extend the classes, which is much simpler than the current suggested way to customize layout.

**Comment by nnixaa** [comment]
@lfagundes looking forward to it!

**Comment by bingika** [comment]
@lfagundes is this done. i am having difficulty in customizing the auth module and is looking forward to try your suggestion. it will be really helpful if you provide the documentation.

**Comment by lfagundes** [comment]
Hi @bingika,

I just pushed some code to my fork, check: https://github.com/lfagundes/nebular/commit/7ceb2566de18902e03bd5ea4d50c1ddf97f52639

I didn't test that code yet and I didn't see the documentation rendered, so I have to do that before making a pull request. I'm not yet completely familiar with angular2 and nebular, so have yet to find how to render that documentation.

**Comment by nnixaa** [comment]
@lfagundes `npm run docs:serve` should do it (then open your browser at http://localhost:4100).

**Comment by nnixaa** [comment]
Hey @lfagundes, we decided to rewrite this article completely based on your suggestion for components inheritance. Tomorrow I will open a PR and if you and @bingika could take a look - that would be great.

**Comment by bingika** [comment]
Hi @lfagundes, I have tried it and the call to super is to be included. 
Also i found the issue in customizing, it was due to the version issue which is already reported in #1807. Thanks for your support.

**Comment by nnixaa** [comment]
@lfagundes, @bingika here you go https://github.com/akveo/nebular/pull/639. Please take a look if you have some time.
