### ISSUE TITLE
Override default bootstrap theme

### ISSUE THREAD

**Issue by antonellopasella** [akveo/nebular#585]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
If I put a basic Bootstrap component (not Nebular's one), it will not be styled correctly 
```
<div class="badge badge-danger"></div>
```

**Expected behavior:**
class badge-danger will be overrided by current theme

**Steps to reproduce:**
Simply put 
```
<div class="badge badge-danger"></div>
```
into a template

**Comment by nnixaa** [comment]
Closing as Nebular 5 planning to drop bootstrap support and completely replace with Nebular components.
