### ISSUE TITLE
Issue when extending environments

### ISSUE THREAD

**Issue by luislard** [akveo/nebular#589]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**

Cannot extend environment variables when building or serving with another configuration.
This is giving issues to use angular translations or building to staging.
**Expected behavior:**

We could use an environmentBase and import it in other enviroment configs so we dont need to duplicate environment configs.
**Steps to reproduce:**

```javascript
// environmentBase.ts
export const environmentBase = {
    production: false,
    api: {
        schema: 'http://',
        base: 'my-local-domain/',
        version: '1.0',
        endpoints: {
            check_login: '/users/check_login',
            register: '/users/register',
        }
    }
  };

// environment.ts
import { environmentBase } from './environmentBase';


export const environment = {
  ...environmentBase,
  production: false,
    api: {
      ...environmentBase.api,
        schema: 'http://',
        base: 'local.en.api.my-local-domain/',
    }
};

//environment.es.ts
import { environmentBase } from './environmentBase';


export const environment = {
  ...environmentBase,
  production: false,
    api: {
      ...environmentBase.api,
        schema: 'http://',
        base: 'local.es.api.my-local-domain/',
    }
};
```
**Related code:**

[Code example and readme explaining the issue available here](https://github.com/luislard/nebular-admin-issue/tree/starter-kit)

### Other information:

**npm, node, OS, Browser**
```
v10.1.0, 6.2.0
Node, npm:  v10.1.0, 6.2.0
OS: macOS Sierra
Browser: Chrome/Safari/Firefox/etc

```

**Angular, Nebular**

[Code example and readme explaining the issue available here](https://github.com/luislard/nebular-admin-issue/tree/starter-kit)

**Comment by luislard** [comment]
Thx, any advise? best practice? I ended up copying all info for all environments

**Comment by aefox** [comment]
although an old issue, since it still opened I will answer so this can be closed.
indeed this is a misconfiguration on the angular side and not related to nebular.
long story short, angular cli has 2 sections to describe different configurations, a `build` section and a `serve` section. see here for more details https://github.com/angular/angular-cli/issues/10800
