### ISSUE TITLE
Module aproximate terms

### ISSUE THREAD

**Issue by orpuig** [akveo/nebular#59]
Hi, great job with nebular!

I was wondering you could tell us something on when are you releasing those new modules: acl / dashboard / data.

Just to know whether it is better for us to wait or dev on our own side. We are specially interested in "acl".

thanks!

**Comment by sameerkattel** [comment]
First thank you for building nebular.

wondering  when  the acl is coming.

**Comment by nnixaa** [comment]
Hi @orpuig, @sameerkattel, now we are having all of the planned milistones here on Github https://github.com/akveo/nebular/milestones, so you could check our plans on the next, and next after versions.
