### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by MrEdgariux** [akveo/nebular#592]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [x] feature request

### Issue description

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by nnixaa** [comment]
Hey @MrEdgariux, anything we can help you with?

**Comment by MrEdgariux** [comment]
help me does not work http://gestyy.com/wKhrSr photos!

https://www.cognitoforms.com/MrEdgariux/DovanuAnketa

2018-07-31 19:02 GMT+03:00 Dmitry Nehaychik <notifications@github.com>:

**Comment by Prefix1802** [comment]
Looks like spam to me.
