### ISSUE TITLE
Tab title not break line

### ISSUE THREAD

**Issue by steven274** [akveo/nebular#601]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

<img width="591" alt="screen shot 2018-08-05 at 6 20 34 pm" src="https://user-images.githubusercontent.com/7889676/43685389-69253d02-98dc-11e8-9a19-1ef16d4c29a8.png">

**Comment by nnixaa** [comment]
Hey @steven274, could you please elaborate?

**Comment by shalinjames** [comment]
I am assuming that he is expecting it to display the title in without text being wrapped.

**Comment by nnixaa** [comment]
I believe this can be simply fixed using CSS. Closing as there is no issue in Nebular.

**Comment by steven274** [comment]
@nnixaa I want multiple tab lines like this

![image](https://user-images.githubusercontent.com/7889676/45585097-f371d280-b908-11e8-9a19-1b62b65cb8b4.png)
