### ISSUE TITLE
Can not build:prod nebular-2. 0.0-rc.9

### ISSUE THREAD

**Issue by Prefix1802** [akveo/nebular#603]
> nebular@2.0.0-rc.9 build nebular-2.
0.0-rc.9
> ng build "--prod" "--aot"

module.js:538
    throw err;
    ^

Error: Cannot find module 'collection-visit'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (nebular-2.
0.0-rc.9\node_modules\cache-base\index.js:5:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nebular@2.0.0-rc.9 build: `ng build "--prod" "--aot"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nebular@2.0.0-rc.9 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     2018-08-05T23_02_26_016Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nebular@2.0.0-rc.9 build:prod: `npm run build -- --prod --aot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nebular@2.0.0-rc.9 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     2018-08-05T23_02_26_077Z-debug.log

C:\nebular-2.0.0-rc.9>npm i
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@
1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do m
y best with it!
npm WARN bootstrap@4.0.0 requires a peer of jquery@1.9.1 - 3 but none is install
ed. You must install peer dependencies yourself.
npm WARN bootstrap@4.0.0 requires a peer of popper.js@^1.12.9 but none is instal
led. You must install peer dependencies yourself.
npm WARN codelyzer@4.0.2 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-
beta <6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.0.2 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta
 <6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.0.2 requires a peer of @angular/platform-browser-dynamic@^2
.3.1 || >=4.0.0-beta <6.0.0 but none is installed. You must install peer depende
ncies yourself.
npm WARN codelyzer@4.0.2 requires a peer of @angular/platform-browser@^2.3.1 ||
>=4.0.0-beta <6.0.0 but none is installed. You must install peer dependencies yo
urself.
npm WARN codelyzer@4.0.2 requires a peer of @angular/common@^2.3.1 || >=4.0.0-be
ta <6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! Cannot read property '0' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     2018-08-05T23_04_18_812Z-debug.log

**Comment by nnixaa** [comment]
Hi @Prefix1802, could you please elaborate? It's hard to tell what's causing the issue from the description.

**Comment by Prefix1802** [comment]
Can you please close thisissue for me?

**Comment by nnixaa** [comment]
Sure!
