### ISSUE TITLE
@mixin install-placeholder cleans the background text of an input.

### ISSUE THREAD

**Issue by valiaga** [akveo/nebular#610]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [X] feature request

### Issue description
When you click on an input the text of the bacgroud is deleted. I do not want this action, I want it to remain as the default configuration of boostrap.

**Current behavior:**
When I click on an input the background text is deleted. I do not want this action

**Expected behavior:**
I would like you to have the default bootstrap configuration. When you click on in input the backgroud text should remain until you start typing.
I do not want to modify the file in the node_modules of my project, if not configure it only for my project

**Steps to reproduce:**

**Related code:**
I know that this action is generated by the mixins install-placeholder() that is in line 103 of the file.
https://github.com/akveo/nebular/blob/master/src/framework/theme/styles/core/_mixins.scss

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by nnixaa** [comment]
Fixed in 4.0
