### ISSUE TITLE
Navigation Menu Item(s) Appear Selected Despite Not Being the Active Page

### ISSUE THREAD

**Issue by bali-ibrahim** [akveo/nebular#620]
### Issue type

**I'm submitting a:**

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Navigation menu item(s) appear selected _despite_ not being the active page.

**Expected behavior:**
_Only_ the active page is selected at all times.

**Steps to reproduce:**

1. Navigate to /auth/login by any means
2. Paste & Go /pages/ui-features/buttons using browser URL bar
3. Repeat 1
4. Paste & Go /pages/ui-features/icons using browser URL bar

At this point, you're supposed to see at least one additional menu item appearing as if selected.

**Related code:**

```
Unable to determine.
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: v10.5.0 and 6.1.0
OS: Windows 10
Browser: Chrome/Firefox
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```
Applicable for the demo @ http://akveo.com/ngx-admin/

**Comment by nnixaa** [comment]
@bali-ibrahim thanks for reporting. https://github.com/akveo/nebular/issues/392 might be related.
