### ISSUE TITLE
Menu (scrollbar) not rendered correctly

### ISSUE THREAD

**Issue by Prefix1802** [akveo/nebular#622]
Hi,

I have reported an issue in ngx-admin "collapsed sidebar not rendered correctly" # 1821. But my guess is i should report it here for obvious reasons. https://github.com/akveo/ngx-admin/issues/1821

When you have a lot of menu items or menu is bigger the window height a scrollbar appears.

![afbeelding](https://user-images.githubusercontent.com/40199655/43935985-c9290f94-9c56-11e8-8351-6e23cbcaec69.png)

1. When you have a look at Bluradmin http://akveo.com/blur-admin-mint you can see that the scrollbar for the menu is approx 1 or two millimeters wide. In ngx admin it is the default width. Is it possible someone can implement the same css styles in nebular?

2. When number 1 is implemented it automatically solves a problem when the menu is collapsed and the scrollbar is overlapping menu items.

![afbeelding](https://user-images.githubusercontent.com/40199655/43936012-e922f4f4-9c56-11e8-866a-6e8d3b27e9ac.png)

**Comment by nnixaa** [comment]
Hi @Prefix1802, thanks for reporting, could you let me know your browser?

**Comment by Prefix1802** [comment]
@nnixaa, 

![afbeelding](https://user-images.githubusercontent.com/40199655/44021917-52661428-9ee6-11e8-948f-fb6796060c35.png)

**Comment by nnixaa** [comment]
I see, unfortunately, there is not we can customize scrollbars using CSS in Firefox, here are some more details https://github.com/akveo/nebular/issues/347
Closing this one as a duplicate.
