### ISSUE TITLE
Question regarding use of NbPasswordAuthStrategy as username login strategy

### ISSUE THREAD

**Issue by sukeshlaghate** [akveo/nebular#623]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] Bug report
* [ ] Feature request
* [x] Question

### Issue description
My understanding is that NbPasswordAuthStrategy uses email and password and can not be used as normal username password strategy that is for e.g username: john.doe password: SomePassword.

How can I use NbPasswordAuthStrategy to use username and password for login  instead of default email and password? or do i need to implement my own AuthStrategy?

Also it would be helpful if you can include examples of using more than one strategies in the documentation.

**Comment by sukeshlaghate** [comment]
same issue and question raised in ngx-admin repository by another user Jonathan002  #1805. 
Thanks

**Comment by Prefix1802** [comment]
@Jonathan002 and @sukeshlaghate ,

As far as i can see in the source code of nebular the email address is passed as a string. My guess is that if you remove validation on the input box, or replace the email address input box with a new input box that, for testing purposes does not do any validation and accepts any string as input, it should work.

**Comment by nnixaa** [comment]
Hey @sukeshlaghate, @Prefix1802 is perfectly right, you just need to use a custom html template for the login/register form (or custom components). The strategy itself doesn't validate the input in any way.

**Comment by sukeshlaghate** [comment]
@nnixaa and @Prefix1802 Thank you for pointing out the right direction. I dug around the repo code and observed that `strategy.authenticate` does not accept headers as its parameters instead one has to write http interceptors to modify requests( as pointed out by @nnixaa in one of the questions asked in this repo) however, wouldn't it make sense to have authenticate method accept headers as optional parameter or have custom headers as strategy option settings? thus eliminating the need to write http interceptors which would impact all requests.
Use case for this is backend may require a special header in request only for login requests while all other requests may not require that header. In my case my backend expects header `X-Requested-With` to be present when making login request. There may be similar cases out there which would require special headers for login request

**Comment by joeyjin** [comment]
Hi, 
Thanks in advanced! 
I am new for the ngx-admin and I tried to do authenticate with my own service. I can see it hit my service (http://localhost:4201/api/auth/login) when I login.  But it always can not login(error message: Oh snap!
Something went wrong.) even if the service return true...What's the problem? Many thanks!

NbPasswordAuthStrategy.setup({
        name: 'email',
        baseEndpoint: 'http://localhost:4201/api',
         login: {
                alwaysFail: false,
                rememberMe: true,
                method: 'post',
                endpoint: '/auth/login',
                redirect: {
                  success: '/',
                  failure: null,
                },
                defaultErrors: ['Email/Password combination is not correct, please try again.'],
                defaultMessages: ['You have been successfully logged in.'],
         },

**Comment by Prefix1802** [comment]
@nnixaa 

can you remove @joeyjin  comment. He made a new issue. #680

**Comment by tanzeelrana** [comment]
is there a way to add custom headers to my requests ?

**Comment by Prefix1802** [comment]
My implementation

auth.interceptor.ts. 

import { Injectable } from '@angular/core';
import {
    HttpRequest,
    HttpHandler,
    HttpEvent,
    HttpInterceptor
} from '@angular/common/http';
import { AuthService } from '../services/auth.service';
import { Observable } from 'rxjs/Observable';

@Injectable()
export class AuthInterceptor implements HttpInterceptor {

    constructor(public auth: AuthService) { }

    intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        request = request.clone({
            setHeaders: {
                Authorization: 'authbasic ' + this.auth.getStoredUserCredentials()
            }
        });

        return next.handle(request);
    }
}

This interceptor appends headers to all my http calls because i imported it in app.module.ts

import { AuthInterceptor } from './@erp/auth/interceptors/auth.interceptor';

providers: [
      {
          provide: APP_BASE_HREF, useValue: '/',
      },
      ProfileService,
      AuthGuard,
      RoleGuard,
      {
          provide: HTTP_INTERCEPTORS,
          useClass: AuthInterceptor,
          multi: true
      }

  ],

And when i dont want my http calls intercepted, for example in auth.service.ts for login purpose. I do this:

private http: HttpClient;

constructor(handler: HttpBackend,
        private router: Router) {
        
        this.http = new HttpClient(handler);
    }

so when you do a this.http.get like this it wont get intercepted because you are making use of HttpBackend

**Comment by mahdi7192** [comment]
if you want to call login method with {username} not with {email}, in the custom login template just change ngModel of email input to this:
`<input nbInput fullWidth [(ngModel)]="user.username"...>`

**Comment by hosseinGanjyar** [comment]
@sukeshlaghate You should **JUST** change **pattern** property in: 

> \node_modules\@nebular\auth\components\login\login.component.js

To > ` pattern=\"[a-zA-Z0-9_.]+\"\n`

**Comment by yggg** [comment]
Closing as answered [here](https://github.com/akveo/nebular/issues/623#issuecomment-412438134)
