### ISSUE TITLE
Multiple select on select tag 

### ISSUE THREAD

**Issue by jaysoniscale** [akveo/nebular#636]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Expected behavior:**
Is it possible to have a multiple select dropdown as a UI Feature of ngx-admin like ng2-bootstrap multiple select dropdown. I have used the ng2-bootstrap select dropdown but its design does not match the theme.

![image](https://user-images.githubusercontent.com/40819612/44138457-9a008c5c-a0a6-11e8-98b4-e23b4f8e1aaf.png)

**Comment by nnixaa** [comment]
Hi @jaysoniscale, this is planned and hopefully will be ready in the upcoming releases.

**Comment by jaysoniscale** [comment]
Glad to hear that. Thanks

**Comment by octavian9** [comment]
any news about the progress ?

**Comment by dhrn** [comment]
+1
