### ISSUE TITLE
nb-checkbox validation

### ISSUE THREAD

**Issue by EvgenyProkopovich** [akveo/nebular#637]
![image](https://user-images.githubusercontent.com/39822739/44138486-cae4ebb2-a07c-11e8-9a2f-543d34388328.png)
![image](https://user-images.githubusercontent.com/39822739/44138527-e6db29e4-a07c-11e8-9ac8-7765c1842e7f.png)
How to validate nb-checkbox? Tell me please.

**Comment by cmajsmith** [comment]
Can you, please, describe what exactly you want to achieve in some more details?

Technically the checkbox being checked can be validated with `required` and I believe no `pattern` check is needed.
