### ISSUE TITLE
Handling multiple auth tokens (access token and identity token)

### ISSUE THREAD

**Issue by alanwolman** [akveo/nebular#64]
Hi,

I am in the process of writing an AuthProvider for Auth0, and would like to store both the identity token and the access token.

Is there a way to store multiple tokens received by a login process.

At this stage, I am doing so by concatenating the tokens together using a separator. Is there a better way of doing this?

Thanks,
Alan

**Comment by nnixaa** [comment]
Hi @alanwolman, I believe for now you can pass the token as a json string from your custom auth provider. Then, you can create a custom token wrapper service and handle the token parsing + add additional methods, smth like this:

```
@Injectable()
export class CusomJwtToken extends NbAuthJWTToken {

  private refreshToken;

  setValue(storedJsonToken: any) {
    let parsedToken: any = {};
    try {
      parsedToken = JSON.parse(storedJsonToken)
    } catch (e) {}

   // now you can get your identity token and store it inside of some var
  }

  // and add a getter
  getIdenityToken(): string {
    return this.identityToken;
  }
}
```

I guess this is a best of you can do for now.

**Comment by aucros** [comment]
from @nebular/auth/providers/email-pass-auth.provider.ts

if i want store a refresh_token sent by server in response body, is correct to store it in the authenticate function at the 2nd map before return the NbAuthResult object with the success login result?



  authenticate(data?: any): Observable<NbAuthResult> {
    const method = this.getConfigValue('login.method');
    const url = this.getActionEndpoint('login');
    return this.http.request(method, url, { body: data, observe: 'response' })
      .map((res) => {
        if (this.getConfigValue('login.alwaysFail')) {
          throw this.createFailResponse(data);
        }


        return res;
      })
      .map((res) => {
       //MY PERSONAL CODE ADDED TO STORE REFRESH TOKEN
        if(res.body.refresh_token) {
           localStorage.setItem('refresh_token',res.body.refresh_token);
        }
       //END
        return new NbAuthResult(
          true,
          res,
          this.getConfigValue('login.redirect.success'),
          [],
          this.getConfigValue('messages.getter')('login', res),
          this.getConfigValue('token.getter')('login', res));
      })
      .catch((res) => {
        let errors = [];
        if (res instanceof HttpErrorResponse) {
          errors = this.getConfigValue('errors.getter')('login', res);
        } else {
          errors.push('Something went wrong.');
        }


        return Observable.of(
          new NbAuthResult(
            false,
            res,
            this.getConfigValue('login.redirect.failure'),
            errors,
          ));
      });
  }

**Comment by Nightbr** [comment]
I think we need to be able to override the NbTokenService in order to handle more Token class. For example to create MyCustomToken with AccessToken, TokenType, RefreshToken, UserId, ... And save this into localstorage and hook properly into auth-provider. Or add custom data handler... But RefreshToken is really common and should be implemented in the NbTokenService (optionnal).

Right now, I made the same quick fix as @aucros in order to set/get refreshToken and use it into the interceptor to refresh my token on 401 and retry failed queries.

**Comment by nnixaa** [comment]
Hey @cloakedch, take a look at the following PR https://github.com/akveo/nebular/pull/638. It is not merged yet but has a lot of info on this matter.

**Comment by cloakedch** [comment]
Thank you @nnixaa, the PR sounds promising. Looking forward to getting it merged.

**Comment by nnixaa** [comment]
It's merged now so I guess we can close this one.

**Comment by BlackXnt** [comment]
@cloakedch Were you able to set this up?

**Comment by cloakedch** [comment]
Yes I did. Are you facing problems?
