### ISSUE TITLE
Menu-max height

### ISSUE THREAD

**Issue by zerox12311** [akveo/nebular#65]
Hi, I'm using this theme
This is really a good theme,but had some bug...
when i menu-item is too much, it will not show all,
I found the max-height of .menu-items.expanded class is lock on 300px
I tried to change the menu css but not have effect,please help me......

**Comment by BryanYin** [comment]
@nnixaa 
I also met this issue, could you please give quick fix? I think a simple change to remove the max-height limitation will do. 
thanks!

**Comment by zerox12311** [comment]
@BryanYin 
Hi , I fix this issue is force override the CSS style in index.html style tag with
```
.menu-items.expanded,
    [_nghost-c2] .menu-item>.menu-items.expanded {
      max-height: 900px;
    }
```

**Comment by BryanYin** [comment]
@zerox12311 
Thank you! this works like a charm!

**Comment by ffreitasit** [comment]
Why the max-height??? O.o

**Comment by nnixaa** [comment]
Hi @ffreitasit, max-height there is for animation porpuses. But of course this is not an excuse and this has to be fixed.
