### ISSUE TITLE
Error in use nb-list 

### ISSUE THREAD

**Issue by 1benayatei** [akveo/nebular#655]
Why not work nb-list ? 

My code :
`<nb-card [size]="'medium'">
    <nb-card-header>List inside nb-card</nb-card-header>
    <nb-list>
        <nb-list-item>12313</nb-list-item>
    </nb-list>
</nb-card>`

Error message : 
'nb-list-item' is not a known element:
1. If 'nb-list-item' is an Angular component, then verify that it is part of this module.
2. If 'nb-list-item' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

**please help me**

**Comment by nnixaa** [comment]
Hi @1benayatei, have you imported the `NbListModule` into the module where you use it? Also, what is your Nebular version?

**Comment by 1benayatei** [comment]
Hi @nnixaa , No, I have not done this. How can i add ? Nebular version : v2.0.0-rc.10

**Comment by agencia** [comment]
hi @1benayatei  , at module level add `import { NbListModule } from '@nebular/theme';` and then append NbListModule to the import list
`@NgModule({
  imports: [
    ThemeModule,
    NbListModule,
  `

**Comment by aefox** [comment]
@1benayatei  if you're using the `ngx-admin` template you can update `theme.module.ts` file to import the `NbListModule`. One thing to note in this particular case is that you will also have to update the `NB_MODULES` const to include the new module so it is loaded by angular. For extra details see [here](https://github.com/akveo/nebular/issues/657#issuecomment-415782425)

**Comment by naodwalk** [comment]
Hello! Using the ngx-admin template, even after adding NbListModule to my theme.module file, it doesn't seem to be able to import it. I get "cannot find name NbListModule". I'm running ngx-admin version 2.1.1. I'm a bit new to Angular, so my apologies in advance if I'm missing something obvious. I appreciate any help :) 

theme.module.ts:
`
const NB_MODULES = [
  NbCardModule,
  NbLayoutModule,
  NbTabsetModule,
  NbRouteTabsetModule,
  NbMenuModule,
  NbUserModule,
  NbActionsModule,
  NbSearchModule,
  NbSidebarModule,
  NbCheckboxModule,
  NbPopoverModule,
  NbContextMenuModule,
  NgbModule,
  NbSecurityModule, // *nbIsGranted directive
  NbListModule,
];
`
my-component.component.ts:
`
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NbCardModule, NbThemeModule, NbLayoutModule, NbListModule} from '@nebular/theme';
import { MyComponentComponent } from './my-component.component';

@NgModule({
  imports: [
    CommonModule,
    NbThemeModule,
    NbCardModule,
    NbLayoutModule,
    NbListModule
  ],
  declarations: [MyComponentComponent]
})
`

**Comment by tim6400** [comment]
I also get 'XXX/node_modules/@nebular/theme/index"' has no exported member 'NbListModule'.
running ngx-admin  "version": "2.3.0",

**Comment by nilsonsrjunior** [comment]
+1

**Comment by nnixaa** [comment]
Closing as it's been a while and seems addressed.

**Comment by Anjalipatil18** [comment]
while upgrading angular v11 to v12
Why not work nb-card and nb-card-footer?
my code
<nb-card class="tableListEdit col-12 p-0" status="danger">
    <nb-card-body>
        <div class="form-group row">
            <label class="col-md-5 col-form-label labelT font-weight-bold"
              >Total Subscribed Users:

            </label>
            <i
                class="nb-close iconClose ml-9"
                (click)="cancel()"
              ></i>
            <label class="col-md-8 col-form-label labelT">
                {{content.title}}
            </label>

            <label class="col-md-10 col-form-label labelT font-weight-bold">
                Select Another Plan To Migrate  All Subscribers:
            </label>
        </div>
        <br>
        <div class="p-3 mb-3 minHeight">
            <div class="subscriptioRadio">
                <label class="radio-label">FREE</label>
               <input  class="radio-input" style="margin-left:78%; cursor: pointer;" type="radio" name="test" value="yes" />
            </div>
           <br >
           <div class="subscriptioRadio">
               <label class="radio-label">$20.00</label>
               <input class="radio-input" style="margin-left:75%; cursor: pointer;" type="radio" name="test" value="yes" />
            </div>
        </div>
    </nb-card-body>
    <br>
    <nb-card-footer class="d-flex justify-content-center ">
        <button type="submit"
                nbButton
                size="small"
                status="info"
        >Migrate All Subsribers
        </button>
    </nb-card-footer>
  </nb-card>

getting this error
 error NG8001: 'nb-card-footer' is not a known element:
1. If 'nb-card-footer' is an Angular component, then verify that it is part of this module.
2. If 'nb-card-footer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

"@nebular/theme": "^8.0.0" upgrade nebular version for angular 12
- error NG8001: 'nb-card' is not a known element:
1. If 'nb-card' is an Angular component, then verify that it is part of this module.
2. If 'nb-card' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

anyone have solution above error?
