### ISSUE TITLE
How to get dynamic permissions for ACL from backend?

### ISSUE THREAD

**Issue by jesus-ibanez** [akveo/nebular#656]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [ ] feature request
* [X] Question

### Issue description

**Current behavior:**
How to get dynamic permissions for ACL from backend instead of static as below:

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
NbSecurityModule.forRoot({
     accessControl: {
       guest: {
         view: ['news', 'comments'],
       },
       user: {
         parent: 'guest',
         create: 'comments',
       },
       moderator: {
         parent: 'user',
         create: 'news',
         remove: '*',
       },
     },
   }),
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by pickonefish** [comment]
I think it could override [NbAclServic](https://github.com/akveo/nebular/blob/a4da28938a2dd633f19008bfa8d9298af45f867a/src/framework/security/services/acl.service.ts) and intercept NbAclServic in App module.

` { provide: NbAclService, useClass: AclBackendService }`

reference: [NbSecurityModule](https://github.com/akveo/nebular/blob/a4da28938a2dd633f19008bfa8d9298af45f867a/src/framework/security/security.module.ts)

**Comment by nnixaa** [comment]
Hey @jesus-ibanez, please check the following comment here https://github.com/akveo/ngx-admin/issues/1779#issuecomment-407459034. Hope this helps!

**Comment by tcbuzor** [comment]
Hi, do you have a sample code to show use of NbAclService.setAccessControl for dynamic privileges?

**Comment by jesus-ibanez** [comment]
Here you are:
```
permissions: NbAccessControl={};

this.authService.onTokenChange()
  .subscribe((token: NbAuthJWTToken) => {
    if (token.isValid()) {
      this.permissions=token.getPayload()['user']['permissions'];
      this.nbAclService.setAccessControl(this.permisos);
    }
  });
```

In my case, i get the permissions from token generated from my backend at path ['user']['permissions']. I set this after login and in the app.component in case of user refresh the browser.
I hope it helps

**Comment by jorgnv** [comment]
Could someone please give an example of how dynamic permissions are achieved

**Comment by Suroor-Ahmmad** [comment]
If anyone looking for the solution, I have used same logic what @jesus-ibanez suggested, inside AuthGuard `canActivate()` method

    canActivate() {
        return this.authService.isAuthenticated()
            .pipe(
                tap(async authenticated => {
                    this.authService.getToken().subscribe(
                        (token: NbAuthJWTToken) => {
                            if (token.isValid()) {
                                this.permissions = token.getPayload().permissions;
                                console.log(this.permissions);
                                this.nbAclService.setAccessControl(this.permissions);
                            }
                        }
                    );
                    if (!authenticated) {
                        this.router.navigate(['auth/login']);
                    }
                }),
            );
    }

**Comment by troddick** [comment]
I need to get accessControl from an api endpoint, as it is too large to return in the payload of the token. 
If I go the route of '{ provide: NbAclService, useClass: AclBackendService }' in my module, I am not sure what the AclBackendService should look like that extends NbAclService. 
Any help would be appreciated! Thanks
