### ISSUE TITLE
Support Angular 5?

### ISSUE THREAD

**Issue by SpiraMira** [akveo/nebular#67]
Any general timeline for a release that supports 5.x ?

**Comment by Tibing** [comment]
Hi @SpiraMira! We are in progress by haven't got the concrete milestone for now.

**Comment by SpiraMira** [comment]
Cool - I may start experimenting with porting some juicy modules like auth for my own purposes. Generally, do you foresee any particular difficulties or porting issues we should watch out for? 

The Angular 5 migration guide is a pretty good step by step approach - may get sticky with rxjs lettables and other services.

Regards.

**Comment by SpiraMira** [comment]
One more thing...do you have a roadmap?

**Comment by nnixaa** [comment]
let's track it there https://github.com/akveo/nebular/issues/108.
