### ISSUE TITLE
nb-news-post

### ISSUE THREAD

**Issue by Mrsbetter** [akveo/nebular#675]
NbInfiniteListDirective update has some trouble, if it is beacause of nb-news-post ,how to add this component?  Can I ask for more detail issue about NbInfiniteListDirective?

**Comment by nnixaa** [comment]
Hi @Mrsbetter, could you please post a complete example of what you are doing and what's not working? Thanks.

**Comment by Mrsbetter** [comment]
Angular6 + nebular2.0.0-rc.10： I want to reload when the list scrolls to the bottom，but it loads when the mouse rolls over，reload too many times

**Comment by Mrsbetter** [comment]
[threshold]="500"
 (bottomThreshold)="loadNext()"
The  [threshold] has no effect， and the  (bottomThreshold) has effect too many times when the mouse rolls over. I don/t know what happened and how to use this new Directive

**Comment by nnixaa** [comment]
@Mrsbetter could you push a reproducible example to https://stackblitz.com?

**Comment by Mrsbetter** [comment]
OK,  waiting some days , i use it  in my compony task, i will spent some time write a reproducible example and push it. Thank you! Have a good weekday
