### ISSUE TITLE
Automatic refresh token doesn't work for NbPasswordAuthStrategy

### ISSUE THREAD

**Issue by minextu** [akveo/nebular#677]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

When using the password strategy and the token has expired, no new http requests are going through, including the refresh request.

**Expected behavior:**

Token get's refreshed and requests get through.

**Steps to reproduce:**

Using the latest git version: 
1. setup auth using the password strategy
2. setup NbAuthJWTInterceptor and NB_AUTH_TOKEN_INTERCEPTOR_FILTER
3. login and let the token expire.

The token won't get refreshed and future http request won't do anything.

**Related code:**

When NbAuthJWTInterceptor intercepts a request while having an expired token, authService.refreshToken() gets called:
https://github.com/akveo/nebular/blob/22e39eb42cf5b66151f1cc907934bea40f7bf101/src/framework/auth/services/interceptors/jwt-interceptor.ts#L16-L19
https://github.com/akveo/nebular/blob/22e39eb42cf5b66151f1cc907934bea40f7bf101/src/framework/auth/services/auth.service.ts#L50-L55

authService.refreshToken() then calls refreshToken() for the appropriate strategy (password strategy in this case):
https://github.com/akveo/nebular/blob/22e39eb42cf5b66151f1cc907934bea40f7bf101/src/framework/auth/services/auth.service.ts#L190-L191
This will start a new refresh request:
https://github.com/akveo/nebular/blob/22e39eb42cf5b66151f1cc907934bea40f7bf101/src/framework/auth/strategies/password/password-strategy.ts#L304-L311

But this request will, by default, get intercepted by NbAuthJWTInterceptor, which again tries to refresh the token and that starts this loop all over.

### Other information:

**npm, node, OS, Browser**
```
Node 6.1.0, npm 6.1.0
OS: Windows 10
Browser: Chrome
```

**Angular, Nebular**
```
nebular: git build (commit 22e39eb42cf5b66151f1cc907934bea40f7bf101)
angular: 6.1.2
```

**Comment by alain-charles** [comment]
@minextu , can you verify that your refreshToken endpoint url matches at least one url in the list of urls the NbAuthJWTInterceptor must not inject the `Bearer` Authorization Header ? 
=> All urls that must not be injected a token in their Authorization Header **must** be listed in the filter function referenced by  NB_AUTH_TOKEN_INTERCEPTOR_FILTER so that the filter returns `true` for them.

Does your function filter return `true` for your refresh token endpoint url ?

**Comment by minextu** [comment]
The refreshToken endpoint was not listed in filter. I thought the refresh request was suppose to be intercepted. It's working now, thanks!
