### ISSUE TITLE
help with login

### ISSUE THREAD

**Issue by joeyjin** [akveo/nebular#680]
Hi,
Thanks in advanced!
I am new for the ngx-admin and I tried to do authenticate with my own service. I can see it hit my service (http://localhost:4201/api/auth/login) when I login. But it always can not login(error message: Oh snap!
Something went wrong.) even if the service return true...What's the problem? Many thanks!

NbPasswordAuthStrategy.setup({
name: 'email',
baseEndpoint: 'http://localhost:4201/api',
login: {
alwaysFail: false,
rememberMe: true,
method: 'post',
endpoint: '/auth/login',
redirect: {
success: '/',
failure: null,
},
defaultErrors: ['Email/Password combination is not correct, please try again.'],
defaultMessages: ['You have been successfully logged in.'],
},

**Comment by joeyjin** [comment]
@Prefix1802, @nnixaa 
Please help!!! waiting on line....

1. I added this section:  token: {
          key: 'token',
        },
2. also in my service return json return with token:
[HttpPost]
        [Route("api/auth/login")]
        public JsonResult login([FromBody]dynamic value)
        {
            var l = Json(_AuthRepository.login((string)value.email, (string)value.password));
            return l;
        }
3. but I still can not login with err:
main.1cb3c98aee5a997429e5.js:1 NbEmailPassAuthProvider:
                          Token is not provided under 'token' key
                          with getter 'function(t,e,n){return I(e.body,n.token.key)}', check your auth configuration


NbPasswordAuthStrategy.setup({
        name: 'email',
        baseEndpoint: 'http://localhost:4201/api',
        token: {
          key: 'token',
        },
         login: {
                alwaysFail: false,
                rememberMe: true,
                method: 'post',
                endpoint: '/auth/login',
                 redirect: {
                  success: '/',
                  failure: null,
                },
                defaultErrors: ['Email/Password combination is not correct, please try again.'],
                defaultMessages: ['You have been successfully logged in.'],
         },
         register: {
           // ...
           endpoint: '/api/auth/register',
         },
      }),

**Comment by joeyjin** [comment]
sorry...problem solved. json format is { token: 'some-jwt-token' }

**Comment by Prefix1802** [comment]
@joeyjin 

What does the response from your api look like? Can you post it?

**Comment by joeyjin** [comment]
![image](https://user-images.githubusercontent.com/6452468/44734877-94126680-aab0-11e8-8770-fb722b92e596.png)

**Comment by joeyjin** [comment]
another question: how can I pass  environment.baseUrl to this instead of hard coding there
this.baseUrl = environment.baseUrl;
BUT comment out has complied error
NbPasswordAuthStrategy.setup({
        name: 'email',
        baseEndpoint: 'http://localhost:4201/api',
     //baseEndpoint: this.baseUrl,

**Comment by Prefix1802** [comment]
@joeyjin 

Read about Constants here:
https://www.code-sample.com/2018/04/angular-5-constant-and-global-variables.html

#69

**Comment by joeyjin** [comment]
@Prefix1802 , @nnixaa 

why my login fail message is Oh snap! Something went wrong. while my setting is like this and it should be like "mail/Password combination is not correct, please try again". where did  i do wrong? please help!
 login: {
                alwaysFail: false,
                rememberMe: true,
                 method: 'post',
                endpoint: '/auth/login',
                redirect: {
                success: '/',
                failure: null,
                },
                
                defaultErrors: ['Email/Password combination is not correct, please try again.'],
                defaultMessages: ['You have been successfully logged in.'],
         },

**Comment by Prefix1802** [comment]
@joeyjin 

When your api login gets called do you get a 200 response back?

like this:

![afbeelding](https://user-images.githubusercontent.com/40199655/44834951-dc599200-ac32-11e8-87d2-325a25174b3b.png)

**Comment by joeyjin** [comment]
@Prefix1802 
yes. like this when I put wrong pw
![image](https://user-images.githubusercontent.com/6452468/44857218-ed0b0780-ac34-11e8-8fb8-2aa635ab49e6.png)

**Comment by joeyjin** [comment]
solved...need to return status code in api!
if (nt.token.Equals("invalid token"))
                this.HttpContext.Response.StatusCode = 401; 
            else
                this.HttpContext.Response.StatusCode = 200;
