### ISSUE TITLE
Calendar example: full calendar day select issue

### ISSUE THREAD

**Issue by artyorsh** [akveo/nebular#689]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Calendar displays duplicated months, which provides additional selection issues.
See on screenshot:
![image](https://user-images.githubusercontent.com/10753921/44900813-4b57e900-ad0e-11e8-9155-88d1ea2e089d.png)

**Comment by aefox** [comment]
This is an old issue and I don't see it reproducing on the latest ngx-admin version (3.1.0). I think this can be closed
