### ISSUE TITLE
Authorization is not working

### ISSUE THREAD

**Issue by nameisvick** [akveo/nebular#69]
hello i have followed  the procedures using this https://akveo.github.io/nebular/#/docs/auth/introduction                      

here is my code 
 app.module

 providers: {
        email: {
          service: NbEmailPassAuthProvider,
          config: {
            baseEndpoint: GlobalVariable.BASE_API_URL_LDAP+'api/InspectionService/PostLoginDetails',
            login: {
             // endpoint: GlobalVariable.BASE_API_URL_LDAP+ 'api/InspectionService/PostLoginDetails/sign-in',
             endpoint: '/api/auth/login',
              method: 'post',
            //  SetRequestHeader:(),
              redirect: {
                success: '/pages',
                failure: null,
              },
            //  setRequestHeader(ContentType:"application/json"){

              }
            },
           
      /*      token: {
            key: 'data.token',
            getter: (module: string, res: HttpModule) => getDeepFromObject(res.body,
             this.getConfigValue('token.key')),
            },*/
          },
        },
      
      forms: {
        login: {
          redirectDelay: 0,
          showMessages: {
            success: true,
          },
        },
        register: {
          redirectDelay: 0,
          showMessages: {
            success: true,
          },
        },
        requestPassword: {
          redirectDelay: 0,
          showMessages: {
            success: true,
          },
        },
        resetPassword: {
          redirectDelay: 0,
          showMessages: {
            success: true,
          },
        },
        logout: {
          redirectDelay: 0,
        },
      },
    }), 

    NgbModule.forRoot(),
    ThemeModule.forRoot(),
    CoreModule.forRoot(),
  ],
  bootstrap: [AppComponent],
  providers: [
    AuthGuard,
    { provide: APP_BASE_HREF, useValue: '/' },
    { provide: NB_AUTH_TOKEN_WRAPPER_TOKEN, useClass: NbAuthJWTToken },
    
  ],
})

my auth-guard-service.ts

import { Injectable } from '@angular/core';
import { CanActivate, Router } from '@angular/router';
import { NbAuthService } from '@nebular/auth';

@Injectable()
export class AuthGuard implements CanActivate {

  constructor(private authService: NbAuthService, private router: Router) {
  }

  canActivate() {
    return this.authService.isAuthenticated()
      .do(authenticated => {
        if (!authenticated) {
          this.router.navigate(['auth/login']);
        }
      });
  }
}

i have no issues while compiling nor in the console but it is NOT passing to next dashboard while giving the correct credentials .. i guess there is no passing of request headers is root cause of error .. can any 1 help me  @nnixaa  can you please help me with this

**Comment by nameisvick** [comment]
@blankstar85  thank you for your response  yet my problem is unsolved 
i've altered my code as you said yet i cannot resolve it . 
`providers: {
        email: {
          service: NbEmailPassAuthProvider,
          config: {
            baseEndpoint: GlobalVariable.BASE_API_URL_LDAP+'api/InspectionService/PostLoginDetails',
            login: {
              endpoint: GlobalVariable.BASE_API_URL_LDAP+ 'api/InspectionService/PostLoginDetails/login',
              method: 'post',
             
              redirect: {
                success: 'app/pages/pages.module#PagesModule',
                failure: null,
              },
             /* token: {
                key: 'Basic YmljczpCaWN0OHo5',
                getter: (module: string, res: HttpResponse<Object>) => getDeepFromObject(res.body,
                 this.getConfigValue('Basic YmljczpCaWN0OHo5')),
              },*/
              
                success: true,
                data: {
                     token: 'tokenfdjklabjkalbjkle'
                   },`
Can you please tell me where i went wrong ...

**Comment by blankstar85** [comment]
The json in my post is what your Backend Server should be returning to the front end. It shouldn't be in the provider.  What are you using for your Backend api?

**Comment by nameisvick** [comment]
it is a .net api  ... 

> " The json in my post is what your Backend Server should be returning to the front end. It shouldn't be in the provider."

   By backend server what do you mean ? By json are referring to API ? where else it should be ? can you please provide some kinda snippets that where i need to pass what  and help me in this

**Comment by nnixaa** [comment]
Hi @nameisvick, kindly provide a complete reproducible example preferably posted on plunker. Also, provide the details on what your API returns for each API method you use. Only this way one can debug and help you out, otherwise it's barely possible and I don't think anyone has much time for guessing. Help us to help you :)

**Comment by rajsanil** [comment]
After Following each steps from document getting error "Oh snap!
Login/Email combination is not correct, please try again.". kindly provide the complete code to implement auth. Thank and regards Rajesh sanil

**Comment by nnixaa** [comment]
Can we consider this as resolved?

**Comment by nsankaranarayanan** [comment]
I configured everything and by json is returning the below. I get "Hooray! You have been successfully logged in.". But the login page does not redirect to the dashboard.

My JSON from the authentication API (I am still testing.). 
{"token":"Hello World"}
