### ISSUE TITLE
`OnItemClick` stored in `ReplaySubject` cause logout right after login 

### ISSUE THREAD

**Issue by thom7kick** [akveo/nebular#695]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
@nnixaa I am subscribing to `onItemClick` then logout from the logout menu item is selected.
```
this.menuService.onItemClick()
    .pipe(takeUntil(this.ngUnsubscribe))
    .subscribe(item => {
      if (item.item.title === this.logoutMenuItem.title) {
        this.logout();
      }
    });
```
it successfully logs but on login again the `onItemClick` is triggered therefore logs out 
user immediately. That's because from the code the clicked items are stored in `ReplaySubject`
``` 
const itemClick$ = new ReplaySubject<NbMenuBag>(1);
```

**Expected behavior:**
i want on logout the `ReplaySubject` cache to be cleared out.

**Steps to reproduce:**
May be add an option to pass a null value as the last clicked item, so that the user has
an option to pass null menu item. so when the subscription picks up the replay it won't do anything. 

**Related code:**

### Other information:
**Angular, Nebular**
```
    "@nebular/theme": "^2.0.0-rc.9"
```

**Comment by thom7kick** [comment]
my solution is to ignore replay with out user interaction
```
 private contentInit = false;

ngAfterContentInit() {
    this.contentInit = true;
  }

// trigger logout
    this.menuService.onItemClick()
    .pipe(takeUntil(this.ngUnsubscribe))
    .subscribe(item => {
      if (item.item.title === this.logoutMenuItem.title && this.contentInit === true) {
        this.logout();
      }
    });
```
i hope it helps someone.

**Comment by pdelorme** [comment]
I had the exact same problem.
Your solution is fixing it. Thanks !
However, this should be left as a open bug since onItemClick() doesnt behave as expected.

**Comment by chris7716** [comment]
@thom7kick could you plz provide me some more detailed explanation of the solution :/
