### ISSUE TITLE
Any soloution?

### ISSUE THREAD

**Issue by malikfaizanhaider** [akveo/nebular#70]
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2017-11-14T22:03:20.426Z
Hash: e68607157a9f05504c59
Time: 14095ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 2.93 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 636 bytes [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 1.21 MB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 852 kB [initial] [rendered]

ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/app/@theme/styles/styles.scss
Module build failed:
@import '../../@spagobi/auth/styles/all';
^
      File to import not found or unreadable: ../../@spagobi/auth/styles/all.
Parent style sheet: stdin
      in I:\ng-spagobi\src\app\@theme\styles\styles.scss (line 6, column 1)
Error:
@import '../../@spagobi/auth/styles/all';
^
      File to import not found or unreadable: ../../@spagobi/auth/styles/all.
Parent style sheet: stdin
      in I:\ng-spagobi\src\app\@theme\styles\styles.scss (line 6, column 1)
    at options.error (I:\ng-spagobi\node_modules\node-sass\lib\index.js:291:26)
 @ ./src/app/@theme/styles/styles.scss 4:14-214
 @ multi ./node_modules/bootstrap/dist/css/bootstrap.css ./node_modules/typeface-exo/index.css ./node_modules/roboto-fontface/css/roboto/roboto-fontface.css ./node_modules/ionicons/scss/ionicons.scss ./node_modules/font-awesome/scss/font-awesome.scss ./node_modules/nebular-icons/scss/nebular-icons.scss ./node_modules/socicon/css/socicon.css ./node_modules/pace-js/templates/pace-theme-flash.tmpl.css ./src/app/@theme/styles/styles.scss
ERROR in src/app/@spagobi/theme/components/menu/menu.service.ts(128,5): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<{ tag: string; item: NbMenuItem; }>'.
  Type '{}' is not assignable to type '{ tag: string; item: NbMenuItem; }'.
    Property 'tag' is missing in type '{}'.
src/app/@spagobi/theme/components/menu/menu.service.ts(132,5): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<{ tag: string; item: NbMenuItem; }>'.
  Type '{}' is not assignable to type '{ tag: string; item: NbMenuItem; }'.
    Property 'tag' is missing in type '{}'.
src/app/@spagobi/theme/components/menu/menu.service.ts(136,5): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<{ tag: string; item: NbMenuItem; }>'.
  Type '{}' is not assignable to type '{ tag: string; item: NbMenuItem; }'.
    Property 'tag' is missing in type '{}'.
src/app/@spagobi/theme/components/menu/menu.service.ts(140,5): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<{ tag: string; item: NbMenuItem; }>'.
  Type '{}' is not assignable to type '{ tag: string; item: NbMenuItem; }'.
    Property 'tag' is missing in type '{}'.
src/app/@spagobi/theme/components/menu/menu.service.ts(170,5): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<{ tag: string; items: NbMenuItem[]; }>'.
  Type '{}' is not assignable to type '{ tag: string; items: NbMenuItem[]; }'.
    Property 'tag' is missing in type '{}'.
src/app/@spagobi/theme/components/menu/menu.service.ts(174,5): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<{ tag: string; }>'.
  Type '{}' is not assignable to type '{ tag: string; }'.
    Property 'tag' is missing in type '{}'.
src/app/@spagobi/theme/components/menu/menu.service.ts(178,5): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<{ tag: string; listener: BehaviorSubject<{ tag: string; item: NbMenuItem; }>; }>'.
  Type '{}' is not assignable to type '{ tag: string; listener: BehaviorSubject<{ tag: string; item: NbMenuItem; }>; }'.
    Property 'tag' is missing in type '{}'.
src/app/@spagobi/theme/components/search/search.service.ts(53,5): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<{ searchType: string; tag?: string; }>'.
  Type '{}' is not assignable to type '{ searchType: string; tag?: string; }'.
    Property 'searchType' is missing in type '{}'.
src/app/@spagobi/theme/components/search/search.service.ts(61,5): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<{ searchType: string; tag?: string; }>'.
  Type '{}' is not assignable to type '{ searchType: string; tag?: string; }'.
    Property 'searchType' is missing in type '{}'.
src/app/@spagobi/theme/components/search/search.service.ts(69,5): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<{ term: string; tag?: string; }>'.
  Type '{}' is not assignable to type '{ term: string; tag?: string; }'.
    Property 'term' is missing in type '{}'.
src/app/@spagobi/theme/components/sidebar/sidebar.service.ts(30,5): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<{ compact: boolean; tag: string; }>'.
  Type '{}' is not assignable to type '{ compact: boolean; tag: string; }'.
    Property 'compact' is missing in type '{}'.
src/app/@spagobi/theme/components/sidebar/sidebar.service.ts(38,5): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<{ tag: string; }>'.
  Type '{}' is not assignable to type '{ tag: string; }'.
    Property 'tag' is missing in type '{}'.
src/app/@spagobi/theme/components/sidebar/sidebar.service.ts(46,5): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<{ tag: string; }>'.
  Type '{}' is not assignable to type '{ tag: string; }'.
    Property 'tag' is missing in type '{}'.
src/app/@spagobi/theme/services/theme.service.ts(92,5): error TS2322: Type 'Observable<NbMediaBreakpoint[]>' is not assignable to type 'Observable<[NbMediaBreakpoint, NbMediaBreakpoint]>'.
  Type 'NbMediaBreakpoint[]' is not assignable to type '[NbMediaBreakpoint, NbMediaBreakpoint]'.
    Property '0' is missing in type 'NbMediaBreakpoint[]'.

**Comment by nnixaa** [comment]
@blankstar85 thanks for your reply. @malikfaizanhaider kindly open more descriptive issues so that someone can help you. Closing for now.
