### ISSUE TITLE
Updating project built off of previous ngx-admin example to updated UI. 

### ISSUE THREAD

**Issue by stubbsy345** [akveo/nebular#705]
Hi I know this issues panel is not intended for guidance but I noticed it's okay to tag as help wanted. If this is the incorrect location please direct me to the correct place to ask. 

Me and some colleagues were building a project using the nebular framework, which we love by the way. We used an old version of ngx-admin as a starting point, i believe version 2.2.0.  I imagine this was probably pulled around 6 months ago, maybe less. I recently started to develop some components on a more recent pull of ngx-admin 2.3.0. The most recent demo project has had a lot of improvements made to UI components in the theme. 

We have now merged our two projects, but the UI is that of the previous version. I have tried to update to the most recent styles by updating all dependencies including nebular. However, the UI has remained the same. I am a little unsure about which files to use in order to update the project to most recent styles. Any guidance you could give me on this would be very appreciated. 

Thanks!

**Comment by nnixaa** [comment]
Hi @stubbsy345, can you please post some of the examples? Have you followed the `CHANGELOG.md` for the details regarding breaking changes?

**Comment by stubbsy345** [comment]
Sorry thanks I figured it out, I was just missing some of the adapted files within the @theme folder itself. With regards to the nb-chat feature, is that found within the current nebular package or is that external? It doesn't seem to be recognised when I am trying to implement currently, but recognises all other nebular components?

**Comment by stubbsy345** [comment]
Can be deleted! Was missing scss values from @theme file in new ui.
