### ISSUE TITLE
directive nbButton not working

### ISSUE THREAD

**Issue by Riderxyz** [akveo/nebular#709]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**

The "nbButton" directive is not working correctly. Try to change the color of the button, size, indicate whether it is Hero type or not or even put it as Full width. Nothing works except the default primary button

**Expected behavior:**

change the buttons color, size and etc.

**Steps to reproduce:**

Take the site installation step-by-step
Then run the application with ng serve
After that, insert the nb-layout in the app.component.html and then the buttons with the nbButton directive.
So far, everything works.
Now add some directive. Be it size, color (in this case is status) or any other. It just does not work.
**Related code:**

<button nbButton status="info">Info</button>

If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

A sample application via GitHub

```
insert short code snippets here
```

### Other information:
NPM:6.4.0
Node:8.9.4
Browser: i'm using Chrome
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by nnixaa** [comment]
Hi @Riderxyz, can you please post a complete example?

**Comment by devKid88** [comment]
@Riderxyz  check if there is NbButtonModule imported in module where you use buttons

**Comment by Riderxyz** [comment]
@nnixaa sure man. Here it is:

<button nbButton hero status="warning">Primary</button>

or any other status. It simply does not work

**Comment by Riderxyz** [comment]
@devKid88 there is a module for this? There's nothing saying about a nbButtonModule in the website.

**Comment by nnixaa** [comment]
Fixed.
