### ISSUE TITLE
Remote user picture blob url

### ISSUE THREAD

**Issue by ohgasauraus** [akveo/nebular#73]
Hi, our user pictures are stored remotely and i can't seem to use it with the &lt;nb-user&gt; component.

I am getting this warning message as follow and the picture is not shown:
WARNING: sanitizing unsafe style value url(SafeValue must use [property]=binding: blob:http://localhost:4200/30dcca0e-0630-4769-accf-4c6d72aaf61d (see http://g.co/ng/security#xss)) (see http://g.co/ng/security#xss)

My file download code as follows:
`this.file.fileDownload(user.id).subscribe(res => {`
&nbsp;&nbsp;`var blob = res.blob();`
&nbsp;&nbsp;`var url = window.URL.createObjectURL(blob);`
&nbsp;&nbsp;`this.img = this.sanitizer.bypassSecurityTrustUrl(url);`
`})`

`<nb-user [name]="name" [picture]="img"></nb-user>`

Isn't &lt;nb-user&gt; picture property already using property binding as stated in the warning message?
Is this a bug with the &lt;nb-user&gt; component?

**Comment by nnixaa** [comment]
Hi @ohgasauraus, as per documentation it is only possible to specify an absolute path or URL to your image.

**Comment by ohgasauraus** [comment]
Oh, didn't notice that. 
Before this, I was using from using ng2-admin and I was able to use this method to load the user picture. 
Will this be considered as future feature enhancement?

**Comment by nnixaa** [comment]
Fixed in https://github.com/akveo/nebular/pull/238
