### ISSUE TITLE
Logout sending token

### ISSUE THREAD

**Issue by traptz** [akveo/nebular#733]
### Issue type

**I'm submitting a ...** 

* [ ] bug report
* [X] feature request

### Issue description
I'm using loopback as REST api, using the default User login/logout. The login setting is working normally, but the logout demands to pass a variable "access_token", if not I got a 401, not authorized from the api.
I'm trying to send the token when calling '/auth/logout', but I don't really know how. Does it need to create/modify a strategy?
I'm using NbPasswordAuthStrategy with NbAuthSimpleToken.

Installed from ngx-admin and copied the components from auth.

**Current behavior:**
It doesnt send the token on logout.

**Expected behavior:**
Send the token on logout url as configured.

**Steps to reproduce:**

**Related code:**
app.module.ts:
```
NbAuthModule.forRoot({
            strategies: [
                NbPasswordAuthStrategy.setup({
                    name: 'email',

                    token: {
                        class: NbAuthSimpleToken,
                        key: 'id',
                    },

                    baseEndpoint: '/',
                     login: {
                        endpoint: 'api/Users/login',
                        method: 'post',
                     },
                     logout: {
                        endpoint: 'api/Users/logout',
                        method: 'post',
                        redirect: {
                            success: '/auth/login',
                            failure: '/',
                        },
                    },
                }),
            ],
            forms: {},
        }),
```
header.component.ts:
```
userMenu = [
                      { title: 'Profile' },
                      {
                          title: 'Log out', link: '/auth/logout',
                      },
                  ];
```
### Other information:

**npm, node, OS, Browser**
```
Node Version: v10.9.0
NPM Version: 6.4.1
OS: Centos 7
Browser: Chrome
```

**Angular, Nebular**
```
Angular: 6.0.0
Nebular: 2.0.0-rc.10
```

**Comment by nnixaa** [comment]
Hi @traptz, I believe you can make a use of Angular HTTP interceptors. An interceptor allows you to `intercept` a request adding additional or customizing the information.

**Comment by traptz** [comment]
Yeah, I guess I figured it out trying...
found the solution in #1375 of ngx-admin project.
Thanks

**Comment by nnixaa** [comment]
Glad to hear!
