### ISSUE TITLE
nothing being displayed

### ISSUE THREAD

**Issue by SharmaVishal94** [akveo/nebular#74]
i cloned nebular theme and  installed dependencies but after then i get this 
![localhost_4200_](https://user-images.githubusercontent.com/20662514/32876256-04122d64-cac2-11e7-8308-c454b44b7161.png)

**Comment by nnixaa** [comment]
Hi @SharmaVishal94, make sure you followed correct installation guide and first of all cloned the right repo :)
https://akveo.github.io/nebular/#/docs/installation/based-on-starter-kit-ngxadmin
