### ISSUE TITLE
Two menus like before authentication and after authentication not replacing

### ISSUE THREAD

**Issue by PrabakarKaruppasamy** [akveo/nebular#741]
Hi All,
I have one project with the combination of Angular 5 and Nebular. The project is developing from scratch not took clone as ngx-admin.

I have the header and menu items in app.component.html like as below.

```
</nb-layout-header>

<nb-sidebar>
    <div>
            <nb-menu  [items]="MENU_ITEMS">
                </nb-menu>
    </div>
    
</nb-sidebar>

<nb-layout-column>
 <router-outlet></router-outlet>
    
      </nb-layout-column>

```

Menu items are described in app.component.ts as below.

```
import { Component } from '@angular/core';
import { NbMenuItem } from '@nebular/theme';
@component({
selector: 'app-root',
templateUrl: './app.component.html',
styleUrls: ['./app.component.css']
})
export class AppComponent {
title = 'app';

public authFlag:boolean = false;

public loginFlag:Boolean = false;

MENU_ITEMS:NbMenuItem[] = [
{
title: 'About',
icon: 'fa fa-home',
link: '/home',
home: true,
},
{
title: 'Help',
icon: 'fa fa-info-circle',
link: '/dashboard',
},
{
title: 'SignIn',
icon: 'fa fa-unlock-alt',
link: '/login',
},
];
}
```

I would like to change the menu after sucessful login. If i give in loginsucess.component.ts it is not working. It is not replacing the new menu items.

Thanks in Advance.

**Comment by yggg** [comment]
Hi @PrabakarKaruppasamy. It's not clear how are you trying to change `MENU_ITEMS` from the code you posted. Could you please provide an example on [stackblitz](https://stackblitz.com/)? 

Here is a small [example](https://stackblitz.com/edit/nebular-741?file=src%2Fapp%2Flayout.component.ts) of changing menu based on authentication state. Use any random email and password to log in.

**Comment by nnixaa** [comment]
Closing as it's been a while.
