### ISSUE TITLE
Previously active menu is selected even after logging out and logged back in

### ISSUE THREAD

**Issue by chris7716** [akveo/nebular#744]
I have been using a customised auth component in ngx-admin. The login and log out functions work quite well but the issue that I am facing right now is that the previously active menu is selected even after I log out and log back in. Is there any particular way that I can use NbMenuService to dis-select the current menu item when logging out?

**Comment by nnixaa** [comment]
Fixed

**Comment by chris7716** [comment]
How could I find the solution plz
