### ISSUE TITLE
ACL parent 

### ISSUE THREAD

**Issue by prasadprabha** [akveo/nebular#747]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [ ] feature request

### Issue description

**Current behavior:**

In my ACL configuration (see below) , "guest" role has view permission for dashboard. However even though I logged in with "normal" role , I am not able to see the userMenu. 

 
**Expected behavior:**
I must see the userMenu , if I logged in with role "normal" (Since it is inheriting from the guest role)

**Steps to reproduce:**

**Related code:**
 NbSecurityModule.forRoot({
      accessControl: {
        guest: {
          view: ['dashboard'],
        },
        normal: {
          parent: 'guest',
          view : ['mytickets','user'],
          create: ['ticket']
        },
        lead: {
          parent: 'normal',
          view : ['leadsdashboard'],
          create: ['approval'],
          remove: '*',
        },
      },
    }),

  <nb-action *nbIsGranted="['view', 'dashboard']" >
      <nb-user [nbContextMenu]="userMenu" [name]="user?.name" [picture]="user?.picture"></nb-user>
    </nb-action>

**npm, node, OS, Browser**

here is my package.json

 "@angular/animations": "^6.0.0",
    "@angular/cdk": "^6.4.6",
    "@angular/common": "6.0.0",
    "@angular/compiler": "6.0.0",
    "@angular/core": "6.0.0",
    "@angular/forms": "6.0.0",
    "@angular/http": "6.0.0",
    "@angular/material": "^6.4.6",
    "@angular/platform-browser": "6.0.0",
    "@angular/platform-browser-dynamic": "6.0.0",
    "@angular/router": "6.0.0",
    "@nebular/auth": "2.0.0-rc.9",
    "@nebular/security": "2.0.0-rc.9",
    "@nebular/theme": "2.0.0-rc.9",

**Comment by nnixaa** [comment]
Hi @prasadprabha, could you post a complete example including the role provider?

**Comment by prasadprabha** [comment]
Here is my custom role provider

@Injectable()
export class RoleProvider implements NbRoleProvider {
 
    constructor(private authService: NbAuthService) {
    }
 
    getRole(): Observable<string> {
      return this.authService.onTokenChange()
        .pipe(
          map((token: NbAuthJWTToken) => {
            let user : User = token.getPayload();
            let role : string = token.isValid() ? user.roles[0] : 'guest';
       //    let role : string = 'normal';
            return role;
          }),
        );
    }
}

**Comment by prasadprabha** [comment]
This is sorted out. As per the nebular configuration NgSecurity Module configuration must be done in app.module.ts . However this since I was using ngx-admin, this has already been done in Coremodule.ts. which I was not aware of. So there was a conflict between these two.

**Comment by nnixaa** [comment]
Ah I see! Glad it worked out.
