### ISSUE TITLE
Angular 5 http request failed

### ISSUE THREAD

**Issue by sayeko** [akveo/nebular#76]
Sending simple login request with email provider I encounter with this error.

"You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable."

I'm using angular 5
angular http 5

**Comment by blankstar85** [comment]
This project is based on angular 4.x, but i don't see why angular 5 wouldn't exactly work. All of that aside, you won't get any help if you don't post any more useful information like code etc that is generating your issue. ( aka we need more details...)
