### ISSUE TITLE
Non-Angular version

### ISSUE THREAD

**Issue by Meldiron** [akveo/nebular#77]
Hello, Is there a pure CSS/JS version? Or just CSS, Im new to Angular and I would like to have pure CSS/JS version.

**Comment by blankstar85** [comment]
the final product of angular is CSS/JS. However it uses typescript and nodejs to create all the files an manage the dependencies on the project as well as generate the final files. There are plenty of tutorials on the web that can get you started.

**Comment by lugovsky** [comment]
Hello @Meldiron, as @blankstar85 explained, we will support development only in TypeScript.

Though I guess you can build scss and use only css from @nebular/theme Though we can't advise you here, as we haven't been using it this way.
