### ISSUE TITLE
Not getting AuthJwt

### ISSUE THREAD

**Issue by sayeko** [akveo/nebular#79]
Getting always string of token instead of AuthJWT object.

**Comment by blankstar85** [comment]
@sayeko Similar to your other issue, you should provide more details of what is going on.... The owners created documentation to help you get started. Specifically the authentication docs are here: [https://akveo.github.io/nebular/#/docs/auth/introduction](url)

**Comment by sayeko** [comment]
@blankstar85 Ok, there is no much to show details I basically use the authentication module without modification I set AuthJWTToken in all the generic methods but getting the SimpleToken for some reason.

And your link not exist.

**Comment by sayeko** [comment]
Anyway my AuthJWTToken is calling but in the code it set setValue go to the base SimpleToken and then what Im only getting string token.

**Comment by blankstar85** [comment]
@sayeko, fixed the url, take a look.

**Comment by nnixaa** [comment]
Hi @sayeko, have you resolved the issue? Let us know if this is still the case.

**Comment by nnixaa** [comment]
Closing due to no updates.
