### ISSUE TITLE
plan for other component

### ISSUE THREAD

**Issue by labyed** [akveo/nebular#8]
when using ng2-admin, i find it so difficult to add external component and adapt there css to the theme, and i find that nebular contains the same components, so we'll face the same problems :S

**Comment by nnixaa** [comment]
Hey @labyed, thanks for your response. Would you mind sharing more details on the issues you faced with the styling of your components?

**Comment by labyed** [comment]
Hi @nnixaa , 
Actually, it's not a problem of ng2-admin but it's a problem with external components, in need, I tried to use, for example a calendar or a typeahead, that don't fit with the style, so I had to modify the external component itself, which lead to us to spend more time in design, and not business. 
I think, that it will be great to add missing components from blur-admin, so like that we have more choices for the UI, so like that we use less external components.
thanks for your efforts.

**Comment by nnixaa** [comment]
Right, I see your point, this, of course, makes sense. Could you share your list of essential components?

**Comment by nnixaa** [comment]
Closing for now.

**Comment by codex-corp** [comment]
@nnixaa 
Are you interested in fullcalendar?  I will be glad for provide a PR.

![image](https://user-images.githubusercontent.com/775654/32400356-a4183584-c107-11e7-9d9a-1d5ca12430ed.png)

**Comment by nnixaa** [comment]
Hey @codex-corp, looks great! I guess the community would be happy to have it, so looking forward to your PR!

**Comment by codex-corp** [comment]
@nnixaa done.
