### ISSUE TITLE
I am using nebular 2.0.0-rc.3 and like to upgrade it to 2.0.0-rc.10, is there any link that explains the steps to be followed

### ISSUE THREAD

**Issue by drchaks83** [akveo/nebular#825]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [ ] feature request

### Issue description

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by nnixaa** [comment]
Closing as it's been a while and seems addressed.
