### ISSUE TITLE
Incorrect document for installation of styles

### ISSUE THREAD

**Issue by enriqueflavio** [akveo/nebular#833]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ X ] bug report
* [ ] feature request

### Issue description

**Current behavior:**

In the documentation it is explained to put the styles files in the file angular.json, but that does not work, it says that it is not possible to find the module.
I was able to resolve this problem by importing the files into the style.css or style.scss file at the root of the project.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by nnixaa** [comment]
Should be fixed now.
