### ISSUE TITLE
Angular 6 library compile error: Directive NbContextMenuDirective, Expected 0 arguments, but got 1

### ISSUE THREAD

**Issue by arabbani** [akveo/nebular#835]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
**I'm using upto date master branch of nebular.**

Can't compile angular 6 library using NbContextMenuDirective got the error :
projects/demo/src/lib/demo.component.ts.DemoComponent.html(4,7): : Directive NbContextMenuDirective, Expected 0 arguments, but got 1.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
node --version
v8.10.0

npm --version
6.2.0
```

**Angular, Nebular**
```
"@angular/core": "^6.1.0",
"@nebular/theme": "^2.0.0-rc.10",
```

**Comment by nnixaa** [comment]
Closing as a duplicated of https://github.com/akveo/nebular/issues/635

**Comment by arabbani** [comment]
But the error is not fixed in master branch. I've tested with with master branch
