### ISSUE TITLE
NbToastrService: Notifications can't be closed in Firefox and Internet Explorer

### ISSUE THREAD

**Issue by minextu** [akveo/nebular#865]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

Notifications created using NbToastrService won't hide in Firefox and Internet Explorer 11.
It's working fine in Chrome.

**Expected behavior:**

The notification closes when you click on it or the timeout expires.

**Steps to reproduce:**

Show a notification using NbToasterService with default options in Firefox or Internet Explorer 11 and try to close it.

Can also be reproduced in the documentation: https://akveo.github.io/nebular/example/toastr/toastr-showcase.component

### Other information:

**Browser**
```
Browser: Firefox 62, Internet Explorer 11
```

**Nebular**
```
nebular: 2.0.1
```

**Comment by Tibing** [comment]
Hi all, the bug has to be resolved after the PR will be merged. If it will not work properly try to uncomment `// import 'web-animations-js';.` in your `polyfills.ts`

**Comment by codinronan** [comment]
@Tibing any way this can be merged into the 2.x version as 2.0.3 or something? I would like to incorporate this fix but can't upgrade to Angular 7 for now...
