### ISSUE TITLE
NbAuth - how to handle OAuth2 provider error callback

### ISSUE THREAD

**Issue by jjgriff93** [akveo/nebular#872]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [X] feature request

### Issue description

**Current behavior:**
Me again :) I have Azure AD B2C set up and mostly working well as the auth provider - one thing I can't see how to configure in Nebular auth is how to handle an error callback gracefully. If a user clicks cancel in Azure AD B2C's log in section, it will callback to the application with an error ID in a fragment like so:

https://localhost:5001/auth/callback#error=access_denied&error_description=AADB2C90091:+The+user+has+cancelled+entering+self-asserted+information.%0D%0ACorrelation+ID:+e629538e-584c-4854-8f63-f6e2f254a883%0D%0ATimestamp:+2018-10-08+12:38:22Z%0D%0A

There's no configuration steps in the auth strategy itself I can see to tell Nebular how to handle this, so I had a go at implementing a re-routing in the callback component to check if `authResult` is success, and if not, redirect to an error page:

```
constructor(private authService: NbAuthService, private router: Router) {
    this.authService.authenticate('AzureADB2C')
      .pipe(takeWhile(() => this.alive))
      .subscribe((authResult: NbAuthResult) => {
        if (authResult.isSuccess() && authResult.getRedirect()) {
          this.router.navigateByUrl(authResult.getRedirect());
        } else {
          this.router.navigate(['auth', 'error']);
        }
      }
    );
  }
```

However, I think I'm misunderstanding how the surrounding `nb-auth` parent component is effecting this because the redirect happens successfully but my auth/error component won't load, I just have a spinner looping round, but I can see in the URL that it's changed to 'localhost:5001/auth/error' so the `authResult is returning successfully. 

I've modified the `app-routing.module.ts` to have this is a route like the other custom auth components but no avail:

```
{
    path: 'auth',
    children: [
      {
        path: '',
        redirectTo: 'dashboard',
        pathMatch: 'full'
      },
      /*
      {
        path: 'login',
        component: NbLoginComponent,
      },
      ...
      {
        path: 'callback',
        component: NbOAuth2CallbackComponent
      },
      {
        path: 'error',
        component: AuthErrorComponent
      }
    ],
```

**Expected behavior:**

Have a configuration section in the strategy set up for OAuth and other providers to handle custom error callbacks, or some advice on how to implement this directly

**Steps to reproduce:**
Ngx-Admin template, with OAuth2 provider set up - if the OAuth2 provider returns an error callback, this behaviour happens

Thank you

**Comment by nnixaa** [comment]
Hi @jjgriff93, is there any errors in the console after the redirect? It sounds like there should be some :)

**Comment by jjgriff93** [comment]
Hey @nnixaa I thought there would be too, but there's no errors to be found: 
![image](https://user-images.githubusercontent.com/25235950/46861435-9d5e5500-ce0a-11e8-9a98-7d059cb789e5.png)

**Comment by nnixaa** [comment]
Hey @jjgriff93, do you think you could post the code of `AuthErrorComponent`? Especially the template part.

**Comment by jjgriff93** [comment]
Hi @nnixaa sure thing:

auth-error.component.ts
```
import { Component } from '@angular/core';
import { NbAuthResult, NbAuthService } from '@nebular/auth';

@Component({
  selector: 'ngx-auth-error',
  styleUrls: ['./auth-error.component.scss'],
  templateUrl: './auth-error.component.html',
})
export class AuthErrorComponent {

  constructor(private authService: NbAuthService) {
  }

  logIn() {
    this.authService.authenticate('AzureADB2C')
      .subscribe((authResult: NbAuthResult) => {
      });
  }
}
```

auth-error.component.html
```
<h1 class="title">Couldn't authenticate you</h1>
<small class="sub-title">
  Sorry, we weren't able to authenticate you. Either you cancelled sign-up/sign-in, or there was an error.
  Please perform CPR and try again.
</small>
<button (click)="logIn()" type="button" class="btn btn-block btn-hero-primary">
  Try again
</button>
```

 Thanks for your help

**Comment by nnixaa** [comment]
@jjgriff93, I believe your component template is missing `<nb-layout>` components, which is a required component for Nebular to work. Just wrap it like this:
```
<nb-layout>
 <nb-layout-column>
 	<h1 class="title">Couldn't authenticate you</h1>
	<small class="sub-title">
	  Sorry, we weren't able to authenticate you. Either you cancelled sign-up/sign-in, or there was an error.
	  Please perform CPR and try again.
	</small>
	<button (click)="logIn()" type="button" class="btn btn-block btn-hero-primary">
	  Try again
	</button>
 </nb-layout-column>

</nb-layout>

**Comment by jjgriff93** [comment]
@nnixaa thanks Dmitry that's done the trick :) for some reason I assumed it was inherited from the nebular auth component html but I was wrong!

Thanks again for your help
