### ISSUE TITLE
Invalid nb-select behavior 

### ISSUE THREAD

**Issue by sokolandia** [akveo/nebular#877]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
 Clicking nb-select inside a form submits a form.

**Expected behavior:**
Button inside nb-select component should have type attribute "button"

**Steps to reproduce:**
 Click select

**Related code:**

```
<form>
  <nb-select>
    <nb-option>Foo</nb-option>
  </nb-select>
</form>
```

### Other information:

**Angular, Nebular**
```
"@nebular/theme": "^2.0.1",

```

**Comment by dj-fiorex** [comment]
I have the same issue! Is this a bug?

**Comment by gilmarsquinelato** [comment]
I found a temporary solution!
```(click)="$event.preventDefault()"```
add this in the nb-select component.
Hope this helps :)
