### ISSUE TITLE
Invalid typings for nb-select

### ISSUE THREAD

**Issue by sokolandia** [akveo/nebular#881]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
To clear previously selected value of nb-select we have to call `handleSelect` method with `{value: null}`. However it is not possible because the method is marked as `protected` and the parameter it expects is `NbOptionComponent<T>` which doesn't allow to simple pass `{value: null}` to it.

**Expected behavior:**
`selectComponent.handleSelect({value: null})` should work

**Steps to reproduce:**

**Related code:**

```
@ViewChild(NbSelectComponent) selectComponent: NbSelectComponent<any>;
selectComponent.handleSelect({value: null})
```

### Other information:

**Angular, Nebular**
```
"@angular/core": "^6.1.0",
"@nebular/theme": "^2.0.1",

```

**Comment by sokolandia** [comment]
Temporary solution:
`
@ViewChild(NbSelectComponent) select: NbSelectComponent<any>;
select['handleSelect'].call(select, {value: null});
`

**Comment by Tibing** [comment]
Hi @sokolandia, you may add `nb-option` with the empty value and click on this options will clear the `nb-select`.

**Comment by sokolandia** [comment]
@Tibing I want to reset it programmatically. I have a "Clear form button" that has to set an empty value in nb-select. Please reopen the issue and fix it

**Comment by gaspardip** [comment]
+1, same with NbRangepickerComponent, need to reset the control programatically.
