### ISSUE TITLE
How to add right aligned down-arrow icon to multilevel nb-menu

### ISSUE THREAD

**Issue by pdomala** [akveo/nebular#883]
Can you please help me customize the nb-menu to add down arrow to the menu item group?

**Comment by Tibing** [comment]
Hi @pdomala, could you please describe more deeply what help exactly do you need?

**Comment by nnixaa** [comment]
Closing as it's been a while.

**Comment by manshahi** [comment]
i have the same question. is it possible to change the arrow icon for top menu item to "plus icon" and when expanded to "minus icon"?

**Comment by anshul-g-AnAr** [comment]
anyone got a way to do it?
