### ISSUE TITLE
Disable step click and just work with prev and next buttons

### ISSUE THREAD

**Issue by ChristianVega5421** [akveo/nebular#902]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x ] feature request

### Issue description

**Current behavior:**
Hello, i was wondering if there is a way to disable the click on the stepper steps and just change between steps with the buttons "prev" or next.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by developcodeza-matthew** [comment]
Would love to have this added. I have a pretty complex sequence of forms and events that would definitely need to have more control over when and where things get submitted.

**Comment by msincuba** [comment]
I would love to have this feature added.
