### ISSUE TITLE
NbAuthService.register(...) attempts to set a token from result on success

### ISSUE THREAD

**Issue by ahall-medullan** [akveo/nebular#903]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
AuthService register method tries to set a token on success even though it is not an authentication mechanism. There is no way to prevent the register method from attempting to set a token. 

**Expected behavior:**
The register method should not try top set a token on success or provide a means to skip attempting to se a token for applications that do not return a token on registration.

**Steps to reproduce:**
Use `NbPasswordAuthStrategy` and register an account successfully.

**Related code:**
https://github.com/akveo/nebular/blob/master/src/framework/auth/services/auth.service.ts#L123
`  register(strategyName: string, data?: any): Observable<NbAuthResult> {
    return this.getStrategy(strategyName).register(data)
      .pipe(
        switchMap((result: NbAuthResult) => {
          return this.processResultToken(result);
        }),
      );
  }`

`  private processResultToken(result: NbAuthResult) {
    if (result.isSuccess() && result.getToken()) {
      return this.tokenService.set(result.getToken())
        .pipe(
          map((token: NbAuthToken) => {
            return result;
          }),
        );
    }

    return observableOf(result);
  }`

**Comment by nnixaa** [comment]
Hi @ahall-medullan, I believe in your case the `requireValidToken` property should do the trick. So in your configuration of the strategy just add the following:

```
register: {
  //...
  requireValidToken: false,
} 
```

Hope this helps.

**Comment by nnixaa** [comment]
Closing as it seems resolved.
