### ISSUE TITLE
Starter kit does not compile

### ISSUE THREAD

**Issue by imdfl** [akveo/nebular#910]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

The starter kit does not compile.

**Expected behavior:**
following npm install and further installation of @angular/cdk (missing from package.json), ng serve will complete successfully and the app will be served.

**Steps to reproduce:**

1. clone https://github.com/akveo/ngx-admin.git
2. open a shell in the cloned folder
3. npm install
4. npm install --save-dev @angular/cdk
5. ng serve

### Other information:

**npm, node, OS, Browser**
Node 8.11.3 npm 6.4.1
Windows 7

**Angular, Nebular**
Angular 6.0.0 Nebular 2.0.1

**Compiler output**

C:\Users\dfl\...\knowsome-webapp-starter-kit>ng serve
Your global Angular CLI version (6.2.3) is greater than your local
version (6.0.0). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 69% building modules 876/886 modules 10 active …eous\not-found\not-found.component.scssDEPRECATION WARNING on line 1, column 8 of C:/Users/dfl/.../knowsome-webapp-starter-kit/node_modules/@nebular/theme/components/cdk/overlay/_overlay.theme.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

Date: 2018-10-15T20:10:32.014Z
Hash: 4d1b837cad3c651a4297
Time: 15526ms
chunk {app-pages-pages-module} app-pages-pages-module.js, app-pages-pages-module.js.map (app-pages-pages-module) 27.4 kB  [rendered]
chunk {main} main.js, main.js.map (main) 198 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 489 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 8.01 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 12.6 kB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 855 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 6.11 MB [initial] [rendered]

ERROR in ./src/app/@theme/components/footer/footer.component.scss
Module build failed:
undefined
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
      in C:\Users\dfl\...knowsome-webapp-starter-kit\src\app\@theme\components\footer\footer.component.scss (line 2, column 1)
ERROR in ./src/app/@theme/components/header/header.component.scss
Module build failed:
undefined
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
      in C:\Users\dfl\...knowsome-webapp-starter-kit\src\app\@theme\components\header\header.component.scss (line 3, column 1)
ERROR in ./src/app/@theme/components/theme-switcher/themes-switcher-list/theme-switcher-list.component.scss
Module build failed:
undefined
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
      in C:\Users\dfl\...knowsome-webapp-starter-kit\src\app\@theme\components\theme-switcher\themes-switcher-list\theme-switcher-list.component.scss (line 4, column 1)
ERROR in ./src/app/@theme/layouts/one-column/one-column.layout.scss
Module build failed:
undefined
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
      in C:\Users\dfl\...knowsome-webapp-starter-kit\src\app\@theme\layouts\one-column\one-column.layout.scss (line 3, column 1)
ERROR in ./src/app/@theme/layouts/sample/sample.layout.scss
Module build failed:
undefined
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
      in C:\Users\dfl\...knowsome-webapp-starter-kit\src\app\@theme\layouts\sample\sample.layout.scss (line 3, column 1)
ERROR in ./src/app/@theme/layouts/three-columns/three-columns.layout.scss
Module build failed:
undefined
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
      in C:\Users\dfl\...knowsome-webapp-starter-kit\src\app\@theme\layouts\three-columns\three-columns.layout.scss (line 3, column 1)
ERROR in ./src/app/@theme/layouts/two-columns/two-columns.layout.scss
Module build failed:
undefined
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
      in C:\Users\dfl\...knowsome-webapp-starter-kit\src\app\@theme\layouts\two-columns\two-columns.layout.scss (line 3, column 1)
ERROR in ./src/app/@theme/components/switcher/switcher.component.scss
Module build failed:
undefined
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/hero-buttons.
      in C:\Users\dfl\...knowsome-webapp-starter-kit\src\app\@theme\components\switcher\switcher.component.scss (line 2, column 1)
i ｢wdm｣: Failed to compile.

**Comment by Plorax** [comment]
Having the exact same issue. Somehow got round it but forgot how, busy trying something and will report back what I tried and if it worked.

**Comment by Plorax** [comment]
Seems to be missing files. Have you tried to find any of them when it says its missing or unreadable ?

I've found that my files are actually not there so the error message is correct in my case.

I believe that the starter-kit branch has missing files and you need to bring them over from the ngx-admin v2.0.3 tagged branch.

**Comment by Plorax** [comment]
Looking at the nebular change-log, they've moved things around a bit

https://github.com/akveo/nebular/blob/master/CHANGELOG.md

The starter-kit is out of date.
@akveo-private

**Comment by Plorax** [comment]
I've manually updated my starter-kit to fix the issue. Just head over to the CHANGELOG and you should be easily surprised how easy it really is.

Its pretty crazy sometimes, working on the cutting-edge with latest updates.

But, I'd rather be doing that and constantly update my code-base than to update a few months later or years later.

**Comment by imdfl** [comment]
@Plorax , thanks heaps. The changelog contained all the necessary steps to make the starter kit compile.
