### ISSUE TITLE
Authorization Problem (Always Successful Login)

### ISSUE THREAD

**Issue by msohaib308** [akveo/nebular#915]
### Issue type

**I'm submitting a ...** 

* [ ] bug report
* [x] feature request

### NbAuthModule.forRoot({
      strategies: [
        NbPasswordAuthStrategy.setup({
          name: 'auth',

          token: {
            class: NbAuthJWTToken,

            key: 'token',
          },

          baseEndpoint: '/api/',
           login: {
            alwaysFail: false,
             endpoint: 'Login',
             method: 'get',
             redirect: {
              success: '/pages',
              failure: '/register',
              },
           },
           register: {
             endpoint: 'register',
             method: 'post',
           },
        }),
      ],
      forms: {
        login: {
          redirectDelay: 0, // delay before redirect after a successful login, while success message is shown to the user
          strategy: 'auth',  // strategy id key.
          rememberMe: false,   // whether to show or not the `rememberMe` checkbox
          showMessages: {     // show/not show success/error messages
            success: false,
            error: true,
          }, // social links at the bottom of a page
        },
      },
    }),
I have Make this **password Strategy** to call my **Asp.net** Web Api Project 
I also setup the proxy server as given below
{
  "/api": {
    "target": "http://localhost:54575",
    "secure": false
  }
}

**Expected behavior:**
I was expecting it to call my api and return auth token and change the url to dashboard
but its url is not changing.

**Comment by nnixaa** [comment]
Hi @msohaib308, did you use ngx-admin as a basis? Are you seeing http requests in your browser network tab under the developer tools?

**Comment by nnixaa** [comment]
Closing as no response.
