### ISSUE TITLE
nb-chat scroll bar rescrolls to the bottom of the container whenever view is updated. 

### ISSUE THREAD

**Issue by stubbsy345** [akveo/nebular#921]
**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description
I am using the nb-chat component with a component adjacent to it containing a counter. Every time the counter updates the nb-chat scroll automatically scrolls to the bottom. I have not managed to come up with a work around as of yet, however, have not had a chance to have a proper look at it. 

I believe the problem is this life hook:

-->

```
ngAfterViewChecked() { 
      this.scrollable.nativeElement.scrollTop = this.scrollable.nativeElement.scrollHeight; 
}
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
2.0.0rc10
```

**Comment by stubbsy345** [comment]
Is there a possible work around I can build in for now. My project relies heavily around the chat component. I am happy to fix this myself but probably won't have time in the next 2 weeks so would be helpful if there was a workaround in the mean time.

**Comment by nnixaa** [comment]
@stubbsy345 thanks for reporting. There will be a fix in the next version, if you are pressed for time you can implement a custom `nb-chat` component having this fix in place, and then replace it once we release @nebular/theme@3.0.1. Here is a link to the fix https://github.com/akveo/nebular/pull/1001.
