### ISSUE TITLE
Cant pass data to dialog

### ISSUE THREAD

**Issue by jagabs** [akveo/nebular#924]
![screen shot 2018-10-21 at 9 59 56 pm](https://user-images.githubusercontent.com/17292042/47267926-b25e8500-d57c-11e8-9914-9cd03429fcf8.png)

	@Input() title: any;

  constructor(protected ref: NbDialogRef<any>) {
  }

  dismiss() {
    this.ref.close();
  }

**Comment by anvial** [comment]
Hello, I suppose you need to provide context structure like this:

`context: { testVar: 'asd'}.`

And you should define `testVar` in Dialog compotent with the same type. For example:

`testVar: any;`

**Comment by sivaadhithya** [comment]
am not able to pass the data till now
this.dialogService.open(messagecomponent, { hasBackdrop: true, closeOnBackdropClick: true,hasScroll:false,context:{id:2222,value:'ssssss'});

**Comment by adrianatellop** [comment]
if you are still alive, sulution is by using the context like in demos BUT yo have tu pass an object with known keys. This are delcared below @input decorator

**Comment by el7or** [comment]
> 
> 
> Hello, I suppose you need to provide context structure like this:
> 
> `context: { testVar: 'asd'}.`
> 
> And you should define `testVar` in Dialog compotent with the same type. For example:
> 
> `testVar: any;`

How I can pass this data to resolver?

**Comment by abhi40308** [comment]
Not able to pass image data

**Comment by palominoortiz** [comment]
solution : the params should be obtain on ngOnInit, not in constructor

**Comment by anandubabu-kr** [comment]
I struggled a bit to understand this. The items should be passed in context following a strict naming and type checks.
Code sample in the container component: 

```ts
  protected openEdit(closeOnBackdropClick: boolean,id:string) {
    this.dialogService.open(UpdateEmployeeComponent, {
      closeOnBackdropClick, context: { employeeId:id }, 
    });
  }
```
Recieving the employeeId in UpdateEmployeeComponent dialoge component 

```ts
  export class UpdateEmployeeComponent implements OnInit {
    @Input() employeeId;
```

@palominoortiz Why onInit ? It seems working right at the starting of class def !
