### ISSUE TITLE
NbSelectComponent doesn't detect changes on options

### ISSUE THREAD

**Issue by 100hz** [akveo/nebular#931]
Hey Akveo, really love the Nebular project and the themes, using it in my project.

There seems to be a Bug in the NbSelectComponent, while changing the option content children.

**Current Behaviour:**
Works as expected when creating options in a nFor at the first time. Option elements cannot be selected, when the option list changes.

**Expected Behaviour:**
Option elements can be selected when the option list changes, e.g. by Observable input.

**Note:**
You probably need to listen to https://angular.io/api/core/QueryList#changes ...

**Comment by sami6002** [comment]
I have this problem too, has any solutions?

**Comment by ceaguilera** [comment]
I hace this problem too! @100hz you heve solution?
