### ISSUE TITLE
Auth refresh token, not being passed?

### ISSUE THREAD

**Issue by Platiplus** [akveo/nebular#933]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Can't find the token on the request using the refresh token method. On my API, I call
``` console.log(request); ```
and I cant't find the token anywhere.

**Expected behavior:**
Check if user is authenticated on auth guards and if it is, pass the current token and refresh it, so the session expires after X minutes when IDLE.

**Steps to reproduce:**
Using the starter kit from ngx-admin with auth modules already set on place, create a simple auth-guard as explained in the tutorial and try to call the refresh token method.

**Related code:**
```
  canActivate() {
    return this.authService.isAuthenticated()
      .pipe(
        tap(authenticated => {
          if (!authenticated) {
            this.router.navigate(['auth/login']);
          } else {
            this.authService.getToken().subscribe((value) => {
              this.authService.refreshToken('email', { token: value['token'] }).subscribe((message) => {
                console.log(message)
              });
            });
          }
        }),
      );
  }
```

### Other information:

**Angular, Nebular**
```
"@nebular/auth": "2.0.0-rc.9",
"@angular/core": "6.0.0"
"name": "ngx-admin",
"version": "2.3.0",
```

**Comment by Platiplus** [comment]
I found the problem on the code in the auth.service.js on @nebular auth service.
I've created a pull request, but it's my first time doing so, any help would be appreciated.

@nnixaa fixed this problem with [#935](https://github.com/akveo/nebular/pull/935), can you lend me a hand?

**Comment by nnixaa** [comment]
Hey @Platiplus, this is fixed in the master branch, you just need to update to the latest Nebular version.

**Comment by Platiplus** [comment]
> Hey @Platiplus, this is fixed in the master branch, you just need to update to the latest Nebular version.

Yeah, I saw it, but this version is the version you guys ship with the ngx-admin starter-kit. Are you considering to update the version that comes with the starter kit or fixing the bug on this version?
