### ISSUE TITLE
Nb-Select not emitting change event

### ISSUE THREAD

**Issue by itkachyshyn** [akveo/nebular#948]
### Nb-Select not emitting event when used with [ngModel]

**I'm submitting a bug report**
### Issue description

**Current behavior:**
Nb-Select does not emit (selectChange) or (ngModelChange) event when using observables with ngModel.

```
<nb-select (selectedChange)="onChange($event)" (ngModelChange)="onChange($event)"
    [ngModel]="selectedLocationUnitGroupId$ | async">
    <nb-option *ngFor="let option of locationUnitGroups$ | async" [value]="option.id">
        {{ option.type }}
    </nb-option>
 </nb-select>

```

**Expected behavior:**
I want nb-select to emit (selectChange) or (ngModelChange) event every time user selects an option

Any ideas how to fix it?

**Comment by pdomala** [comment]
I am having the same issue. Nb-select does not work if the options are generated using ngFor and observables. Hardcoding nb-option tags works fine.

**Comment by mckuok** [comment]
Anyone have a solution?

**Comment by mushu8** [comment]
up plz

**Comment by Tibing** [comment]
Hi guys, the issue will be resolved in the nearest future.

**Comment by mushu8** [comment]
Thanks @Tibing
How near please ? hours ? days ? weeks ?
I'm currently on a client project and start thinking of ng-select but it will break the ui … :(

**Comment by Tibing** [comment]
Hi @mushu8, hope I'll be done this week, and next release version will be published next week

**Comment by mushu8** [comment]
ok thanks 👍

**Comment by thomasreji** [comment]
am facing the same issue too. When is the plan to release?

**Comment by gaspardip** [comment]
any workaround for this in the meantime?

**Comment by mushu8** [comment]
I’ve integrated ng-select

**Comment by anupam42** [comment]
@pdomala Have got any solutions for ur issue because i am facing the same issue

**Comment by AsmaGargouri** [comment]
We are facing the same problem. Is there any solution yet please ?

**Comment by nu5rim3** [comment]
any update?

**Comment by t33zy** [comment]
Anyone got this issue solved? Please help

**Comment by chadirahme** [comment]
still not working !!

**Comment by ruodeng** [comment]
my solution is that, I have a pickupAddress which type is string, but put it into a temp array, only contain one value, and loop this array can work.
```
         <div class="form-group" *ngFor="let bc of tempPickupAddress">
                  <nb-select   *ngIf="canEdit" fullWidth [(selected)]="bc" (selectedChange)="onUpdatePickupAddress($event)" >
                    <nb-option-group   *ngFor="let pick of pickupAddress">
                    <nb-option  [value]="pick._id"> {{pick.unit}} {{ pick.street }}</nb-option>
                    </nb-option-group>
                  </nb-select> 
            </div>
```
related component
```
... 
tempPickupAddress = [null];
...
// In the ajax
    this.tempPickupAddress = [data.bulkOrder.pickupAddress];
...
// Update on select change.
 onUpdatePickupAddress(event) {
    this.bulkOrder.pickupAddress = event;
  }
```

**Comment by bkstorm** [comment]
I have the same problem. This issue has not been solved.

**Comment by AngelCareaga** [comment]
Solved this...

HTML
```
<nb-select placeholder="Seleccionar Talla" [(selected)]="selectedItemTalla" filled status="warning">
          <nb-option *ngFor="let talla of tallas" (click)="cambiaTalla(talla.sigla)" [value]="talla.sigla">{{talla.sigla}} <span style="opacity: 0.4 !important;">&nbsp;({{talla.quantity}} Disp)</span></nb-option>
        </nb-select>
```
AND TS
```
cambiaTalla(talla){
    console.log(talla);
  }
```

The Key is in the (click), cheers!!!

**Comment by GreedyA1** [comment]
same issue with selectedChange. @AngelCareaga  click doesn't work for me. it just simply doesn't trigger anything.

**Comment by codeztech-atique** [comment]
Same issue

**Comment by codeztech-atique** [comment]
Same issue @AngelCareaga does not work form me - 
 <nb-select class="optionsData" [(selected)]="this.statusData">
          <nb-option *ngFor="let status of tagsAPIStatus" (change)="selectedChange(status)" [value]="this.statusData === status ? status : ''">
            <span>&nbsp;{{status}}</span>
          </nb-option>
        </nb-select>

  selectedChange(e) {
    console.log(e);
    this.statusData = e;
  }


Not working

**Comment by Nisha-Yadav-1** [comment]
> Solved this...
> 
> HTML
> 
> ```
> <nb-select placeholder="Seleccionar Talla" [(selected)]="selectedItemTalla" filled status="warning">
>           <nb-option *ngFor="let talla of tallas" (click)="cambiaTalla(talla.sigla)" [value]="talla.sigla">{{talla.sigla}} <span style="opacity: 0.4 !important;">&nbsp;({{talla.quantity}} Disp)</span></nb-option>
>         </nb-select>
> ```
> 
> AND TS
> 
> ```
> cambiaTalla(talla){
>     console.log(talla);
>   }
> ```
> 
> The Key is in the (click), cheers!!!

This would create too many event listeners. This could create a performance issue if used on multiple select box on single page and if each select box contains lots of options.

**Comment by aritrabasu104** [comment]
@AngelCareaga @Nisha-Yadav-1 
We can use selectedChange event like this
`<nb-select nbTooltip="This value is required" class="col-sm-2" placeholder="Select" (selectedChange)="updateForm()"
            formControlName="transmissionType">`

**Comment by JoseSpx** [comment]
Same issue, please fixed it. thanks

**Comment by JoseSpx** [comment]
Solved this.
(selectedChange)="selectedClientChange($event)"
Send the "$event", and the method will receive the value selected.

**Comment by westrindade** [comment]
Eu estou usando o translate...
Quando altero o idioma as opções de seleção são alteradas corretamente, mas se ja estiver selecionado uma opção, ele não altera ela, mas ao clicar no componente ele altera.
Podem me ajudar?

**Comment by amarnandeshwar786** [comment]
I am facing the following UI issue, is anyone have a solution then please help to resolve this issue

![image](https://user-images.githubusercontent.com/34885267/147901246-7a5a5e37-cc7e-4baa-8fc9-4659c63dac61.png)

**Comment by anupam42** [comment]
> I am facing the following UI issue in nb-select, is anyone have a solution then please help to resolve this issue
> 
> ![image](https://user-images.githubusercontent.com/34885267/147901246-7a5a5e37-cc7e-4baa-8fc9-4659c63dac61.png)

@amarnandeshwar786 might with css class overlapping issue. Check some margin top added.

**Comment by nikita-fuchs** [comment]
None of the proposed solutions here work. The only thing you can do is have it directly put into the corresponding form control under its formcontrol name, and then listen to its changes.

like:

```
<form [formGroup]="tarifSchemaDataForm"> .... and then further below...

 <nb-select *ngSwitchCase="'options'"  [selected]="" fullWidth="true" placeholder="{{field.label}}" formControlName="{{field.name}}" nbPopover="{{field.helpMessage}}" nbPopoverTrigger="noop" nbPopoverContext="{{field.name}}">
            <nb-option *ngFor="let option of field.options | keyvalue" value="{{ option.key }}" > <div class="numberCircle">{{option.key}}</div><span style="white-space:nowrap;"> &nbsp;&nbsp;{{option.value }}</span></nb-option>
          </nb-select>

```
