### ISSUE TITLE
nbdatepicker onclick button

### ISSUE THREAD

**Issue by hmedikarim** [akveo/nebular#951]
please how can i show the nebular datepicker when i click in button

**Comment by Tibing** [comment]
Hi @hmedikarim, you can use `nb-datepicker` explicitly without binding it to the `nbDatepicker` directive. Just query it with `@ViewChild` and call `show()` method.

```html
<nb-datepicker [(date)]="date"></nb-datepicker>
<button (click)="showDatepicker()"></button>
```
```ts
@ViewChild(NbDatepickerComponent) datepicker;
showDatepicker() {
  this.datepicker.show();
}
```

**Comment by pjdabrowski** [comment]
@Tibing Your exapmle causes:

`Uncaught TypeError: Cannot read property 'y' of undefined
    at NbAdjustableConnectedPositionStrategy.push../node_modules/@angular/cdk/esm5/overlay.es5.js.FlexibleConnectedPositionStrategy._getOriginRect (overlay.es5.js:3164)`

Is it new bug in version 3.4.1 or am i missing something ?

**Comment by salomi9** [comment]
For anybody still looking for better solutions (this solution opens calendar on icon/button click)
```
<input
  #dateInput
  id="date"
  class="date"
  nbInput
  placeholder="select a date"
  [nbDatepicker]="datePicker"
/>
<button nbSuffix nbButton ghost (click)="dateInput.click()">
  <nb-icon icon="calendar"> </nb-icon>
</button>
<nb-datepicker #datePicker ></nb-datepicker>
```

then you can set the visibility of input tag to hidden and width to 0px
styling:
```
.date{
      visibility: hidden;
      width: 0px;
      padding: 0 !important;
    }
```
