### ISSUE TITLE
nbdatepicker show year only

### ISSUE THREAD

**Issue by hmedikarim** [akveo/nebular#957]
please help me how can i show year oly in nbdatepicker

**Comment by Tibing** [comment]
Hi @hmedikarim, It's not possible in datepicker for now. For the cases like that, we have the [Calendar Kit](https://akveo.github.io/nebular/docs/components/calendar-kit/overview#nbcalendarkitmodule) module. With help of this module, you may build your custom datepicker with the year only view. Please investigate it and read the documentation for deeper explanation.
