### ISSUE TITLE
Parallels calls to NbAccessChecker.isGranted with RxJS ForkJoin never resolves

### ISSUE THREAD

**Issue by jromerob** [akveo/nebular#964]
I'm trying to make parallels calls to get ACL permissions with the service NbAccessChecker.

Wrapping the calls with ForkJoin, the observable response never resolve and no error shows

### Issue type

**I'm submitting a ...

* [ x ] bug report

### Issue description

**Current behavior:**

I'm trying to make parallels calls to get ACL permissions with the service NbAccessChecker.

Wrapping the calls with ForkJoin, the observable response never resolve and no error shows

      forkJoin(
            this.accessChecker.isGranted('create', 'inmuebles'),
            this.accessChecker.isGranted('remove', 'inmuebles')
          )
            .subscribe(
              (permissions) => {
                this.canEdit = permissions[0];
                this.canDelete = permissions[1];
              },
              error =>
                // tslint:disable-next-line:no-console
                console.log(error)
            );

Individual call resolve right
 this.accessChecker.isGranted('create', 'inmuebles').suscribe((granted)=>.. .. ...)

**Expected behavior:**
forkJoin must resolve the observable with an array [boolean,boolean] or thow an error

**Related code:**
```
 forkJoin(
            this.accessChecker.isGranted('create', 'inmuebles'),
            this.accessChecker.isGranted('remove', 'inmuebles')
          )
            .subscribe(
              (permissions) => {
                this.canEdit = permissions[0];
                this.canDelete = permissions[1];
              },
              error =>
                // tslint:disable-next-line:no-console
                console.log(error)
            );
```

### Other information:

**Angular, Nebular**
```
   "rxjs": "^6.1.0",
    "rxjs-compat": "^6.1.0",
    "@angular/common": "6.0.0",
    "@angular/compiler": "6.0.0",
    "@angular/core": "6.0.0",
    "@angular/forms": "6.0.0",
    "@angular/http": "6.0.0",
    "@angular/platform-browser": "6.0.0",
    "@angular/platform-browser-dynamic": "6.0.0",
    "@angular/router": "6.0.0",
"@nebular/auth": "^2.0.1",
    "@nebular/bootstrap": "^2.0.1",
    "@nebular/security": "^2.0.1",
    "@nebular/theme": "^2.0.1",
```

**Comment by nnixaa** [comment]
Hi @jromerob, I just tried this in a simple configuration myself, and it is working fine. 

Please provide a minimal reproducible example preferably push it to stackblitz, so that we can check. Thanks.

**Comment by jromerob** [comment]
Sorry for the veeeeeery late response:

`const create$ = this.accessChecker.isGranted('create', 'tesauros');
    const remove$ = this.accessChecker.isGranted('remove', 'tesauros');

    forkJoin([create$, remove$])
      .subscribe(
        (permissions) => {
          this.canEdit = permissions[0];
          this.canDelete = permissions[1];
          this.initAuthorsTableSettings(this.canEdit, this.canDelete);
        }
      );`

**Comment by katebatura** [comment]
Hi! In order for `forkJoin` to emit a value, all given observables have to emit something at least once and complete. Conversely, if there is an observable that never completes, forkJoin will never complete either. But we can't complete Observable that `isGranted()` returns because the role can change and  `isGranted()` must emit new value. So, try to use `combineLatest` or `zip` instead of `forkJoin`.
