### ISSUE TITLE
File to import not found or unreadable

### ISSUE THREAD

**Issue by tanmayparmar** [akveo/nebular#967]
### File to import not found or unreadable:

**I'm submitting a ...**  (check one with "x")

* [ x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

I am running NPM start command but it is failed to compiled
**Expected behavior:**

It should compile successfully. 
**Steps to reproduce:**

**Related code:**
<!-- 
If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:
->

```
insert short code snippets here
```
ERROR in ./src/app/@theme/components/footer/footer.component.scss
Module build failed: 
@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /media/tanmay/New Volume/Work/yds-canada/yds-canada-web/ngx-admin-starter-kit/src/app/@theme/components/footer/footer.component.scss (line 2, column 1)
ERROR in ./src/app/@theme/components/header/header.component.scss
Module build failed: 
@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /media/tanmay/New Volume/Work/yds-canada/yds-canada-web/ngx-admin-starter-kit/src/app/@theme/components/header/header.component.scss (line 3, column 1)
ERROR in ./src/app/@theme/components/theme-switcher/themes-switcher-list/theme-switcher-list.component.scss
Module build failed: 
@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /media/tanmay/New Volume/Work/yds-canada/yds-canada-web/ngx-admin-starter-kit/src/app/@theme/components/theme-switcher/themes-switcher-list/theme-switcher-list.component.scss (line 4, column 1)
ERROR in ./src/app/@theme/layouts/one-column/one-column.layout.scss
Module build failed: 
@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /media/tanmay/New Volume/Work/yds-canada/yds-canada-web/ngx-admin-starter-kit/src/app/@theme/layouts/one-column/one-column.layout.scss (line 3, column 1)
ERROR in ./src/app/@theme/layouts/sample/sample.layout.scss
Module build failed: 
@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /media/tanmay/New Volume/Work/yds-canada/yds-canada-web/ngx-admin-starter-kit/src/app/@theme/layouts/sample/sample.layout.scss (line 3, column 1)
ERROR in ./src/app/@theme/layouts/three-columns/three-columns.layout.scss
Module build failed: 
@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /media/tanmay/New Volume/Work/yds-canada/yds-canada-web/ngx-admin-starter-kit/src/app/@theme/layouts/three-columns/three-columns.layout.scss (line 3, column 1)
ERROR in ./src/app/@theme/layouts/two-columns/two-columns.layout.scss
Module build failed: 
@import '~@nebular/theme/styles/global/bootstrap/breakpoints';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/breakpoints.
Parent style sheet: stdin
      in /media/tanmay/New Volume/Work/yds-canada/yds-canada-web/ngx-admin-starter-kit/src/app/@theme/layouts/two-columns/two-columns.layout.scss (line 3, column 1)
ERROR in ./src/app/@theme/components/switcher/switcher.component.scss
Module build failed: 
@import '~@nebular/theme/styles/global/bootstrap/hero-buttons';
^
      File to import not found or unreadable: ~@nebular/theme/styles/global/bootstrap/hero-buttons.
Parent style sheet: stdin
      in /media/tanmay/New Volume/Work/yds-canada/yds-canada-web/ngx-admin-starter-kit/src/app/@theme/components/switcher/switcher.component.scss (line 2, column 1)

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```
{
  "name": "ngx-admin",
  "version": "2.3.0",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/akveo/ngx-admin.git"
  },
  "bugs": {
    "url": "https://github.com/akveo/ngx-admin/issues"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "IE 11"
  ],
  "scripts": {
    "ng": "ng",
    "conventional-changelog": "conventional-changelog",
    "start": "ng serve",
    "build": "ng build",
    "build:prod": "npm run build -- --prod --aot",
    "test": "ng test",
    "test:coverage": "rimraf coverage && npm run test -- --code-coverage",
    "lint": "ng lint",
    "lint:fix": "ng lint ngx-admin-demo --fix",
    "lint:styles": "stylelint ./src/**/*.scss",
    "lint:ci": "npm run lint && npm run lint:styles",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "ng e2e",
    "docs": "compodoc -p src/tsconfig.app.json -d docs",
    "docs:serve": "compodoc -p src/tsconfig.app.json -d docs -s",
    "prepush": "npm run lint:ci",
    "release:changelog": "npm run conventional-changelog -- -p angular -i CHANGELOG.md -s"
  },
  "dependencies": {
    "@angular/animations": "^7.1.0-beta.2",
    "@angular/cdk": "^7.0.3",
    "@angular/common": "7.1.0-beta.2",
    "@angular/compiler": "7.1.0-beta.2",
    "@angular/core": "7.1.0-beta.2",
    "@angular/fire": "^5.1.0",
    "@angular/forms": "7.1.0-beta.2",
    "@angular/http": "7.1.0-beta.2",
    "@angular/platform-browser": "7.1.0-beta.2",
    "@angular/platform-browser-dynamic": "7.1.0-beta.2",
    "@angular/router": "7.1.0-beta.2",
    "@nebular/auth": "2.0.0-rc.9",
    "@nebular/security": "2.0.0-rc.9",
    "@nebular/theme": "^2.0.2",
    "@nebular/bootstrap": "^2.0.2",
    "@ng-bootstrap/ng-bootstrap": "1.0.0",
    "bootstrap": "4.0.0",
    "classlist.js": "1.1.20150312",
    "core-js": "2.5.1",
    "firebase": "^5.5.7",
    "intl": "1.2.5",
    "ionicons": "2.0.1",
    "nebular-icons": "1.0.8",
    "normalize.css": "6.0.0",
    "pace-js": "1.0.2",
    "roboto-fontface": "0.8.0",
    "rxjs": "^6.1.0",
    "rxjs-compat": "^6.1.0",
    "socicon": "3.0.5",
    "typeface-exo": "0.0.22",
    "web-animations-js": "2.2.5",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.0",
    "@angular/cli": "^7.0.4",
    "@angular/compiler-cli": "7.1.0-beta.2",
    "@angular/language-service": "7.1.0-beta.2",
    "@compodoc/compodoc": "1.0.1",
    "@types/jasmine": "2.5.54",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "6.0.90",
    "codelyzer": "4.0.2",
    "conventional-changelog-cli": "1.3.4",
    "husky": "0.13.3",
    "jasmine-core": "2.6.4",
    "jasmine-spec-reporter": "4.1.1",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.1.1",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.3.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "npm-run-all": "4.0.2",
    "protractor": "5.1.2",
    "rimraf": "2.6.1",
    "stylelint": "7.13.0",
    "ts-node": "3.2.2",
    "tslint": "5.7.0",
    "tslint-language-service": "0.9.6",
    "typescript": "3.1.6"
  }
}

**Comment by Tibing** [comment]
Hi @tanmayparmar, could you please provide you stacktrace?

**Comment by Prefix1802** [comment]
@tanmayparmar 

That is because you are using ngxadmin v2.3.0 and you changed the angular dependencies in package.json to version 7 and up.

Also your Nebular depencies are 2 different versions.

In fact my guess is you have tried to update a lot of depencies, like Typescript, but it does not work like that. that's why you are getting errors.

**Comment by tanmayparmar** [comment]
@Prefix1802  I was able to figure out the problem. The problem was more related to path of the import files. I guess, ngx-admin starter kit's import files are old. Although, i would like to know, Which are the two dependencies of the nebular i am using?

**Comment by Prefix1802** [comment]
@tanmayparmar 

"@nebular/auth": "2.0.0-rc.9",
    "@nebular/security": "2.0.0-rc.9",
    "@nebular/theme": "^2.0.2",
    "@nebular/bootstrap": "^2.0.2",
