### ISSUE TITLE
Incorrect documentation for Checkbox component

### ISSUE THREAD

**Issue by denStrigo** [akveo/nebular#969]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description
Incorrect documentation for Checkbox component in the `Installation` section.
https://akveo.github.io/nebular/docs/components/checkbox/overview#nbcheckboxcomponent

> Import  `NbCheckboxComponent` to ...

 Should be:  

> Import `NbCheckboxModule`

![screenshot_1](https://user-images.githubusercontent.com/8480994/48270183-78312680-e44a-11e8-8617-aee72c77551a.jpg)

**Comment by nnixaa** [comment]
fixed in 3.0.0
