### ISSUE TITLE
nb-select does not work properly on scrolling

### ISSUE THREAD

**Issue by fatma-hassanein** [akveo/nebular#971]
### Issue type

I'm submitting an issue regarding the nb-select, when adding an nb-select component inside the nb-header and I make it fixed, when I scroll through the page and try using the nb-select component, its menu stays up and does not scroll properly with it !
* [x] bug report
* [ ] feature request

```
<nb-layout>
<nb-layout-header fixed>
<nb-select>
            <nb-option value="1">Mansoura</nb-option>
            <nb-option value="2">October</nb-option>
            <nb-option value="3">North Coast</nb-option>
            <nb-option value="4">Sharm El-Sheikh</nb-option>
</nb-select> 
</nb-layout-header>
</nb-layout>
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by fatma-hassanein** [comment]
When adding an nb-select component inside the nb-header and I make it fixed, when I scroll through the page and try using the nb-select component, its menu stays up and does not scroll properly with it !

**Comment by Tibing** [comment]
Hi @fatma-hassanein, could you please provide us a reproducible stackblitz?

**Comment by fatma-hassanein** [comment]
Ok 👌

**Comment by fatma-hassanein** [comment]
The issue you referenced after being solved didn't solve my problem, should I open a new issue ??
My issue is when I put a nb-select inside the nb-header and make it fixed the menu of the select doesn't work properly, the header suddenly disappear and the menu is half cropped and misplaced !

![screenshot 6](https://user-images.githubusercontent.com/17416140/49734719-e78a7800-fc8d-11e8-9a92-94770faac394.png)
![screenshot 8](https://user-images.githubusercontent.com/17416140/49734720-e78a7800-fc8d-11e8-8297-9b103c25ec7a.png)



@nnixaa

**Comment by Tibing** [comment]
Hi @fatma-hassanein, could you please provide us a reproducible [stackblitz](https://stackblitz.com/)?

**Comment by nnixaa** [comment]
Closing as no answer.

**Comment by Mautriz** [comment]
How do I solve this ?
