### ISSUE TITLE
Select  does not hide on scrolling

### ISSUE THREAD

**Issue by denStrigo** [akveo/nebular#992]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description
nb-select component does not hide on the scroll. The issue reproduced if scroll container, not `body`.

**Current behavior:**
![scroll](https://user-images.githubusercontent.com/8480994/48555891-7c9a8b00-e8f3-11e8-8346-d9ce85251231.jpg)

Related to #971

**Comment by Doston1i** [comment]
any solution above issue i am also having same issue 
<img width="1425" alt="Screenshot 2023-07-11 at 12 54 39 PM" src="https://github.com/akveo/nebular/assets/53547433/95db243a-3ba7-4c50-98b5-39f6d7d8be6b">
