### ISSUE TITLE
[Feature Request] Reactive Smart Table cell coloration based dynamic evaluation of validation rules

### ISSUE THREAD

**Issue by oleersoy** [akveo/nebular#993]
* [ X ] feature request

I've built [@fireflysemantics/validator](https://github.com/fireflysemantics/validator/#readme).

I'd like to integrate it with the smart table such that:

1. The smart table colors the invalid cell an `error` color
    - This would be done after the first validation pass on data
    - Only invalid data rows are displayed
2. If the user corrects the value the entity:
    - It could trigger triggering other validation rules and color the corresponding invalid cell should then be displayed 
3. Once an entity has been corrected, save that entity to an entity store like [@fireflysemantics/slice](https://github.com/fireflysemantics/slice#readme) or NgXS via a save function attached to an entity wrapper.

I was thinking that perhaps the smart table could render entities contained in a wrapper that implements a specific interface providing additional data that the row renderer would need.

Specifically the wrapper would support a `validate()` function call that checks if the entity is valid and also updates validation meta data contained by the same wrapper.

Naturally I'd be happy to go to work on this if you guys are interested.

Thoughts?

**Comment by oleersoy** [comment]
Also is this the repository for the smart table:
https://github.com/akveo/ng2-smart-table

It's still using the `ng2` prefix, so I thought perhaps it might be moved to a newer repository?

**Comment by oleersoy** [comment]
I'm going to close this and simplify it.  Looks like perhaps the perhaps most of the work can be done with `type: 'custom'` cell components that validate or save the row.

**Comment by TolgaDaSilva** [comment]
Do you have a solution for validating or saving a row?
